### ISSUE TITLE
Modeline only appears in non-file buffers

### ISSUE THREAD

**Issue by VirgiliusHaufniensis** [seagle0128/doom-modeline#1]
I have a problem, where the mode-line only is visible in buffers not associated with files (e.g. *scratch*, dired). As soon as i open an existing file, the modeline completely disappears. 

I tried removing modules from my .emacs, but to no avail. It doesn't work with the following .emacs:

`
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("ORG" . "http://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("MELPA STABLE" . "http://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("MELPA" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("MARMALADE" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("GNU ELPA" . "http://elpa.gnu.org/packages/"))
(setq package-archive-priorities
      '(("ORG"          . 10)
        ;;("MELPA STABLE"  . 7)
        ("GNU ELPA"     . 5)
        ;;("MARMALADE"    . 2)
        ("MELPA"        . 9)))

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))
(setq use-package-always-ensure t)
(require 'bind-key)

;;; Use-package
(use-package projectile)
(use-package shrink-path)
(use-package eldoc-eval)
(load "~/.emacs.d/doom-modeline.el")
(require 'doom-modeline)
(+doom-modeline|init)
`

(also, the package is not available on Melpa yet)

**Comment by seagle0128** [comment]
Thanks for the reporting. Actually the package has not been approved by Melpa so far.

Regarding this issue, I tested with your configurations. It seems the `all-the-icons` package is missing. Please add `(use-package all-the-icons)` and retry. It works well for me as below.

![image](https://user-images.githubusercontent.com/140797/41292600-9f05e01a-6e85-11e8-80e0-4efb13d8596f.png)

**Comment by VirgiliusHaufniensis** [comment]
It still doesn't work for me. I am on Windows if that makes any difference. 

![udklip](https://user-images.githubusercontent.com/26080212/41292804-e1d00650-6e53-11e8-89b4-f022db4ac922.PNG)

**Comment by VirgiliusHaufniensis** [comment]
I found this in the *Messages* buffer

`../../../Users/Troels/.emacs.d/doom-modeline.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead. [3 times]
Loading c:/Users/Troels/.emacs.d/doom-modeline.el (source)...done`

**Comment by seagle0128** [comment]
Does it work now?
Yes. I also noticed this warning. But for Emacs 24 and 25, there is no `when-let*`. Let me look into and address it.

**Comment by VirgiliusHaufniensis** [comment]
It still doesn't work, but now I get this error:
`Error during redisplay: (eval (doom-modeline-format--main)) signaled (invalid-regexp "Trailing backslash") [4 times]`

**Comment by seagle0128** [comment]
OK. Did you install `all-the-icons` fonts?  Run `M-x all-the-icons-install-fonts`. It should be the fonts issue here.

**Comment by VirgiliusHaufniensis** [comment]
Yes, I have run the command, and I'm afraid it doesn't change anything.

**Comment by VirgiliusHaufniensis** [comment]
I think this might be an issue with the encoding in Windows. I'll be back.

**Comment by seagle0128** [comment]
Please try other fonts or encodings. Hmm, I am not using Windows now :(

**Comment by seagle0128** [comment]
If the fonts are still not displayed correctly, please try to put these codes in `init.el`, and let me know the results.

```elisp
(defun +doom-maybe-icon-octicon (&rest args)
  (when (and (display-graphic-p) (not (eq system-type 'windows-nt)))
    (apply 'all-the-icons-octicon args)))

(defun +doom-maybe-icon-faicon (&rest args)
  (when (and (display-graphic-p) (not (eq system-type 'windows-nt)))
    (apply 'all-the-icons-faicon args)))

(defun +doom-maybe-icon-material (&rest args)
  (when (and (display-graphic-p) (not (eq system-type 'windows-nt)))
    (apply 'all-the-icons-material args)))
```

**Comment by VirgiliusHaufniensis** [comment]
I have now tested it on my work computer, and it's the same thing. The lisp code above doesn't change anything :-(

**Comment by seagle0128** [comment]
Also on Windows? Any output in the *Messages* buffer?

**Comment by VirgiliusHaufniensis** [comment]
Yes, my work computer runs Windows. And the output in \*Messages\* is *exactly* the same.

**Comment by seagle0128** [comment]
I tested on Windows just now. It works fine. Please update and retry. I am using `consolas` fonts with GNU Emacs 26.1 on Windows 10.

![image](https://user-images.githubusercontent.com/140797/41347723-220849c8-6f3d-11e8-99ef-7cf12734e081.png)

**Comment by VirgiliusHaufniensis** [comment]
It's working! Turns out I was running 26.093 or something like that. I've now upgraded to 26.1. Thank you so much.

**Comment by seagle0128** [comment]
Welcome! I disabled `all-the-icons` in Windows due to the bad performance and formats. Please refer to my latest commit. In my testing, the icons are not showed correctly.

I'm closing this issue. Please let me know if you still have questions. Thanks.

**Comment by VirgiliusHaufniensis** [comment]
Have you seen [this?](https://github.com/domtronn/all-the-icons.el/issues/28).

Putting `(setq inhibit-compacting-font-caches t)` in my .emacs solves the issue at least for me.

**Comment by seagle0128** [comment]
I tried this workaround, but seems it doesn't work. The icons in modeline are messy, and the Emacs is extremely slow after I updated `all-the-icons`.

**Comment by seagle0128** [comment]
Hi @yiufung ,

1. Please use the latest Emacs 26.1.
1. Please update `doom-modeline` to the latest version.
1. Run `M-x all-the-icons-install-fonts` and install the dwonloaded fonts manually.
1. Try with these configs if using `cnfonts`.

```elisp
(defun cnfonts--set-all-the-icons-fonts (&optional _)
    "Show icons in all-the-icons."
    (when (featurep 'all-the-icons)
      (dolist (charset '(kana han cjk-misc bopomofo gb18030))
        (set-fontset-font "fontset-default" charset "all-the-icons" nil 'append)
        (set-fontset-font "fontset-default" charset "github-octicons" nil 'append)
        (set-fontset-font "fontset-default" charset "FontAwesome" nil 'append)
        (set-fontset-font "fontset-default" charset "Material Icons" nil 'append))))

(add-hook 'cnfonts-set-font-finish  #'cnfonts--set-all-the-icons-fonts)
```

if you still encounter this issue, try `M-x toggle-debug-on-error`, and provide more errors for troubleshooting.
