### ISSUE TITLE
file-name not working if buffer unmodified

### ISSUE THREAD

**Issue by hubisan** [seagle0128/doom-modeline#10]
Thanks for creating a package for doom-modeline!

Getting following error if using `(setq doom-modeline-buffer-file-name-style 'file-name)` :
`Error during redisplay: (eval (doom-modeline-format--main)) signaled (void-function active)`

And this throws that error:
https://github.com/seagle0128/doom-modeline/blob/501a930d32f236f08da6b787a69e2ff904c9c22f/doom-modeline.el#L521-L526

The function `(active)` is void because it has been renamed to `doom-modeline--active`

**Comment by seagle0128** [comment]
Thanks! It's a bug. Will fix soon.
