### ISSUE TITLE
Segments sometimes get stuck with inactive face

### ISSUE THREAD

**Issue by aaronjensen** [seagle0128/doom-modeline#103]
**Describe**

My theme has a different face for the inactive mode line. Specifically, the mode line itself is darker and it has a box only when inactive. This is the theme that I use: 

https://github.com/aaronjensen/night-owl-emacs

The problem that I've been having with doom-modeline (which is fantastic, thank you!) lately is that segments will occasionally get "stuck" with the inactive face when the rest of the mode line is using the active face. I've seen the version control segment get stuck rendering with the inactive face. 

**Steps and Expected**

Unfortunately, I don't have consistent repro steps for this and it's very possible that this is actually an Emacs 27 on macOS Mojave rendering bug. I'm opening the issue here in case you have a quick idea what the issue may be. If not, feel free to close and I can reopen if and when I have a consistent repro.

**Environment:**
 - OS: macOS 
 - Version 10.14
 - Package version 20190124

**Additional context**
Will take a screenshot next time I see it.

**Comment by seagle0128** [comment]
I didn't observe this issue in Emacs 26.1. It's difficult to troubleshooting if the issue is unable to reproduce. Let's open it for now.

**Comment by zsxh** [comment]
I have a similar problem when company-box-mode is enabled. company-box pop list then modeline face will be inactive. 

emacs -q
``` elisp
(require 'all-the-icons)
(require 'doom-modeline)
(doom-modeline-init)
(require 'company)
(company-mode)
(require 'company-box)
(company-box-mode)
```
![_emacs_20190127023053](https://user-images.githubusercontent.com/10348978/51791506-2beeba80-21df-11e9-8834-aac6e2604c57.gif)

**Environment:**

- OS: manjaro
- Emacs Version: 27.0.50
- Package version 20190124

**Comment by seagle0128** [comment]
Hmm... I think it's related to `child-frame` feature since 26. I am looking for the solution. Any ideas are welcome!

**Comment by aaronjensen** [comment]
Awesome, thanks @seagle0128, I'll try it out soon.

**Comment by stardiviner** [comment]
great！

**Comment by seagle0128** [comment]
np. But it seems melpa stops building the packages somehow. Have to wait for fixing the building issue.

**Comment by aaronjensen** [comment]
Looks like a new version built.

**Comment by seagle0128** [comment]
Yep, the build system is recovered.

**Comment by aaronjensen** [comment]
It looks like this didn't fix everything: 

![image](https://user-images.githubusercontent.com/8588/52075017-114e7580-2540-11e9-8b66-0d3bd0832ff1.png)

It appears that when using ivy (in the minibuffer), it renders the inactive version.

**Comment by seagle0128** [comment]
@aaronjensen I am using `ivy` and unable to reproduce this issue. Could you please provide more details?

**Comment by aaronjensen** [comment]
I wish I could... it's still intermittent. It happens sometimes in magit too. Just to be clear, you have a similar style difference between your active and inactive modeline, yes?

**Comment by seagle0128** [comment]
No. I am using `doom-themes`. The active and inactive faces are different.

**Comment by aaronjensen** [comment]
Okay, I'll keep an eye out for a reproduction and let you know. Also, I'm on Emacs 27, if that makes a difference.

**Comment by stardiviner** [comment]
I have similar issue, but I check out `other-window` command. Found it has adviced by `save-buffer`. Maybe this is the cause. And @seagle0128 Can you fix doom-modeline works `super-save`?
