### ISSUE TITLE
Add customization for hiding the buffer coding segment

### ISSUE THREAD

**Issue by r-darwish** [seagle0128/doom-modeline#104]
**Is your feature request related to a problem? Please describe.**
I don't need to see the buffer coding in the modeline. When I split my screen vertically I'm lacking space in the mode line, so I'll be happy to hide this segment.

**Describe the solution you'd like**
Some customization variable to hide this specific segment, or a generic way to hide any segment.

**Describe alternatives you've considered**
I don't know any

**Additional context**
None

**Comment by seagle0128** [comment]
Hi, you have a several ways to achieve it.

- Redefine main modeline as below.

```elisp
(doom-modeline-def-modeline 'main
  '(bar workspace-number window-number evil-state matches buffer-info remote-host buffer-position parrot selection-info)
  '(debug minor-modes input-method major-mode process vcs checker))
```
- Use minimal modeline as default.
```elisp
(doom-modeline-set-modeline 'minimal 'default)
```
- Define your own modeline and make it as default.
