### ISSUE TITLE
doommodeline initialization is giving an error

### ISSUE THREAD

**Issue by huseyinyilmaz** [seagle0128/doom-modeline#106]
**Describe**
With the latest update doomline initialization is giving following error:
```doom-modeline-init: Symbol’s value as variable is void: mu4e-alert-modeline-formatter```

**Steps and Expected**
I am using almost default configuration: 
```https://github.com/huseyinyilmaz/emacs-config/blob/440dc2d363362d6602610529cf79371095e9fc2b/lisp/user-init-doommodeline.el```
With this config just start emacs and you should get the error.

**Environment:**
 - OS: MacOS
 - Version 10.14.2
 - Package version: 20190130.1628

**Additional context**
 Screenshots, recordings, logs and/or messages...

**Comment by suryaaditya** [comment]
i see same error after the doom-mode line upgrade today

**Comment by seagle0128** [comment]
Today the PR #105 was merged, and introduced this issue. But I've fixed it. Please upgrad to the latest version.

**Comment by seagle0128** [comment]
@seanfarley could you please look into this issue. I merged #107 as a workaound.

**Comment by darth10** [comment]
I got the same issue after upgrading today.
Thanks for the speedy fix @seagle0128!

**Comment by huseyinyilmaz** [comment]
@seagle0128 Thank you for fixing this.

I downloaded version `20190130.1935` and confirmed that problem is solved.

**Comment by seanfarley** [comment]
Oops! Sorry for the error!
