### ISSUE TITLE
Show Python virtualenv in mode line version

### ISSUE THREAD

**Issue by gpanders** [seagle0128/doom-modeline#109]
**Is your feature request related to a problem? Please describe.**
The Python version in the modeline tells me the number of the Python version I am using, but this is often not as useful to know as the virtual environment I am in.

**Describe the solution you'd like**
If I am using a virtual environment (I use pyenv) then display the name of my virtual environment instead of the Python version number.

**Describe alternatives you've considered**
I have tried setting the `doom-modeline-python-executable` function to `"pyenv"`, but this package adds a lambda to `python-mode-hook` that sets the command args to `--version`, which just returns the version number of `pyenv`. `pyenv version` (without the dashes) returns the name of the Python virtualenv/version is currently active in the shell.

Alternatively, support for [pyenv-mode](https://github.com/proofit404/pyenv-mode) where the Python version string in the modeline shows the version set by that package (obtained from the function `(pyenv-mode-version)`). Currently the `doom-modeline-env` functions only support shell commands and not Elisp functions.

**Comment by seagle0128** [comment]
Now `venv` is supported and recommended. If you still want to use `pyenv`, PR is welcome. I am on the vacation and have no effort to implement it.
