### ISSUE TITLE
undefined function doom-modeline-fix-anzu-count

### ISSUE THREAD

**Issue by CeleritasCelery** [seagle0128/doom-modeline#11]
I pulled the latest version of doom modeline and I am now getting the error `undefined function doom-modeline-fix-anzu-count` when ever I search. Removing the `eval-when-compile` wrapper fixed the issue for me. I think the problem is if `evil-anzu` has not been loaded when `doom-modeline` is compiled then this function never gets defined.

**Comment by seagle0128** [comment]
Thanks for the reporting. Fixed and please test.
