### ISSUE TITLE
custom modeline is not set as default

### ISSUE THREAD

**Issue by guidoschmidt** [seagle0128/doom-modeline#111]
**Describe**
My custom defined doom-modeline doesn't get set as default modeline

**Steps and Expected**
I use doom-modeline with `use-package` like this.

```elisp
(use-package doom-modeline
  :ensure t
  :config
  (defvar skycolor-clock)
  (doom-modeline-def-segment skycolor-clock
    (sky-color-clock))

  (defvar custom-evil-state)
  (doom-modeline-def-segment custom-evil-state
    (evil-state-char))

  (setq find-file-visit-truename t)
  (setq doom-modeline-bar-width 3)
  (setq doom-modeline-height 20)
  (setq doom-modeline-buffer-file-name-style 'truncate-upto-project)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-lsp t)

  (doom-modeline-def-modeline 'gs
    '(bar buffer-encoding buffer-info)
    '(vcs skycolor-clock custom-evil-state))
  (doom-modeline-set-modeline 'gs 'default)
  :hook
  (after-init . doom-modeline-mode))
```

Unfortunatelly the default modeline is present at all buffers. Using `(doom-modeline-set-modeline 'gs)` I can temporarily make my custom modeline appear, but switching to another buffer, the default modeline is still presented.

**Environment:**
 - OS: macOS
 - Version 10.14.2
 - Package version 20190201.248

**Comment by guidoschmidt** [comment]
👍 nice! that worked. Could be pointed out more in the README 🙃

**Comment by chasote** [comment]
Can you please clarify how you solved this issue? I have made multiple attempts at following the instructions and can not get my custom modeline to work. Thank you for any assistance!
```
(use-package doom-modeline
  :hook
  (after-init . doom-modeline-mode)
  :config
  (setq doom-modeline-buffer-file-name-style 'relative-from-project
	doom-modeline-icon t
	doom-modeline-major-mode-icon t)
  (doom-modeline-def-modeline 'custom
			      '(bar buffer-info buffer-position)
			      '(major-mode checker))
  (defun setup-custom-modeline ()
    (doom-modeline-set-modeline 'custom 'default))
  (add-hook 'doom-modeline-mode 'setup-custom-doom-modeline))

**Comment by chasote** [comment]
@guidoschmidt @seagle0128

**Comment by chasote** [comment]
I've tried setting the :hook init portion at the end of the config as well in line with the .emacs.d file I found in your repository. Still doesn't work.
