### ISSUE TITLE
Setting `doom-modeline-bar-width` to 0 shows a ugly square

### ISSUE THREAD

**Issue by lshoravi** [seagle0128/doom-modeline#115]
**Describe**
Setting `doom-modeline-bar-width` to 0 shows a ugly square

**Steps and Expected**
`M-: (setq doom-modeline-bar-width 0)`

**Environment:**
 - OS: Opensuse TW
 - Package version: 20190204

**Additional context**
![image](https://user-images.githubusercontent.com/42211142/52538344-d33c2780-2d71-11e9-8d45-9e18507fda42.png)

**Comment by seagle0128** [comment]
You shouldn't set `doom-modeline-bar-width` to 0. If you want to hide bars, you need to define faces of `doom-modeline-bar` and `doom-modeline-inactive-bar`.

**Comment by radarbrokers** [comment]
If you just want to hide the bar, just set its color to match mode-line:

```elisp
(set-face-background 'doom-modeline-bar (face-background 'mode-line))
```
