### ISSUE TITLE
Ugly square somehow related to doom-modeline-bar-width

### ISSUE THREAD

**Issue by wbthomason** [seagle0128/doom-modeline#116]
**Describe**
I get the exact same visual error as #115, but without ever setting `doom-modeline-bar-width`. Manually setting `doom-modeline-bar-width` to any non-zero value after a GUI window has loaded removes the box. I'm not sure how to make this go away without needing to manually set this value in every new window.

**Steps and Expected**
Steps to reproduce the behavior: Start Emacs. Observe box. `M-: (setq doom-modeline-bar-width 3)`. Observe the box goes away.

I would expect that the box would never appear, as nothing in my config should be modifying `doom-modeline-bar-width`, and `M-: (print doom-modeline-bar-width)` while the box is showing returns 6.

**Environment:**
 - OS: Arch Linux
 - Package version [e.g. 20190211]

**Additional context**
The screenshot in #115 shows what I see.

**Comment by wbthomason** [comment]
I'm using Emacs 26.1, with no DE (just i3 as a WM). I have added that to my config - both in an `:init` block and a `:config` block with `use-package`, but it does not fix the issue.

The relevant part of my config: 
```elisp
(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-mode)
  :config (setq doom-modeline-bar-width 3
                doom-modeline-enable-word-count t
                doom-modeline-icon t
                doom-modeline-major-mode-icon t
                doom-modeline-major-mode-color-icon t
                doom-modeline-lsp t))
```

**Comment by seagle0128** [comment]
The bars only respect GUI. Can you share the command of `emacsclient`?

**Comment by wbthomason** [comment]
`emacsclient --create-frame`. All of my testing has been with GUI Emacs, yep.

**Comment by seagle0128** [comment]
I tested on Manjaro/i3WM with GNU Emacs 27. Both `emacs` and `emacslcient` work well. My config is: https://github.com/seagle0128/.emacs.d . 

![image](https://user-images.githubusercontent.com/140797/52653655-5f457f00-2f2b-11e9-9e93-cb457eb73dfd.png)

The bars will be drawn on GUI, unless `create-image` fails. If so need to check emacs itself.
I am thinking the workaround is to set `doom-modeline-bar-width` in `make-frame`.
e.g.
```elisp
(advice-add #'make-frame :after #'my-set-doom-modeline-bar-width)
```

**Comment by wbthomason** [comment]
That's very strange. Adding the advice unfortunately doesn't help; neither does using a hook approach. I tried
```elisp
(advice-add #'make-frame :after (lambda (&rest r) (setq doom-modeline-bar-width 3)))
```
and
```elisp
(add-hook 'after-make-frame-functions (lambda (frame) (setq doom-modeline-bar-width 3)))
```
but neither had an effect. 

Because you mentioned the bar might not be drawn if `create-image` fails, I checked `*Messages*` and noticed the error
```
Color allocation error ((image :type xpm :data /* XPM */
static char * percent[] = {
"3 25 2 1",
". c brightblack",
"  c brightblack","...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"...",
"..."}; :scale 1 :ascent center))
```
repeating. That seems potentially relevant?

Do you use an AUR package for Emacs 27? If so, I can try installing that to see if the behavior is specific to 26.1

**Comment by seagle0128** [comment]
Yes, I am using Emacs 27 from AUR.

**Comment by wbthomason** [comment]
Unfortunately, the change in versions doesn't change anything. I'll keep poking at workarounds related to the apparent `emacsclient` cause for the issue. Thanks for the patience and help!

**Comment by seagle0128** [comment]
Obviously `create-image` doesn't work somehow in your env. I think it' related to emacs and DE.

Try this workaround:
```elisp
(add-hook 'after-make-frame-functions #'doom-modeline-refresh-bars)
```

**Comment by wbthomason** [comment]
Ah! The colorscheme was the problem - I was using one of the Base16 themes; when I switch to a custom theme I wrote, the box goes away. I'll investigate how to fix the Base16 theme. Thank you again for all your help and patience!
