### ISSUE TITLE
Doomline not showing up

### ISSUE THREAD

**Issue by 4goodapp** [seagle0128/doom-modeline#117]
**Describe**
I just try to install doom-modeline It gives me a warning message and not applying.

**Steps and Expected**
I added this in my init file and expect it works

```
(use-package  eldoc-eval ;;not sure if I need this
  :config
  (autoload 'eldoc-in-minibuffer-mode "eldoc-eval")
  (eldoc-in-minibuffer-mode 1)
  )

(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  )
```
I get this warning message:
`Error (use-package): eldoc-eval/:config: Autoloading file ~/EMACS_CONFIGS/my_emacs/elpa/eldoc-eval-0.1/eldoc-eval.elc failed to define function eldoc-in-minibuffer-mode [2 times]`
___
using just the following code in my init file, I get this on message buffer:
```
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  )
```
`byte-code: Symbol’s function definition is void: eldoc-in-minibuffer-mode`

**Environment:**
 - OS: Linux
 - Version 26.1
 - Package version: 1.7.1

**Additional context**

 Screenshots, recordings, logs and/or messages...

![image](https://user-images.githubusercontent.com/6249230/52665514-b46d9a80-2f03-11e9-8365-2caa7150a378.png)

**Comment by seagle0128** [comment]
Please double check if `eldoc-eval` is installed correctly. I suggest to reinstall it. The latest version is ` 20190106.2000`.

**Comment by 4goodapp** [comment]
I find the issue, I had the following in my init file which pinned the oldest version of eval-eldoc-0.1 from GNU ELPA:

```
  (setq package-archives
      '(("GNU ELPA"     . "https://elpa.gnu.org/packages/")
        ("MELPA Stable" . "https://stable.melpa.org/packages/")
        ("MELPA"        . "https://melpa.org/packages/"))
      package-archive-priorities
      '(("GNU ELPA"     . 10)
        ("MELPA Stable" . 5)
        ("MELPA"        . 0)))

```
