### ISSUE TITLE
Height too big and not constant

### ISSUE THREAD

**Issue by wrachwal** [seagle0128/doom-modeline#118]
**Issues**
* Default height takes *too* much vertical space (not good for "modern" TV-like displays)
* Height 'jumps' depending on contents
* Text not ideally v-centered (maybe not feasible to achieve)

**Environment:**
- Linux, Ubuntu 18.04 LTS
- 2560 x 1600 (16:10) display, "scaling factor for menu and title bars" (1,12)
- zero configuration, only height being set when not default
- current master, but noticed weeks ago, presumably when height was increased to 44
* 38a3930 2019-02-14 Remove doom-modeline--github-open-notifications.

**GIFs**
* doom-modeline-height = 44, default value
![doom-height-44-default](https://user-images.githubusercontent.com/59827/52816091-c0429380-30a0-11e9-9d41-4388b943b577.gif)
* doom-modeline-height = 25
![doom-height-25](https://user-images.githubusercontent.com/59827/52815925-3eeb0100-30a0-11e9-9a4d-ac450ea7fe05.gif)

**Comment by seagle0128** [comment]
Obviously, `doom-modeline` is not applied to the `*Messages*` buffer in your env.
Try `M-x eval-expression RET (doom-modeline-set-main-modeline)` in `*Messages*` buffer.

Regarding `doom-modeline-height`, it's up to the font of Emacs.
```elisp
(defvar doom-modeline-height (let ((font (face-font 'mode-line)))
                               (if (and font (fboundp 'font-info))
                                   (* 2 (aref (font-info font) 2))
                                 25))
  "How tall the mode-line should be (only respected in GUI Emacs).")
```

**Comment by noctuid** [comment]
Why is there extra space at the top compared to the normal modeline, and is there any way around that?

**Comment by seagle0128** [comment]
Because icons is displayed in `doom-modeline`. Try disable icons or run emacs
 in terminal.

**Comment by noctuid** [comment]
Do you know extra space is required above the icons? They don't visually take up nearly the amount of extra space required above them, and decreasing the height will eliminate the extra space below them. It looks like this is also the case for spaceline with icons too and is probably just a limitation of using icons in the modeline, but I'm curious why it happens.

**Comment by seagle0128** [comment]
`all-the-icons` displays the icons with adjust and height properties, which needs some extra space to show. For details, please query to all-the-icons.
