### ISSUE TITLE
How to hide match segment which shows the "blue" line.

### ISSUE THREAD

**Issue by c0001** [seagle0128/doom-modeline#12]
Hi seagle0128:

Thanks for extract the doom-modeline from doom-emacs.

With the view hours usage for it, I really loved the simple way and pure visualization experience of
this package, but I also found something which I want it to be hidden ---> the blue line segment
which holds the evil-search info or sth else.

````
+---------+-+------------------------------------------------------------------------+
|eyebrowse| |                                                                        |
+---------+-+------------------------------------------------------------------------+
           ^
           |
           |
           |
           |
           |
       this blue segment
````

How can I hide it because that I didn't use evil and anzue, iedit or other windows number package?
(I've read the raw code, but without any thoughts for leading movables of actual action based on the elisp skill on the current stage of my emacs career.)

Hope for your help 😃

**Comment by seagle0128** [comment]
This segment is `matches` for searching and replacing including isearch, iedit, anzu, evil-anzu. If you don't need it, you can add this to your config after loading `doom-modeline`.

```elisp
(doom-modeline-def-modeline main
                            (workspace-number window-number bar matches " " buffer-info buffer-position  " " selection-info)
                            (global buffer-encoding major-mode vcs flycheck))
```

**Comment by seagle0128** [comment]
@c0001 if there is no issue, I will close it. Please feel free to reopen if you still have question.

**Comment by c0001** [comment]
Sorry for fiew days lagging for replying for the terrible wall break :smile: :

Thanks for give's me the key prompt for looking round of this issue.

The mainly assumed by me was wrong, that this is not the problem about evil-panel, it's the problem
about modeline bar.

This is my hacking:


- First was remove the bar modeline enable from all doom-modeline type
``` emacs-lisp
(doom-modeline-def-modeline main
                            (workspace-number window-number  matches " " buffer-info buffer-position  " " selection-info)
                            (global buffer-encoding major-mode vcs flycheck))

(doom-modeline-def-modeline minimal
                            (workspace-number  matches " " buffer-info)
                            (media-info major-mode))

(doom-modeline-def-modeline special
                            (workspace-number window-number  matches " " buffer-info-simple buffer-position " " selection-info)
                            (global buffer-encoding major-mode flycheck))

(doom-modeline-def-modeline project
                            (workspace-number window-number  buffer-default-directory)
                            (global major-mode))

(doom-modeline-def-modeline media
                            (workspace-number window-number  " %b  ")
                            (global media-info major-mode))

```

But when I saw the nature of this problem I found that actually I just want it be the same color with eyebrowse-workspace color, thus the following hacking was simple for approach this:

``` emacs-lisp
    (set-face-attribute 'doom-modeline-eyebrowse nil :inherit highlight)
    
    ;; eyebrowse workspace face was inherit from hightlight which was the same one defface in doom-modeline-bar so that this setting will make bar and eyebrowse workspace modeline segment'sbackground merging into the same block visual.

```

And going on for the hacking , I prefer to using my own face for above thing , then the hacking like this was nice for me:

``` emacs-lisp
(use-package doom-modeline
    :load-path "your path for forked of doom-modline"
    :hook (after-init . doom-modeline-init)
    :config
    (use-package eldoc-eval
      :init (setq eldoc-eval-preferred-function 'eval-expression))

    (setq doom-modeline-buffer-file-name-style 'file-name)

    (defface doom-modeline-eyebrowse-dirived '((t ()))
      "The face used for eyebrowse dirived workspace.")

    (set-face-attribute 'doom-modeline-eyebrowse-dirived nil
                        :background "#deaa00" :foreground "purple4" :bold t)
    
    (doom-modeline-def-segment workspace-number
      "The current workspace name or number. Requires
`eyebrowse-mode' to be enabled."
      (if (and (bound-and-true-p eyebrowse-mode)
               (< 0 (length (eyebrowse--get 'window-configs))))
          (let* ((num (eyebrowse--get 'current-slot))
                 (tag (when num (nth 2 (assoc num (eyebrowse--get 'window-configs)))))
                 (str (if (and tag (< 0 (length tag)))
                          (concat (int-to-string num) ":" tag)
                        (when num (int-to-string num)))))
            (propertize (format " %s " str)
                        'face (if (string-match-p "\\.[[:digit:]]" str)
                                  'doom-modeline-eyebrowse-dirived
                                'doom-modeline-eyebrowse)))
        ""))
    (set-face-attribute 'doom-modeline-eyebrowse nil
                        :background "black" :foreground "yellow" :bold t)
    (set-face-attribute 'doom-modeline-bar nil :background "black")
    (doom-modeline-refresh-bars))
```

Above hacking is about that:
- resetting the eyebrowse-tag segment bg and fg color
- resetting the bar segment color be same eyebrowse tag.
- let eyebrowse tag segment also show the slot number either with the tag name.
- changing eyebrowse workspace segment when swithing to the special workspace.

The illustrator for review like be:
![img](https://github.com/c0001/entropy-github-snippets/blob/master/demo-doom-line.gif)

**Comment by seagle0128** [comment]
Good to know you address the issue with customizing the `doom-modeline`.

**Comment by c0001** [comment]
Thanks for your contribution of  both of your [centaur-emacs](https://github.com/seagle0128/.emacs.d) and this `doom-modeline`.

For general view, my emacs  config was 99% dirived from your  `centaur-emacs` , because of that is pure and laconical for emacs newbie as me. From the learning process with your emacs config, promoting my knowledge-base about how to build my own simple sets of config for daily using.

Fiew moths ago, I was drooled over the modern and laconical visual style of  `doom-emacs`, especially for it's modeline visualization for a long time and hope that gods (DALAO) to extract it and let it be the open interface in melpa. And you did it 🌞 ! Nice 💯

**Comment by seagle0128** [comment]
@c0001 Glad you like and benefit from them 😄
