### ISSUE TITLE
The icons for GIT branch and Flycheck are not resolved in emacs client

### ISSUE THREAD

**Issue by deepakjacob** [seagle0128/doom-modeline#120]
**Describe**
The icons for GIT branch and Flycheck are not resolved in `emacs client` mode in iterm2 window.
Please note that `all-the-icons` font is installed and works in an expected manner when emacs is running in GUI mode

**Steps and Expected**

1.  Run `$ emacs --daemon` in an iterm 2 instance
2. Run `$ emacs -nw .` or `$ emacsclient -t` to open emacs in client mode
3. Configure iterm to use `all-the-icons` as the ASCII font (see the 3rd image - to see how to configure)

The issue is happening because `doom-modeline` loads fonts from multiple sources (not all icons are from `all-the-icons`

Expectation: The icons should show correct representation regardless of the mode used.

**Environment:**
emacs --version: GNU Emacs 26.1
OS: Mac OSX Mojave

**Additional context**
 See the images below there are two `?` characters shown for GIT and Flycheck status (bottom right)

<img width="1440" alt="screen shot 2019-02-22 at 1 29 02 pm" src="https://user-images.githubusercontent.com/100649/53263424-66952700-36a7-11e9-9c2d-73a40f188210.png">

When ran in GUI mode - works as expected.

<img width="1362" alt="screen shot 2019-02-22 at 1 31 16 pm" src="https://user-images.githubusercontent.com/100649/53263465-7ca2e780-36a7-11e9-8d99-43d0ae438563.png">

Iterm2 configuration
<img width="914" alt="screen shot 2019-02-22 at 1 42 19 pm" src="https://user-images.githubusercontent.com/100649/53263576-c986be00-36a7-11e9-88d0-c92f8c68ab25.png">

**Comment by seagle0128** [comment]
`all-the-icons` includes a several fonts actually. Refer to https://github.com/domtronn/all-the-icons.el#resource-fonts . iterm2 only supports one Non-ASCII font in the setting, so only displays some icons correctly. In you screenshots, only icons of `all-the-icons` font are displayed, while not for `fontawesome`, `material` and others. In the terminal, the recommendation is not using icons. The ultimate solution is using another font like `icons-in-terminal`, but there is no elisp lib so far.
