### ISSUE TITLE
% symbol not displayed in global string

### ISSUE THREAD

**Issue by yyoncho** [seagle0128/doom-modeline#121]
**Describe**
When a variable added to global-mode-line string contains % it is not rendered properly in doom-modeline(the % is missing). I tested the same piece of code in emacs -q and it works fine. 

**Steps and Expected**
```
(defcustom test-var2 "Test %" "")
(add-to-list 'global-mode-string (list '(t test-var2)))
(setq test-var2 "This % wont be displayed")
```
**Environment:**
 - OS: linux 
 - Version [e.g. 10]
 - Package version - `doom-modeline-20190204.918`

**Comment by seagle0128** [comment]
try "%%"?

**Comment by yyoncho** [comment]
%% works but the code is not doom specific and the result is that it displays %% when you are not using doom-modeline. Here it is the relevant commit: https://github.com/emacs-lsp/lsp-java/commit/aa726746a35e0cab69a6fd198a128395d71419fc

**Comment by seagle0128** [comment]
The root cause is `format-mode-line`.

```elisp
(format-mode-line '("test %")) ; => "test "
(format-mode-line '("test %%")) ; => "test %"
```

**Comment by seagle0128** [comment]
@yyoncho Can you try this solution, please?

```elisp
(doom-modeline-def-segment misc-info
  "Mode line construct for miscellaneous information.
By default, this shows the information specified by `global-mode-string'."
  (if (doom-modeline--active)
      (replace-regexp-in-string (regexp-quote "%") "%%%%"
                                (format-mode-line mode-line-misc-info)
                                t t)))
```

**Comment by yyoncho** [comment]
@seagle0128 it seems like after this change it works fine. Thank you.

**Comment by seagle0128** [comment]
Then I will commit it first. I am not sure if it has side-effects. Please do more tests and let me know if you have the issue.

**Comment by yyoncho** [comment]
Found an issue - when doing you should preserve the original face of the % otherwise it will appear with default face but the original might be propertized(not sure what is the proper way to do that).

**Comment by seagle0128** [comment]
@yyoncho Don't know how to reproduce and fix it 😞

**Comment by yyoncho** [comment]
Hm, I am a bit struggling to provide a script to reproduce it since doom-modeline is behaving a bit inconsistetly . So, when I propertize a string and then put it in global-string doom-modeline just ignores but when lsp-java is doing  that the face appears properly but only the % is not with the proper face(due to the replace % code).

The face is ignored:

``` emacs-lisp
(defcustom test-var2 "Test %" "")
(add-to-list 'global-mode-string (list '(t test-var2)))
(setq test-var2 (propertize "Some %" 'face 'lsp-java-progress-face)) ;; or 'success face
```
Here it is what I get with lsp-java progress reporting:

![Selection_114](https://user-images.githubusercontent.com/13259670/54090151-c531f480-4379-11e9-88eb-f52ea15321cd.png)

**Comment by seagle0128** [comment]
@yyoncho I am able to reproduce it with `(add-to-list 'global-mode-string '(:eval test-var2))`.
