### ISSUE TITLE
Support keycast

### ISSUE THREAD

**Issue by jhenahan** [seagle0128/doom-modeline#122]
[`keycast`](https://github.com/tarsius/keycast) is a package from tarsius which prints the last keybinding pressed along with its associated function in the modeline. I think it's a nice bit of discoverability for existing keybindings, and it'd be pleasant to see it supported in a featureful modeline.

I've been hacking around a bit to see if I can port the approach that was taken for `minions` since they work similarly, but so far I haven't made much progress. I'm planning to spend some more dedicated hacking time this weekend, but if you beat me to it then I won't be mad. 😄

**Comment by seagle0128** [comment]
The simplest way is adding `keycast` to `global-mode-string`.

```elisp
(add-to-list 'global-mode-string '("" mode-line-keycast))
```

![image](https://user-images.githubusercontent.com/140797/53473400-ddae2f00-3a9c-11e9-998e-633b1e82d63c.png)

It's hard to enable `keycast-mode` in `doom-modeline` since it will  insert after `mode-line-buffer-identification`.
```elisp
user-error: Cannot turn on keycast-mode.  mode-line-buffer-identification not found in mode-line-format
```

**Comment by seagle0128** [comment]
I am closing it since it seems no question so far.

**Comment by 4goodapp** [comment]
Does this help to make it works with  doom-modeline https://github.com/tarsius/keycast/issues/7#issuecomment-473607503 ?

I don't know much about Elisp.

**Comment by seagle0128** [comment]
@4goodapp It doesn't work for `doom-modeline` or others. You just need `(add-to-list 'global-mode-string '("" mode-line-keycast))` with `doom-modeline`.

**Comment by 4goodapp** [comment]
Thanks.

**Comment by d1egoaz** [comment]
@4goodapp did you manage to use keycast?

**Comment by d1egoaz** [comment]
It's now working for me 🎉 
https://github.com/tarsius/keycast/issues/7#issuecomment-627604064

**Comment by Gleek** [comment]
keycast seems to give out the error even after adding to `global-mode-string`. I had to add `pre-command-hook` to run `keycast--update` manually to get it to work. This is what I have in my config.
```elisp
(use-package keycast
  :bind ("C-c t k" . +toggle-keycast)
  :config

  (defun +toggle-keycast()
    (interactive)
    (if (member '("" mode-line-keycast " ") global-mode-string)
        (progn (setq global-mode-string (delete '("" mode-line-keycast " ") global-mode-string))
               (remove-hook 'pre-command-hook 'keycast--update)
               (message "Keycast disabled"))
      (add-to-list 'global-mode-string '("" mode-line-keycast " "))
      (add-hook 'pre-command-hook 'keycast--update t)
      (message "Keycast enabled"))))

**Comment by d1egoaz** [comment]
@Gleek it was also failing for me, not sure since when

I modified my previous config to use your pre-hook command and it's working again!

```emacs-lisp
(after! keycast
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
        (add-hook 'pre-command-hook 'keycast--update t)
      (remove-hook 'pre-command-hook 'keycast-mode-line-update)))
  (setq keycast-substitute-alist '((evil-next-line nil nil)
                                   (evil-previous-line nil nil)
                                   (evil-forward-char nil nil)
                                   (evil-backward-char nil nil)
                                   (ivy-done nil nil)
                                   (self-insert-command nil nil))))
(add-to-list 'global-mode-string '("" mode-line-keycast))
(keycast-mode)
```

**Comment by AtomicNess123** [comment]
"Symbol’s function definition is void: after!" I am on Emacs Prelude and this is not working. Any ideas?

**Comment by d1egoaz** [comment]
> "Symbol’s function definition is void: after!" I am on Emacs Prelude and this is not working. Any ideas?

`after!` is a macro for doom users.

Use the `non doom-emacs users` code from https://github.com/tarsius/keycast/issues/7#issuecomment-627604064

**Comment by AtomicNess123** [comment]
Still, I don't see the key strokes anywhere in my doom mode line :(

**Comment by Gleek** [comment]
@AtomicNess123 have you already tried the snippet I [posted above](https://github.com/seagle0128/doom-modeline/issues/122#issuecomment-780683648). 
If that doesn't work, can you double check if your `global-mode-string` and ensure that it has `mode-line-keycast`. Try running  `keycast--update` manually to see if it updates after that.

**Comment by AtomicNess123** [comment]
Now it works! Somehow I needed to restart my emacs. Thank you.

**Comment by wang1zhen** [comment]
As a minor reminder, the `mode-line-keycast` has been renamed to `keycast-mode-line`, so the snippet should be updated to
```elisp
(add-to-list 'global-mode-string '("" keycast-mode-line))
```

**Comment by ghoseb** [comment]
Sharing an updated snippet for *non doom-emacs* users.
This is based on the snippet by @Gleek and the updated comment from @wang1zhen 

```elisp
(use-package keycast
  ;; uncomment this if you're using straight.el
  ;:straight t
  :bind ("C-c t k" . +toggle-keycast)
  :config
  (defun +toggle-keycast()
    (interactive)
    (if (member '("" keycast-mode-line " ") global-mode-string)
        (progn (setq global-mode-string (delete '("" keycast-mode-line " ") global-mode-string))
               (remove-hook 'pre-command-hook 'keycast--update)
               (message "Keycast OFF"))
      (add-to-list 'global-mode-string '("" keycast-mode-line " "))
      (add-hook 'pre-command-hook 'keycast--update t)
      (message "Keycast ON"))))
```

**Comment by laampui** [comment]
Recently, `keycast-mode` has been updated and added `keycast-mode-line-mode`. I would like to customize the `keycast-mode-line-insert-after`, but `doom-mode-line` has been already customize `mode-line-format` to `("%e"
 (:eval
  (doom-modeline-format--main)))`. Any help how to adapt the newest version of `keycast` package? Thanks @seagle0128

**Comment by seagle0128** [comment]
@lasmpui Try `(setq keycast-mode-line-insert-after '(:eval (doom-modeline-format--main)))`.

**Comment by laampui** [comment]
```lisp
(use-package keycast
  :after (doom-modeline dashboard)
  :config
  (setq keycast-mode-line-insert-after '(:eval (doom-modeline-format--main)))
  (add-to-list 'global-mode-string '("" keycast-mode-line))
  :hook
  (doom-modeline-mode . keycast-mode-line-mode))
```

@seagle0128  with this setting, everything looks fine except in `dashboard-mode`, because there is a `
 (:eval
  (doom-modeline-format--dashboard))`

![image](https://user-images.githubusercontent.com/15785343/206883156-645880a2-4b0b-4743-895c-a247bfa7b9db.png)

**Comment by seagle0128** [comment]
@laampui Actually `doom-modeline-format--main` is applicable for the most of cases, not for other mode-lines, e.g. dashboard, special, vcs, package, etc.

**Comment by mishrasubhajit** [comment]
> ```emacs-lisp
> (use-package keycast
>   ;; uncomment this if you're using straight.el
>   ;:straight t
>   :bind ("C-c t k" . +toggle-keycast)
>   :config
>   (defun +toggle-keycast()
>     (interactive)
>     (if (member '("" keycast-mode-line " ") global-mode-string)
>         (progn (setq global-mode-string (delete '("" keycast-mode-line " ") global-mode-string))
>                (remove-hook 'pre-command-hook 'keycast--update)
>                (message "Keycast OFF"))
>       (add-to-list 'global-mode-string '("" keycast-mode-line " "))
>       (add-hook 'pre-command-hook 'keycast--update t)
>       (message "Keycast ON"))))
> ```

Hi, this works fine until there are split screens. In that case, keycast works for the newest screen. Any help? I tried some tinkering but there was no solution. Thanks!

**Comment by seagle0128** [comment]
@mishrasubhajit Not sure if you need `doom-modeline-display-misc-in-all-mode-lines`.
