### ISSUE TITLE
Error on opening new file on Windows (invalid-regexp "Trailing backslash")

### ISSUE THREAD

**Issue by Zulu-Inuoe** [seagle0128/doom-modeline#123]
**Describe**
On attempting to `find-file` on a new file with `doom-modeline` active I get an error and the file fails to open.

**Steps and Expected**
1. On Windows, have the `HOME` environment variable set to eg: `C:\Users\Zulu\`
2. With `doom-modeline` active, `find-file` and type the name of a non-existent file to create  a new one.
3. Press RET

The minibuffer will report an error. I've toggled error-on-error and here is the backtrace:

```
Debugger entered--Lisp error: (invalid-regexp "Trailing backslash")
  string-match("^C:\\Users\\Zulu\\" "c:/Users/" 0)
  replace-regexp-in-string("^C:\\Users\\Zulu\\" "~" "c:/Users/")
  shrink-path--dirs-internal("c:/Users/" t)
  doom-modeline--buffer-file-name("c:/Users/Zulu/file.txt" "~/file.txt" shrink)
  doom-modeline-buffer-file-name()
  doom-modeline-update-buffer-file-name()
  run-hooks(find-file-hook)
```

I have actually traced this issue to be usage of `getenv` directly as the input to `replace-regexp-in-string` in `shrink-path.el` line 55:

```lisp
(let* ((home (getenv "HOME"))
       (path (replace-regexp-in-string
              (s-concat "^" home) "~" full-path)))
  ...)
````

I've submitted a pull request here:

https://gitlab.com/bennya/shrink-path.el/merge_requests/1

which changes `(getenv "HOME")` to `(expand-file-name "~")` so it yields an emacs-portable file name to use ("c:/Users/Zulu" on my system).

However, the maintainer has not responded and it has been some time. So I'm opening it here to get some more visibility since it makes `doom-modeline` (and projects that use it) unusable on some Windows systems.

Thank you!

**Environment:**
 - OS: Windows x64
 - Version: 10
 - Package version `20190228.1658`

**Additional context**
None.

**Comment by seagle0128** [comment]
You may notice this issue https://gitlab.com/bennya/shrink-path.el/issues/2 was filed by me.

In fact, there is a simple workaround to address:  `Set $HOME to  C:\Users\Zulu`,
or override `shrink-path--dirs-internal`.

**Comment by Zulu-Inuoe** [comment]
Thanks! 

Sorry, I didn't notice it was you who filed that issue.
I suggested changing HOME as you said to a user in https://github.com/portacle/portacle/issues/106
And though that user says it didn't fix it, I'm inclined to believe that their emacs didn't get the updated env var.

However, I'd still like it fixed just to avoid issue in the future for other users who (like me) define HOME this way. 
In case you're curious: it's paranoid response to a program long ago doing The Wrong Thing because HOME didn't end with a slash.

So while that's a workaround, I do hope we hear from @bandresen

**Comment by seagle0128** [comment]
I think it's fine to redefine or override `shrink-path--dirs-internal` in your codes, since it's long time to waiting for the author's feedback. I will add this into `doom-modeline` soon.

```elisp
(defun shrink-path--dirs-internal (full-path &optional truncate-all)
  "Return fish-style truncated string based on FULL-PATH.
Optional parameter TRUNCATE-ALL will cause the function to truncate the last
directory too."
  (let* ((home (getenv "HOME"))
         (path (replace-regexp-in-string
                (s-concat "^" home "$") "~" full-path))
         (split (s-split "/" path 'omit-nulls))
         (split-len (length split))
         shrunk)
    (->> split
         (--map-indexed (if (= it-index (1- split-len))
                            (if truncate-all (shrink-path--truncate it) it)
                          (shrink-path--truncate it)))
         (s-join "/")
         (setq shrunk))
    (s-concat (unless (s-matches? (rx bos (or "~" "/")) shrunk) "/")
              shrunk
              (unless (s-ends-with? "/" shrunk) "/"))))
```

**Comment by Zulu-Inuoe** [comment]
@seagle0128 That results in an incorrect replace when `HOME` uses backslashes as opposed to forward slashes.
If you use `(expand-file-name "~")` you'll get the right behaviour

**Comment by seagle0128** [comment]
@Zulu-Inuoe  Doesn't `(s-concat "^" home "$")` work for you? I tested it and works well in my env.

**Comment by Zulu-Inuoe** [comment]
@seagle0128 It doesn't error, but it also fails to shrink paths under the home directory.

My `~/.emacs.d/init.el` is bring 'shrunk' to `/c/U/Z/.emacs.d/init.el` using your change because it's trying to regex `^C:\Users\Zulu\$` with `c:/Users/Zulu/` and failing

**Comment by Zulu-Inuoe** [comment]
Additionally, I don't think you want the "$" there in any case since it won't generally match.

Leaving the code as was, but replacing the getenv will make it work as intended while not introducing weird cases with HOME having or not having an ending slash

**Comment by seagle0128** [comment]
Okay. I will commit again.
