### ISSUE TITLE
buffer-info loses face after frame focus

### ISSUE THREAD

**Issue by seanfarley** [seagle0128/doom-modeline#133]
**Describe**
It appears (at least in emacs 26) that the buffer name loses its color after switching frames.

**Steps and Expected**
Run doom (you don't need to enable doom's :modeline). Then switch frames to something else. The color is lost as the screenshots can show.

**Environment:**
 - OS: macos
 - Version 10.13
 - Package version doom-modeline-20190304.1702

**Additional context**
<img width="497" alt="screen shot 2019-03-04 at 6 59 52 pm" src="https://user-images.githubusercontent.com/20887/53779800-74705680-3eb6-11e9-818c-ea1f14066d7e.png">
<img width="305" alt="screen shot 2019-03-04 at 7 00 27 pm" src="https://user-images.githubusercontent.com/20887/53779801-74705680-3eb6-11e9-899a-dede8fd9cafa.png">

@hlissner says it's from a divergence in code (not sure the exact cause) but I'm just putting this here for my own sanity :-)

**Comment by seagle0128** [comment]
It may be caused by https://github.com/seagle0128/doom-modeline/commit/c69ec1e5c556a5cbbd4b47abc824e6180227e91a. I am investigating.

**Comment by seanfarley** [comment]
Thanks, it seems fixed now!
