### ISSUE TITLE
强制Daemon启动也使用GUI的mode-line format

### ISSUE THREAD

**Issue by cireu** [seagle0128/doom-modeline#134]
**Is your feature request related to a problem? Please describe.**
使用systemd以daemon模式启动emacs。在加载配置文件的过程`(display-graphic-p)`的返回值为nil。之后在X Window下用client连接server。all-the-icons不会被默认启用，而且modeline的上下padding也会丢失。

**Describe the solution you'd like**
Emacs 26以后没有了frame local variable。但是可以用frame-parameter。每次更新modeline时判断该部分内容，决定是否按有GUI的方式渲染modeline。

**Describe alternatives you've considered**

**Additional context**

**Comment by cireu** [comment]
想了下不太现实，`mode-line-format`是buffer local变量

不过如何让daemon启动也强制使用GUI的mode-line format呢

**Comment by seagle0128** [comment]
这样的使用方式不对。为何不在GUI下使用`server-mode`?

**Comment by cireu** [comment]
因为在GUI下使用server-mode时Emacs不能隐藏到后台，这样`C-x C-c`按得太爽就把server给杀了

目前的我的尝试是：如果daemon模式下启动，则把`doom-modeline-mode`的挂在after-make-frame-functions`上，否则挂在`after-init-hook`上。这样做是有图标了，但是还是没有padding和左边的小色块

![default](https://user-images.githubusercontent.com/18224684/53876591-196b6a80-4042-11e9-9f7e-fb269cdd8233.png)

**Comment by cireu** [comment]
使用exwm解决问题  :P
