### ISSUE TITLE
doom-modeline showing buffer is modified when it's not 

### ISSUE THREAD

**Issue by haji-ali** [seagle0128/doom-modeline#139]
(Posted originally to `doom`, but reposted here based on @hlissner suggestion)

Open a new file, writing some long text, call `fill-paragraph` on the text, buffer is modified and `doom-modeline` reflects that, save the file, buffer is not modified and `doom-modeline` reflects that. Now, if I call `fill-paragraph` again on the same text, `doom-modeline` shows that the buffer was modified (even though the text hasn't changed), now if save the buffer a message shows "(No changes need to be saved)" but `doom-modeline` keeps showing that the buffer is modified no matter how many times I save.

**Comment by seagle0128** [comment]
I think I know the root cause. Will drop a commit soon. But please help to test in case it brings side-effects.

**Comment by haji-ali** [comment]
Seems working so far. With these two advices on `set-buffer-modified-p` are the other hooks and advices (on saving, undos and other functions) needed? Especially considering `doom-modeline-update-buffer-file-state-icon` depends only on the state of `buffer-modified-p`.

**Comment by seagle0128** [comment]
It's a good question! Perhaps there are some performance issue here. I am investigating...

**Comment by seagle0128** [comment]
I optimize the performance and will keep improving.

**Comment by haji-ali** [comment]
Apologies for opening this again. But it seems that in the latest version the issue described appears again. Strangely, when I call "fill-paragraph" the second time, the filename does not change face (i.e., it still appears as not modified), but the _icon_ shows that the buffer was modified.
