### ISSUE TITLE
Requiring doom-modeline is slow

### ISSUE THREAD

**Issue by noctuid** [seagle0128/doom-modeline#140]
Requiring doom-modeline for the first time takes ~0.13-0.25 seconds (normally a little above 0.2s) according to `benchmark-run` with `emacs -Q`. I tried benchmarking requiring all dependencies and only requiring all-the-icons took a significant amount of time (0.05s). I didn't do any further benchmarking to find out what's taking the rest of the time.

As a side note, I did notice that `doom-modeline-core` adds a lot of advice and hooks and enables `eldoc-in-minibuffer-mode`. Requiring a package shouldn't do things like this (e.g. enabling modes) at the top level; this sort of configuration should be in some setup function.

**Comment by seagle0128** [comment]
You may know that, originally this package was extracted from `doom-emacs` project, although it's a separate one and provides more powerful features. `all-the-icons` and `eval-eldoc` are dependencies of `doom-modeline`. The is a historic issue. Let's try to improve that. Your opinions are welcome! Thanks!

**Comment by noctuid** [comment]
I'm consistently getting around 0.1 second when I profile now (not sure I was getting >0.2 so often before or if I'm missing something).

About half of that is loading all-the-icons. Since it's possible to use doom-modeline without all-the-icons, it might make sense to conditionally require it when functions from all-the-icons are used instead of at the top of the file.

The other half of the time is spent loading shrink-path (~0.02s loading `s` and `f`) and in the code to get the default height of the modeline is ~0.03s (`font-info` is slow). Unless there's a faster way to get a reasonable default height, it looks like there's actually not much room for optimization.

I'll make a separate issue for the second thing I suggested.

**Comment by seagle0128** [comment]
Thanks for the details! It's helpful.

**Comment by seagle0128** [comment]
I reverted this change due to #149 . 
If delay loading `all-the-icons`, it beaks this case: Start `doom-modeline-mode` in emacs daemon and enable `doom-modeline-icon` later in clients.
