### ISSUE TITLE
All the icons icon misalignment when increasing icon scale

### ISSUE THREAD

**Issue by noctuid** [seagle0128/doom-modeline#141]
**Describe**
Copied from domtronn/all-the-icons.el#136
> Changing both `all-the-icons-scale-factor` and `doom-modeline-height` in general does not work well. It results situations where icons are positioned in different areas in the modeline and extra space (e.g. one icon is kind of centered, another is all the way at the bottom of the modeline, etc.).

> There are a lot of magic numbers in doom modeline (e.g. as `:height` arguments in `doom-modeline-segments.el` and `1.2` in `doom-modeline-icon-height`), and I don't know the logic behind the choices. I was able to get things to look better in some cases by messing with these values but didn't really attempt to figure anything out.

This is a very minor issue for me at least because I've come to like the default height and icon size fine, and there are no issues there. It would be nice if the number choice was documented though (e.g. height 1.3 vs. 1.1; looks like a lot of this has been here since the code was originally extracted from doom).

**Steps and Expected**
Increase `doom-modeline-height` and `all-the-icons-scale-factor`. Icons are not centered in the modeline or aligned with each other. The issue is worse as `all-the-icons-scale-factor` increases. For example:
```elisp
(setq doom-modeline-height 50
      all-the-icons-scale-factor 2)
```

**Environment:**
 - OS: Linux
 - Version 4.20.6
 - Package version 5c926b81de74e8d50d7ef9d68ec485d90f295438

**Additional context**
Here is a screenshot:
![2019 03 05_09 45 59_-_org_src_uncleanorg_emacslisp_](https://user-images.githubusercontent.com/4250696/53814301-5d208000-3f2d-11e9-979e-3f075027792a.png)

**Comment by seagle0128** [comment]
It's a historical issue indeed. It looks with normal and smaller scale factor and height, but not good for bigger ones. I will try to improve it if possible. But you mentioned it's a minor issue so no promise so far. Thank you for reporting!

**Comment by seagle0128** [comment]
After the investigation, it seems hard to align all icons for all scale factors. I don't think it's deserved to fix this edge case. If you have a fast way to address, please let me know. Thanks!

**Comment by seagle0128** [comment]
I found a simple way to improve icons alignment, and won't touch all codes about icons.
