### ISSUE TITLE
Buffer does not seem to be associated with any file

### ISSUE THREAD

**Issue by tareefdev** [seagle0128/doom-modeline#147]
Today I updated the doom-modeline package, and after restarting my emacs I got this error:

```
Debugger entered--Lisp error: (error "Buffer does not seem to be associated with any file")
  signal(error ("Buffer does not seem to be associated with any file"))
  error("Buffer does not seem to be associated with any file")
  revert-buffer--default(t t)
  revert-buffer(t t)
  #f(compiled-function (sym val op where) #<bytecode 0x1b6be8d>)(doom-modeline-icon nil set nil)
  (setq doom-modeline-icon nil)
  eval-buffer(#<buffer  *load*-663955> nil
```
I tried to install and require all-the-icons package but this does not solve the problem.
I tried to uninstall the doom-modeline package and the error message does not show any more.

**Environment:**
 - OS: Arch Linux
 - Emacs Version 26.1
 - Package version 20190313.309

**Comment by seagle0128** [comment]
Thanks for reporting! 

Which version did you use before upgrading? Could you please provide more details and steps? I couldn't reproduce it locally.

**Comment by jumper047** [comment]
Today after upgrade got this message - "Error (use-package): doom-modeline/:config: Buffer does not seem to be associated with any file".
Sorry, don't remember version before update. I think i updated it somethin like 1-3 weeks ago.
Modeline config is here:
```
(use-package doom-modeline
    :ensure t
    :defer t
    :hook (after-init . doom-modeline-mode)
    :config
    (setq doom-modeline-buffer-file-name-style 'file-name)
    (setq doom-modeline-icon t)
    ;;(setq doom-modeline-major-mode-icon t)
    (setq inhibit-compacting-font-caches t)
    )
```

**Comment by seagle0128** [comment]
Does the issue still occurs after restarting Emacs?

**Comment by demoore** [comment]
I have the same issue. What worked for me was commenting out:

```elisp
(setq doom-modeline-icon t)
```

**Comment by tareefdev** [comment]
> Thanks for reporting!
> 
> Which version did you use before upgrading? Could you please provide more details and steps? I couldn't reproduce it locally.

Even myself I couldn't reproduce it, using the same config for doom-modeline on another device. Although setting `(setq doom-modeline-icon t)` before `(doom-modeline-init)` worked for me too, the error still appears with `(setq doom-modeline-icon nil)`.

**Comment by seagle0128** [comment]
@demoore @tareefdev Thanks for the information! I think I do know the root cause. Will fix it soon.

**Comment by tareefdev** [comment]
Thanks for your great work.

**Comment by seagle0128** [comment]
@tareefdev Welcome! Since there are many refactors recently, it needs more testings to stabilize it.
