### ISSUE TITLE
Customize modeline background color (theme) according to variable values

### ISSUE THREAD

**Issue by QiangF** [seagle0128/doom-modeline#148]
**Is your feature request related to a problem? Please describe.**
I use hydra and I want the mode line to be in light red color when a hydra is active. There are other situations that the full line color is a better indicator, like if the cursor is in the mini buffer.

**Describe the solution you'd like**
A function to quickly change the theme of the mode line.

**Comment by seagle0128** [comment]
I think you should try the `mode-line` face.
