### ISSUE TITLE
`(setq doom-modeline-icon 1)` fails and hangs emacs daemon

### ISSUE THREAD

**Issue by zeusdeux** [seagle0128/doom-modeline#149]
**Describe**
Setting the `doom-modeline-icon` to a truthy value fails and renders emacs unusable by causing most commands to fail (as they presumably interact with the modeline).

**Steps and Expected**
Eval `(setq doom-modeline-icon 1)`

Expected: `t`
Observed: `Symbol's value as variable is void: all-the-icons-scale-factor`

**Environment:**
 - OS: macOS 
 - Version 10.14.3
 - Package version 20190315.1820

The regression seems to have been introduced by 92f99bbd964dd65216509d77c67d3b775c4849ea

**Comment by zeusdeux** [comment]
Thanks for the quick fix!

**Comment by zeusdeux** [comment]
@seagle0128 Any timeline on when the fix will be available on melpa?

**Comment by seagle0128** [comment]
Can you describe your steps and details?

**Comment by zeusdeux** [comment]
That was my exact patch locally haha! No worries at all @seagle0128! Thank you for all the good work! ^_^
