### ISSUE TITLE
Can you please add which-func mode to the feature list ?

### ISSUE THREAD

**Issue by hubgitname** [seagle0128/doom-modeline#151]
Impressive list of features that can be displayed on the mode-line.
Can you please add which-func-mode to the list ? 
If you are not aware which-func-mode shows the function the cursor
is currently on, in the mode-line. Useful if it is a large function to fit in a page.

I am thinking of moving from telephone line. and this is one feature that is missing
here.

**Comment by seagle0128** [comment]
`doom-modeline` supports `which-function-mode` which leverages `mode-line-misc-info`. I don't know what's the point of this issue. Did you check it?

![image](https://user-images.githubusercontent.com/140797/54740050-2917b100-4bf5-11e9-80c1-0d474803b561.png)

**Comment by hubgitname** [comment]
I managed t screw up my config, when I started from scratch it works correctly. I'll debug my config later, no problem with this package.
