### ISSUE TITLE
Mode line is truncated on small screen

### ISSUE THREAD

**Issue by qhuyduong** [seagle0128/doom-modeline#152]
**Describe**
On my 13 inch screen, modeline is truncated although there's still spaces in between. How can I make it fit my screen?

![image](https://user-images.githubusercontent.com/16358771/54744398-7f86ee80-4bf9-11e9-8193-5459c1e3f9a9.png)

**Steps and Expected**
Enable doom-modeline on small screen

**Environment:**
 - OS: Mac OS X
 - Version [10.14]
 - Package version [e.g. 20190314.912]

**Comment by seagle0128** [comment]
I couldn't reproduce this issue on my Macbook Pro 13. Please provide more details.

**Comment by qhuyduong** [comment]
@seagle0128 I found out that this happen after I enable `fancy-battery` mode. How can I fix it?

**Comment by seagle0128** [comment]
Did you try other fonts?

**Comment by qhuyduong** [comment]
Yes it's fixed after changing font. Thank you very much!

**Comment by seagle0128** [comment]
Welcome! Glad to know the issue is addressed.

**Comment by matthew-piziak** [comment]
I can reproduce this on `doom-modeline-20190830.1605` with `Iosevka` at height `120` with `fancy-battery-mode` enabled. Emacs version `GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)`.

**Comment by seagle0128** [comment]
@matthew-piziak Please try the latest version.

**Comment by matthew-piziak** [comment]
@seagle0128 I tried b76ff9b5d691021cb55ded51692965937283bcd6 and now I just get `doom-modeline--prepare-segments: fancy-battery is not a defined segment`.

**Comment by seagle0128** [comment]
@matthew-piziak fancy-battery segment is removed since it's not maintained, and now support display-battery-mode with battery segment.

**Comment by matthew-piziak** [comment]
That works great. Thank you @seagle0128!
