### ISSUE TITLE
How to shorten git branch name in vcs segment

### ISSUE THREAD

**Issue by qhuyduong** [seagle0128/doom-modeline#154]
The modeline looks so cramped if the branch name is long. Is there any way to shorten it?
![image](https://user-images.githubusercontent.com/16358771/55665084-44282900-5863-11e9-9058-c9631d5b099c.png)

**Comment by seagle0128** [comment]
Add `doom-modeline-vcs-max-length` to control the length of branch name. Please test.

**Comment by qhuyduong** [comment]
Awesome! Thank you.
