### ISSUE TITLE
Using 26.2 version, doom-modeline-height doesn't take effect in emax64

### ISSUE THREAD

**Issue by zijianyue** [seagle0128/doom-modeline#156]
mode-line height seems not right 
![image](https://user-images.githubusercontent.com/6119928/56403591-9b32f280-6294-11e9-81aa-e13e08f99cd4.png)

Using emax64 26.2 (a version build for windows)
https://github.com/m-parashar/emax64

The official version emacs 26.2
![image](https://user-images.githubusercontent.com/6119928/56403720-49d73300-6295-11e9-8daa-116cd523a924.png)

your 26.1 version emax64 works well too

**Comment by seagle0128** [comment]
Apparently `emacsx64` doesn't support image well. Eval `(image-type-available-p 'xpm)` on your env, you should get nil. The bar cannot be created correctly (`create-image` fails and returns error), so the height won't be changed.

**Comment by zijianyue** [comment]
libXpm-nox4.dll
