### ISSUE TITLE
Feature request: Option to disable modification icon

### ISSUE THREAD

**Issue by nsemrau** [seagle0128/doom-modeline#158]
Okay, I'm aware that this really sounds like a first world problem but here goes:

I would like to disable the floppy disk icon that appears when you modify the buffer:
![Screenshot from 2019-04-19 23-22-30](https://user-images.githubusercontent.com/4363876/56444834-c51f0000-62fa-11e9-8cc7-b3d5a1a2178e.png)

I only set `doom-modeline-major-mode-icon t`, but as per the docstring that activates `doom-modeline-icon` and so with every modification in the buffer the floppy appears. I would like to disable the floppy, since I hate it when elements in my UI suddenly shift and move position.

I would like to have the display of the icons permanently like this:
![Screenshot from 2019-04-19 23-19-23](https://user-images.githubusercontent.com/4363876/56445182-34492400-62fc-11e9-8757-aaa901f03805.png)
with the text turning into its light red face to indicate a modification of the buffer, just as it is now.

Could you please introduce an option named `doom-modeline-disable-modification-icon` or similar? I tried several combinations of `doom-modeline-icon` (`nil` or `t`) and `doom-modeline-major-mode-icon t`, but if you want the major-mode icon you seem to have to take the modification icon as well.

**Comment by seagle0128** [comment]
Add two options: `doom-modeline-buffer-state-icon` and `doom-modeline-buffer-modification-icon`. The buffer states include modification, readonly, not exist and buffer narrow, etc. If `doom-modeline-buffer-state-icon` is nil, only texts are displayed for states. If `doom-modeline-buffer-modification-icon` is nil, modification icon (floppy) won't be displayed.

```elisp
;; Whether display icons for buffer states. It respects `doom-modeline-icon'.
(setq doom-modeline-buffer-state-icon t)

;; Whether display buffer modification icon. It respects `doom-modeline-icon'
;; and `doom-modeline-buffer-state-icon'.
(setq doom-modeline-buffer-modification-icon t)
```
