### ISSUE TITLE
mode-line-process not recognized 

### ISSUE THREAD

**Issue by CeleritasCelery** [seagle0128/doom-modeline#16]
doom modeline use [this](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline.el#L610) code to determine if it should add the mode-line-process. however when running a `compilation-mode` buffer  it will update `mode-line-process` to show the exit status. this `mode-line-process` does not satisfy the predicate `stringp` resulting in nothing being added modeline. Instead, `mode-line-process` looks like this 
```lisp
(#(":exit [0]" 0 9
   (face compilation-mode-line-exit help-echo "Compilation finished"))
 (" ["
  (:propertize
   (:eval
    (int-to-string compilation-num-errors-found))
   face compilation-error help-echo "Number of errors so far")
  " "
  (:propertize
   (:eval
    (int-to-string compilation-num-warnings-found))
   face compilation-warning help-echo "Number of warnings so far")
  " "
  (:propertize
   (:eval
    (int-to-string compilation-num-infos-found))
   face compilation-info help-echo "Number of informational messages so far")
  "]"))
```

**Comment by seagle0128** [comment]
Hello @CeleritasCelery , 
`doom-modeline` doesn't support `compilation` process. The code snippets you mentioned are for `flycheck`. It seems you are requesting a new feature, right? PR are welcome.

**Comment by CeleritasCelery** [comment]
Sorry, I highlighted the wrong line in my link. I really meant [Line 610](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline.el#L610) (fixed above). 

Here is the code: 
```lisp
(doom-modeline-def-segment major-mode
  "The major mode, including process, environment and text-scale info."
  (propertize
   (concat (format-mode-line mode-name)
           (when (stringp mode-line-process)
             mode-line-process)
           (when doom-modeline-env-version
             (concat " " doom-modeline-env-version))
           (and (featurep 'face-remap)
                (/= text-scale-mode-amount 0)
                (format
                 (if (> text-scale-mode-amount 0)
                     " (%+d)"
                   " (%-d)")
                 text-scale-mode-amount)))
   'face (if (doom-modeline--active) 'doom-modeline-buffer-major-mode)))
```

you can see that the doom-modeline is trying to support `mode-line-process`, but is expecting it to be a string. AFAICT, this is never the case. I have never found a buffer or mode where `mode-line-process` is a string and therefore actually added to the modeline. 

Given that we are now looking at the right section of code, this seems less like a feature request and more of a bug.

**Comment by seagle0128** [comment]
Understood completely now. Thanks for the detailed explanations!
Actually it's as designed, but I'm glad to see the improvements. So please proceed your PR. Let's move on.

**Comment by CeleritasCelery** [comment]
I have tried to make it work without success. Do you know why it is not recognized as a string? To me, the example I gave above looks like a string with text properties, but that seems to not be the case. How does `mode-line-process` need to be transformed so it will will work with doom-modeline?

**Comment by seagle0128** [comment]
In my understanding, your case is to integrate `compilation` process into mode-line. The original design is porting from `doom-emacs`. I think the better solution is add a new segment `process`.

The screenshot is like this:
![image](https://user-images.githubusercontent.com/140797/44003698-a307a6b0-9e89-11e8-9578-7aaca5180a96.png)

Is it what you need?

**Comment by CeleritasCelery** [comment]
Thanks, that worked.
