### ISSUE TITLE
Incorrect Package-Requires

### ISSUE THREAD

**Issue by vjoki** [seagle0128/doom-modeline#160]
There's 2 issues in `doom-modeline.el` `Package-Requires`.

1. `Package-Requires` includes dash but it is not required anywhere within this package, so it seems it could simply be removed. This is just a minor nitpick since shrink-path will pull in dash anyway.
2. `Package-Requires` specifies eldoc-eval 0.1 when it actually should be 1.1. 

2 results in legitimate issues (like the one in seagle0128/doom-modeline#117) with configurations using both ELPA and MELPA with ELPA having higher priority. As then normally installing doom-modeline with package.el will pull in the ancient 0.1 version because thats exactly what `Package-Requires` is telling it to do. This means seagle0128/doom-modeline#36 and seagle0128/doom-modeline#117 are actually valid bugs and can be fixed by simply specifying the correct version of eldoc-eval.

On the other hand eldoc already has the functionality built-in so eldoc-eval could simply be removed as also noted in hlissner/doom-emacs#420.

**Comment by seagle0128** [comment]
Thanks for reporting.

1. `dash` is required by `shrink-path`. According to the guideline of melpa, it should be added.
1. The version of `eldoc-eval` in `melpa` is still *0.1* (eldoc-eval-20190106.2000). But I agree `eldoc-eval` is not necessary now. I will remove it.

**Comment by vjoki** [comment]
1. Wait which guideline says that, is this something `dash` specific? As far as I've understood only listing direct dependencies is meaningful.
2. Doesn't matter now that it's gone but `eldoc-eval` does have _1.1_ in in `melpa-stable`.

**Comment by seagle0128** [comment]
1. `dash` was not in the required package, but the reviewers of melpa requested to add it: https://github.com/melpa/melpa/pull/5550#issuecomment-401523926

2. I've removed `eldoc-eval`. In `melpa`, `eldoc-eval` is still 0.1 as below. You should file an issue for `eldoc-eval`.

![image](https://user-images.githubusercontent.com/140797/56601565-121e1180-662e-11e9-8e0b-8d705e72d148.png)

**Comment by vjoki** [comment]
1. That's interesting.
2. I might as well do that. Seems the author simply added a version tag without touching that comment.

**Comment by seagle0128** [comment]
Hope all clear now :-)

**Comment by vjoki** [comment]
Yep, thanks.
