### ISSUE TITLE
gnus notification support

### ISSUE THREAD

**Issue by will08rien** [seagle0128/doom-modeline#162]
I would like to see notifications of new messages in the mode line when using gnus and doom modeline.

**Is your feature request related to a problem? Please describe.**
I have used gnus-notify.el in the past with the standard modeline but it doesn't seem to show a notification in the doom modeline.

**Describe the solution you'd like**
There should be a way to display an indication of unread messages in gnus groups when using doom modeline.

**Describe alternatives you've considered**
gnus-desktop-notify can be used instead (as long as modeline alert is not configured), but it is not the same beast.
I will have a blast at fixing support for gnus-notify.el and see if it can be genericised before reviewing with you.

**Comment by seagle0128** [comment]
I am not using gnus now. The PRs are always welcome, like mu4e.

**Comment by will08rien** [comment]
I will take a look and raise PR. Many thanks! Note, may be a little while as my time is currently fairly limited.

**Comment by seagle0128** [comment]
Closed by #279.
