### ISSUE TITLE
Inconsistent color breaks in modeline

### ISSUE THREAD

**Issue by Alexander-Miller** [seagle0128/doom-modeline#164]
**Describe**
Some situations, like magit's popups, can break the colors of the modeline: https://imgur.com/a/C7fWtTB

**Steps and Expected**
I use my own [simple implementation](https://github.com/Alexander-Miller/dotfiles/blob/master/.config/spacemacs/user-config.org#default) where it's best visible, but you should be able to see it in magit with doom's defaults as well. You just need different faces for active and inactive modelines.

Annoyingly enough this is my own fault, since this behavior was introduced by https://github.com/seagle0128/doom-modeline/pull/135. I don't know what doom's internals look like,so maybe you can fix it, but if not then my change will need to be reverted.

**Comment by seagle0128** [comment]
Can you try this?
```elisp
(doom-modeline-def-segment std::modeline::buffer-id
  (propertize (buffer-name)
              'face (if (doom-modeline--active) 'mode-line-buffer-id 'mode-line-inactive)))
```

**Comment by Alexander-Miller** [comment]
> Can you try this?

Seems to work, though I'd have to create some inactive-faces for my other segments.

Btw the problem was also not present when I tried emacs 27.
