### ISSUE TITLE
Width is off by 1-2 chars, dividers don't align with buffers or frame

### ISSUE THREAD

**Issue by aureumleonis** [seagle0128/doom-modeline#165]
**Describe**
Using the latest version in melpa, the total width of the modeline is not calculated correctly and it's usually off by 1-2 chars.

![doom-mode-off](https://user-images.githubusercontent.com/6925097/57101278-bc083880-6cd5-11e9-885f-16aba7a25829.PNG)

This is emacs 26.1 running in tmux. The buffer widths are correct. Could this be related to double-width chars? I'm using nerd-fonts which doesn't seem to have the expected mappings for symbols but the offset doesn't seem to match.

**Comment by seagle0128** [comment]
It's not compatible with nerd fonts so far.  Please install all-the -icons first.
