### ISSUE TITLE
Eglot: Closing file issues error if server is shut down.

### ISSUE THREAD

**Issue by alexanderbarbosa** [seagle0128/doom-modeline#167]
**Describe**
Closing a random CSS file after shutting down an Eglot server issues error of `number-or-marker-p`. Disabling doom-modeline won't issue that error.

May be **doom-modeline** looks for an eglot server, not finding one returns `nil`, hence issues that error.

**Steps and Expected**
- emacs -Q
- m-x package-inititilize
- open color.scss
- m-x eglot
- eglot-shutdown  (css-language-server)
- close CSS server
- closing css file issues error

**Environment:**
 - OS: Debian SID (10)
 - Version:  emacs 26.2
 - Package version: 20190505.2255 - commit 0dfbb0

**Additional context**
**screenshot**: https://i.ibb.co/Gk7pxZw/2019-05-06-000005-1366x768-scrot.png

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  doom-modeline-update-eglot()
  run-hooks(eglot--managed-mode-hook eglot--managed-mode-off-hook)
  eglot--managed-mode(-1)
  eglot--managed-mode-onoff()
  kill-buffer("_colors.scss")
  ido-visit-buffer("_colors.scss" kill t)
  ido-buffer-internal(kill kill-buffer "Kill buffer: " "_colors.scss" nil ignore)
  ido-kill-buffer()
  funcall-interactively(ido-kill-buffer)
  #<subr call-interactively>(ido-kill-buffer nil nil)
  apply(#<subr call-interactively> ido-kill-buffer (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> ido-kill-buffer nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (ido-kill-buffer nil nil))
  call-interactively(ido-kill-buffer nil nil)
  command-execute(ido-kill-buffer)
```

**Comment by seagle0128** [comment]
Thanks for the detailed report! Will fix it soon.
