### ISSUE TITLE
Undefined variable evil-ex-start-word-search

### ISSUE THREAD

**Issue by CeleritasCelery** [seagle0128/doom-modeline#17]
I updated to the last version for fix to #16 and I am now getting the error `Symbol’s value as variable is void: evil-ex-start-word-search`. Looks like this was introduced in d9c49ac9626eac871d9711ae17bbf66de269c9cc. From looking at the evil source code, `evil-ex-start-word-search` is a function, not a variable. It certainly doesn't exist in my environment.

**Comment by seagle0128** [comment]
Sorry for the inconvenience! This have been resolved, but need some time to sync to melpa. Please update a couple hours later.
