### ISSUE TITLE
Recently flycheck info is truncated

### ISSUE THREAD

**Issue by codesuki** [seagle0128/doom-modeline#171]
As the title says.
Here is a picture:
<img width="505" alt="Screen Shot 2019-05-15 at 9 00 44" src="https://user-images.githubusercontent.com/5276006/57739800-f4554100-76ef-11e9-8fb4-cc2eb61570c6.png">

Any idea how to fix or what could have caused it?

**Comment by seagle0128** [comment]
Can you please provide more details? Does it exist on Linux?

**Comment by codesuki** [comment]
This is on osx. I am pretty sure it worked until recently. 
Version is from earlier today. 

Are there specific details I could provide that would help?

**Comment by seagle0128** [comment]
Did you customized mode-line? I didn't encounter this issue on macOS Mojave with GNU Emacs 26.2. And it looks different from the default style of doom-modeline.

**Comment by seagle0128** [comment]
Please test with the latest version.

**Comment by codesuki** [comment]
Still happening :( 
This is my config:
```
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t)
  (setq doom-themes-enable-italic t)
  (doom-themes-visual-bell-config)
  (doom-themes-treemacs-config)
  (load-theme 'doom-one t))

(use-package doom-modeline
  :ensure t
  :config
  (setq doom-modeline-buffer-file-name-style 'truncate-with-project)
  (setq doom-modeline-major-mode-color-icon nil)
  (setq doom-modeline-minor-modes nil)
  (setq doom-modeline-github t)
  (setq doom-modeline-buffer-encoding nil)
  (doom-modeline-mode))
```

**Comment by seagle0128** [comment]
What's the font are you using?
