### ISSUE TITLE
flymake error

### ISSUE THREAD

**Issue by wailo** [seagle0128/doom-modeline#172]
**Describe**
I am getting this error when lsp-mode is active
 
**Steps and Expected**
- Open a file with lsp-mode and flymake active
- Edit the file then press save

**Environment:**
 - OS: Mac OS
 - Mojave
 - 20190515.206
 - Emacs 26.1

**Additional context**
Stack trace (culled)
`Debugger entered--Lisp error: (error "Format specifier doesn’t match argument type")
  format("error: %d, warning: %d, note: %d\nmouse-1: List all problems%s" "\nwheel-up/wheel-down: Previous/next problem" 16 0 3)
  doom-modeline-update-flymake-text(lsp--flymake-backend backend-token22 (#s(flymake--diag :buffer #<buffer main.c> :beg 6775 :end 6781 :type :error :text "implicit declaration of function 'getpid' is invalid in C99" :backend lsp--flymake-backend) #s(flymake--diag :buffer #<buffer main.c> :beg 6775 :end 6781 :type :error :text "this function declaration is not a prototype" :backend lsp--flymake-backend) #s(flymake--diag :buffer #<buffer main.c> :beg 10756 :end 10761 :type :error :text "use of undeclared identifier 'pid_t'"`

**Comment by seagle0128** [comment]
@vjoki Can you please check this issue which is related to `flymake`?
