### ISSUE TITLE
Vertical separators showing up when modeline is inactive

### ISSUE THREAD

**Issue by guerarda** [seagle0128/doom-modeline#173]
**Describe**
I'm seeing vertical separators around the major-mode indicator, and also on the left side of the modeline, that don't match the color of the modeline when it is inactive. The major mode icon also doesn't match the background color. 

![Screen Shot 2019-05-17 at 14 59 53](https://user-images.githubusercontent.com/4053928/57958366-7d1cda00-78b4-11e9-9267-7cd20b2b1742.png)

**Steps and Expected**
I always run into this issue when using Magit's popup buffer, e.g. when calling _magit-dispatch_ from the Magit Status Buffer.

The issue only appears when the modeline is inactive because of a popup, it looks fine when the modeline is inactive because a different window is selected (screenshot below). That's what I would expect to see instead of the first screenshot.
![Screen Shot 2019-05-17 at 12 50 11](https://user-images.githubusercontent.com/4053928/57958570-121fd300-78b5-11e9-9bb9-a887a8dfb629.png)

The issue with the major-mode icon only appears when I set _all-the-icons-color-icons_ to nil.
When _all-the-icons-color-icons_ it set, I see the following:
![Screen Shot 2019-05-17 at 12 20 31](https://user-images.githubusercontent.com/4053928/57959236-a4c17180-78b7-11e9-85fe-71da9d32c413.png)
The icon looks ok but the vertical separators are still visible.

**Environment:**
- MacOS 10.14.4
- Emacs 26.2
- doom-modeline 20190516.1759

I initially thought it was a problem with my configuration, I use the solarized-dark theme, but I can see the same issue with the default emacs theme and a minimal init.el. 

The issue doesn't exist when I use the doom-one theme.

**Additional context**
The same issue with the default emacs theme:
![Screen Shot 2019-05-17 at 12 51 22](https://user-images.githubusercontent.com/4053928/57958764-c28dd700-78b5-11e9-977a-27e16d732e55.png)

Let me know if you need more info, or if you want me to try anything !

**Comment by seagle0128** [comment]
Yeah, I am testing with doom themes, so didn't see this issue. I will check soon.

**Comment by seagle0128** [comment]
Please test.

**Comment by guerarda** [comment]
Yep, it works. Thanks !
