### ISSUE TITLE
"CRLF" truncated to "RLF"

### ISSUE THREAD

**Issue by nasoundead** [seagle0128/doom-modeline#175]
**Describe**
I am using this mode line , i find a little bug as described in title.

**Environment:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**
![image](https://user-images.githubusercontent.com/13186459/57979579-6ad8a280-7a52-11e9-8088-697262ef65e9.png)

**Comment by seagle0128** [comment]
That's as designed, but "CRLF" is better.
