### ISSUE TITLE
Error for TRAMP python in doom-modeline-env

### ISSUE THREAD

**Issue by bdc34** [seagle0128/doom-modeline#180]
**Describe**
Doom-modeline throws an error when loading a python file via TRAMP.

**Steps and Expected**
Load a python file with TRAMP via ssh while ELPY is installed.

**Environment:**
 - OS: mint linux
 - Version 25.3
 - Package version 20190530.555

**Additional context**
 Debugger entered--Lisp error: (file-error "Setting current directory" "No such file or directory" "/users/xxxx/arxiv-analysis/")
  make-process(:name "doom-modeline-env" :buffer nil :command ("python" "--version"))
  apply(make-process (:name "doom-modeline-env" :buffer nil :command ("python" "--version")))
  start-process("doom-modeline-env" nil "python" "--version")
  apply(start-process ("doom-modeline-env" nil "python" "--version"))
  doom-modeline-env--get("python" ("--version") #[257 "!\211\207" [doom-modeline-env-parser doom-modeline-env-version] 3 "\n\n(fn PROG-VERSION)"])
  doom-modeline-update-env()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer load2017.py> "/ssh:arxiv-xxxx:/users/xxxx/arxiv-analysis/ng/load2017.py" nil nil "/ssh:arxiv-xxxx:/users/xxxx/arxiv-analysis/ng/load2017.py" ((2 . 1651) (-1 . 1)))
  find-file-noselect("/ssh:arxiv-xxxx:/users/xxxx/arxiv-analysis/ng/load2017.py" nil nil nil)
  find-file("/ssh:arxiv-xxxx:/users/xxxx/arxiv-analysis/ng/load2017.py")
  dired-find-file()
  funcall-interactively(dired-find-file)
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)

**Comment by seagle0128** [comment]
Hi, Did you install `python` locally?

**Comment by bdc34** [comment]
Yes, doom-modeline works fine with local python development.

**Comment by seagle0128** [comment]
Please try the latest version.

**Comment by seagle0128** [comment]
Please test the latest version.

**Comment by bdc34** [comment]
Yes, 20190531.1404 fixes it for me. Thank you.

**Comment by seagle0128** [comment]
Great! Welcome, @bdc34 .
