### ISSUE TITLE
Monochrome theme

### ISSUE THREAD

**Issue by andreyorst** [seagle0128/doom-modeline#182]
Active:
![image](https://user-images.githubusercontent.com/19470159/58874858-9609f580-86d2-11e9-9162-97dbd4e7821b.png)
Inactive:
![image](https://user-images.githubusercontent.com/19470159/58874811-7246af80-86d2-11e9-8ca5-55c0e777f1dd.png)
Is there any way to display modeline with colors like in inactive state, but with background of active state. E.g. like so:
![image](https://user-images.githubusercontent.com/19470159/58874993-fd27aa00-86d2-11e9-8d09-ff73a384dd37.png)

I've tried to change some faces, but it only affects text, icons stay colored. Am I'm missing something?

**Comment by seagle0128** [comment]
Try customizing the face of `mode-line-inactive`.

**Comment by andreyorst** [comment]
>Try customizing the face of `mode-line-inactive`.

How it will help me to display active modeline as inactive?

**Comment by seagle0128** [comment]
There is no option to display active mode-line as inactive one. How to differ them if all colors are same? I don't understand the point of this requirement perhaps.

**Comment by andreyorst** [comment]
> How to differ them if all colors are same? I don't understand the point of this requirement perhaps.

I don't want to display active modeline as inactive, I want active modeline to use single color for every element like in inactive modeline instead of all these colors that distract me.

I've tried to customize these faces:
```
doom-modeline-buffer-path
doom-modeline-buffer-file
doom-modeline-buffer-modified
doom-modeline-buffer-major-mode
doom-modeline-buffer-minor-mode
doom-modeline-project-parent-dir
doom-modeline-project-dir
doom-modeline-project-root-dir
doom-modeline-highlight
doom-modeline-panel
doom-modeline-debug
doom-modeline-info
doom-modeline-warning
doom-modeline-urgent
doom-modeline-unread-number
doom-modeline-bar
doom-modeline-inactive-bar
doom-modeline-evil-emacs-state
doom-modeline-evil-insert-state
doom-modeline-evil-motion-state
doom-modeline-evil-normal-state
doom-modeline-evil-operator-state
doom-modeline-evil-visual-state
doom-modeline-evil-replace-state
doom-modeline-persp-name
doom-modeline-persp-buffer-not-in-persp
```

But it only affects text color, not icons.

**Comment by andreyorst** [comment]
If I chane `:foreground` of all these faces to `#FF0000` I get this result:
![image](https://user-images.githubusercontent.com/19470159/58884707-95c92480-86e9-11e9-92db-84f768901dfa.png)

**Comment by seagle0128** [comment]
```elisp 
(setq doom-modeline-major-mode-color-icon nil
       all-the-icons-color-icons nil)
```

**Comment by andreyorst** [comment]
Thanks for the fix!

**Comment by nazzacode** [comment]
@seagle0128 's solution
```elisp
setq doom-modeline-major-mode-color-icon nil
       all-the-icons-color-icons nil)
```

isn't working for me, any ideas?
