### ISSUE TITLE
Windows are not properly aligned due to non-standard modeline height

### ISSUE THREAD

**Issue by kurnevsky** [seagle0128/doom-modeline#183]
The main problem here is buffer-switcher. Try to open it with `M-x bs-show` when you have two buffers open. Doom modeline will hide the last buffer because buffer-switcher calculates the window height automatically:

![screenshot-2019-06-06-22:07:15](https://user-images.githubusercontent.com/2943605/59059611-eaf26b00-888e-11e9-87da-93d401ab30b6.png)

Also see how scrolls are displayed:

![screenshot-2019-06-06-22:08:43](https://user-images.githubusercontent.com/2943605/59059617-ee85f200-888e-11e9-852f-84abd27a71eb.png)

**Comment by seagle0128** [comment]
Can you reproduce with `emacs -Q`? I couldn't reproduce it on my env.

![image](https://user-images.githubusercontent.com/140797/59124136-7ce29c80-8991-11e9-86b0-6be2d4c0a93b.png)

The scrollbar is disabled in mode-line, and it's as designed.

**Comment by kurnevsky** [comment]
Yep, the same with emacs -Q:

![screenshot-2019-06-07-21:52:54](https://user-images.githubusercontent.com/2943605/59126898-b8f80c00-8955-11e9-90c0-1e42a2190d2a.png)

Here is minimal config I used:

```el
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(unless (package-installed-p 'doom-modeline)
  (package-install 'doom-modeline))
(require 'doom-modeline)
(doom-modeline-mode)
```

**Comment by seagle0128** [comment]
I tested with `emacs -Q` (27.0.50, macOS Mojave). The scroll bars are correct. Regarding `bs-show` buffers, I think it's an issue of `bs-show`, which should calculate the height according to the height of mode-line. The height of `doom-modeline` is greater than the default one.

![image](https://user-images.githubusercontent.com/140797/59129640-f41f2d00-899f-11e9-980e-8c927d83c211.png)

**Comment by kurnevsky** [comment]
OS: Arch Linux, Emacs version: 26.2, packege is the latest available from melpa.

**Comment by kurnevsky** [comment]
`bs-show` uses `fit-window-to-buffer` which works correctly after window is shown if execute it manually. So I have an impression that in case of `bs-show` it's executed _before_ doom-modeline sets its height. It would explain incorrect scrollbars as well.

**Comment by seagle0128** [comment]
I still think it's an issue of `bs-show`. You can try this:

```elisp
(add-hook 'window-configuration-change-hook #'bs--track-window-changes)
```

**Comment by kurnevsky** [comment]
The problem is that `bs-show` creates a window with `split-window-below` and right after that sets it height with `fit-window-to-buffer`, but `split-window-below` doesn't run any hooks like `window-configuration-change-hook`.

**Comment by seagle0128** [comment]
`doom-modeline` sets the height of mode-line in `window-configuration-change-hook`.  If `bs-show` refreshes the window after that, the issue should be addressed IMO. Or you can try other hooks or  advices to fix. Anyway, I don't know what I can do for `doom-modeline` so far. I suggest you try `ido-switch-buffer` or `ivy-swith-buffer` for better experience.

**Comment by kurnevsky** [comment]
ok, thanks. I also don't see how it can be solved properly on doom modeline side, so closing the issue.

**Comment by jjzmajic** [comment]
Given [this](https://github.com/magit/transient/issues/63), will the issue be addressed on doom-modeline's side, or should patches be submitted to transient, which-key, and buffer switcher?

**Comment by seagle0128** [comment]
`doom-modeline` can do nothing unless it knows when and how to trigger the refreshing for other packages. IMO the package should calculate the window height according to the real mode-line height while creating the window, or refresh after creating it.

**Comment by seagle0128** [comment]
@jjzmajic As @tarsius mentioned, `redisplay` does work well but costly. Maybe the best solution is to change in emacs itself, but for packages it's fine IMO.

I can do the same thing in `doom-modeline` if necessary.

**Comment by yuhan0** [comment]
The above change a3b6432569b57440816155bda47ce76f1169c2b9 causes major slowdowns with the hydra package, triggering a redisplay on every keystroke and flickering the screen, because `lv-message` calls fit-window-to-buffer. 

Is there a less heavy-handed way of going about things? I simply removed the advices from my local config in the meantime.

**Comment by tarsius** [comment]
Ran into essentially the same issued, worked around it with https://github.com/tarsius/moody/commit/a7fb64d6fae15ed6ff87e540ff177134fc0b19b5; only run the kludge as often as needed, which is once. You should do the same here.

**Comment by seagle0128** [comment]
Thanks, @tarsius ! New patch 3eeb09040546c6160cd3cdca68318c6212c72a8e was committed already.

**Comment by yuhan0** [comment]
This still doesn't solve the lag/flickering issue with hydra, because the call to `(doom-modeline--redisplay)` occurs from the *LV* buffer which is destroyed and created on every keypress, so the buffer-local variable does not persist. 

I'm not sure if this calls for a different mechanism in doom-modeline, or if an issue should be raised with hydra to simply persist the *LV* buffer.

**Comment by tarsius** [comment]
I don't see any flickering with `transient`, which also uses `lv`. Haven't tried with `hydra`.

The proper fix is to fix this in Emacs, but I want to finish some things before I report this issue.

**Comment by seagle0128** [comment]
It does work well in my env, for both `transitent` and `hydra`. My configuration is [here](https://github.com/seagle0128/.emacs.d).

**Comment by seagle0128** [comment]
The height issue was resolved, but the workaround brings a new blinking issue as below.

https://emacs-china.org/t/hydra-doom-modeline/11537

**Comment by seagle0128** [comment]
Already fixed in 4cc375a.

**Comment by deftsp** [comment]
@seagle0128 Sorry the mode-line height problem again.
 
1. M-x `org-agenda`  pop up the ` *Agenda Commands*`, the window height correct.
2. M-x `org-agenda` again, the last line of the buffer will be hidden
3. kill the ` *Agenda Command*` buffer,  M-x `org-agenda`, the height will be correct.

With vanilla mode-line no such problem.

//

The window pop up by  `flyspell-correct-avy-menu` flickering. `avy-menu` call `fit-window-to-buffer` also.

Env:
GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, Carbon Version 162 AppKit 1894.3) of 2020-02-03

**Comment by seagle0128** [comment]
@deftsp No such issue in my local env. Please retry with the latest version. If you still have this issue, please provide more details including screenshots and recordings.

**Comment by deftsp** [comment]
@seagle0128  I just figured it out.

When calling `org-agenda`  for the second time,  it will reuse the buffer ` *Agenda Commands*`,  however, local variable `doom-modeline--size-hacked-p`  has been set to `t`.  When `org-agenda-get-restriction-and-command` call `fit-window-to-buffer`, the advice hook will not trigger `redisplay`. So the height will not be correct.

I removed `doom-modeline--size-hacked-p` from `doom-modeline-redisplay`,   the `" *Agenda Commands*" `buffer height problem fixed.  Maybe  " *Agenda Commands*" is a special case.


`avy-menu` flickering is not disrelated to doom-modeline.

**Comment by seagle0128** [comment]
@deftsp Why double calling `org-agenda`? It's not a common case, I think. As the comments above, this is just a workaround for the Emacs issue. Of course you can remove `doom-modeline--size-hacked-p`, but it will bring neogative impacts for the performance, e.g hydra.

**Comment by deftsp** [comment]
In fact, in my daily use, calling `org-agenda`  is frequently.  I think there's no perfect solution for now. Thanks for your time!
