### ISSUE TITLE
doom-modeline breaks query-replace

### ISSUE THREAD

**Issue by andresm** [seagle0128/doom-modeline#185]
**Describe**
If doom-modeline is enabled, c++ mode is enabled, and the the buffer is a file, then query-replace fails: 

"Match data clobbered by buffer modification hook"

**Steps and Expected**

1. Enable doom-modeline:
```
(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-mode)
  :config
  (setq doom-modeline-github nil)
  (setq doom-modeline-github-interval 0)
  (setq doom-modeline-icon t)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-major-mode-icon t)
  (setq doom-modeline-major-mode-color-icon t)
  (setq doom-modeline-minor-modes t)
  (setq doom-modeline-persp-name t)
  (setq find-file-visit-truename t))
```
2. Open a file from disk, and be sure c++ mode is enabled. (If the file is not loaded from disk the bug is not triggered)

3. query-replace, change whatever for whatever i.e. "A" -> "b"

4. Set it to replace all: "!"

5 The following error is displayed: "Match data clobbered by buffer modification hook" 

The expected results is that the text is replaced in the buffer

**Environment:**
 - OS: Linux Debian 9
 - Emacs Version: 25.1.1
 - Package version: doom-modeline 20190608 (melpa)

**Additional context**
The error is in a hook installed in `after-changes-functions`:

`doom-modeline-update-buffer-file-name`

The bug is solved by enclosing the body of the function in save-match-data to prevent the corruption of the search results.

**Comment by seagle0128** [comment]
Thanks for the detailed reporting!

I checked the GNU mail list, and confirm `save-match-date` is the solution. I also did some tests locally. It seems the issue only exists on Emacs 25.1.x, while not on 25.2+, 26.x, 27.x. Is it right? If adding `save-match-data`, is there any side-effects?
