### ISSUE TITLE
Undesired buffer-revert

### ISSUE THREAD

**Issue by aagon** [seagle0128/doom-modeline#186]
Commit 62f48c0 introduced a regression :

Switching from frame 1 to frame 2, and back to frame 1 reverts the buffer opened in the focused window, which is almost always undesirable (in particular, if said buffer is an .org file with structure, reverting the buffer reverts the folding back to startup folding, which is undesirable).

This (intended ?) behaviour was introduced with this advice from commit 62f48c0 :
```elisp
(advice-add #'handle-switch-frame :after #'(lambda (&rest _)
                                             "Rever the current buffer."
                                             (ignore-errors (revert-buffer t t))))
```
Maybe this snippet was introduced for very good reasons. However, using the revert-buffer function when trying to update the modeline is far too violent. On top of that, the advice is unnamed, which makes its removal tricky.

Regardless of the problem Mr. Zhang was trying to solve when he introduced this, my advice would be, by order of preference :
- Getting rid of it.
- If you must keep it, name the advice so that removing it can easily be done in one's init file with a simple
```elisp
(advice-remove #'handle-switch-frame #'named-function-to-replace-lambda)
```

If neither course of action is followed, I'm adding here, for reference, a robust way of getting rid of the advice, that consists in removing all the advices on the function, and re-adding all of them except the one :
```elisp
(advice-mapc
   (lambda (adv prop)
     (advice-remove 'handle-switch-frame adv))
   'handle-switch-frame)

(advice-add #'handle-switch-frame :after #'doom-modeline-set-selected-window)
```

Whatever you decide, I can prepare a trivial PR with the changes.

Aymeric Agon-Rambosson

**Comment by seagle0128** [comment]
Thanks for reporting!

The commit 62f48c062ee02b2f07a7b19ed52496e9927b9c24	is addressing incorrect buffer names after switching in/out frames, and frankly I didn't realize folding/unfolding features. It's a workaround for the minor issue
, and if it brings the side-effect, I may revert it for now, unless I got the better solution.

BTW, did you encounter the issue if removing the advice?

**Comment by aagon** [comment]
Thank you for the quick follow-up !

> BTW, did you encounter the issue if removing the advice?

It may require some more testing, but I haven't had any problem with buffer names after switching frames. I could try more if I had the steps to reproduce the original buffer name bug (which I didn't find in the issue tracker)

Aymeric Agon-Rambosson

**Comment by seagle0128** [comment]
I am pretty sure `emacs-plus` has that issue while the vanilla emacs hasn't. So the commit should be reverted.
