### ISSUE TITLE
buffer-filename-style not working properly if home is in in /var/

### ISSUE THREAD

**Issue by A6GibKm** [seagle0128/doom-modeline#188]
**Describe**
When using doom-modeline in a system where the user home is located at `/var/home/username` doom-modeline will reduce for example the location of a file `~/.emacs.d/init.el` to `/v/h/u/.emacs.d/init.el`.

**Environment:**
 - Fedora Silverblue 30
 - doom-modeline-buffer-encoding is set to default

**Comment by seagle0128** [comment]
Can you evaluate this in Emacs?
```elisp
(getenv "HOME")
```

**Comment by A6GibKm** [comment]
Yup, in both cases it returns `/home/username`. idk how fedora does it but so far this is the first time a piece of software knows home it is actually located in `/var/home`.

**Comment by seagle0128** [comment]
Is it a new feature in the latest Fedora? Or is it a symlink?

The truncate path respects `$HOME` var in `doom-modeline`, so you can try `(setenv "HOME" "/var/home/username")` in your local configuration.

**Comment by A6GibKm** [comment]
That worked. This is a feature of fedora silverblue https://docs.fedoraproject.org/en-US/fedora-silverblue/.

**Comment by seagle0128** [comment]
I don't understand this feature completely yet. If HOME directory is changed, all related functions, utils should be changed accordingly. You may try `(setq find-file-visit-truename t)` for symlinks.

I am closing it. Please reopen if you still have problems.
