### ISSUE TITLE
How can I show the name of the current project/repo with `doom-modeline-minor-modes` enable?

### ISSUE THREAD

**Issue by mrbig033** [seagle0128/doom-modeline#191]
### Runtime Environment

- MX Linux 18
- GNU Emacs 27.0.50
- doom-modeline 20190701.1148
- [dotfiles](https://github.com/mrbig033/dotfiles)
- [~/.emacs.d](https://github.com/mrbig033/Emacs)

### Issue

Right now it only shows the current branch ("master" etc).

**Comment by seagle0128** [comment]
Can you please attach some screenshots for better understandings?

**Comment by seagle0128** [comment]
Any update?

**Comment by mrbig033** [comment]
![In this image](https://user-images.githubusercontent.com/36245777/61167995-30a0f400-a51d-11e9-9172-96593b331c90.png)
, to the right, Doom Modeline only shows the major mode and the current branch ("master"). I wish it could also show the name of the repository. In this particular case, it's called "emacs" ([hosted here](https://github.com/mrbig033/Emacs)).

**Comment by seagle0128** [comment]
If you want to current project info, you can use the one of the styles below. It's duplicated if it's displayed in the vcs segment.

```elisp
(setq doom-modeline-buffer-file-name-style 'truncate-upto-project) ; or truncate-with-project, truncate-except-project, relative-from-project
```

**Comment by aburlot** [comment]
Sorry for commenting this old closed issue, but it pops on Google when one searches _emacs doom-modeline add project name_. It should be toggled using `(setq doom-modeline-project-name t)`.
