### ISSUE TITLE
Modeline doesn't update (battery, time)

### ISSUE THREAD

**Issue by WorldsEndless** [seagle0128/doom-modeline#193]
**Describe**
The modeline displays my time and the battery. However, upon entering the buffer, neither of these ever changes; if I open a new buffer, I'll see the updated time/battery%, but if I switch back to the previous buffer, I see the previous frozen values. 

**Steps and Expected**
Expect to see up-to-date changes, but they are frozen. 

**Environment:**
 - OS: OpenSUSE Tumbleweed (Linux)
 - Version: Tumbleweed (rolling)
 - Package version 20190708

**Comment by seagle0128** [comment]
Which version of Emacs?

Are you using `display-time-mode` and `fancy-battery-mode`?
And could you please provide more details, e.g. messages, logs, screenshots or recordings?

**Comment by WorldsEndless** [comment]
Emacs 26.1. 

Yes, using both those modes. Looking into fancy-battery, I've just changed the battery-update time so hopefully that helps there. I don't see an analogous setting for updating the clock, though.

**Comment by WorldsEndless** [comment]
I can verify that fixing the interval DID fix my battery display, which now updates. However, the clock still does not , and is different in each buffer (?!).

**Comment by seagle0128** [comment]
No. It's the built-in functionality of vanilla Emacs. The behaviors should be exactly same as default mode-line.

**Comment by WorldsEndless** [comment]
This just in: I rebooted the entire system and, upon loading, it STILL displayed the frozen times from about an hour ago. I find this very surprising.

**Comment by seagle0128** [comment]
How about in `emacs -Q`?

**Comment by WorldsEndless** [comment]
After more time debugging than I should have, I found the user error: wrong format time string. I had:
`" %a %m.%d %H:%m"`

This, of course, made what I thought were my minutes actually my months (being month 07, I didn't notice) I corrected this and all was fixed:

" %a %m.%d %H:%M"
