### ISSUE TITLE
Invalid face reference when using `(setq doom-modeline-persp-name t)`

### ISSUE THREAD

**Issue by UndeadKernel** [seagle0128/doom-modeline#195]
**Description**
The update procedure of the modeline segment that shows which persp is active seems to be broken. When `(setq doom-modeline-persp-name t)`, the message buffer shows:
```lisp
Invalid face reference: nil
Invalid face attribute :inherit nil
```
This is due to how [this variable](https://github.com/seagle0128/doom-modeline/blob/bdbf45e690ba443dc725f68e4d16ea529f48127c/doom-modeline-segments.el#L1338) is set in [this function](https://github.com/seagle0128/doom-modeline/blob/bdbf45e690ba443dc725f68e4d16ea529f48127c/doom-modeline-segments.el#L1345). The `face` symbol evaluates to either `nil` or `t` and not a face symbol.

**Steps to Reproduce**
Start emacs with the variable `doom-modeline-persp-name' set to `t`. Switch to a `real` buffer (i.e., source code). See in the message area the message "Invalid Face attrbite" appear.

**Environment:**
 - OS: Arch GNU/Linux and Doom Emacs

**Comment by seagle0128** [comment]
Thank you for the detailed report!

It's wired. I couldn't reproduce on Emacs 27, but I will drop a commit soon to fix it.

**Comment by UndeadKernel** [comment]
That did the trick!
Thanks @seagle0128
