### ISSUE TITLE
Question: Can I display a Pomodoro timer in the modeline?

### ISSUE THREAD

**Issue by ema2159** [seagle0128/doom-modeline#196]

**Comment by seagle0128** [comment]
`org-pomodoro` can be displayed in `doom-modeline`.

![image](https://user-images.githubusercontent.com/140797/61234114-dabe8d00-a764-11e9-976a-6ee80b7bf095.png)

**Comment by ema2159** [comment]
Could you show me a snippet of the configuration for reference? Thanks in advance!

**Comment by seagle0128** [comment]
Please refer to https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-org.el#L161 .

**Comment by ema2159** [comment]
By the way, why did you labeled this with a help wanted? Just curious 😅

**Comment by seagle0128** [comment]
Oh, my mistake. Wrong label here 😢
