### ISSUE TITLE
Is it possible to put the current time on Doom Modeline?

### ISSUE THREAD

**Issue by mrbig033** [seagle0128/doom-modeline#198]
### Runtime Environment

- MX Linux 18
- [dotfiles](https://github.com/mrbig033/dotfiles)
- GNU Emacs 27.0.50
- Org mode version 9.2.3
- Evil version 1.2.14
- [~/.emacs.d](https://github.com/mrbig033/emacs)

### Issue

If so, how can I do that?

**Comment by seagle0128** [comment]
`M-x display-time`
