### ISSUE TITLE
Pixel Scroll Mode Performance Bug

### ISSUE THREAD

**Issue by DarkArc** [seagle0128/doom-modeline#199]
**Describe**
When using `pixel-scroll-mode` combined with `doom-modeline`, scrolling via the mouse is unusable.

**Steps and Expected**
- Install `doom-modeline` and enable `pixel-scroll-mode`

**Environment:**
 - OS: Linux
 - Version: 4.18.0-25-generic Ubuntu
 - Package version: 2.4.0

**Comment by seagle0128** [comment]
Hi, I couldn't reproduce with `emacs -Q`. The laggy issue exists on Centaur Emacs with `pixel-scroll-mode`, then I did profilers, but it shows `doom-modeline` doesn't consume lots of CPU resources.

![image](https://user-images.githubusercontent.com/140797/61688835-9c266500-ad58-11e9-9fd7-1ef557ec94bd.png)

Would you please provide more clues and details?

**Comment by seagle0128** [comment]
I found similar issues on

https://github.com/syl20bnr/spacemacs/issues/11549
https://www.reddit.com/r/emacs/comments/8rml8f/emacs_26_pixelscrollmode_gcs_like_theres_no/

AFAIK, it may be a common issue of `pixel-scroll-mode` itself.

**Comment by DarkArc** [comment]
Interesting; so here's what I can say, if I disable doom-modeline, it's somewhat usable, if I have doom-modeline, it's completely unusable, and the editor hangs for several seconds per scroll; forget scrolling rapidly.

![image](https://user-images.githubusercontent.com/778012/61724465-8ff0d680-ad5d-11e9-901d-0fcd0c62034a.png)

I think it may be the memory related to the formatting call.

I also have font sizes customized so that may be related:
![image](https://user-images.githubusercontent.com/778012/61724536-b31b8600-ad5d-11e9-85ec-5396bcaddb62.png)

````
;; configure custom mode line
(require 'doom-modeline)
(doom-modeline-mode 1)

(setq doom-modeline-height 20)
(set-face-attribute 'mode-line nil :height 115)
(set-face-attribute 'mode-line-inactive nil :height 115)
```

**Comment by seagle0128** [comment]
I would say it's related to the GC and `pixel-scroll-mode`. Try increasing `gc-cons-threshold`, disabling `column-number-mode`, `line-number-mode` and `size-indication-mode`.

IMO, `pixel-scroll-mode` is not usable. It's released without enough testing. I might recommend these configurations to replace it.

```elisp
;; Mouse & Smooth Scroll
;; Scroll one line at a time (less "jumpy" than defaults)
(when (display-graphic-p)
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1))
        mouse-wheel-progressive-speed nil))
(setq scroll-step 1
      scroll-margin 0
      scroll-conservatively 100000)
```

**Comment by DarkArc** [comment]
Yeah, I already tried adjusting the GC, even to absurdly high amounts, and it doesn't make a big differently sadly. I've got a few of those configurations in there already as well :).

This isn't a huge priority for me, I've got a Mac for work and the scrolling on there with the touch pad is amazing, but with a mouse on my desktop in comparison it really sucks. I was looking to make it a bit more enjoyable.

I wanted to report it though, because several people were commenting about how various modeline packages were slowing things down, and as it turns out, it's somewhat useable without the modeline package; so I thought it should probably be on your radar. 

Some people mentioned debouncing, I'm not sure how to do that in elisp, or if you're already doing it, seemed like it might be a reasonable way to reduce the overhead. 

I agree pixel-scroll-mode still needs a lot of work. It's unfortunate that mainstream emacs doesn't have a good smooth scrolling solution; my ideal would be similar to in browser smooth scrolling with scrolling acceleration.

**Comment by seagle0128** [comment]
Well, actually I encountered the same issues with `emacs -Q`. `pixel-scrll-mode` just works a little bit better with default mode-line than other mode-line.

Since I am working on macOS as well, I suggest you to try the snippet I provided above, and amazing [MOS](https://mos.caldis.me/). You will enjoy the real smooth scrolling with mouse on macOS, just like touch pad.

**Comment by DarkArc** [comment]
Mouse is an issue on Linux not Mac OS unfortunately; I'm using both depending on the day/place/project. Thanks though!

**Comment by seagle0128** [comment]
Welcome! I think you'd better file an issue to GNU Emacs project.

**Comment by NightMachinary** [comment]
The line scrolling solutions don't work for inline images though. (Even with Apple's trackpads.)

**Comment by NightMachinary** [comment]
I opened an upstream [bug report](https://mail.google.com/mail/u/1/#sent/QgrcJHsbkfHVtHPGfkBFHclLXDrzQwqJWVB).

**Comment by archer-65** [comment]
Problem still here.
I have to use default modeline for decent scrolling.

**Comment by martianhi** [comment]
i have this issue very badly, but using ultra scroll. discussion with its dev here: https://github.com/jdtsmith/ultra-scroll/discussions/50. they believe it's the modeline's issue.

if i disable doom-modeline, i can pixel-precision scroll very well. on linux, emacs 31, updated doom-modeline.

**Comment by seagle0128** [comment]
@martianhi Can you please try this snippet? And to disable some segments in your env for troubleshooting.

``` emacs-lisp
(column-number-mode -1)
(line-number-mode -1)
(size-indication-mode -1)
(setq doom-modeline-percent-position nil)
```
According to the [profiling](https://github.com/jdtsmith/ultra-scroll/discussions/50#discussioncomment-18133271), the bottleneck is `ultra-scroll`.

Have to dig out the root cause.

**Comment by martianhi** [comment]
re profiling, see the subsequent reply in the discussion i linked. i'm inclined to agree with the ultra-scroll author, as their explanation makes good sense (they anticipated the issue correctly when i first brought it up), they understand the mechanisms involved well, and also fits with my experience: without doom-modeline, ultra-scroll is v fast. but i have no knowledge of modelines or scrolling.

i evaluated that code snippet in my loaded emacs, then tried scrolling, issue persists. if i should test it out some other way, let me know. i seem to mostly encounter the issue in large org files, regardless of fold state.

> And to disable some segments in your env for troubleshooting.
i'm not sure i follow you. if i should do something further, let me know.

**Comment by martianhi** [comment]
here is a revealing, and more correct (because CPU not mem) profile report:

```
        3246  78% - command-execute
        2830  68%  - funcall-interactively
        2826  68%   - ultra-scroll
        2574  62%    - ultra-scroll-down
        2428  58%     - eval
        2392  57%      - doom-modeline-segment--word-count
        2392  57%       - count-words
        2326  56%          forward-word-strictly
          12   0%      + doom-modeline-segment--buffer-info
          12   0%      + doom-modeline-format--main
           8   0%      + doom-modeline-segment--misc-info
           4   0%        doom-modeline-segment--workspace-name
         217   5%    + ultra-scroll-up
          33   0%    + posn-at-point
           4   0%     execute-extended-command
         416  10%  + byte-code
         836  20% + redisplay_internal (C function)
          32   0% + timer-event-handler
          20   0% + jit-lock-function
           5   0% + winner-save-old-configurations
           0   0%   ...
```

`doom-modeline-segment--word-count` looks like the culprit. also, none of the doom-modeline redisplay functions are running when scroll-up is called, which fits with my experience that it is only sluggish when scrolling down. can `doom-modeline-segment--word-count` be cached somehow? there is possibly no need to re-check changes to word counts when scrolling.

**Comment by martianhi** [comment]
with `(setq doom-modeline-enable-word-count nil)`: no scrolling issues.

presumably you could cache the buffer word count and only check for a new count if some typing had been done.

**Comment by jdtsmith** [comment]
Does throttling count-words fix the issue for you?  I'm considering just throttling the entire mode line during scroll (restoring after) as an `ultra-scroll` user option.  Mode line are redisplayed very aggressively in emacs.  They provide incredibly fast C-based data injection for basic stuff (buffer-name, etc.), but the `:eval` route has exploded in recent times.  Interpreting ELISP is much slower (and it doesn't get compiled by native comp unless you set it up correctly).

**Comment by martianhi** [comment]
i did this, as per the link you shared, and yes it seems to have fixed my issue: https://github.com/seagle0128/doom-modeline/pull/831.

i figure there would be other similar bottlenecks in `doom-modeline` that i haven't encountered but that others may have (i don't know its code).

and yes, perhaps all redisplay could be throttled, blanket-wise? i thought it perhaps best to patch `doom-modeline`, but maybe the option in `ultra-scroll` would at least stop folks like me bothering you about issues elsewhere! then it doesn't matter what package the bottleneck is in. maybe both helps.

**Comment by jdtsmith** [comment]
You can't throttle redisplay itself, since that's what drives the updated display during scroll, but you could cache/throttle the mode line temporarily, during scroll.  Will look at it.

**Comment by seagle0128** [comment]
> with `(setq doom-modeline-enable-word-count nil)`: no scrolling issues.

@martianhi It makes sense if `doom-modeline-enable-word-count` is enabled, since it requires frequent calculations. Thus it will slow down Emacs even with `emacs -Q`. In this case, throttling `doom-modeline-enable-word-count ` is just a workaround.

Actually in `doom-modeline`, many segments (e.g. buffer-name, check status, lsp, etc.) are only updated when they are changed for better performance, while others (e.g. buffer status, column/line number, position percentage, word count, etc.) are re-displayed in realtime, for compatibility.

> Does throttling count-words fix the issue for you? I'm considering just throttling the entire mode line during scroll (restoring after) as an `ultra-scroll` user option. Mode line are redisplayed very aggressively in emacs. They provide incredibly fast C-based data injection for basic stuff (buffer-name, etc.), but the `:eval` route has exploded in recent times. Interpreting ELISP is much slower (and it doesn't get compiled by native comp unless you set it up correctly).

@jdtsmith Basically I agree with you, that the ultimate solution is "throttling the entire mode line during scroll (restoring after)". And I will suggest to make the user option as `t` by default. But I am not sure how much the cost is as you mentioned.

**Comment by jdtsmith** [comment]
Not hard to wrap the entire mode-line in a moderate speed throttle, but I worry more about "failed restoration" after it returns.  Aside from scrolling, there are other high-cadence redisplay scenarios, e.g. holding down the arrow or PgUp/Down keys with a high key repeat rate, where recalculating on every event will slow things down.  

**Update**: an apparent bug in `format-mode-line` arises when `(display (:min-width (SPEC)))` is used (the displayed element is displayed at its "natural" width).  Does `doom-modeline` use `:min-width`?

**Comment by seagle0128** [comment]
> **Update**: an apparent bug in `format-mode-line` arises when `(display (:min-width (SPEC)))` is used (the displayed element is displayed at its "natural" width). Does `doom-modeline` use `:min-width`?

@jdtsmith No, `doom-modeline` doesn't.
