### ISSUE TITLE
If you want any help, mind putting a TODO together?

### ISSUE THREAD

**Issue by jsmestad** [seagle0128/doom-modeline#2]
Wanted to toss my hat in the ring to help on the project. If you have any TODOs or anything you can add, I'd be happy to contribute some time :)

**Comment by seagle0128** [comment]
Very glad to hear from you, and appreciate your contributions in advance!

I've submitted this package to MELPA. The PR is https://github.com/melpa/melpa/pull/5550.

Actually I'm porting the  new codes from `develop` branch of DOOM Emacs. If you are interested, please refer to `develop` branch of `doom-modeline`. I posted the issues on https://github.com/hlissner/doom-emacs/issues/136#issuecomment-397055092. 

I have no formal TODO list for now, but I'm open to get new ideas, suggestions and feedbacks.

**Comment by jsmestad** [comment]
Awesome. Will do!

**Comment by seagle0128** [comment]
The `develop` branch has almost done. I tested and it works well on my laptop.
