### ISSUE TITLE
Helm mode line is mixedly active/inactive when previewing a line

### ISSUE THREAD

**Issue by lerouxrgd** [seagle0128/doom-modeline#200]
**Describe**
When previewing a line from an Helm buffer, if the modeline has different background colors for active/inactive, then they will be mixed up.
The parts of the modeline having Helm text appear as active, and the rest as inactive.

**Steps and Expected**
The whole Helm modeline should appear either as active or inactive.

**Environment:**
 - OS: Arch GNU/Linux and Emacs doom-themes

**Additional context**
See an example of previewing an LSP match (xref) in Doom Nova theme:
![image](https://user-images.githubusercontent.com/6103291/61756552-cc075400-adbc-11e9-8487-da3141d0f51d.png)

**Comment by seagle0128** [comment]
Please test the latest version.

**Comment by lerouxrgd** [comment]
It fixed it for Helm modeline, thank you !

Just a small detail, I realized the same thing happens when closing Emacs while an active process is still running:
![image](https://user-images.githubusercontent.com/6103291/61831593-8acf7c80-ae6e-11e9-9321-df5aa4b87f74.png)

**Comment by seagle0128** [comment]
Unfortunately I cannot reproduce this issue locally. Would you please provide details?

**Comment by lerouxrgd** [comment]
So I get this if I have an active process running, like a shell started with `M-x shell`, and then from a regular file buffer I try to quit Emacs with `C-x C-c`, it will prompt the regular message `Active processes exist; kill them and exit anyway` and the focus will be on the minibuffer. 
At this moment the modeline is displayed mixedly active/inactive.

**Comment by seagle0128** [comment]
Why the process buffer is displayed while killing the Emacs as below?

https://youtu.be/xbSSm_p782c?list=PLdkj6XH8GYPQ1UmSJ3eSfcfF9QnibFv1l

**Comment by lerouxrgd** [comment]
Yes I am using `doom-nova`, Emacs version 26.2 on Arch Linux.

The buffer displaying the process to kill actually appeared on the next window, and I didn't include it on my last picture.
If I force it to appear on the same window it is as follows:
![Screenshot_20190725_183653](https://user-images.githubusercontent.com/6103291/61892730-b6a13f80-af0c-11e9-8648-ed993fcf5597.png)

**Comment by seagle0128** [comment]
I still couldn't reproduce on macOS and Linux Mint. Can you try Emacs 27?

**Comment by jjzmajic** [comment]
I'm not sure if I'm experiencing something similar [here](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L2463). The elisp fileicon in helm is now always white, and never purple like it used to be.

**Comment by seagle0128** [comment]
@jjzmajic f541215023f07e80f78145c358b6c1096e83e4db has been committed. The color is changed to blue for helm.

**Comment by jjzmajic** [comment]
I just pulled the changes, but my icon is still white. Despite `all-theh-icons-blue` being a blue face. Any hints as to what may be going on?

**Comment by jjzmajic** [comment]
Any way to change it back without redefining the whole segment?

**Comment by seagle0128** [comment]
@jjzmajic No need any change from user side. Just update the package to the latest.
