### ISSUE TITLE
fill-paragraph does not update buffer-file-state-icon

### ISSUE THREAD

**Issue by haji-ali** [seagle0128/doom-modeline#201]
I believe that the hook on `fill-paragraph` [here](https://github.com/seagle0128/doom-modeline/blob/7c318f0708e488c3ca32a19089641949a6ced59e/doom-modeline-segments.el#L346) should be replicated for the `buffer-file-state-icon`, something like

```
  (advice-add #'fill-paragraph :after #'doom-modeline-update-buffer-file-state-icon)
```

The original issue (#139) was fixed in  f4582bc but then undone in cc29f430
Is there a reason why the advice on `set-buffer-modified-p` and `restore-buffer-modified-p` was removed?

**Comment by seagle0128** [comment]
It's for performance optimization. `set-buffer-modified-p` and `restore-buffer-modified-p` are low level functions and called by many functions. I believe the advice of `fill-paragraph` should be removed now.
