### ISSUE TITLE
Request: Work with "delight" for major modes

### ISSUE THREAD

**Issue by mrbig033** [seagle0128/doom-modeline#202]
## Runtime Environment

- MX Linux 18
- [i3wm](https://i3wm.org/) version 4.13
- [i3/config](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- [dotfiles](https://github.com/mrbig033/dotfiles)
- GNU Emacs 27.0.50
- Org mode version 9.2.3
- Evil version 1.2.14
- [~/.emacs.d](https://github.com/mrbig033/emacs)

### Issue

**Is your feature request related to a problem? Please describe.**

`delight` does not for major modes. 

Example:

``` emacs-lisp
(use-package org
  :ensure nil
  :delight)
```

Keeps `Org` in the modeline. 

None of these work with `doom-modeline` either:

``` emacs-lisp
(use-package delight
  :ensure t
  :config
  (delight '(
             (projectile-mode nil)
             (sh-mode " sh " "Shell-script[bash]")
             (org-mode "" "Org")
             (Org-Src "" "OrgSrc")
             (overwrite-mode " Ovl" t)
             (special-mode " special" "special")
             (message-mode " messages" "Messages")
             (markdown-mode " md" "Markdown")
             (emacs-lisp-mode "" "*Org.**")
             (fundamental-mode " fund" "Fundamental")
             (web-mode " web" "Web")
             (undo-tree-mode " " "Undo-Tree")
             (super-save-mode "" "super-save")
             (counsel-mode "" "counsel")
             (abbrev-mode "" "Abbrev")
             (evil-org-mode "" " EvilOrg")
             (elmacro-mode " " "elmacro")
             (ivy-mode "" "ivy")
             (python-mode " Py" " Python")
             (emacs-lisp-mode " elisp" "Emacs-Lisp")
             (lisp-interaction-mode " lisp int" "Lisp Interaction"))))
```

**Describe the solution you'd like**

For `delight` to work with `doom-modeline`. 

**Describe alternatives you've considered**

I also tried the package `rich-minority`. 

**Is your feature request related to a problem? Please describe.**

Yes, supporting `delight` directly solves the issue.

**Comment by seagle0128** [comment]
According to the codes, `delight` advices `format-mode-line` which is really tricky for `mode-name`. `powerline` is also incompatible with it.

Now I am trying to avoid using `format-mode-line` for `major-mode` and `minor-mode-alist`. Please test the new version.

**Comment by mrbig033** [comment]
Thank you but I'm not sure I understand. What you mean by "test the new version"? I updated all my packages and it still doesn't work:

- doom-modeline: 20190801.1802
- delight: 1.5

**Comment by seagle0128** [comment]
I committed a new change with another solution. Please test.

**Comment by mrbig033** [comment]
You mean on Melpa or here on the repository?

**Comment by mrbig033** [comment]
Okay, it's working flawlessly now. Thank you very much!
