### ISSUE TITLE
Custom face for the LSP icon

### ISSUE THREAD

**Issue by futile** [seagle0128/doom-modeline#203]
**Is your feature request related to a problem? Please describe.**
There is currently no way to specify a face used for the lsp-icon, as it uses either `success` or `warning` (see https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1616).

**Describe the solution you'd like**
A new face that can be used to change the appearance of the lsp icon. Maybe two, one for working and one for not working, not sure what is best here.

**Describe alternatives you've considered**
Currently a workaround is changing `success` and `warning` directly, but this is suboptimal, as this is a more general adjustment than the one I want to express.

**Additional context**
None.

**Comment by seagle0128** [comment]
I added `doom-modeline-lsp-success`, `doom-modeline-lsp-warning` and `doom-modeline-lsp-error` for the LSP icon, which supports both `lsp-mode` and `eglot`.

**Comment by futile** [comment]
Wow, really quick! Thanks a lot, that 100% solves my issue :)

**Comment by andreyorst** [comment]
Sorry for bumping closed issue, but is it possible to change rocket icon to something else? Maybe allow user to set the icon through `all-the-icons` package?

**Comment by seagle0128** [comment]
@andreyorst No, I am not going to provide such customizations. But you can rewrite `doom-modeline-lsp-icon` to achieve it.
