### ISSUE TITLE
allow custom width for git status component

### ISSUE THREAD

**Issue by mattsawyer77** [seagle0128/doom-modeline#204]
**Is your feature request related to a problem? Please describe.**
Most of the projects I work on typically have long branch names with common prefixes (e.g., `feature/` or `bugfix/`). This makes the git status part of the modeline less usable. I haven't found a way to customize this, though I am no elisp expert so maybe I'm missing something.

**Describe the solution you'd like**
I would simply like a variable to set to override the default width of the git status part of the modeline if possible.

**Comment by seagle0128** [comment]
Did you try `doom-modeline-vcs-max-length`?

**Comment by mattsawyer77** [comment]
thanks @seagle0128 that works perfectly. For some reason I did not think to search for "vcs".

**Comment by seagle0128** [comment]
Welcome! Glad to know it works.
