### ISSUE TITLE
Add a option to disable vim mode in modeline

### ISSUE THREAD

**Issue by taigacute** [seagle0128/doom-modeline#205]
**Is your feature request related to a problem? Please describe.**
Hi , Add a option to disable vim mde in modeline, what do you think?  I think its not necessary
,so add a option to control  it will be good.

**Comment by seagle0128** [comment]
I can implement this feature, but it doesn't make sense. How does the `evil` user know the current editing state if they are removed from mode-line. It will confuse the users. So I don't think it's a good idea to disable it in the mode-line. The default behavior of `evil` is also displaying the state in the mode-line.

**Comment by taigacute** [comment]
for vim user ,the cursor in normal  is box , in insert is bar.. and when you switch other mode ,the commandline will show you like this `--INSERT--`

**Comment by seagle0128** [comment]
https://github.com/seagle0128/doom-modeline#faq

> How can I define my own mode-line?
