### ISSUE TITLE
Modifying evil-state color.

### ISSUE THREAD

**Issue by jandamm** [seagle0128/doom-modeline#207]
**Describe**
I want to change the color and title of `evil-state` indicators (in `modals` segment).
Using the code youve given in #8 it does not work.
It will change the text but won't change the color.

**Steps and Expected**
Add to Emacs config:
```lisp
(setq evil-normal-state-tag   (propertize "[Normal]" 'face '((:background "blue" :foreground "black")))
```
I would expect a black `[Normal]` on a blue background.

I get green `[Normal]` on a clear/black background

**Environment:**
 - OS: macOS
 - Version 10.14.6
 - Package version 20190804

**Additional context**
I'm using `doom-emacs`, so the `setq` is wrapped in `(after! doom-modeline ...)`.
This is what it looks like with the snippet above.
![Screen Shot 2019-08-07 at 12 24 16](https://user-images.githubusercontent.com/5963139/62615823-56e46480-b90e-11e9-8304-b378a428f1ed.png)

**Comment by seagle0128** [comment]
You should customize the faces below.

```elisp
doom-modeline-evil-emacs-state
doom-modeline-evil-insert-state
doom-modeline-evil-motion-state
doom-modeline-evil-normal-state
doom-modeline-evil-operator-state
doom-modeline-evil-visual-state
doom-modeline-evil-replace-state
```

**Comment by atimofeev** [comment]
Not sure if I did this in best way, but for anyone wondering how to implement this in Doom Emacs, code is following:
`(setq doom-modeline-modal-icon nil
      evil-normal-state-tag   (propertize "[Normal]")
      evil-emacs-state-tag    (propertize "[Emacs]" )
      evil-insert-state-tag   (propertize "[Insert]")
      evil-motion-state-tag   (propertize "[Motion]")
      evil-visual-state-tag   (propertize "[Visual]")
      evil-operator-state-tag (propertize "[Operator]"))

(defun setup-doom-modeline-evil-states () ;; setting up colors
  (set-face-attribute 'doom-modeline-evil-normal-state nil   :background "green"  :foreground "black")
  (set-face-attribute 'doom-modeline-evil-emacs-state nil    :background "orange" :foreground "black")
  (set-face-attribute 'doom-modeline-evil-insert-state nil   :background "red"    :foreground "white")
  (set-face-attribute 'doom-modeline-evil-motion-state nil   :background "blue"   :foreground "white")
  (set-face-attribute 'doom-modeline-evil-visual-state nil   :background "gray80" :foreground "black")
  (set-face-attribute 'doom-modeline-evil-operator-state nil :background "purple"))

(add-hook 'doom-modeline-mode-hook 'setup-doom-modeline-evil-states)
`
![image](https://github.com/seagle0128/doom-modeline/assets/39891735/b2895a03-0f7e-4c85-94dc-0b26077445c2)
![image](https://github.com/seagle0128/doom-modeline/assets/39891735/cddc80a6-a572-4eb5-b9c4-01ffb924c481)

**Comment by aloispichler** [comment]
Same, with colors from spacemacs:
```
(defun setup-doom-modeline-evil-states () ;; setting up spacemacs colors
  (setq doom-modeline-modal-icon nil
        evil-emacs-state-tag    (propertize " [Emacs] " )
        evil-normal-state-tag   (propertize " <Normal> ")
        evil-insert-state-tag   (propertize " <Insert> ")
        evil-visual-state-tag   (propertize " <Visual> ")
        evil-motion-state-tag   (propertize "[Motion]")
        evil-operator-state-tag (propertize "[Operator]"))
  (set-face-attribute 'doom-modeline-evil-normal-state nil   :background "DarkGoldenrod2" :foreground "black")
  (set-face-attribute 'doom-modeline-evil-emacs-state nil    :background "SkyBlue2"       :foreground "black")
  (set-face-attribute 'doom-modeline-evil-insert-state nil   :background "chartreuse3"    :foreground "white")
  (set-face-attribute 'doom-modeline-evil-motion-state nil   :background "plum3"          :foreground "white")
  (set-face-attribute 'doom-modeline-evil-visual-state nil   :background "gray80"         :foreground "black")
  (set-face-attribute 'doom-modeline-evil-operator-state nil :background "purple"))

(add-hook 'doom-modeline-mode-hook 'setup-doom-modeline-evil-states)
```
