### ISSUE TITLE
Disabling symbolic links expanding

### ISSUE THREAD

**Issue by Svadkos** [seagle0128/doom-modeline#209]
From https://github.com/hlissner/doom-emacs/issues/1660

**Describe**
I was trying to disable symbolic links expanding and ended up with this mess
![Screenshot](https://user-images.githubusercontent.com/9449246/62822565-c3f93380-bb74-11e9-95f6-f9c24a6cbd14.png)
It affects directories with git, and works without problems in normal dirs.

**Steps and Expected**
`(setq-default find-file-visit-truename nil)` in doom/config.el, then open any file in directory with git and symbolic link in path.

**Environment:**
 - OS: Archlinux
 - Version: latest
 - Package version: 20190812.1448

**Comment by seagle0128** [comment]
It seems duplicate with #51 .

**Comment by Svadkos** [comment]
That's right I guess. But still, I don't see any clean solution, should I use [this](https://github.com/seagle0128/doom-modeline/issues/51#issuecomment-451709846) snippet somewhere?

**Comment by seagle0128** [comment]
Yes, please try it and let me know the results.

**Comment by Svadkos** [comment]
Using [this](https://github.com/seagle0128/doom-modeline/issues/51#issuecomment-451673314) snippet directory with git shows resolved path, which is not what I expect, but still better than before:
![shot](https://user-images.githubusercontent.com/9449246/63181785-6f582b80-c040-11e9-90ba-81aa13e5a417.png)
But it broke in normal directories without git:
![shot](https://user-images.githubusercontent.com/9449246/63181981-ea214680-c040-11e9-90b6-4766ddf7071f.png)

[This](https://github.com/seagle0128/doom-modeline/issues/51#issuecomment-451709846) snippet has the same problem as unmodified modeline, except that it shows unresolved path with mouseover:
![screens](https://user-images.githubusercontent.com/9449246/63182966-5ac96280-c043-11e9-8f00-7fbc9b2e78f6.png)

**Comment by seagle0128** [comment]
I am afraid it's as designed. I am curious why you use `(setq-default find-file-visit-truename nil)` for symlinks. I suggest you use `(setq doom-modeline-buffer-file-name-style 'buffer-name)`.

**Comment by Svadkos** [comment]
Too bad. I use `(setq-default find-file-visit-truename nil)` for the same reason as described in [this post](https://github.com/seagle0128/doom-modeline/issues/51#issuecomment-451601939). Some directories in my home dir are linked to directories on separate hdd, which is mounted to /mnt. So when I open a file in symlinked dir and workdir changes to resolved path, there's no easy way to return to previous context which is really annoying.

Maybe at least [this](https://github.com/seagle0128/doom-modeline/issues/51#issuecomment-451709846) snippet can get into upstream so that mouseover would work?

**Comment by seagle0128** [comment]
Are you using `relative-from-project` for `doom-modeline-buffer-file-name-style`?

According to the docs of `file-truename` and `find-file-visit-truename`, it's as designed. [This](https://github.com/seagle0128/doom-modeline/issues/51#issuecomment-451709846) snippet doesn't make sense, and I don't know if it will brings side-effects.  

> Return the truename of FILENAME.

> If FILENAME is not absolute, first expands it against default-directory.
The truename of a file name is found by chasing symbolic links
both at the level of the file and at the level of the directories
containing it, until no links are left at any level.

**Comment by Svadkos** [comment]
It works now, thank you!

**Comment by seagle0128** [comment]
@Svadkos Can you take a look at https://github.com/seagle0128/doom-modeline/issues/224#issuecomment-542562386 , and let me know your opinion?

**Comment by seagle0128** [comment]
I add a new option (`doom-modeline-project-detection`) for project root detection. Since the issue in `projectile` isn't fixed yet (and I don't think they want to fix...), you should use `ffip` or `project` while using with symlink folders.

Please refer to item 7 in [FAQ](https://github.com/seagle0128/doom-modeline#faq)

**Comment by Svadkos** [comment]
So far, everything works well, thanks again.
