### ISSUE TITLE
modeline buffer file name's color seems wired

### ISSUE THREAD

**Issue by nicehiro** [seagle0128/doom-modeline#210]
**Describe**
Since I use other themes(not doom-themes), the buffer file name's color was getting ugly. How to customize it?

**Steps and Expected**
Open a project file will show ugly buffer file name

**Environment:**
 - OS: Arch

**Additional context**
![image](https://user-images.githubusercontent.com/17773634/63209511-63d63480-c114-11e9-9147-6a1ffab5d80d.png)

**Comment by seagle0128** [comment]
I guess you should customize the face `doom-modeline-buffer-path`, `doom-modeline-project-parent-dir`, `doom-modeline-project-dir` or `doom-modeline-project-root-dir`.

**Comment by nicehiro** [comment]
Thanks, customize first three face fix my problem.
