### ISSUE TITLE
Integrate phi-search?

### ISSUE THREAD

**Issue by andreyorst** [seagle0128/doom-modeline#212]
Phi search allows using isearch with multiple cursors. Currently when [phi-search](https://github.com/zk-phi/phi-search) is active there's default modeline:

![image](https://user-images.githubusercontent.com/19470159/63519882-61048680-c4fc-11e9-94e4-e0eb191d6248.png)
(note `*phi-search*` on the right)

It would be nice if doom-modeline could display the counter as it does for multiple cursors. Or in some separate area of modeline. Since doom-modeline supports multiple-cursors, I think it's logical to support search that supports mc as well.

**Comment by seagle0128** [comment]
It's a new feature request. Since I am not using `phi-search`, I need more time to implement it. And PRs are welcome!

**Comment by andreyorst** [comment]
> Since I am not using `phi-search`

Do you use multiple cursors? If so, can you share the trick how to do the forward or backward search without `phi-search`? (if you ever do susch search of course). Maybe there's different package or some elisp hack which I'm not avare of. I'm asking because I'd like to drop the use of `phi-search` if I could, but unfortunately it's the only one I know that is compatible with `multiple-cursors.el`

**Comment by seagle0128** [comment]
I am a user of `swiper`. I don't think the scenario you described is common.

**Comment by articuluxe** [comment]
I’ve found either phi-search or iy-go-to-char.

**Comment by seagle0128** [comment]
why not use `swiper` and `avy`? `phi-search` and `iy-go-to-char` are too old...

**Comment by andreyorst** [comment]
`swiper` doesn't allow to move existing multiple cursors to specific location. When refactoring code with multiple cursors it is convenient to move all existing multiple cursors into specific position in their respective lines, instead of selecting everything from the scratch. A brief example:

    int varName = 10; // some var
    int secondVarName = 2000; // some other variable.

By selecting these two lines and then using `mc/mark-all-in-region-regex` to mark all upper case letters we have these three cursors (`[text|]` represents region `[]` and the cursor `|` at the end):

    int var[N|]ame = 10; // some var
    int second[V|]ar[N|]ame = 2000; // some other variable.

Then we can call `C-x C-l` to downcase those regions, and insert `_` before those:

    int var_|name = 10; // some var
    int second_|var_|name = 2000; // some other variable.

After that I want to align comments. I just use `phi-search` to find `; `

    int var_name = 10[; |]// some var
    int second_var_name = 2000[; |]// some other variable.

Now I can simply align cursors with `mc/vertical-align-with-space`:

    int var_name = 10;          // some var
    int second_var_name = 2000; // some other variable.

It may look like a quite long action, but I can perform such transformations rather quickly. Without `phi-search` I would need to manually add cursors every time I want to select something in lines when the desired thing can't be reached with `C-f` or `C-M-f` movements.

`phi-search` is old, but that doesn't mean anything bad. Emacs itself is quite old.

**Comment by andreyorst** [comment]
Here's asciicast of my example:
https://asciinema.org/a/5v2MOKbT8ThINbNGgbrgx4mDq

**Comment by seagle0128** [comment]
Interesting! Thanks for the great recordings.

I didn't do such things with `phi-search`. Did you try `swiper-mc`? I am not sure if it's able to do the exact same things but looks similar.

https://oremacs.com/2015/10/14/swiper-mc/

Well, if you think `phi-search` is unique, the PR is always welcome.

**Comment by andreyorst** [comment]
> Did you try swiper-mc? I am not sure if it's able to do the exact same things but looks similar.

Yes. It allows placing cursors to the matched search patterns, which isn't quite useful in my workflow.

> Well, if you think phi-search is unique, the PR is always welcome.

I'll try to look into the sources of doom-modeline in order to integrate `phi-search`. Can we have this issue back opened to track it?
