### ISSUE TITLE
Wrong icon for haskell file extension (and probably some others)

### ISSUE THREAD

**Issue by Dr-Dd** [seagle0128/doom-modeline#214]
For some reason, even after correctly installing `doom-modeline` and `all-the-icons` from MELPA, and running `all-the-icons-install-fonts`, some icons get overridden (the only case that i've encountered is with `.hs` files).
The only icon fonts that have been installed on the system are from the `all-the-icons` package. EDIT: i forgot to mention the fact that the icons are displayed normally inside the windows, i don't know if this is a modeline problem or a font problem.

Here's a snippet from my `init.el`

```elisp
;; doom modeline (+ all-the-icons dependency)
(use-package all-the-icons
  :ensure t) ; REMEMBER to RUN "all-the-icons-install-fonts" after installation 
(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-mode)
  :config (setq doom-modeline-height 25))
;; == end of doom modeline ==
```

**Environment:**
 - OS: Arch
 - Emacs version: 26.2
 - doom-modeline version: 20190820.1749
 - all-the-icons version: 20190320.180 

![screen](https://user-images.githubusercontent.com/37450282/63639190-d30dd480-c690-11e9-98bd-69801bd0231d.png)

**Comment by seagle0128** [comment]
What's the file name? It's "test.hs"? Try other names.

**Comment by Dr-Dd** [comment]
@seagle0128 god...you are perfectly right, sorry for wasting your time, I thought globs only matched extensions. Thanks alot!

**Comment by seagle0128** [comment]
Welcome.
