### ISSUE TITLE
Reading a desktop file hides doom-modeline

### ISSUE THREAD

**Issue by qleguennec** [seagle0128/doom-modeline#216]
**Describe**
When I reload a desktop file written with doom-modeline on, the usual modeline is shown for certain buffers (example, my `init.el`)

**Steps and Expected**
- Open user init file
- Save destop and kill emacs
- Read desktop file
- The init file buffer doesn't show doom-modeline.

**Environment:**
 - OS: Archlinux
- Emacs: 27.0.50
 - Package version 20190820.1749

NB: The `*Messages*` buffer shows doom-modeline as expected.

**Comment by seagle0128** [comment]
I couldn't recreate this issue. Please make sure of loading `doom-modeline` before `desktop`. If you still have this issue please provide more details.

**Comment by qleguennec** [comment]
Loading `desktop` after `doom-modeline` fixed the issue. Thanks.
