### ISSUE TITLE
Disable/customize modeline for some windows.

### ISSUE THREAD

**Issue by jandamm** [seagle0128/doom-modeline#219]
**Is your feature request related to a problem? Please describe.**
I'm using dengste/minimap and the modeline is showing in the minimap window as well.

**Describe the solution you'd like**
I would like to disable the doom-modeline in the minimap window or have a custom modeline in this window where nothing is displayed (empty modeline).

I think this could also be useful for some who would like to have different information in the modeline depending on the buffer content.

**Comment by seagle0128** [comment]
`(setq mode-line-format nil)` or use [hide-mode-line](https://github.com/hlissner/emacs-hide-mode-line)
