### ISSUE TITLE
Major mode indicator is partially pushed out of visible area

### ISSUE THREAD

**Issue by technician77** [seagle0128/doom-modeline#222]
**Describe**
(add-to-list 'global-mode-string celestial-mode-line-string) causes major mode indicator to be partially pushed out of the visible area

**Steps and Expected**
Install celestial-mode-line
Add  (add-to-list 'global-mode-string celestial-mode-line-string))
Everything looks normal when doom-modeline is started

**Environment:**
 - OS: Windows 10
 - Version GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
 - Package version 20190914.242

**Additional context**
![image](https://user-images.githubusercontent.com/18722291/65117205-fefb4c00-d9e9-11e9-895a-5eec0831af99.png)
![image](https://user-images.githubusercontent.com/18722291/65117478-4bdf2280-d9ea-11e9-8f2f-8958cdea0f92.png)

**Comment by seagle0128** [comment]
Obviously some icons (unicode font) are used in `celestial-mode-line-string`. The solution is setting the font width to 2 to these icons (`doom-moddeline--set-font-widths`). Another workaround is to put some whitespaces at the end of the mode-line.

**Comment by technician77** [comment]
> Another workaround is to put some whitespaces at the end of the mode-line.
Is there a simple way to do this without "hardcoding" anything? Asking for stupid me who has no programming skills but must use a programmable editor.

**Comment by seagle0128** [comment]
Please see it 5 in https://github.com/seagle0128/doom-modeline#faq.
