### ISSUE TITLE
Sometimes wrong Icon for C filetype 

### ISSUE THREAD

**Issue by andreyorst** [seagle0128/doom-modeline#228]
**Describe**
Some times icon for C buffer is correct one:

![image](https://user-images.githubusercontent.com/19470159/66408983-960b6080-e9f8-11e9-9268-308c7e94757d.png)

Some times it is not:
![image](https://user-images.githubusercontent.com/19470159/66408899-707e5700-e9f8-11e9-8430-3c00a9cd5eb8.png)

I'm not sure what causes this.

**Steps and Expected**
I just open some C buffers and it is either correct icon or not. I think only one icon should be used.

**Environment:**
 - OS: Arch Linux
 - Package version 20191008.415

**Comment by seagle0128** [comment]
Hi @andreyorst , 

It's not an issue. The lab glass icon is displayed because the filename includes `test`, that means this file is a test file generally. The behavior is inherited from `all-the-icons`.

**Comment by andreyorst** [comment]
To me this is a wrong icon, since it doesn't reflect the major mode, yet the current major mode is displayed when hovering on the icon.

- What this icon is for then if it's not file type?
- Can file type be displayed with an icon?
- Can icon be inferred from `major-mode` variable instead of file name?

**Comment by seagle0128** [comment]
`doom-modeline` leverages `all-the-icons` to display icons of `major-mode`. If you still think it's an issue, please file an issue there.

**Comment by andreyorst** [comment]
I did not realized that `all-the-icons` internal algorithms are related to the selection of icon. I've thought that `doom-modeline` inspects current major mode, and puts icon with `all-the-icons-someicon` function by associating major modes with icons from `all-the-icons` fonts. Sorry for misunderstanding.

**Comment by seagle0128** [comment]
IMO it's not a bug, but you can change `all-the-icons-icon-alist` to modify the icons.

Remove this from `all-the-icons-icon-alist`.

```elisp
("-?test\\."        all-the-icons-fileicon "test-generic"           :height 1.0 :v-adjust 0.0 :face all-the-icons-dgreen)
```

**Comment by wyuenho** [comment]
WRT to domtronn/all-the-icons.el#163, why is the mode line not getting the icon from the major mode but instead the file name?

**Comment by seagle0128** [comment]
@wyuenho `all-the-icons-icon-for-buffer` is used in `doom-modeline`.

**Comment by andreyorst** [comment]
Why not `all-the-icons-icon-for-mode` though? It seem more natural as this icon displays major mode on hover

**Comment by seagle0128** [comment]
`all-the-icons-icon-for-buffer` provides more icons via comparing `auto-mode-alist`.
>Get the formatted icon for the current buffer.
This function prioritises the use of the buffers file extension to
discern the icon when its major-mode matches its auto mode,
otherwise it will use the buffers major-mode to decide its
icon.
