### ISSUE TITLE
Why modeline doesn't show horizontal cursor position?

### ISSUE THREAD

**Issue by piojanu** [seagle0128/doom-modeline#229]
Hi!

How to turn on a horizontal cursor position? Currently, modeline shows only a line number:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23562932/66505075-df2be500-eaca-11e9-83e8-3da5eabbbd8d.png">
I couldn't find a solution on my own :/

Thanks!

**Comment by seagle0128** [comment]
```elisp
(setq column-number-mode t
      line-number-mode t)
```

**Comment by piojanu** [comment]
Thanks!

**Comment by seagle0128** [comment]
Welcome :)
