### ISSUE TITLE
Modeline suddenly very tall

### ISSUE THREAD

**Issue by trev-dev** [seagle0128/doom-modeline#23]
...and it looks like there's a bear tryin' to peek its way into the right hand side. It goes away if I comment out doom-modeline. Fresh install on a different machine.

What do you think this is?

![wtf](https://user-images.githubusercontent.com/28788713/45274940-aa380380-b46e-11e8-8986-dc10935507f3.png)

**Comment by seagle0128** [comment]
Did you install `all-the-icons` fonts? 

> This package requires the fonts included with all-the-icons to be installed. Run M-x all-the-icons-install-fonts to do so.

**Comment by trev-dev** [comment]
I did, but you know what I didn't do? Install the all-the-icons fonts as per the all-the-icons instructions. Bet you that's what it is. Now I'm dying to know what the modeline is referencing instead of the little page with the exclamation point in it.

**Comment by seagle0128** [comment]
Good to know the issue was addressed. I'm considering to add FAQ.
