### ISSUE TITLE
Args out of range error on Emacs 27 on every click

### ISSUE THREAD

**Issue by andreyorst** [seagle0128/doom-modeline#232]
**Describe**
I don't think that this issue is strictly related to your plugin, but after last checkout from Emacs master and building `emacs-git-27.0.50.139018-1` I get this error, when doom-modeline plugin configuration exists:

    sort: Args out of range: [nil :family :foundry :swidth :height :weight :slant :underline :inverse :foreground ...], 19

I've figured out that this is actually related to my modification of `after-focus-change-function`: 
```emacs-lisp
(add-function :after after-focus-change-function #'solaire-mode-reset)
```
If I do this modification before I load `doom-modeline` Emacs becomes irresponsible to clicks at all. If I do it after, Emacs is responsible, but each focus-change event flashes the error, displayed above.

I've checked which functions are added to `after-focus-change-function` by doom-modeline, and found that the method you're using is exactly the same as I do for `solaire-mode-reset`:

```emacs-lisp
(with-no-warnings
  (if (boundp 'after-focus-change-function)
      (progn
        (defun doom-modeline-focus-change ()
          (if (frame-focus-state)
              (doom-modeline-focus)
            (doom-modeline-unfocus)))
        (add-function :after after-focus-change-function #'doom-modeline-focus-change))
    (progn
      (add-hook 'focus-in-hook #'doom-modeline-focus)
      (add-hook 'focus-out-hook #'doom-modeline-unfocus))))
```
Except that I use cond and more complex logic for no reason:

```emacs-lisp
(cond ((not (boundp 'after-focus-change-function))
       (add-hook 'focus-in-hook  #'solaire-mode-reset))
      (t
       (add-function :after after-focus-change-function #'solaire-mode-reset)))
```

Do you have any thoughts on how I can fix this? Maybe the problem is in `solaire-mode-reset` though. But I still wonder, why if I enable doom-modeline after my modification it completely breaks mouse clicks, and doesn't if I load my modification after doom-modeline.

**Environment:**
 - OS: Arch Linux
 - Package version [e.g. 201801228]

Also, if the variable looks like so everything works, but error message pops:

```
Value:
#f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames)
                                                                                                                       doom-modeline-refresh-frame)
                                                                                              doom-modeline-focus-change)
                                                                     #f(compiled-function
                                                                        ()
                                                                        #<bytecode 0x157ab1f10b65>))
                                            #f(compiled-function
                                               ()
                                               #<bytecode 0x157ab1f14a59>))
                   solaire-mode-reset)
```

If it looks like so:

```
Value:
#f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames)
                                                                                                                       solaire-mode-reset)
                                                                                              doom-modeline-refresh-frame)
                                                                     doom-modeline-focus-change)
                                            #f(compiled-function
                                               ()
                                               #<bytecode 0x1577cd2caa89>))
                   #f(compiled-function
                      ()
                      #<bytecode 0x1577cd2ce87d>))
```

Nothing works.

**Comment by andreyorst** [comment]
To summarize:
- If I load my **solaire** config before **doom-modeline** Emacs can't register clicks properly, and every click is error message in `*Messages*`
- If I load **doom-modeline** before my **solaire** config, some clicks work, and some display error message and don't work.

**Comment by seagle0128** [comment]
Interesting...

I added your snippet in my [config](https://github.com/seagle0128/.emacs.d/), but couldn't reproduce the issue. I am also wondering why reset solaire-mode while focusing in. I don't think it's necessary, unless there are some tricks about themes or faces in your config.

BTW, I am using GNU Emacs 27.0.50 on macOS Catalina.

**Comment by andreyorst** [comment]
@seagle0128 I've disabled my code, and still some times get this error message while clinking

**Comment by andreyorst** [comment]
> I couldn't find your config

[here](https://github.com/andreyorst/dotfiles/tree/master/.emacs.d)

> Did you test with emacs -Q?

I did, but this issue is kinda random to appear. I'll try to come up with easy steps

>  Well, my suggestion is checking the faces and themes in your config first.

I'm using doom-themes, doom-one to be specific.

**Comment by seagle0128** [comment]
Strange! I tested with your snippet. No issue...

![image](https://user-images.githubusercontent.com/140797/66931729-1c631a80-f069-11e9-9d21-2af468d6b3da.png)

**Comment by seagle0128** [comment]
Right! Since I am also using 27.0.50, but I didn't encounter this issue. If the recent changes breaks something, we should read the log and messages from Emacs to address it. It seems 27 is not stable and I'd like wait for pre-test or release version.

**Comment by andreyorst** [comment]
My build of Emacs 27 is based on this commit: `d502f0c4b5bf0d6dbf0a125b01db21fa3b6292df`
Maybe your build is outdated and you don't have this issue yet?

**Comment by andreyorst** [comment]
Sure:
<details>
 <summary>Backtrace (Hidden)</summary>

```
Debugger entered--Lisp error: (args-out-of-range [nil :family :foundry :swidth :height :weight :slant :underline :inverse :foreground :background :stipple :overline :strike :box :font :inherit :fontset :vector] 19)
  face-attrs-more-relative-p(mode-line-inactive solaire-mode-line-face)
  sort((solaire-mode-line-face) face-attrs-more-relative-p)
  face-remap-order((mode-line-inactive))
  face-remap-add-relative(mode-line mode-line-inactive)
  doom-modeline-unfocus()
  doom-modeline-focus-change()
  apply(doom-modeline-focus-change nil)
  #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames) doom-modeline-refresh-frame) doom-modeline-focus-change)()
  apply(#f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames) doom-modeline-refresh-frame) doom-modeline-focus-change) nil)
  #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames) doom-modeline-refresh-frame) doom-modeline-focus-change) #f(compiled-function () #<bytecode 0x156d8b3298a9>))()
  apply(#f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames) doom-modeline-refresh-frame) doom-modeline-focus-change) #f(compiled-function () #<bytecode 0x156d8b3298a9>)) nil)
  #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore blink-cursor--rescan-frames) doom-modeline-refresh-frame) doom-modeline-focus-change) #f(compiled-function () #<bytecode 0x156d8b3298a9>)) #f(compiled-function () #<bytecode 0x156d8b32ba45>))()
  handle-focus-out((focus-out #<frame emacs@s06 0x55b62c1ed010>))
  funcall-interactively(handle-focus-out (focus-out #<frame emacs@s06 0x55b62c1ed010>))
  call-interactively(handle-focus-out nil [(focus-out #<frame emacs@s06 0x55b62c1ed010>)])
  command-execute(handle-focus-out nil [(focus-out #<frame emacs@s06 0x55b62c1ed010>)] t)
```
</details>

I've changed the emacs command to:

```
emacs -q --eval "(progn 
                   (package-initialize)
                   (setq debug-on-error t)
                   (require 'doom-themes)
                   (load-theme 'doom-one t)
                   (require 'solaire-mode)
                   (solaire-mode)
                   (require 'doom-modeline)
                   (doom-modeline-mode))"
```

**Comment by seagle0128** [comment]
You should check if there are some changes of `face-remap-add-relative`, `face-remap-order`, and `order`.

**Comment by andreyorst** [comment]
Git blame shows that latest changes in `face-remap-add-relative` and `face-remap-order` are from 2012.

What is `order`? I don't see such function or variable anywhere in the source code.

**Comment by theophilusx** [comment]
I am also seeing this error, but when I create a new frame or switch between frames. I'm loading the doom-modeline package using use-package. I only started seeing this on emacs 27.0.50 after recent build (last 2 days) and the error seems to be triggered by changes in focus. The backtrace is attached

[backtrace.txt](https://github.com/seagle0128/doom-modeline/files/3737840/backtrace.txt)

**Comment by andreyorst** [comment]
I've also figured out why I added the

```emacs-lisp
(add-function :after after-focus-change-function #'solaire-mode-reset)
```

to my config. I have to set some faces on per buffer basis, and resetting solaire is required to make it seamless.

Though this function alone doesn't cause the error, I think it's strange that it makes the situation orders of magnitude worse.

**Comment by theophilusx** [comment]
In case it helps, I'm not adding any custom focus functions. I only load the doom-modeline package with no other focus related tweaks.

**Comment by theophilusx** [comment]
Just noticed there was a new version of doom-modeline in melpa. Updated, but has not changed the error.

**Comment by kamoii** [comment]
I had the same problem, so I inspected a little. Found a workaround.
```elisp
(setq internal-lisp-face-attributes
  [nil
   :family :foundry :swidth :height :weight :slant :underline :inverse
   :foreground :background :stipple :overline :strike :box
   :font :inherit :fontset :vector :extend])
```
Its prabably an emacs bug introduced recently. Commit f9206f34d63104c50659a15d3615646a09df87bf intorduced new `LFACE_EXTEND_INDEX` enum for `lface_attribute_index` in `src/dispextern.h`, but probably forget to add corresponding value to `internal-lisp-face-attributes` defvar, causing an `arg-out-of-error` for few face related funcitons.

**Comment by seagle0128** [comment]
@kamoii would you please report to gnu. org?

**Comment by kamoii** [comment]
@seagle0128 After searching the issue list, I found it was already reported.
https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01686.html

**Comment by wedens** [comment]
I have (probably) the same issue on recent emacs 27 build and I don't use solaire-mode.

```
Debugger entered--Lisp error: (args-out-of-range [nil :family :foundry :swidth :height :weight :slant :underline :inverse :foreground :background :stipple :overline :strike :box :font :inherit :fontset :vector] 19)
  face-attrs-more-relative-p(mode-line-inactive mode-line-inactive)
  sort((mode-line-inactive) face-attrs-more-relative-p)
  face-remap-order((mode-line-inactive))
  face-remap-add-relative(mode-line mode-line-inactive)
  doom-modeline-unfocus()
  doom-modeline-focus-change()
  apply(doom-modeline-focus-change nil)
  #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore (closure (t) nil (if (frame-focus-state) nil (garbage-collect)))) doom-modeline-refresh-frame) doom-modeline-focus-change)()
  apply(#f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore (closure (t) nil (if (frame-focus-state) nil (garbage-collect)))) doom-modeline-refresh-frame) doom-modeline-focus-change) nil)
  #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore (closure (t) nil (if (frame-focus-state) nil (garbage-collect)))) doom-modeline-refresh-frame) doom-modeline-focus-change) #f(compiled-function () #<bytecode 0x159555f790cd>))()
  apply(#f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore (closure (t) nil (if (frame-focus-state) nil (garbage-collect)))) doom-modeline-refresh-frame) doom-modeline-focus-change) #f(compiled-function () #<bytecode 0x159555f790cd>)) nil)
  #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after #f(advice-wrapper :after ignore (closure (t) nil (if (frame-focus-state) nil (garbage-collect)))) doom-modeline-refresh-frame) doom-modeline-focus-change) #f(compiled-function () #<bytecode 0x159555f790cd>)) #f(compiled-function () #<bytecode 0x1595560a0011>))()
  handle-focus-in((focus-in #<frame emacs-main 0x565559415730>))
  funcall-interactively(handle-focus-in (focus-in #<frame emacs-main 0x565559415730>))
  call-interactively(handle-focus-in nil [(focus-in #<frame emacs-main 0x565559415730>)])
  command-execute(handle-focus-in nil [(focus-in #<frame emacs-main 0x565559415730>)] t)
```

**Comment by kamoii** [comment]
FYI, fix(commit 270ca..) has been merged into master.

**Comment by andreyorst** [comment]
Since this is an upstream bug, this issue was false from the beginning. Thanks everyone for the patience! I can confirm that issue no longer reproducible in the latest build of Emacs 27
