### ISSUE TITLE
Warning about fancy-battery-mode

### ISSUE THREAD

**Issue by jsmestad** [seagle0128/doom-modeline#234]
**Describe**
Installing emacs-plus 27.0.50 and installing doom-modeline on my MBP, I get an error from use-package

`Error (use-package): doom-modeline/:config: Symbol’s value as variable is void: fancy-battery-last-status`

Funny thing is, I do not use `fancy-battery` at all. Even after trying with fancy-battery installed, I get the same error, but the battery status shows up. 🤷‍♂️

**Environment:**
 - OS: macOS
 - Version: Mojave
 - Package version 20191022

**Comment by TakaakiFuruse** [comment]
I had the same problem.

Mine is Mint Linux 19.02 and Spacemacs Dev. Looks like fancy-battery is called from doom-modeline and causing problem?

Is there any way to remove dependency of fancy-battery, because the library is not maintained anymore?

**Comment by seagle0128** [comment]
This is a regression issue. I will fix it soon.

@TakaakiFuruse Thank you for the information! I am thinking to drop `fancy-battery-mode`, and use built-in `display-battery-mode` instead.

**Comment by jjzmajic** [comment]
Dang that was fast. Thanks @seagle0128!

**Comment by TakaakiFuruse** [comment]
@seagle0128 
Just applied your patch and confirmed that the problem is gone. 
Thanks for your job.
