### ISSUE TITLE
LSP icon doesn't update when server crashes

### ISSUE THREAD

**Issue by muirrn** [seagle0128/doom-modeline#238]
My LSP sever crashed and I chose not to restart it. However, the mode line still shows a green rocket ship and `LSP Conneced ...` on mouseover.

**Comment by seagle0128** [comment]
I don't know how to mock LSP crashes. If I kill the LSP process, the icon will turn to yellow, and lsp-mode will remind to restart the server.

@yyoncho , do you know how to check the LSP server crashed? Or is there any hook or function to notify it?

**Comment by yyoncho** [comment]
I think that `lsp-after-uninitialized-hook` could be used.

**Comment by seagle0128** [comment]
I've already used it like this, but as @muirrn mentioned it didn't work.

```elisp
(add-hook 'lsp-after-uninitialized-hook #'doom-modeline-update-lsp)
```

**Comment by muirrn** [comment]
Hmm, I can't reproduce this anymore. I tried a few things but the modeline always updated properly.
