### ISSUE TITLE
Modeline doesn't display properly in certain buffers

### ISSUE THREAD

**Issue by muirrn** [seagle0128/doom-modeline#239]
**Describe**
Doom mode line not rendered in certain buffers. For example the mode and cursor position aren't displayed. See right buffer:
<img width="1669" alt="Screen Shot 2019-10-25 at 3 21 35 PM" src="https://user-images.githubusercontent.com/11356572/67607983-3a9cda80-f73b-11e9-9f6f-494109fc8049.png">

**Steps and Expected**
Run `(switch-to-buffer (url-retrieve-synchronously "https://play.golang.org/p/HmnNoBf0p1z"))` (URL is not important, just happened to be what I ran).

I expected the buffer to show basic info such as "Fundamental" mode and cursor position.

**Environment:**
 - OS: Mac
 - Version 10.14
 - Package version 20191025.1606

**Comment by seagle0128** [comment]
I don't think it's an issue. If set `fundamental-mode` to this buffer, the mode-line should Okay.

**Comment by muirrn** [comment]
The buffer is already in `fundamental-mode`, though. If you examine `major-mode` or run `C-h m` you can verify.

**Comment by seagle0128** [comment]
It seems `url-retrieve-synchronously` forces to set the mode-line to "%b [%s]". I tried `telephone-line` and `spaceline`, and also observe the same phenomenon.

![image](https://user-images.githubusercontent.com/140797/67636937-8654ad00-f910-11e9-802b-4a7eb3f36326.png)

Try this snippet:
```elisp
(let ((buf (url-retrieve-synchronously "https://play.golang.org/p/HmnNoBf0p1z")))
  (with-current-buffer buf
    (fundamental-mode))
  (switch-to-buffer buf))
```

**Comment by muirrn** [comment]
Alright, thanks.
