### ISSUE TITLE
EOL (End Of Line) change

### ISSUE THREAD

**Issue by actonDev** [seagle0128/doom-modeline#240]
First things first: thanks for this great modeline! :)

The only thing that I miss with this mode line (vs the default/usual ones) is that I cannot change the EOL mode.

In the default modeline you just click the current EOL and it cycles between DOS/unix/mac.
In doom-modeline you can indeed see the EOL, but the click behavior is acting on the coding system.

If you have `CRLF UTF-8` shown in the modeline I think it makes sense that each one is clickable to change its perspective property. Right now both act as the same clickable button, for the encoding.

**Comment by seagle0128** [comment]
Well, that's by designed. But maybe I can implement this feature.
