### ISSUE TITLE
Checker segment is cut in half lengthwise.

### ISSUE THREAD

**Issue by itome** [seagle0128/doom-modeline#241]
**Describe**
Last part of checker segment is not visible.

**Steps and Expected**
I'm using default configuration in https://github.com/syl20bnr/spacemacs/

https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-modeline/packages.el#L34

**Screenshot**
![Screenshot from 2019-10-27 09-57-51](https://user-images.githubusercontent.com/24409457/67627961-faf00300-f8a0-11e9-932d-530efd90dd36.png)

**Comment by seagle0128** [comment]
Please provide the details as the template for the better troubleshooting. Thanks!

**Comment by itome** [comment]
Sorry, additional infomations, please tell me if additional info is needed.

**Describe**
Checker section isn't displayed properly.
expected
<img width="293" alt="Screen Shot 2019-10-28 at 18 49 42" src="https://user-images.githubusercontent.com/24409457/67668675-c0c35600-f9b3-11e9-97ba-c565643f432a.png">

my modeline
<img width="243" alt="Screen Shot 2019-10-28 at 18 45 28" src="https://user-images.githubusercontent.com/24409457/67668627-a8533b80-f9b3-11e9-8a85-9c509b93a603.png">

**Environment:**
 - OS: MacOS Catalina, Ubuntu 18.04 (issue reproduced in both os)
 - Version 27.0
 - Package version doom-modeline-20190909.918

**Comment by seagle0128** [comment]
Please try `doom-modeline-20191027.1850`.

**Comment by noctuid** [comment]
I have this issue with the latest commit but only if I enable `doom-modeline` before the first GUI frame (e.g. if I have `(doom-modeline-mode)` in my config and start an Emacs daemon and then create a frame). If I create a frame and then enable doom modeline, there are no issues.

**Comment by itome** [comment]
@seagle0128 
Issue not fixed with latest version. Any idea to avoid @noctuid 's issue?

**Comment by seagle0128** [comment]
@itome Are you using daemon mode as well? I couldn't reproduce the issue on my MacBook.

- macOS Catalina, Mint Linux 19.2
- 20191104.1412
- GNU Emacs 27.0.50

**Comment by seagle0128** [comment]
@noctuid @itome Any update? What font are you using in Emacs?

**Comment by noctuid** [comment]
It happens for me regardless of font. It doesn't happen for me for elisp. It happens in org mode for the no checker available icon (which is different depending on whether I enabled doom modeline before or after the first GUI frame):
![2019 11 09_12:09:45_-_emacsbahamut](https://user-images.githubusercontent.com/4250696/68532419-f1c45480-02ea-11ea-9746-c61e4be2fd12.png)

vs.:
![2019 11 09_12:12:49_-_emacsbahamut](https://user-images.githubusercontent.com/4250696/68532423-fbe65300-02ea-11ea-981a-c210964ee941.png)

Unfortunately, I can't reproduce this issue with a minimal config. I'll let you know If I can find a minimal config to reproduce it.

**Comment by itome** [comment]
I'm using source code pro and issue happens in other fonts too.

**Comment by itome** [comment]
This issue was already fixed in latest version. Thanks.
