### ISSUE TITLE
Strange character in org-mode.

### ISSUE THREAD

**Issue by ecnelises** [seagle0128/doom-modeline#243]
**Describe**
There's such strange character when editing org files (see below).

**Steps and Expected**
1. Use `:e test.org` to edit an org file (new or existing are okay).
2. Did any changes to make it in non-saved state.

**Environment:**
 - OS: macOS
 - Version: 10.15
 - Package version
  - Doom: `7f317e32ca5b4eaa32edd1e323deab94de95991d`

**Additional context**
No such character when running emacs in terminal.
<img width="234" alt="截圖 2019-10-28 下午6 13 35" src="https://user-images.githubusercontent.com/10329663/67670350-ab97f880-f9ae-11e9-97bf-18bc98691c17.png">

**Comment by seagle0128** [comment]
What's the Package version?

**Comment by ecnelises** [comment]
> What's the Package version?

`pkg-info-version-info` says `doom-modeline` is `2.7.0`. I updated `.emacs.d` repo to `762c374198a919facb6a36185d6be680359ecc88` (`all-the-icon` fonts not installed) and change font to Monaco (or comment all in `config.el`), the problem still happens. The character should be the emoji 🔒 and 💾.

**Comment by seagle0128** [comment]
I couldn't reproduce this issue on my env. Can you reproduce with `emacs -Q`?

**Comment by ecnelises** [comment]
> I couldn't reproduce this issue on my env. Can you reproduce with `emacs -Q`?
> 
> BTW, it should be an icon from `all-the-icons`, while not emoji character in GUI.

I tried another network and successfully re-installed `all-the-icons`. Now the issue goes away. Sorry and thank you!
