### ISSUE TITLE
Unable to kill *scratch* when I start emacs

### ISSUE THREAD

**Issue by shanyouli** [seagle0128/doom-modeline#248]
**Describe**
"\*scratch\*" buffer seems to have to exist if you want doom-modeline to work correctly.
When I initialize the emacs to execute (kill-buffer "*scratch*"), start doom-modeline, I will get an error.
```
Funcall-interactively: No buffer named *scratch*
```
The minimum profile is
```lisp
;; No display `*scratch*'
(defun remove-scratch-buffer ()
  (if (get-buffer "*scratch*")
      (kill-buffer "*scratch*")))

(add-hook 'after-change-major-mode-hook #'remove-scratch-buffer)

(require 'package)
(unless (package-installed-p 'doom-modeline)
  (package-refresh-contents)
  (package-install 'doom-modeline))
(package-initialize)
(require 'doom-modeline)
(doom-modeline-mode)
```

**Comment by seagle0128** [comment]
Right! `doom-modeline` will set mode-line for the `*scratch` buffer, which is created by default. I didn't realize this buffer would be deleted by users. Let me think how to fix it.
