### ISSUE TITLE
Huge space appeared at the beginning of the modeline

### ISSUE THREAD

**Issue by andreyorst** [seagle0128/doom-modeline#249]
There was no such big space before the mode icon before:

Old:
![image](https://user-images.githubusercontent.com/19470159/68486885-1a007480-0253-11ea-9000-49a22e65e52e.png)
New:
![image](https://user-images.githubusercontent.com/19470159/68486695-ae1e0c00-0252-11ea-989d-3f707f4dd3c8.png)

Reproduces with `emacs -q`

**Environment:**
 - OS: Fedora 31
 - Version Emacs 27
 - Package version 20191107.1908

**Comment by seagle0128** [comment]
Please test the latest version.
