### ISSUE TITLE
modeline flycheck position error

### ISSUE THREAD

**Issue by Jackson-soft** [seagle0128/doom-modeline#25]
![image](https://user-images.githubusercontent.com/3928114/45289745-8634fa80-b520-11e8-84e9-5b8532f809e3.png)

**Comment by Jackson-soft** [comment]
if  "YaHei Monaco:pixelsize=14" is OK

**Comment by seagle0128** [comment]
Sorry. I am not very clear. Do you mean the icon of flycheck status is out of mode-line scope? If so, to change the font family or size will be helpful. I recommend `source code pro`. It's not an issue.

**Comment by seagle0128** [comment]
If you stick to use the "YaHei Monaco:pixelsize=18", please add this config and try.
```elisp
(doom-modeline-def-modeline 'main
        '(workspace-number window-number bar evil-state matches " " buffer-info buffer-position " " selection-info)
       '(global buffer-encoding major-mode process vcs flycheck " "))

(doom-modeline-def-modeline 'special
       '(window-number bar evil-state matches " " buffer-info-simple buffer-position " " selection-info)
       '(global buffer-encoding major-mode process flycheck " "))
```

Please feel free to reopen if you still have question.
