### ISSUE TITLE
Doom modeline no longer shows evil status in text

### ISSUE THREAD

**Issue by njunxuan** [seagle0128/doom-modeline#254]
**Describe**
Doom modeline no longer shows the text status of EVIL. For e.g: NORMAL, INSERT etc. I believe this was due to the update in e93660e93f1df91e8494f386ad3a8149f6d77e0f. Now, the modeline only shows a dot and uses color to indicate the current status.

Is there some way/setting to revert back to the original behaviour?

I have tried `(setq doom-modeline-evil-state-icon nil)` but it does not seem to change anything. Thank you! 😄 

**Environment:**
 - OS: MacOS
 - Version: 27 HEAD
 - Package version 20191111.740

**Additional context**
Using emacs HEAD together with spacemacs

**Comment by seagle0128** [comment]
I suppose you were using unicode characters.
Try `(setq doom-modeline-unicode-fallback nil)`.
