### ISSUE TITLE
Doc for modal state icon

### ISSUE THREAD

**Issue by ema2159** [seagle0128/doom-modeline#258]
Hi Mr. Zhang. I see you implemented this cool feature giving different options of modal state icons to the user. However, it doesn't seem to be documented (at least in the README it isn't). Could you add some documentation?

**Comment by seagle0128** [comment]
In README, you can find this, and the screenshots of `evil`. What's else do you need? PR is always welcome 😄 

> An indicator for modal editing state, including evil, overwrite, god, ryo and xah-fly-keys, etc.

**Comment by ema2159** [comment]
I think I did not express myself correctly. Originally, `doom-modeline` had an evil indicator in the form of <I>, <N>, <V> etc. Since the update, now it's a bullet icon. I thought there was a way to do like `(setq doom-modeline-evil-indicator 'bullet) or `'letter` or something like that to switch between both that wasn't documented. That's what I meant but I think such option doesn't exist or does it?

**Comment by atanasj** [comment]
I see this is closed, but @ema2159, is there a solution to this i.e., `'bulllet` or `'letter`?

**Comment by ema2159** [comment]
As I understand, there isn't

**Comment by seagle0128** [comment]
Did you check `doom-modeline-modal-icon`?

**Comment by justinjk007** [comment]
> Did you check doom-modeline-modal-icon? Is it what you want?

That helped me
