### ISSUE TITLE
Visual glitches in between irc and irc-buffers segments

### ISSUE THREAD

**Issue by endoffile78** [seagle0128/doom-modeline#259]
**Describe**
I get a black bar in between the irc segment and each buffer in the irc-buffers segment. It will occasionally go away and have a uniform color but it comes back eventually. 

**Steps and Expected**
I don't know how to reproduce it, it happened immediately.

**Environment:**
 - OS: Linux
 - Version: 5.3.9
 - Package version: master

**Additional context**

![doom](https://user-images.githubusercontent.com/11342054/68998891-e094be00-087d-11ea-81b0-05329525a2e8.png)

**Comment by seagle0128** [comment]
Which version of `doom-modeline` are you using? `irc-buffers` segment has been removed in master branch. Please try the latest version.

**Comment by endoffile78** [comment]
This seems to be gone on master.
