### ISSUE TITLE
dracula主题下颜色的渲染不正常

### ISSUE THREAD

**Issue by lambdacn** [seagle0128/doom-modeline#26]
你好，readme里面给出的例图很赞
<img width="637" alt="image" src="https://user-images.githubusercontent.com/22525327/45533280-b5ea4800-b829-11e8-9c5d-c23a93aa9057.png">
但是在我使用的dracula主题下似乎不能正常显示
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22525327/45533194-6277fa00-b829-11e8-97d2-2e0fc4895997.png">

版本是 macos10.13 emacs-mac26

**Comment by seagle0128** [comment]
请使用`doom-themes`里的`doom-dracula`。doom-modeline 和这些主题是经过适配的。
