### ISSUE TITLE
circe tracking buffers no longer work

### ISSUE THREAD

**Issue by seanfarley** [seagle0128/doom-modeline#260]
**Describe**
This is from a recent refactor to make circe modeline work with erc.

To fix this a few questions need to be answered:
 - should we put back `irc-buffers` or have a flag that changes the segment's behavior? (see [here](https://github.com/seagle0128/doom-modeline/pull/110#issuecomment-554683833) for more info)
 - `circe` doesn't use `tracking-add-buffers` and friends so we'll need some of the old hooks back or we could send a PR to circe to use them
 - probably other stuff I'm forgetting now

**Comment by seagle0128** [comment]
> should we put back irc-buffers or have a flag that changes the segment's behavior? 

Actually new option `doom-modeline-irc-buffers` was added while merging `irc` and `irc-buffers` segment. I think it's what you need. 

> circe doesn't use tracking-add-buffers and friends so we'll need some of the old hooks back or we could send a PR to circe to use them

I removed all hooks and advices. I think this issue has been addressed. Please try the latest version.

**Comment by seanfarley** [comment]
> I removed all hooks and advices. I think this issue has been addressed. Please try the latest version.

Ah, yes, that seems to have fixed the hooks; thanks!

> Actually new option doom-modeline-irc-buffers was added while merging irc and irc-buffers segment. I think it's what you need.

I see what you did now. This is a bit different from what I wrote. Previously, I had two segments so that I could see a small notification (the quote icon + number of messages as you have in your first screenshot) in the modeline but, and this is where things are missing, I only want this segment in my non-chat perspectives. The reason for this is that I usually have limited horizontal space in the modeline due to flycheck, vcs info, encoding, etc.

When I switch to my "chat" (circe, erc, etc) perspective, then I don't have all the flycheck / vs / encoding / etc in the modeline since it's a different type of buffer. Therefore, I prefer to see the list of all buffers being tracked.

Combining both segments into and having the behavior switch depending on the perspective seems a bit complicated as opposed to using `doom-modeline-def-modeline`.

Anyways, what do you think?

**Comment by seagle0128** [comment]
OK. I understand what you need completely now. I will add `irc-buffers` segment back, and remove `doom-modeline-irc-buffers`.

**Comment by seanfarley** [comment]
Wow, so fast; thanks so much!
