### ISSUE TITLE
Fancy battery icon is not shown anymore

### ISSUE THREAD

**Issue by iris-garcia** [seagle0128/doom-modeline#263]
**Describe**
Not sure if there was a breaking change in fancy-battery or in doom-modeline, but currently it is not showing its icon.

**Environment:**
 - OS: Linux
 - Version: 5.3.4-arch1-1-ARCH

**Additional context**
![fancy_battery](https://user-images.githubusercontent.com/3024945/69082843-38c7ed80-0a41-11ea-9ad9-3a799f0e4b91.png)

**Comment by seagle0128** [comment]
[Feature] Use built-in `battery` instead of unmaintained `fancy-battery`.
See 93135d422086b51488033485fb3f5a8fa75659d2.
