### ISSUE TITLE
把doom-modeline-evil-state-icon的显示改回原来的用字母N、I、V、E显示

### ISSUE THREAD

**Issue by georgealbert** [seagle0128/doom-modeline#265]
在11月6日的commit后，doom-modeline-evil-state-icon的显示用颜色来提示evil的当前mode的状态，建议改回原来的用字母N、I、V、E显示。这样更加直观。

**Comment by seagle0128** [comment]
设置`(setq doom-modeline-evil-state-icon nil)`。
最新版本中设置 `(setq doom-modeline-modal-icon nil)`。
