### ISSUE TITLE
Modeline height changes upon reloading `init.el`

### ISSUE THREAD

**Issue by apc** [seagle0128/doom-modeline#269]
**Describe**
Whenever I load `init.e`, the height of the modeline changes. The height goes back to its default as soon as I interact with the mini-buffer. 

**Steps and Expected**

Load Emacs with this config file (I ran `emacs -q -l` followed with the path to the stripped-down `init` file below): 

```

(setq gc-cons-threshold 402653184
      gc-cons-percentage 0.6)
(add-hook 'after-init-hook
          `(lambda ()
             (setq gc-cons-threshold 800000
                   gc-cons-percentage 0.1)
             (garbage-collect)) t)

;; Initialize package.el
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives
             '("org" . "https://orgmode.org/elpa/") t)
(package-initialize)

;; Bootstrap `use-package'
(setq-default use-package-always-ensure t ; Auto-download package if not exists
              use-package-always-defer t ; Always defer load package to speed up startup
              use-package-verbose nil ; Don't report loading details
              use-package-expand-minimally t  ; make the expanded code as minimal as possible
              use-package-enable-imenu-support t) ; Let imenu finds use-package definitions
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(set-face-attribute 'default nil :height 175  :font "Input Mono Compressed" :weight 'regular)

(use-package all-the-icons)

(use-package nord-theme
  :ensure t
  :defer nil
  :config
  (load-theme 'nord t)
  (setq nord-region-highlight "default")
  )

(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  :config
  ;; (setq doom-modeline-height 55)
  (setq doom-modeline-height 1)
  (setq doom-modeline-icon nil)
  (set-face-attribute 'mode-line nil :height 151)
  (set-face-attribute 'mode-line-inactive nil :height 151)
  )


```

The apparent bug only shows up when using both `nord` as a theme *and* `Input Mono` as a font. (I tried using `nord` with a different font and I did not get the unwanted behavior; I tried using `Input Mono` with the default theme and did not get the unwanted behavior.) I suspect the problem may be due to the fact that the version of `Input` I have in my system has a non-standard line-height built-in. What's odd is that using `Input` with the default theme is not enough to generate the problem. 

**Environment:**
 - OS: macOS
 - Version: 10.14.6
 - Package version: 20191124.1405

**Additional context**

![ezgif-2-87e45bd3712c](https://user-images.githubusercontent.com/350504/69501202-bc199100-0ed0-11ea-8abb-c2a47cf8bb53.gif)

**Comment by seagle0128** [comment]
Check `(doom-modeline--font-height)` in the buffer. The root cause is the `:height` attribute of `mode-line`, which is related to the font version. BTW, I couldn't reproduce the issue in my env.

**Comment by apc** [comment]
Thanks for taking the time to look into this. By "check `(doom-modeline--font-height)` in the buffer" do you mean to suggest I evaluate that expression? (Sorry, I'm quite new to Emacs, in case it wasn't obvious.)

At any rate, simply removing `(setq doom-modeline-height 1)` from the `:config` section seems to have taken care of the issue. I guess I don't understand what's going on, but there's no need to open an issue here just for *that*. (!)

**Comment by seagle0128** [comment]
Yes, just evaluate `(doom-modeline--font-height)` in the buffer. You could look into the function `doom-modeline--font-height` for details.

**Comment by apc** [comment]
Thanks, will do!
