### ISSUE TITLE
Visual block modeline indicator not shown on `C-v`

### ISSUE THREAD

**Issue by duianto** [seagle0128/doom-modeline#27]
### Description

The evil visual block modeline indicator doesn't appear when `C-v` is pressed. But it does appear when `o` is pressed, which moves the cursor to the other end of the selection.

### Steps to reproduce

- Start Emacs
- Open a new buffer: `C-x b` `test` `<return>`
- Type a letter: `a`
- Start an evil visual block selection: `C-v`

### Expected behavior

The modeline should show: `1x1B`

### Actual behavior

The modeline doesn't indicate that there is an active selection, even though the minibuffer shows:
`-- VISUAL BLOCK --`

When `o` is pressed, then the `1x1B` indicator appears on the modeline.

### Additional Notes

Pressing `C-x SPC` shows the block indicator on the modeline instantly.

Emacs also seems to have issues with detecting an evil visual block selection. Because when a visual block selection is started `C-v` then both the Emacs toolbar copy button and the edit menu > copy entry are disabled. They become enabled when `o` is pressed.

### System Info

(both packages were installed from melpa)
doom-modeline 20180911.941 a476d582a282d33b2db927dabc39e4e607292f9d
evil 20180914.1216
Emacs 26.1
Windows 10 Version 1803

**Comment by seagle0128** [comment]
Thanks for the reporting! I'm so impressive about your detailed reports.

Actually it's the design of `evil-mode`. In `evil-viusal-block`, `(evil-transient-mark -1)` is called to unmark the region. I don't know why, but find a trick to address this issue.

**Comment by duianto** [comment]
Just tested the latest version and the visual block indicator now appears instantly. Thank you.
