### ISSUE TITLE
Continuous word count degrades performance 

### ISSUE THREAD

**Issue by jmromer** [seagle0128/doom-modeline#270]
**Describe**

PR #268 introduced a performance regression for large `text-mode` files, which (in particular YAML files) suffer degraded performance when `doom-modeline-enable-word-count` is non-nil.

A continuous word count makes sense for composing text (for example with markdown-mode / org-mode), but I don't see a clear use case for it when editing something like YAML.

Proposed remedial steps:

1. Add a new flag `doom-modeline-enable-continuous-word-count` to enable / disable the continuous word count separately from the selection word count
2. Change the default for `doom-modeline-continuous-word-count-modes` to be an empty list
3. Change to logic to only detect specific modes listed, not derived modes
4. Add `doom-modeline-continuous-word-count-excluded-modes` to exclude specific modes
5. Some combination of 1-4

Any preferences here? Happy to implement any / all of the above.

**Steps and Expected**
- Open a large `text-mode` file with `doom-modeline-enable-word-count` enabled.

**Environment:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]
 - Package version [e.g. 201801228]

**Comment by seagle0128** [comment]
I remove `derived-mode-p` and change the default value of `doom-modeline-continuous-word-count-modes`.
