### ISSUE TITLE
Can't get doom-modeline-minor-modes to work

### ISSUE THREAD

**Issue by RexYuan** [seagle0128/doom-modeline#272]
**Describe**
After I set `doom-modeline-minor-modes` in customize system in emacs and save it for future sessions, I can a line of  `'(doom-modeline-minor-modes t)` in the `custom-set-variables` function in my `.emacs`. But when I re-open emacs, it changes back to nil again.

**Steps and Expected**
Toggle "Doom Modeline Minor Modes" to "On" and save it. Re-open emacs. It shows "Doom Modeline Minor Modes" as "Off".

**Environment:**
 - OS: macOS Catalina
 - Version: GNU Emacs 26.3
 - Package version:  20191013.1248

**Additional context**
I'm sorry if this doesn't make any sense. I'm very new to emacs.

**Comment by seagle0128** [comment]
It does work well for me definitely.
Please check your configurations, if there is `(setq doom-modeline-minor-modes nil)`.
