### ISSUE TITLE
void function battery-update

### ISSUE THREAD

**Issue by Emantor** [seagle0128/doom-modeline#274]
**Describe**
Doom Emacs emits a backtrace on start and does not load all modules

**Steps and Expected**
1. Update doom emacs via `git pull` and `bin/doom update)
2. start doom emacs
3. Observe backtrace in additional context
4. Expectation is to not have a backtrace and have doom emacs start normally

**Environment:**
 - OS: Arch Linux
 - Version rolling/latest
 - Package version: latest master via doom emacs and straight (211c0d0c28c27a9f700b5c10ba2e4b0e3f9bdcd9)

**Additional context**
```
Debugger entered--Lisp error: (void-function battery-update)
  battery-update()
  doom-modeline-override-battery-modeline()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
```

**Comment by duianto** [comment]
The same error is observed in Spacemacs (`develop` branch),
with the `dotspacemacs-mode-line-theme` variable set to: `doom`

**Comment by hlissner** [comment]
Adding `(fset 'battery-update #'ignore)` to your private config will suppress the error while we wait for a fix.

**Comment by duianto** [comment]
Confirmed, adding hlissners temporary fix to the `dotspacemacs/user-init` section of `.spacemacs`, removes the startup warning in Spacemacs.
