### ISSUE TITLE
[HOW-TO] need instructions on how to activate nyan-mode

### ISSUE THREAD

**Issue by verajosemanuel** [seagle0128/doom-modeline#275]
Installed Doom emacs using doom modeline. Installed nyan-mode but need some help activating

Regards

**Comment by seagle0128** [comment]
By default, just enable `nyan-mode`. That's all!

The root cause is the main mode-line is customized in `doom-emacs`. You should inquiry there, or customize yourself (No. 5 of https://github.com/seagle0128/doom-modeline#faq).
