### ISSUE TITLE
strange modeline height  after buffer content changed

### ISSUE THREAD

**Issue by hekinami** [seagle0128/doom-modeline#278]
**Describe**

while content of buffer changed, the modeline height was doubleld and that is strange.

I installed doom-modeline with package.el with newest package (20191209.1736) and the issue occurred.

If I downgraded to a old one (e.g. doom-modeline-20191029.1741.tar) it works in the correct way.

**Steps and Expected**

just open a file and change it. 

**Environment:**
 - OS: Linux Mint 
 - Version 19
 - Package version 20191209.1736

**Additional context**
 Screenshots, recordings, logs and/or messages...
![image](https://user-images.githubusercontent.com/10599084/70913638-62306500-2051-11ea-8ecc-192759558145.png)

![image](https://user-images.githubusercontent.com/10599084/70913661-6bb9cd00-2051-11ea-9b9b-60821b14fa8a.png)

**Comment by seagle0128** [comment]
Emacs version? What I can see  is the buffer state icon is incorrect in screenshot 2.

**Comment by hekinami** [comment]
26.3

**Comment by seagle0128** [comment]
What's the font are you using?

**Comment by hekinami** [comment]
According to information I have got now, I don't think it's an issue related directly to the configuration (e.g. font) of other part of emacs. Because just as  I mentioned in the first post, if I downgrade doom-modeline to older version, it works fine.  (refer to the screenshot)

![image](https://user-images.githubusercontent.com/10599084/71447421-3e63d200-2769-11ea-9200-77f4d205abc5.png)

![image](https://user-images.githubusercontent.com/10599084/71447423-44f24980-2769-11ea-846a-ed94de67cd78.png)

I don't know how to check the actual font is used by doom-modeline, any hint?

**Comment by seagle0128** [comment]
I couldn't reproduce this issue. Can you reproduce it with emacs -q ?

**Comment by hekinami** [comment]
I found it's conflicting with https://github.com/tumashu/cnfonts which is a font configuration tool for Chinese fonts.  cnfonts changed the default font setting and I think which is used by doom-modeline. 

My thinking is if the display in the mode line  is controlled by a face (I am not sure which one) then I can specify the font explicit for it (I am not sure which font should be either)

Any hint?

**Comment by seagle0128** [comment]
This issue was reported to cnfonts long time ago. Please refer to https://github.com/tumashu/cnfonts/issues/98. My suggestion is NOT using `cnfonts` with `all-the-icons`, or set the fallbacks yourself.

**Comment by hekinami** [comment]
for whom using cnfonts and doom-modeline(all-the-icons) together, we have a simple solution to make them coexist. Just configure your cnfonts in the following way.

(use-package cnfonts
  :ensure t
  :after all-the-icons
  :hook (cnfonts-set-font-finish
         . (lambda (fontsizes-list)
             (set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'append)))
  :config
  (cnfonts-enable))

**Comment by seagle0128** [comment]
Thanks for the update, @hekinami !

**Comment by hekinami** [comment]
Guys

if you want the best effect matching seagle0128's original design, the order of the fonts specified is important,  you'd better put 'FontAwesome' in the last line like

```elisp
(use-package cnfonts
  :ensure t
  :after all-the-icons
  :hook (cnfonts-set-font-finish
         . (lambda (fontsizes-list)
             (set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'append)
             ))
  :config
  (cnfonts-enable))
```

**Comment by hekinami** [comment]
by 2020/09/10, cnfonts and all-the-icons have seemingly already solved conflict with each  other, I can tested in emacs 27 with following configure, and it works well for me. We don't have to  specify the fonts for unicode characters ourselves any more.

```elisp
    (use-package cnfonts
      :ensure t
      :config
      (cnfonts-enable))

    (use-package all-the-icons
      :ensure t
      :after cnfonts
      )
```

**Comment by seagle0128** [comment]
Thanks, @hekinami . Although I don't see any changes for all-the-icons in cnfonts. Maybe just because you change the loading sequence?

**Comment by hekinami** [comment]
Not sure, but I used the same configuration for emacs 26.3 and 27.1, and likely they don't work in the same way. 

Anyway, if someone else still report the same issue, let's discuss then.
