### ISSUE TITLE
Support for nerd-fonts

### ISSUE THREAD

**Issue by To1ne** [seagle0128/doom-modeline#28]
First and for all, this is awesome. This modeline works perfect out-of-the-box.

But I think I'm struggling since I'm using Fura Code from [Nerd Fonts](https://nerdfonts.com/).
Nerd-fonts integrate all-the-icon fonts in 1 single font (at least I think they do). For me it might just be easier to use such a font, instead of several fonts.

Although I don't know if it's easy to do. Because it seems to me the NerdFonts are differently spread across the unicode private space and also the vertical align tends to be different.

**Comment by seagle0128** [comment]
`Nerd Fonts` looks great. But the there is no elisp lib to handle nerd fonts currently. If supporting nerd fonts in doom-modeline, I need to build a new lib to handle this. It may takes long time...

**Comment by To1ne** [comment]
Yeah, you're right. We better ask all-the-icons to support NerdFonts.

**Comment by seagle0128** [comment]
Yes, that's a great idea 😄

**Comment by seagle0128** [comment]
@To1ne FYI. I am working with @twlz0ne on https://github.com/twlz0ne/nerd-icons.el, and trying to integrate nerd icons into `doom-modeline` with the similar interfaces as `all-the-icons`, but encounter some issues. e.g. there is no `elisp`, `org` icons in `nerd-fonts`. The progress is slow.
