### ISSUE TITLE
切换pyim输入时，无法正常显示输入法名称

### ISSUE THREAD

**Issue by cxb811201** [seagle0128/doom-modeline#283]
**Describe**
使用 doom-emacs+pyim输入法 

**Steps and Expected**

**Environment:**
 - OS: archlinux
 - Emacs Version: 28.0.50

**Additional context**
![image](https://user-images.githubusercontent.com/2104470/71610382-5608e380-2bcb-11ea-9c7f-3a443fd44701.png)

**Comment by seagle0128** [comment]
这个看起来是字符编码问题。我没有使用 `Doom Emacs`，请修改你的 encoding 试试。我本地的 `Centaur Emacs`中是正常的。

**Comment by cxb811201** [comment]
字符编码全部都UTF-8，还是有该问题

同时，我也参考你的encoding配置进行了重新设置，结果还是同样的问题

**Comment by seagle0128** [comment]
请用emacs -Q 重现，doom的设置问题请求助社区
