### ISSUE TITLE
wrong-type-argument stringp evil-visual-tag

### ISSUE THREAD

**Issue by zsxh** [seagle0128/doom-modeline#284]
**Describe**
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp evil-visual-tag)

**Steps and Expected**
M-x evil-visual-state, error happens.

**Environment:**
 - OS: [manjaro]
 - Version [18.1.5]
 - Package version [20191231]

**Additional context**
 Screenshots, recordings, logs and/or messages...

**Comment by seagle0128** [comment]
It seems related to https://github.com/emacs-evil/evil/issues/1180 and https://github.com/emacs-evil/evil/commit/40bda9ed89c8a28109601e63962431ff69370828.
