### ISSUE TITLE
The flycheck numbers are pushed to the right and getting cut when enabling minions-mode

### ISSUE THREAD

**Issue by hisnawi** [seagle0128/doom-modeline#287]
**Describe**
I have minions-mode enabled
When enabling:
          doom-modeline-minor-modes            t
          doom-modeline-checker-simple-format  nil
The flycheck numbers are pushed to the right and getting cut.

**Steps and Expected**
I believe doing the above should suffice

**Environment:**
 - OS: MACOS
 - Version Mojave
 - Package version 20200106.622

**Comment by hisnawi** [comment]
Is there a reason this was moved to closed without even a comment?

**Comment by seagle0128** [comment]
The patch 07837775ebac572df61b00485d92723ff120c67d has been submitted.

**Comment by hisnawi** [comment]
My bad. I am using an iPhone app that only showed the issue was closed without other info. Looking at the web version I see the patch. Thank you for the quick response.

**Comment by hisnawi** [comment]
Still having some trouble:

![image](https://user-images.githubusercontent.com/8878871/74791995-f2b53c80-5270-11ea-913a-1b922f18ded3.png)

**Comment by seagle0128** [comment]
@hisnawi What font are you using?

**Comment by hisnawi** [comment]
PragmataPro

**Comment by seagle0128** [comment]
Can you try other fonts, please?

**Comment by seagle0128** [comment]
Please test new version.

**Comment by hisnawi** [comment]
not sure why you removed the update you had:
```
(doom-modeline-def-modeline 'main
  '(bar workspace-name window-number modals matches buffer-info remote-host buffer-position word-count parrot selection-info)
  '(objed-state misc-info persp-name battery grip irc mu4e gnus github debug lsp minor-modes input-method indent-info buffer-encoding major-mode process vcs checker " "))
```
This actually fixed it!

**Comment by seagle0128** [comment]
I've added an extra space at the end to avoid the cut-off issue in the latest commit.

**Comment by hisnawi** [comment]
Great.Thanks!
