### ISSUE TITLE
set-face-background doesn't work for mode-line face in emacs27 daemon mode

### ISSUE THREAD

**Issue by kangjianbin** [seagle0128/doom-modeline#289]
**Describe**
`(set-face-background 'mode-line "#00FF00")` doesn't work in daemon mode in emacs27.
This function works in emacs26 daemon mode.

**Steps and Expected**
1. Start emacs in daemon mode:   `emacs --daemon`
2. start emacsclient:  `emacsclient -t -c`
3. Evaluate `(set-face-background 'mode-line "#00FF00")`, mode-line's background doesn't change

**Environment:**
 - OS: Linux  Debian testing
 - Version: Debian testing
 - Package version:  doom-modeline commit id: a7a0370c50d5c5942e02e9aedb18a645b38322d1

**Additional context**

**Comment by seagle0128** [comment]
I couldn't reproduce with Emacs 28. Did you reproduce with `emacs -Q`?

**Comment by seagle0128** [comment]
Close due to no activities.
