### ISSUE TITLE
Show narrow/widen symbol on read-only buffers

### ISSUE THREAD

**Issue by hisnawi** [seagle0128/doom-modeline#290]
When (narrow-or-widen) on a read only buffer, the narrow/widen symbol doesn't show up in the modeline since the lock symbol (read only) comes on top.
Would be nice if the narrow/widen symbol comes (next) to the lock symbol when activated.

**Comment by seagle0128** [comment]
Patch was committed, but I am not sure is the performance is impacted. Please test.

**Comment by hisnawi** [comment]
Works perfectly. Thanks
