### ISSUE TITLE
helm-rg candidate count

### ISSUE THREAD

**Issue by manuel-uberti** [seagle0128/doom-modeline#292]
**Describe**
Even though I'm not using `doom-modeline`, I am using its code to patch my mode-line for Helm. (So thanks a lot for this project!). I hope this can be helpful, then.

As I reported [here](https://github.com/cosmicexplorer/helm-rg/issues/22), there is a problem in the code:

```emacs-lisp
(format " %d/%d"
        (helm-candidate-number-at-point)
        (helm-get-candidate-number t))
```

`(helm-get-candidate-number t)` is always less than `(helm-candidate-number-at-point)` in a helm-rg buffer.

**Steps**
- install `helm-rg`
- set this options for `helm-rg`:
```emacs-lisp
(setq helm-rg-include-file-on-every-match-line t
      helm-rg-prepend-file-name-line-at-top-of-matches nil)
```
- visit `helm-rg.el`
- <kbd>M-x helm-rg RET helm-rg RET</kbd>

**Environment:**
 - OS: Ubuntu 18.04.3
- Latest `helm-rg` from MELPA

**Additional context**
This is a screenshot to display the problem:
![Screenshot from 2020-01-31 09-07-41](https://user-images.githubusercontent.com/8199224/73522696-6221d400-4409-11ea-9890-4c86edba8131.png)

**Comment by seagle0128** [comment]
Have to wait for the feedback from `helm-rg`.

**Comment by manuel-uberti** [comment]
FWIW, I found this: https://github.com/emacs-helm/helm/issues/787#issuecomment-68468083

It's a bit old, but probably still relevant.

**Comment by seagle0128** [comment]
I don't think this issue is able to be addressed in `doom-modeline`.

**Comment by manuel-uberti** [comment]
I think so too. Let me close here then. :)
