### ISSUE TITLE
How do I change the face of git branch in doom-modeline

### ISSUE THREAD

**Issue by CSRaghunandan** [seagle0128/doom-modeline#294]
As the title suggests, I want to be able to change the face of the git branch shown in the `doom-modeline` along with the all-the-icons icon for it.

I don't see a face separately for the vcs segment of the mode-line. Maybe its inheriting some other face? But I'm unable to figure out which.

**Comment by seagle0128** [comment]
The current faces for git branch name is `doom-modeline-info`, `doom-modeline-warning` and `doom-modeline-urgent`.

Do you want to change the faces for both icon and text, or just text (branch name)?

**Comment by CSRaghunandan** [comment]
> The current faces for git branch name is `doom-modeline-info`, `doom-modeline-warning` and `doom-modeline-urgent`.
> 
> Do you want to change the faces for both icon and text, or just the face for the text (branch name)?

Both the icon and the text. Also, is it possible to add a space after the icon? IMO It'll look slightly better with a space in between the icon and the text

**Comment by seagle0128** [comment]
There is one half-width space between icon and text.
