### ISSUE TITLE
Add Icons that decorate the modeline in EAF mode

### ISSUE THREAD

**Issue by MatthewZMD** [seagle0128/doom-modeline#296]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Icons for EAF/browser, EAF/pdf-viewer, etc.

没研究过doom-modeline的代码，先放个issue。

**Comment by seagle0128** [comment]
Do you mean the icons for the EAF buffers? If so, it's should be a quest for `all-the-icons`.

**Comment by MatthewZMD** [comment]
我的意思不是创建新的icon，而是从已有的icon池里面选几个作为EAF的icon

**Comment by seagle0128** [comment]
那也是 `all-the-icons`的功能，或者用户自己创建。

**Comment by MatthewZMD** [comment]
原来是这样，我还以为是doom-modeline这边控制的。打扰了

**Comment by seagle0128** [comment]
`doom-modeline`只会显示buffer  icons，除了特定的 segment，并不会创建图标和规则。
