### ISSUE TITLE
all-the-icons not displaying correct icon

### ISSUE THREAD

**Issue by hisnawi** [seagle0128/doom-modeline#298]
I noticed that some files don't show the correct icon with al-the-icons in doom-modeline.
Although they show correctly in all-the-icons-ivy and all-the-icons-dired.

Is that a known issue?
I can provide screenshots.

**Comment by seagle0128** [comment]
Please provide more details.

**Comment by hisnawi** [comment]
This is for example a fish shell script not showing it's icon in modeline:
![image](https://user-images.githubusercontent.com/8878871/74023753-3ba5f080-4955-11ea-97e9-05d40550345f.png)

But shows up in dired:
![image](https://user-images.githubusercontent.com/8878871/74023818-65f7ae00-4955-11ea-81c1-511f65c98a62.png)

And in counsel-jump-file:
![image](https://user-images.githubusercontent.com/8878871/74023870-832c7c80-4955-11ea-9ffa-6d951fb09314.png)

**Comment by seagle0128** [comment]
In my env, it's displayed correctly. Please update to the latest and retry.

![image](https://user-images.githubusercontent.com/140797/74026590-7c4b4b80-49e1-11ea-9b73-e78e47a8637d.png)

**Comment by hisnawi** [comment]
I am already on latest. Could you share how you installed relevant fonts and your configuration?

**Comment by seagle0128** [comment]
See  [Centaur Emacs](https://github.com/seagle0128/.emacs.d).
