### ISSUE TITLE
Panel height taller than rest of the bar

### ISSUE THREAD

**Issue by WolfeCub** [seagle0128/doom-modeline#30]
I'm having an issue where the panel height is much taller then the height of the mode line itself. Any ideas what could be causing this?

[Here](https://u.teknik.io/ZlhcL.png) is an example of what I mean.

Thanks!

**Comment by WolfeCub** [comment]
Yeah I installed `all-the-icons` through emacs. Here's the embedded image: 

![example](https://user-images.githubusercontent.com/1369773/46164018-d919ec00-c25a-11e8-89a4-530d1c831010.png)

Thanks!

**Comment by seagle0128** [comment]
Thanks for providing the embedded image to troubleshooting!

Would you please let me know more details?
1. OS
1. Emacs version
1. `doom-modeline` version
1. Color theme
1. Any error messages?

I suggest to upgrade `doom-modeline` to the latest version, set `doom-modeline-height` and observe the changes.
e.g. `(setq doom-modeline-height 26)`.

**Comment by WolfeCub** [comment]
1. Arch Linux - `4.18.9-arch1-1-ARCH `
2. 27.0.50
3. `20180926.920`
4. [Custom theme](https://github.com/WolfeCub/dotfiles/blob/master/emacs/.emacs.d/themes/my-theme.el)
5. `Fira Mono` and `Fira Code` for the fallback.
6. No error messages.
7. No sorry :(

I have the latest version from MELPA and i've tried doom-modeline-height but regardless of what I set it too it's always slightly bigger.

I'll try out some different fonts.

**Comment by seagle0128** [comment]
Thanks for the quick response!
It's very wired. Please change the font size or change to other fonts.
I suspect the font is too large and exceed the mode-line height. To prove it, you can increase doom-modeline-height to 29 or larger, or decrease font size to 12 or smaller.

**Comment by seagle0128** [comment]
Or try this:

`M-x eval-defun`
```elisp
(doom-modeline-def-modeline 'main
                            '(workspace-number window-number evil-state matches " " buffer-info buffer-position " " selection-info)
                            '(global buffer-encoding major-mode process vcs flycheck))
```

**Comment by WolfeCub** [comment]
I tried that elisp snippet and the same issue occurs. I also tried Fira 12 and mode-line height of 29 and the issue also occurred. Do you have a font I could try that you know works for sure?

**Comment by seagle0128** [comment]
Would you please try Source Code Pro 12 cor DejaVu Sans Mono 12.
Actually I tried to recreate this issue with Fira 15 locally. I believe it's a font size issue. If you decrease the font size, it looks better. IMO it's not an issue, since the panel height is same as the font height. If you use this snippet, you could notice the bar is removed. The fact is the bar height (`doom-modeline-height`) is smaller than the font height, as well as the panel height in this case.

```elisp
(doom-modeline-def-modeline 'main
                            '(workspace-number window-number evil-state matches " " buffer-info buffer-position " " selection-info)
                            '(global buffer-encoding major-mode process vcs flycheck)
```

**Comment by WolfeCub** [comment]
This is the result if I swap the font to `DejaVu Sans Mono 12`.

![temp](https://user-images.githubusercontent.com/1369773/46222131-658ce300-c31d-11e8-8ee5-522b17835ff0.png)

**Comment by seagle0128** [comment]
@WolfeCub can you try DejaVu Sans Mono 10 or 9?

**Comment by WolfeCub** [comment]
![temp](https://user-images.githubusercontent.com/1369773/46233792-173e0b00-c342-11e8-80b4-38e1ce34a0ed.png)

**Comment by seagle0128** [comment]
OK. I see. You didn't enable `winum-mode` or `window-numbering-mode`.
Can you eval this snippet to get the height of `mode-line`?
```elisp
(- (elt (window-pixel-edges) 3) 
   (elt (window-inside-pixel-edges) 3))
```

**Comment by seagle0128** [comment]
I think I found a workaround to adjust the bars height and make the mode-line look better.

**Comment by WolfeCub** [comment]
Great! Thanks for your help.

**Comment by WolfeCub** [comment]
One other thing I noticed was the box get's taller when there's 0/0 results then when it's matching something. 

![temp](https://user-images.githubusercontent.com/1369773/46247748-edd2bd00-c3dd-11e8-85e9-a9191479776e.png)
![temp](https://user-images.githubusercontent.com/1369773/46247750-f6c38e80-c3dd-11e8-94f8-0607550b4d88.png)

**Comment by seagle0128** [comment]
Hi, 
I cannot reproduce with the latest version. Please update and retry.

![image](https://user-images.githubusercontent.com/140797/46253277-c812ea00-c4a9-11e8-804b-32e8ac6b83a9.png)

![image](https://user-images.githubusercontent.com/140797/46253281-d7923300-c4a9-11e8-870b-bda639fc63a1.png)

**Comment by WolfeCub** [comment]
That was with the latest version. Setting a height of 39 works perfectly actually. Would there be a good way to determine this number problematically so it adjusts when I change font?

**Comment by seagle0128** [comment]
I made a several commits and please update again. I'm not sure if it's perfect but deserves to try.
