### ISSUE TITLE
Variable width faces support

### ISSUE THREAD

**Issue by Vincent-P** [seagle0128/doom-modeline#301]
**Is your feature request related to a problem? Please describe.**
I really enjoy having variable-width fonts for every UI fonts, but I can't do this with doom-modeline.
If for example I set `doom-modeline-buffer-path` or `doom-modeline-buffer-file` face family to "Noto Sans" with this: `(set-face-attribute 'doom-modeline-buffer-path nil :family "Noto Sans")`, the buffer in inactives modelines will still be displayed using a fixed-width font.

**Describe the solution you'd like**
Is it possible to have inactive variant for each face? Maybe there is an even better solution?

**Describe alternatives you've considered**
Well there isn't any alternative so I am stuck with fixed-width font for now...

**Additional context**
![image](https://user-images.githubusercontent.com/10779205/74199609-ec1d3880-4c64-11ea-97c7-edcecb2bf8d7.png)

**Comment by seagle0128** [comment]
You may need to change the faces of `mode-line` and `mode-line-inactive`, but the icons may be not displayed corrected.

**Comment by Vincent-P** [comment]
Yes it breaks the icon font that's why I didnt mention it.

**Comment by Vincent-P** [comment]
I am going to try thanks!

**Comment by seagle0128** [comment]
I committed a patch to support different fonts in mode line. Just need to set `mode-line` and `mode-line-inactive` face. All icons should be Okay now. The  right position of the segment may not be accurate but I think it's a minor issue.

**Comment by Vincent-P** [comment]
Now I have this issue: https://github.com/seagle0128/doom-modeline/issues/300

**Comment by seagle0128** [comment]
Are you using doom?

**Comment by Vincent-P** [comment]
No.
I added this to my config:
```
  (set-face-attribute 'mode-line nil :family "Noto Sans")
  (set-face-attribute 'mode-line-inactive nil :family "Noto Sans")
```
The mode indicator in the inactive mode-line is a weird character instead of an icon, it also happens with other fonts.

**Comment by seagle0128** [comment]
A new face `doom-modeline-icon-inactive` is introduced. Hope all icons can be displayed correctly now.

**Comment by Vincent-P** [comment]
It's perfect now thanks a lot! :)

**Comment by seagle0128** [comment]
@Vincent-P Great! Can you please help to test with the default font as well?
