### ISSUE TITLE
Latest update completely broke doom-modeline

### ISSUE THREAD

**Issue by CSRaghunandan** [seagle0128/doom-modeline#303]
doom-modeline was working perfectly fine before, but the latest commit seems to have broken the right side of the modeline content. Its misaligned. Attached is a screenshot for reference

![screenshot-2020-02-12_11-53-38](https://user-images.githubusercontent.com/5226809/74308638-bb392280-4d8e-11ea-9e62-4af9d11ffd32.png)

**Comment by seagle0128** [comment]
Could you please provide more details? I coulnd't reproduce it.

PS: try the latest version as well.

**Comment by CSRaghunandan** [comment]
I updated to the latest commit and it looks like the problem persists when i'm running emacs via `emacsclient`, but if I'm running emacs normally, I don't have this issue. It used to work perfectly file before the major version bump.

This is my [doom-modeline config](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-mode-line.

**Comment by ralsei** [comment]
Seconded: ![](https://qtp2t.club/pub/doom-modeline.png)

**Comment by seagle0128** [comment]
Okay. I can reproduce it with `emcasclient`.

**Comment by seagle0128** [comment]
Please test the new version.

**Comment by CSRaghunandan** [comment]
Its working now, thanks

**Comment by Dr-Dd** [comment]
There might have been a regression on this, with emacsclient the bar looks like this

![alt](https://i.imgur.com/W8V2x9K.png)

Here's my related config:
https://github.com/Dr-Dd/.emacs.d/blob/master/lisp/init-doom-modeline.el
