### ISSUE TITLE
Checker warning icon conflicts with pretty-font

### ISSUE THREAD

**Issue by MeltWS** [seagle0128/doom-modeline#304]
Checker error/warning icon doesn't display due to conflict with pretty-font.el.

Have firacode, doom-modeline, flycheck, [pretty-font.el](https://github.com/ekaschalk/.spacemacs.d/blob/master/layers/display/local/pretty-fonts/pretty-fonts.el) for ligatures
Start without ligatures, warning checker displays as expected.
<details> <summary> Load ligatures </summary> 

```elisp
(use-package pretty-fonts		; lisp folder
  :load-path "~/.emacs.d/lisp/"
  :config
  (declare-function pretty-fonts-add-hook "pretty-fonts")
  (declare-function pretty-fonts-set-fontsets-for-fira-code "pretty-fonts")
  (pretty-fonts-add-hook 'prog-mode-hook pretty-fonts-fira-code-alist)
  (pretty-fonts-add-hook 'org-mode-hook  pretty-fonts-fira-code-alist)
  (pretty-fonts-set-fontsets-for-fira-code))
```
</details>
<details> <summary> icon breaks and defaults to text </summary>

![image](https://user-images.githubusercontent.com/15630634/74384715-35e75980-4df2-11ea-9a8f-ccb56616118d.png)

</details>

Expected : Icon shows

 - Windows 10
 - Package version 20200212.1455

is related to #69 and doom-emacs uses a [work arround](https://github.com/hlissner/doom-emacs/commit/909c27796843a4b3e236354f96d0dd98266e5b97) for an icon already

A way to fix is to change the used icon `"block"` to `"do_not_disturb_alt"` 

```elisp
(defun doom-modeline-checker-icon (icon unicode text face)
  "Displays the checker ICON with FACE.

UNICODE and TEXT are fallbacks.
Uses `all-the-icons-material' to fetch the icon."
  (if (string-equal icon "block") (setq icon "do_not_disturb_alt"))
  (doom-modeline-icon 'material icon unicode text
                      :face face :height 1.1 :v-adjust -0.225))

```

As far as I can tell `block` and `do_not_disrupt_alt` icons are the same.

**Comment by seagle0128** [comment]
It's not an issue of `doom-modeline`. The root cause is `pretty-font` conflicts with `all-the-icons`. `block` icon is overrided by `pretty-fonts in this case.

I can change `block` to `do_not_disturb_alt`, but I cannot ensure other icons will be displayed correctly. The ultimate solution is not using `prettry-font` or resolve the confilicts as `doom-emacs` did.
