### ISSUE TITLE
modeline icon color is inconsistent when using which-key

### ISSUE THREAD

**Issue by RicardoMing** [seagle0128/doom-modeline#306]
**Describe**
When using which-key, the doom-modeline becomes inactive, but the icon's background color is still
the active one, making it inconsistent with the whole modeline.

**Steps and Expected**
1. Using fresh Doom Emacs
2. Press any key (`SPC`) to trigger which-key
3. See error
![image](https://user-images.githubusercontent.com/11895323/74590200-50664080-5047-11ea-911b-a756ebd36c3c.png)

The normal active and inactive modeline should be: 
![image](https://user-images.githubusercontent.com/11895323/74590224-860b2980-5047-11ea-881f-947e5367120e.png)
![image](https://user-images.githubusercontent.com/11895323/74590219-7c81c180-5047-11ea-8004-363c42218237.png)

**Environment:**
 - OS: Ubuntu
 - Version 18.04
 - Package version b0978a452 2020-02-14

**Comment by seagle0128** [comment]
Please test.

**Comment by seagle0128** [comment]
I realized it may be related to the color themes. Does this issue occurs with specific theme, or all themes? If only in this theme, you need to set the face `doom-modeline-icon-inactive` yourself, or raise a request.

**Comment by RicardoMing** [comment]
I have tested with some other doom themes, they all have this problem.
- doom-one
![doom-one](https://user-images.githubusercontent.com/11895323/74597418-2c801a80-509a-11ea-86f9-c6c87cace5f2.png)
- doom-one-light
![image](https://user-images.githubusercontent.com/11895323/74597458-c21baa00-509a-11ea-9db8-110d198c7090.png)
- doom-gruvbox
![image](https://user-images.githubusercontent.com/11895323/74597473-06a74580-509b-11ea-8776-4673b24c5054.png)
- doom-solarized-light
![image](https://user-images.githubusercontent.com/11895323/74597503-6e5d9080-509b-11ea-97ef-78e132142177.png)

By adding ```(custom-set-faces `(doom-modeline-icon-inactive ((t (:inherit mode-line-inactive)))))``` to Doom's config.el, this problem was fixed.

However, there still is an inconsistent region at the right edge of modeline when flycheck inactive.
![image](https://user-images.githubusercontent.com/11895323/74597646-9ea62e80-509d-11ea-9a7a-1ec125188067.png)

**Comment by seagle0128** [comment]
I couldn't reproduce the issue yet. 
It seems you are using `doom`. Could you please reproduce with `emacs -Q` and provide the details?

**Comment by RicardoMing** [comment]
Minimal reproduce init file:
```elisp
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/dash/")
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/all-the-icons/")
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/memoize/")
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/shrink-path/")
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/s/")
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/f/")
(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/which-key/")
(require 'which-key)
(which-key-mode)

(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/flycheck/")
(require 'flycheck)
(global-flycheck-mode)

(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/doom-modeline/")
(require 'doom-modeline)
(doom-modeline-mode 1)

(add-to-list 'load-path "~/GitHub/emacs.d/doom/.local/straight/build/doom-themes/")
(add-to-list 'custom-theme-load-path "~/GitHub/emacs.d/doom/.local/straight/build/doom-themes/")
(load-theme 'doom-dark+ t)
```
![image](https://user-images.githubusercontent.com/11895323/74605551-22930180-5104-11ea-8a22-2f9a296b65fb.png)

When flycheck inactive:
![image](https://user-images.githubusercontent.com/11895323/74605603-8caba680-5104-11ea-8b6a-9c802b736f2e.png)

The problem still exists when using other doom themes.

**Comment by seagle0128** [comment]
Please test the new version.

**Comment by RicardoMing** [comment]
Thank you very much. I have tested with patch 0ce7ddfa0d in vanilla emacs and doom. The problem was solved perfectly.

**Comment by davidhaley** [comment]
This also fixed a modeline color bug that I have in the latest version.

```
(custom-set-faces
    '(doom-modeline-icon-inactive ((t (:inherit mode-line-inactive)))))
```

```
generated  Sep 18, 2023 08:35:34
system     "EndeavourOS Linux" Linux 6.5.3-arch1-1 x86_64
emacs      29.1 ~/.config/emacs/
doom       3.0.0-pre PROFILE=_@0 HEAD -> master 2be3cf4b 2023-09-17 05:07:52 +0200 ~/.config/doom/
shell      /bin/bash
features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS
	  TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB
traits     batch server-running envvar-file custom-file
modules    :config use-package :completion (company +childframe) vertico :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +defaults) treemacs (vc-gutter +pretty) vi-tilde-fringe
	  window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors snippets :emacs dired electric (undo +tree) vc :checkers syntax :tools (debugger +lsp) direnv docker
	  (eval +overlay) lookup lsp magit pdf :lang emacs-lisp json (javascript +lsp) lua markdown (ocaml +lsp) (org +pretty +roam2 +pandoc +jupyter) (python +lsp +pyright +poetry) sh (web +html +css +lsp) yaml
	  :app (emms +restore) :config (default +bindings +smartparens)
packages   (deno-fmt) (jupyter) (svelte-mode) (focus) (transpose-frame) (copilot :recipe (:host github :repo zerolfx/copilot.el :files (*.el dist))) (org-fragtog) (rjsx-mode :disable t) (magit-delta :recipe
	  (:host github :repo dandavison/magit-delta)) (lsp-ui) (eldoc-box) (blamer :recipe (:host github :repo artawower/blamer.el)) (blacken) (rg) (keyfreq) (evil-textobj-line)
 ```
