### ISSUE TITLE
Error during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (void-function copy-list)

### ISSUE THREAD

**Issue by kurnevsky** [seagle0128/doom-modeline#307]
After last commit I get `Error during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (void-function copy-list)` after focus-out/focus-in emacs frame.

 - OS: Arch Linux
 - GNU Emacs 26.3
 - Package version 20200216.1503

It seems doom-modeline should explicitly require `cl` for that function.

**Comment by kurnevsky** [comment]
And after I load `cl` I get
```
Invalid face attribute :inherit nil
Invalid face reference: nil
```

**Comment by seagle0128** [comment]
It seems you are not using the latest version. Please update.

**Comment by kurnevsky** [comment]
I am, I reported it long before you fixed it :)

**Comment by seagle0128** [comment]
My bad. I forgot to push the changes.
