### ISSUE TITLE
Invalid face warnings in *Messsages* buffer when enabling doom-modeline

### ISSUE THREAD

**Issue by thermopyle** [seagle0128/doom-modeline#308]
**Describe**
When I enable doom-modeline I get a lot of warnings in the *Messages* buffer;
```
Invalid face reference: nil
Invalid face attribute :inherit nil
```
If I disable doom-modeline the warnings disappear.

**Steps and Expected**
Enable doom-modeline, restart Emacs and check the *Messages* buffer.

**Environment:**
 - OS: MacOS
 - Version 10.14.6 Mojave
 - Package version 20200217.1123

**Comment by achempion** [comment]
I have the same issue.

Emacs: 26.2 (9.0)
OS: Catalina 10.15.2
Package: 20200217.1123

similar issue https://github.com/seagle0128/doom-modeline/issues/168

`all-the-icons-install-fonts` command executed but nothing changed

**Comment by seagle0128** [comment]
It seems a compatibility issue. No such issue on 27+. I am working on it.
