### ISSUE TITLE
Modeline icons resolve to strange characters 

### ISSUE THREAD

**Issue by jwhittle933** [seagle0128/doom-modeline#310]
**Describe**
Mode line resolves major mode icons (Go in my case) to I suppose Chinese characters, as well as others. I have powerline and nerd fonts installed. Switch around between them the result is the same. 

**Steps and Expected**
I sincerely have no idea how one would reproduce this. 
Config: 
```lisp
dotspacemacs-mode-line-theme '(doom)
...
(setq doom-modeline-icon (display-graphic-p))
  (setq doom-modeline-major-mode-icon t)
  (setq doom-modeline-major-mode-color-icon t)
  (setq doom-modeline-unicode-fallback nil)
  (set-face-attribute 'mode-line nil :family "SauceCodePro NF" :height 100)
```

**Environment:**
I'm on a 2020 16" MacBook Pro, Emacs installed from binary, running Spacemacs.

**Additional context**
<img width="298" alt="Screen Shot 2020-02-18 at 1 42 53 PM" src="https://user-images.githubusercontent.com/41909513/74767284-92b09d00-5254-11ea-85ee-d619df6bb585.png">
<img width="461" alt="Screen Shot 2020-02-18 at 1 43 51 PM" src="https://user-images.githubusercontent.com/41909513/74767352-b7a51000-5254-11ea-8c36-a645dcf163bf.png">

**Comment by seagle0128** [comment]
Did you installed all-the-icons fonts as the description of README?

**Comment by seagle0128** [comment]
[all-the-icons](https://github.com/domtronn/all-the-icons.el) are necessary. Run `M-x all-the-icons-install-fonts` to install the resource fonts. On Windows, the fonts should be installed manually. `all-the-icons` only support GUI. Please refer to [all-the-icons.el](https://github.com/domtronn/all-the-icons.el) for details.

 If the icons are not displayed correctly although `all-the-icons` fonts are installed correctly, please install the [non-free](http://users.teilar.gr/~g1951d/License.pdf) font [Symbola](http://users.teilar.gr/~g1951d/Symbola.zip). This issue usually occurs on Windows. 

Please reopen if you still have trouble.

**Comment by bk138** [comment]
I have the issue as well, though with a different config on `GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-05-14, modified by Debian`. 

I have:

* deleted `.emacs.d`
* deleted `~/.local/share/fonts`
* run `M-x all-the-icons-install-fonts`.

Here's a minimal self-bootstrapping config to repro:

```
;;
;; bootstrap use-package as per http://cachestocaches.com/2015/8/getting-started-use-package/
;;
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(if (string-equal system-type "gnu/linux")
    (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")) ; make default https elpa usable again
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; configure use-package
(eval-when-compile
  (require 'use-package)
  (require 'use-package-ensure)
  (setq use-package-always-ensure t))

(use-package all-the-icons)

(use-package doom-modeline
  :config
  (doom-modeline-mode)
  )
```

With which the modeline then looks like this:
![image](https://github.com/seagle0128/doom-modeline/assets/80450/ee66292c-6ce9-4812-988d-f53ee81fe46e)


Would you be so kind and reopen @seagle0128 ? Is there anything I can do to rule out an issue on the distribution's side?

**Comment by seagle0128** [comment]
@bk138 Currently `nerd-icons` is leveraged in `doom-modeline`. You should install nerd-fonts via `M-x nerd-icons-install-fonts`.

**Comment by bk138** [comment]
> @bk138 Currently `nerd-icons` is used in `doom-modeline`, while `all-the-icons` has been dropped. You should install nerd-fonts via `M-x nerd-icons-install-fonts`. Please read REAME.

Yeah that's it. Thank you!

**Comment by pratik-abhyankar** [comment]
> @bk138 Currently `nerd-icons` is used in `doom-modeline`, while `all-the-icons` has been dropped. You should install nerd-fonts via `M-x nerd-icons-install-fonts`. Please read REAME.

This was it. I was using `all-the-icons` too in my config. Installing `nerd-fonts` resolved the issue.

**Comment by dfireBird** [comment]
I have this issue in Windows. Even after installing nerd-fonts manually using font viewer. 

I used `nerd-icon-insert` and can see that some of icons don't have proper fonts and resolve to boxes instead.

**Comment by seagle0128** [comment]
@dfireBird `M-x nerd-icons-install-fonts`.

**Comment by AnweshGangula** [comment]
> @bk138 Currently `nerd-icons` is used in `doom-modeline`, while `all-the-icons` has been dropped. You should install nerd-fonts via `M-x nerd-icons-install-fonts`. Please read REAME.

This was it, finally. Thank you

**Comment by plutonium-239** [comment]
Hi, I was facing the same issue, installing Symbols Nerd Font did fix it for when emacs opens in a separate window, however when I run it in the terminal itself (`-nw`), it does not. I was already using a nerd font that works well in all other programs that use these icons. Why is emacs not able to display them?

Also, I don't even get an "unknown font character" symbol, I get the whole unicode code point printed (screenshot). I have already turned on `:ui unicode` in the `init.el` file (and synced).

![Image](https://github.com/user-attachments/assets/c4f5af9e-02a2-4e37-a6ba-7415b067996a)
