### ISSUE TITLE
Howto request: Add segment to modeline

### ISSUE THREAD

**Issue by tecosaur** [seagle0128/doom-modeline#311]
Hello,

Sorry to be a bother but I am hoping you may be willing to help me work out how to add a particular segment to the modeline.
I'd quite like to add the currently playing track (found from a dbus query) to a segment around the middle ***but*** only if the window is wider than a particular value.

Would you have any suggestions about how I may do this?

tecosaur

**Comment by seagle0128** [comment]
Never mind! Glad you get touch with me to enhance the `doom-modeline`.

Basically there are two methods to extend `doom-modeline.

1. Use `doom-modeline-def-segment` to define a new segment. The use `doom-modeline-def-modeline` to define a new modeline or add to the existing one.
e.g.
```elisp
(doom-modeline-def-segment process
  "The process info."
  (if (doom-modeline--active)
      mode-line-process
    (propertize (format-mode-line mode-line-process)
                'face 'mode-line-inactive)))
```

1. If the information is simple, just add to `mode-line-misc-info` or `global-mode-string`.  You can get the help from the info manual. Please see [here](https://github.com/seagle0128/doom-modeline#faq) item 5.

The PR is always welcome!
