### ISSUE TITLE
Frame-spanning modeline option

### ISSUE THREAD

**Issue by tecosaur** [seagle0128/doom-modeline#312]
I find the modeline really useful. It provides what I consider to be important information about the file I'm dealing with at a glance.

Sometimes I find myself splitting a buffer into 2, 3 horizontal panes. Unfortunately at this point, the modeline shrinks to a size where the information I want to see is being cut off.

If it's possible to add a way to make the modeline stretch across the whole frame and adjust the content based on the current buffer that would very nicely solve this minor issue of mine :smiley: 

To me, the _ideal_ solution would be that this mode could be automatically toggled on window-changes when `frame-width / panes < threshold` :)

Other than that, I'm loving the modeline. Keep up the great work!

#### Nice modeline
![image](https://user-images.githubusercontent.com/20903656/74815563-6d935b80-5334-11ea-9cc0-0d74b19de983.png)
#### Cramped modeline :disappointed: 
![image](https://user-images.githubusercontent.com/20903656/74815612-84d24900-5334-11ea-87bd-b18cc650431b.png)
#### Ideal modeline :smiley: 
![image](https://user-images.githubusercontent.com/20903656/74815757-c662f400-5334-11ea-944d-aa360af55ca8.png)

**Comment by seagle0128** [comment]
I am afraid it's impossible unless Emacs changes the mode-line mechanism. There is no perfect solution for it.

Some discussions are below.
https://emacs.stackexchange.com/questions/45004/id-like-a-global-mode-line-in-my-frame
https://emacs.stackexchange.com/questions/9537/single-mode-line-for-all-windows

**Comment by tecosaur** [comment]
Given that the seems to be a "would be nice, but emacs doesn't let us ATM" perhaps we should move on by requesting this of the Emacs folks ¯\\_(ツ)_/¯

**Comment by seagle0128** [comment]
You are right. You can raise the request there.

**Comment by seagle0128** [comment]
@tecosaur I committed a patch (https://github.com/seagle0128/doom-modeline/commit/a25dc7267eccb3138793fe71b598d337d2447ae0) to address the issue of long file name. 

>  [Feature] Simplify buffer name and others when the window is small.
> 1. Introduce an option: doom-modeline-window-width-limit.
> 2. Check if the window is small (window-width <=
>  doom-modeline-window-width-limit) while window size is changed.
>  3. Only display buffer name when the window is snall.
> 4. Don't display pers-name when the window is small.

**Comment by tecosaur** [comment]
That's a very welcome addition, thanks!

**Comment by seagle0128** [comment]
@tecosaur Another solution is https://github.com/kiennq/emacs-mini-modeline. See https://github.com/seagle0128/doom-modeline/issues/315.

**Comment by evertedsphere** [comment]
Is there a way to integrate doom-modeline and mini-modeline? Perhaps by somehow feeding a doom-modeline-generated format into `mini-modeline-format`?

**Comment by seagle0128** [comment]
@evertedsphere  No. `mini-modeline` leverages minibuffer, so that the icons are not displayed correctly due to the height issue. It should be fine if not displaying the icons.

**Comment by evertedsphere** [comment]
Right, if i did that, what would be the way to get doom-modeline to output
raw left and right format strings?

**Comment by seagle0128** [comment]
@evertedsphere Maybe you can try these

```elisp
(doom-modeline-def-modeline 'main-l
  '(bar workspace-name window-number modals matches buffer-info remote-host buffer-position word-count parrot selection-info))
(doom-modeline-def-modeline 'main-r
  nil
  '(objed-state misc-info persp-name battery grip irc mu4e gnus github debug lsp minor-modes input-method indent-info buffer-encoding major-mode process vcs checker))

("%e" (:eval (doom-modeline-format--main-l)))
("%e" (:eval (cdr (doom-modeline-format--main-r))))
```

**Comment by tecosaur** [comment]
Oooh @evertedsphere that's very clever. I assume you are suggesting we take the 'whole' mode-line, take the left and right components and spread them across the multiple sub-modelines to create a large single modeline :grin:

**Comment by seagle0128** [comment]
See #315 .

**Comment by tecosaur** [comment]
With http://ruzkuku.com/texts/emacs-global.html perhaps this might be possible soon?

**Comment by maikol-solis** [comment]
I am also interested in a solution for the single modeline across windows. I also tried mini-modeline and the results aren't functional (the buffer jumps every time I move the cursor)


> ```emacs-lisp
> (doom-modeline-def-modeline 'main-l
>   '(bar workspace-name window-number modals matches buffer-info remote-host buffer-position word-count parrot selection-info))
> (doom-modeline-def-modeline 'main-r
>   nil
>   '(objed-state misc-info persp-name battery grip irc mu4e gnus github debug lsp minor-modes input-method indent-info buffer-encoding major-mode process vcs checker))
> 
> ("%e" (:eval (doom-modeline-format--main-l)))
> ("%e" (:eval (cdr (doom-modeline-format--main-r))))
> ```


I tried this code, but I don't understand what does `%e` mean? 

Could it be possible to have a working example, to see how to implement this?

Thanks in advance.

**Comment by seagle0128** [comment]
@maikol-solis  
> %e -- print error message about full memory.

To be clear, the `mode-line-format` is set to 
```elisp
'(("%e" (:eval (doom-modeline-format--main-l)))
  ("%e" (:eval (cdr (doom-modeline-format--main-r)))))
```

**Comment by maikol-solis** [comment]
Ah ok thanks. 

So the correct config should be something like 

```
(setq mode-line-format '(("%e" (:eval (doom-modeline-format--main-l)))
                                          ("%e" (:eval (cdr (doom-modeline-format--main-r)))))))
```

Isn't?

**Comment by seagle0128** [comment]
@maikol-solis correct.

**Comment by maikol-solis** [comment]
@seagle0128  This is weird,  in doom if I review this variable with `SPC h a` I got this 

```
Global Value
("%e"
 (:eval
  (doom-modeline-format--main)))
```

Is this correct?

**Comment by seagle0128** [comment]
@maikol-solis use setq-default.

**Comment by benthamite** [comment]
The way I solved this is by distinguishing elements that are and aren’t buffer-specific, and by moving the latter to the [tab-bar](https://www.gnu.org/software/emacs/manual/html_node/emacs/Tab-Bars.html). See [my config](https://github.com/benthamite/dotfiles/blob/master/emacs/config.org#tab-bar) for details.

<img width="1728" alt="image" src="https://github.com/seagle0128/doom-modeline/assets/5490677/5e866965-5bb0-479f-8ca4-2dec666cc938">

**Comment by maikol-solis** [comment]
One of my biggest issues with modeline is the org-pomodoro timer (I use it a lot). 

This snippet, removes all the org-pomodoro information from the modeline to the minibuffer. 

This is not ideal, but it works well enough. The only downside here is your `*Message*` buffer is populated every time the pomodoro changes the time (every second, more or less). 

I don't know how to improve this, but for the moment isn't a big deal. 

```elisp
(use-package! org-pomodoro
  :config
  (defun org-pomodoro-update-minibuffer ()
    "Set the minibuffer accordingly to the current state."
    (let ((s (cl-case org-pomodoro-state
               (:pomodoro
                (propertize org-pomodoro-format 'face 'org-pomodoro-mode-line))
               (:overtime
                (propertize org-pomodoro-overtime-format
                            'face 'org-pomodoro-mode-line-overtime))
               (:short-break
                (propertize org-pomodoro-short-break-format
                            'face 'org-pomodoro-mode-line-break))
               (:long-break
                (propertize org-pomodoro-long-break-format
                            'face 'org-pomodoro-mode-line-break)))))
      (setq org-pomodoro-mode-line nil)

      (setq org-pomodoro-minibuffer
            (when (and (org-pomodoro-active-p) (> (length s) 0))
              (concat org-clock-heading  " [" (format s (org-pomodoro-format-seconds)) "] "))))
    (display-message-or-buffer org-pomodoro-minibuffer "*Org Pomodoro*"))


  (defun org-clock-update-minibuffer ()
    "Remove the mode line with clock information.
When optional argument is non-nil, refresh cached heading."
    (setq org-mode-line-string nil))


  (advice-add #'org-pomodoro-update-mode-line :override #'org-pomodoro-update-minibuffer)
  (advice-add #'org-clock-update-mode-line :override #'org-clock-update-minibuffer))
```
