### ISSUE TITLE
Frame focus error

### ISSUE THREAD

**Issue by cyril-allignol** [seagle0128/doom-modeline#313]
**Describe**
Upon focus change, the following error occurs:
`doom-modeline-focus-change: Symbol’s function definition is void: frame-focus-state`
I don't see any side-effect other than the error message cluttering my mini-buffer and *Messages* buffer.

**Steps and Expected**
- Launch `emacs -Q`
- In scratch buffer, eval:
`(let ((default-directory  "~/.emacs.d/"))
  (normal-top-level-add-subdirs-to-load-path))
(require 'doom-modeline)`
- Leave focus from Emacs and grab focus again
- Observe error message

**Environment:**
 - OS and version: Debian 10.3
 - Emacs Version: Official 26.1
 - Configuration: N/A
 - Package version: 20200219.543

**Comment by cyril-allignol** [comment]
I confirm the latest melpa version works as expected. Thanks for the fix!

**Comment by seagle0128** [comment]
Thank you for the update!
