### ISSUE TITLE
Advise on embedding the modeline into the minibuffer

### ISSUE THREAD

**Issue by ishovkun** [seagle0128/doom-modeline#315]
**Is your feature request related to a problem? Please describe.**
I am trying to find a way to display doom modeline in the minibuffer.
I am currently trying to make the package mini-modeline use the format of doom modeline.
(mini-modeline is located at https://github.com/kiennq/emacs-mini-modeline).

I am able to place the contents of the doom modeline into the minibuffer.
The problem I am facing is that the text is truncated.
I understand that the problem might be not on your side; therefore, I am simply asking for any suggestions.

The setup I currently come up with is as follows:
packages.el:
```
(package! mini-modeline :recipe (:host github :repo "kiennq/emacs-mini-modeline"))
```
config.el: doom-modeline part
```
(after! doom-modeline
  (progn
    (winum-mode)
    (setq doom-modeline-height 5
          ;; shorter buffer names
          doom-modeline-buffer-file-name-style 'buffer-name
          ;; show icons
          doom-modeline-icon t
          ;; Whether display color icons for `major-mode'. It respects
          ;; `doom-modeline-icon' and `all-the-icons-color-icons'.
          doom-modeline-major-mode-icon t
          doom-modeline-major-mode-color-icon nil
          doom-modeline-modal-icon nil
          doom-modeline-buffer-state-icon nil
          ;; If non-nil, a word count will be added to the selection-info modeline segment.
          doom-modeline-enable-word-count nil
    )
))
```
config.el: mini-modeline part
```
(use-package! mini-modeline
  :after doom-modeline
  :config
  (defun my-setup-mini-modeline()
    (add-hook 'minibuffer-inactive-mode-hook
              (lambda ()
                (make-local-variable 'face-remapping-alist)
                (add-to-list 'face-remapping-alist '(default (:background "#21252b")))))

        (doom-modeline-def-modeline 'minibuffer-line
      '(modals workspace-name window-number matches buffer-info remote-host buffer-position word-count selection-info)
      '(misc-info major-mode process vcs lsp checker " \n"))

    (setq mini-modeline-r-format '(:eval (doom-modeline-format--minibuffer-line)))
    )

    (add-hook 'mini-modeline-mode-hook 'my-setup-mini-modeline)
  )
```
After loading emacs I manually run M-x mini-modeline-mode.

Finally, I am attaching the screenshot of what I see:
![Screenshot_20200304_220407](https://user-images.githubusercontent.com/11154303/75952635-1f1dab00-5e64-11ea-93b9-6c60747415f2.png)

Again, I apologize if I am posting this to the wrong place.

**Comment by seagle0128** [comment]
Well, I guess the problem is the height. Try these solution:
1. `(setq doom-modeline-height 1)`.
1.  Remove `bar` segment from the mode-line. see [FAQ](https://github.com/seagle0128/doom-modeline#faq) item 4.
1. Increase minibuffer height.

**Comment by ishovkun** [comment]
Thanks for your reply.
1. Does not help at all.
2. Yes, it's definitely the icons.
3. I couldn't find an option to have a fractional minibuffer height. Multiples of the line height is not an option for me.

**Comment by seagle0128** [comment]
Then you should use option 2.

**Comment by ishovkun** [comment]
But what's the fun in that? :-)
I am closing this.
Thank you so much for your feedback.

**Comment by seagle0128** [comment]
@ishovkun It seems hard to increase the minibuffer height.
I got another solution: Smaller icon size. See `all-the-icons-scale-factor`.

**Comment by andersjohansson** [comment]
`all-the-icons-scale-factor` works, but I also use `all-the-icons-dired` and don't want the icons to be scaled down there.
I implemented a `doom-modeline-icons-scale-factor` variable here (along with another commit for using other faces so that the face remapping done in mini-modeline since https://github.com/kiennq/emacs-mini-modeline/pull/19 doesn't interfere):
https://github.com/andersjohansson/doom-modeline/tree/mini-modeline

This works pretty fine with my current config:
````emacs-lisp
(use-package eldoc-eval)
(use-package doom-modeline
  :demand t
  :custom
  (doom-modeline-buffer-file-name-style 'truncate-all)
  (doom-modeline-bar-width (frame-parameter nil 'left-fringe))
  (doom-modeline-height 10)
  (doom-modeline-icon t)
  (doom-modeline-icons-scale-factor 0.8)
  :config
  (set-face-attribute 'doom-modeline nil :inherit 'default)
  (set-face-attribute 'doom-modeline-inactive nil :inherit 'default)
  )

(use-package mini-modeline
  :after doom-modeline
  :config
  (doom-modeline-def-modeline 'minibuffer-line
    '(modals workspace-name window-number matches buffer-info remote-host buffer-position word-count selection-info misc-info major-mode process vcs lsp checker))

  (setq mini-modeline-r-format '(:eval (doom-modeline-format--minibuffer-line)))

  (setq mini-modeline-right-padding 1
        mini-modeline-enhance-visual nil)

  (set-face-attribute 'mode-line nil :box nil)
  (set-face-attribute 'mini-modeline-mode-line nil :background (face-background 'modus-theme-intense-blue) :height 0.2)
  (set-face-attribute 'mini-modeline-mode-line-inactive nil :background (face-background 'fringe) :height 0.2)

  :hook (after-init . mini-modeline-mode)
  )

````
(using modus-operandi-theme)

![Skärmbild från 2020-04-03 12-17-33](https://user-images.githubusercontent.com/846411/78350716-f04f3d80-75a5-11ea-8b6c-3210c18abcf9.png)

Works pretty fine, but what is a still bit off for some icons now is the `:v-adjust`

**Comment by andersjohansson** [comment]
Pushed another commit for scaling the `:v-adjust`. Not very beautiful code, but it works. Setting `(setq doom-modeline-icons-v-adjust-factor 0.8)` aligns the icons much better. Maybe I could just have used the same scaling factor as for the icon size, but wanted to keep all options open for now.

![Skärmbild från 2020-04-03 13-43-31](https://user-images.githubusercontent.com/846411/78357111-2645ef00-75b1-11ea-9eb5-eec06fa6dd7a.png)


Still a little issue with the major-mode icon, that's because the `:v-align` is set in `all-the-icons-icon-alist` and not scaled when the major-mode icon is read via `all-the-icons-icon-for-buffer`.

**Comment by andersjohansson** [comment]
By the way, I don’t intend this as changes to be pulled into `doom-modeline`, I’ll update my fork if I find this worthwhile.

**Comment by seagle0128** [comment]
Well, I'd like add to the README if you find the perfect solution.

**Comment by nazzacode** [comment]
Hey, this is a feature I would really like to see. For people coming from editors like vs-code this would be a very welcome feature. Is there anything that can be done to make this a bit more accessible? I cant seem to get any of the code snippet suggested to work.

**Comment by quangIO** [comment]
If you can live without icons then in doom-emacs you can have something like this:

(Note, for doom-emacs, I disabled `modeline` module in `init.el` and add `(package! doom-modeline)` to `packages.el`)

```elisp
(use-package! doom-modeline
  :custom
  (doom-modeline-buffer-file-name-style 'truncate-except-project)
  (doom-modeline-icon nil))

(use-package! mini-modeline
  :after doom-modeline
  :config
  (doom-modeline-def-modeline 'minibuffer-line
    '(modals workspace-name window-number matches buffer-info remote-host buffer-position word-count selection-info misc-info major-mode process vcs lsp checker))

  (setq mini-modeline-r-format '(:eval (doom-modeline-format--minibuffer-line)))

  (setq mini-modeline-right-padding 1
        mini-modeline-enhance-visual t)

  (set-face-attribute 'mode-line nil :box nil)
  (set-face-attribute 'mini-modeline-mode-line nil :background (face-background 'fringe) :height 0.2)
  (set-face-attribute 'mini-modeline-mode-line-inactive nil :background (face-background 'fringe) :height 0.2)

  (mini-modeline-mode 1))

```

![image](https://user-images.githubusercontent.com/13181907/193481849-6dbc9cc4-6e5f-42e8-859f-441167a85627.png)
