### ISSUE TITLE
Support tab-bar-mode

### ISSUE THREAD

**Issue by Linuus** [seagle0128/doom-modeline#317]
**Is your feature request related to a problem? Please describe.**
I’m replacing eyebrowse with tab-bar-mode in emacs 27 but I miss the workspace name in the mode-line.

**Describe the solution you'd like**
Show the current tab name in the mode-line

**Describe alternatives you've considered**
- Use eyebrowse - works fine but I like built in things if they exist.
- Look at the actual tab instead - Well... I’m using a Mac and the tab-bar GUI isn’t there yet. Also, I don’t really want to show the tab bar anyway, I just want the functionality of it and then see only the current tab name :)

I have this code in my config now. It kind of simulates the same functionality as the eyebrowse segment. It shows the index (+1) for the tab if there's no explicit name set. If there is an explicit name it uses that.

```elisp
(doom-modeline-def-segment tab-name
  "The current tab name or tab index.
Requires `tab-bar-mode' to be enabled."
  (if (bound-and-true-p tab-bar-mode)
      (let ((current-tab (tab-bar--current-tab)))
        (when current-tab
          (let* ((tab-index (tab-bar--current-tab-index))
                (explicit-name (alist-get 'explicit-name (tab-bar--current-tab)))
                (tab-name (alist-get 'name (tab-bar--current-tab)))
                (str (if explicit-name
                          tab-name
                        (+ 1 tab-index))))
            (propertize (format " %s " str) 'face
                                (if (doom-modeline--active)
                                    'doom-modeline-buffer-major-mode
                                  'mode-line-inactive)))))))
```

**Comment by seagle0128** [comment]
AFAIK, `eyebrowse` and `tab-bar` have different purpose. `eyebrowse` is for workspace layouts, while `tab-bar` is for frame-local tabs. I don't know how and why use `tab-bar` for workspace layouts management. So, please clarify what do you want to display on the mode-line. I know only buffer name is displayed on the tab. Am I wrong?

**Comment by Linuus** [comment]
They do the same thing though - they store the current window configuration. So each tab = one eyebrowse workspace.

Or what would the practical difference be?

**Comment by seagle0128** [comment]
OK. Let me do some investigations.

**Comment by seagle0128** [comment]
@Linuus Can you test these snippets in your env? I am not sure if it's a good idea to show this information, for all users.

``elisp
(doom-modeline-def-segment workspace-name
  "The current workspace name or number.
Requires `eyebrowse-mode' or `tab-bar-mode' to be enabled."
  (let ((name (cond
               ((and (bound-and-true-p eyebrowse-mode)
                     (< 1 (length (eyebrowse--get 'window-configs))))
                (assq-delete-all 'eyebrowse-mode mode-line-misc-info)
                (when-let*
                    ((num (eyebrowse--get 'current-slot))
                     (tag (nth 2 (assoc num (eyebrowse--get 'window-configs)))))
                  (if (< 0 (length tag)) tag (int-to-string num))))
               ((bound-and-true-p tab-bar-mode)
                (funcall tab-bar-tab-name-function)))))
    (propertize (format " %s " name) 'face
                (if (doom-modeline--active)
                    'doom-modeline-buffer-major-mode
                  'mode-line-inactive))))
```

**Comment by seagle0128** [comment]
I merge it into `workspace-name` segment. A minor issue is the tab name will be displayed in both tab-bar and mode-line on Linux.

**Comment by Linuus** [comment]
Looks like it works great. Thanks 👍
