### ISSUE TITLE
Display the difference of commits between local and remote

### ISSUE THREAD

**Issue by ishovkun** [seagle0128/doom-modeline#318]
It would be cool if the mode-line could display the difference in commit numbers between local and origin.
Specifically, I would like to have an option to see something like this:
![image](https://user-images.githubusercontent.com/11154303/76846721-306c9d00-67fe-11ea-9a27-8271577aad7b.png)
The image shows that the origin is zero commits ahead from the local, and
the local is one commit ahead from the origin.

This should probably be a separate segment or be a part of the vcs segment.
For me, it's easier to parse this segment in order to decide whether I need to sync my work as opposed to interpreting the vcs icon.

**Comment by seagle0128** [comment]
Well, I would like say this is a good feature for git users. They are displayed in `magit`. `doom-modeline` is based on built-in `vc-mode` , which is for more VCS backends, but it doesn't provide more information, except `needs-update` and `needs-merge` states. Honestly I don't how to get the VCS details so far.

**Comment by seagle0128** [comment]
See `vc-state`. This seems a request for emacs itself.
