### ISSUE TITLE
Show column of cursor position

### ISSUE THREAD

**Issue by mwip** [seagle0128/doom-modeline#319]
Would it be possible to add the current column position of the cursor to the doom-modeline? That would help to achieve style standards in many use cases. VIM shows the current position by default as row,column in the status. 

In the standard modeline this would be done with the `%c` parameter: 
https://www.gnu.org/software/emacs/manual/html_node/efaq/Displaying-the-current-line-or-column.html

Unfortunately I did not find that parameter in `M-x customize group RET doom-modeline RET`

**Comment by seagle0128** [comment]
Did you enable `column-number-mode`?

<img width="522" alt="Screen Shot 2020-03-19 at 10 44 29 PM" src="https://user-images.githubusercontent.com/140797/77079592-3eefca00-6a33-11ea-9416-a8f4efa35147.png">

**Comment by mwip** [comment]
Indeed that solves that issue. Thanks... :)
