### ISSUE TITLE
Tramp mode lags when doom-modeline enabled

### ISSUE THREAD

**Issue by bramboomen** [seagle0128/doom-modeline#32]
Hi, I just started using emacs, so this issue could well be specific to my configuration, but when editing remote files over ssh, movement and input feels very sluggish. When I disable the doom-modeline, there is no difference between performance on local files.

I'm really enjoying the package otherwise, thanks!

**Comment by seagle0128** [comment]
Hello, based on the information, it's really hard to dig out the root cause.
Would you please provide more details?
1. OS
1. Emacs version
1. `doom-modeline` version
1. Emacs configurations
1. what files? It's better provide the examples with address and credential.
1. other clues

My guess is the remote files may be not in the project or vcs, but not 100% sure. Need more information to troubleshooting.

.

**Comment by seagle0128** [comment]
Thanks for the information!

I checked your Emacs configurations, and noticed `projectile-mode` is not enabled. Would you please enable it to try?

**Comment by seagle0128** [comment]
Welcome! Glad to know the issue has been fixed.
I am considering to add this to FAQ.

**Comment by envypole** [comment]
It seems that the project root is always the same for a given buffer, so do we really need to call `projectile-project-root` on every motion? I use the following code to cache the value, I think it fixes the issue:
```elisp
(defun my-cache-project-root (orig-fn &rest args)
  (if (local-variable-p 'my-project-root)
      my-project-root
    (setq-local my-project-root (apply orig-fn args))))
(advice-add 'doom-modeline-project-root :around #'my-cache-project-root)
```

**Comment by seagle0128** [comment]
@envypole It's a good idea to optimize the performance. I'll try to merge.

**Comment by seagle0128** [comment]
Recently I rewrote the codes of buffer info, and the performance is much better than before, especially for remote files. Please update and try the fancy styles.

```elisp
truncate-upto-project
truncate-from-project
truncate-with-project
truncate-except-project
```

**Comment by seagle0128** [comment]
@ashiklom You are right! It's for updating the `modified` status after changing the buffer. It works well for the local files, but I have to agree it can be optimized.
