### ISSUE TITLE
Doom-modeline not displaying anything except window number

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/doom-modeline#321]
Doom-modeline not displaying anything except window number after the recent update. I am not sure if this is a conflict with some other package. I had to restart my laptop after a 2 weeks today and when opened emacs a bunch of packages got updated.

**Environment:**
 - OS and version: [MacOs]
 - Emacs Version: [26.3]
 - Configuration: [Centuar]
 - Package version: [doom-modeline-20200322.636]

This is how it looks now, there is no information on mode-line except for window numbers -
![image](https://user-images.githubusercontent.com/23665525/77367548-6347f100-6d28-11ea-8a03-4f5eff98784f.png)

**Comment by seagle0128** [comment]
Please check the `*Message*` buffer and get the errors or warnings.

**Comment by CsBigDataHub** [comment]
@seagle0128 , there were no errors in messages buffer. Had to deleted elpa directory and re-open emacs. looks like its working fine.

Thanks
