### ISSUE TITLE
Other than color based indicators for various modes

### ISSUE THREAD

**Issue by andreyorst** [seagle0128/doom-modeline#324]
Hi, this problem is both because of my configuration and current implementation of the feature. When I'm using god mode I can see a circle in the modeline:

![image](https://user-images.githubusercontent.com/19470159/77921058-eed0fd00-72a7-11ea-95af-82ae81671683.png)

When I use overwrite mode I can also see the circle in the modeline:

![image](https://user-images.githubusercontent.com/19470159/77921058-eed0fd00-72a7-11ea-95af-82ae81671683.png)

When both modes are active, there are two circles:

![image](https://user-images.githubusercontent.com/19470159/77921169-132cd980-72a8-11ea-86e6-12f09f2a19f3.png)

The problem is, that there's no way to tel whether it is god mode or overwrite mode active when only one circle is in the modeline. That bitten me quite a few times already. **Now, I know** that that's because I'm using a monochrome colorscheme for the modeline:

![image](https://user-images.githubusercontent.com/19470159/77921630-b0880d80-72a8-11ea-9f05-529a2abbbb8b.png)

Another problem is that I like it to be this way much better than default colorful style.

**Describe the solution you'd like**
Different icons for these modes would be nice solutions. Some ideas:
- `border_color` icon from `all-the-icons` for overwrite mode: ![image](https://user-images.githubusercontent.com/19470159/77922116-4de34180-72a9-11ea-87fa-f5b6c9294a7d.png)
- Maybe `broadcast` icon for `god-mode`: ![image](https://user-images.githubusercontent.com/19470159/77922758-23de4f00-72aa-11ea-9f3c-e0969a7bd2a9.png)
- `child` icon also looks like a good fit for `god-mode`: ![image](https://user-images.githubusercontent.com/19470159/77922925-6011af80-72aa-11ea-9c8c-210c872d4cdd.png)
- I'm not using `evil` so I don't know icons for modes it provides, e.g. visual (if there is), insert, normal, maybe others..

**Describe alternatives you've considered**
 Previously there were `<G>` `<O>` `<I>` `<N>` indicators for different modes, like evil, but now it seems that there's only circle left. Maybe option to fallback to textual indicators would be nice solution, though I'm more of a fan of icons.

**Comment by seagle0128** [comment]
See doom-modeline-modal-icon.

**Comment by andreyorst** [comment]
Sorry, didn't seen this option while gathering over Customize, this is good one. That's describes alternative, I'm considering, but what about icon solution? Is this hard to implement?

**Comment by seagle0128** [comment]
I need some time to investigate the icon solution. Stay tune.
