### ISSUE TITLE
Right margin unalignment when telega.el or skype.

### ISSUE THREAD

**Issue by DanGNU** [seagle0128/doom-modeline#325]
**Describe**
When I start telega.el the right margin goes farther out the margin. Sometimes it happens when I start skype while in EXWM.

**Steps and Expected**
1. Start Emacs with doom-modeline-mode activated by default.
2. Start telega.el with M-x telega RET.
3. The activated buffer will have a right line going farther out of the screen.

I can't reproduce it with emacs -Q because I need EXWM, telega and doom-modeline to have this problem, but I tried mood-line and I don't have such error there.

**Environment:**
 - OS and version: Arch Linux 5.5.13
 - Emacs Version: 26.3
 - Configuration: mood-line minions company-quickhelp readline-complete slime-company company-auctex company-emoji company-math company-shell company org-pdfview pdf-tools tablist all-the-icons-ibuffer doom-modeline doom-themes all-the-icons telega auctex rainbow-delimiters pulseaudio-control abyss-theme slime smartparens vterm exwm.
 - Package version: 20200322.636

**Additional context**

Here is visible how the default mode line looks like with telega.el open.
![default-modeline](https://user-images.githubusercontent.com/62719065/78119689-4004fc00-7422-11ea-97b0-9a9bd7fb1ab9.png)

Here under doom-modeline. Please look at the right margin.
![doom-modeline](https://user-images.githubusercontent.com/62719065/78119702-42675600-7422-11ea-95e5-2a4e74ce4bed.png)

And as trial, I checked with mood line also to see if there is the same error, and there isn't, still I don't know why.
![mood-line](https://user-images.githubusercontent.com/62719065/78119704-43988300-7422-11ea-873a-7a62c8e1d1df.png)

**Comment by seagle0128** [comment]
How about disabling `battery-mode` and/or `minions-mode`?

**Comment by DanGNU** [comment]
Ah, you are right, if I disable those two, the mode line displays properly.

**Comment by seagle0128** [comment]
This is related to the fonts. It's very hard to calculate the accurate with of all icons (unicode characters).

**Comment by DanGNU** [comment]
Interesting, and there isn't a way to tell to the mode line "display until this part but extend to the left as necessary"?

**Comment by seagle0128** [comment]
No solution so far. Please let me know if you have.

**Comment by DanGNU** [comment]
May you explain to me this part of `doom-modeline-def-modeline`?

```
:align-to​
                           (​-​ (​+​ right right-fringe right-margin)
                              ,(​*​ (​let​ ((width (doom-modeline--font-width)))
                                    (​or​ (​and​ (​=​ width ​1​) ​1​)
                                        (​/​ width (​frame-char-width​) ​1.0​)))
                                  (​string-width​
                                   (​format-mode-line​ (​cons​ ​"​"​ rhs-forms))))))))
```

It's just that in mood-line the right alignment is done in a simpler way. And sorry if this is not the way to link code, I'm a noob in GitHub.
