### ISSUE TITLE
modeline cuts off when resizing with default-text-scale

### ISSUE THREAD

**Issue by spicyriceball** [seagle0128/doom-modeline#329]
**Describe**
Description says it all: the right-hand side of my doom modeline has been cut off because I'm using the package default-text-scale to zoom. This is a nonissue in most buffers, except when flycheck is involved (images in additional context). A hotfix I've discussed on the doom server is adding a small space padding to the right, but it would be best if something more foolproof was done. 
**Steps and Expected**
It should account for the resizing and move it left if possible or something along those lines.

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

Using this (either as init file or with `emacs -Q --load /path/to/thisfile`):
<details>
 <summary>Minimal Configuration</summary>

```lisp
;; -*- lexical-binding: t -*-

(require 'package)

(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package use-package
  :config
  (setq-default use-package-always-defer nil
                use-package-always-ensure t
                use-package-always-demand t
                byte-compile-warnings nil))

(use-package doom-themes
  :custom
  (doom-vibrant-brighter-comments t)
  (doom-vibrant-brighter-modeline t)
  :config
  (doom-themes-org-config)
  (load-theme 'doom-dracula t))

(line-number-mode t)
(column-number-mode t)

(use-package doom-modeline
  :custom
  (doom-modeline-icon t)
  (doom-modeline-major-mode-icon t)
  (doom-modeline-version t)
  (doom-modeline-buffer-file-name-style 'file-name)
  :config
  (doom-modeline-mode))

(use-package default-text-scale
  :init
  (default-text-scale-mode))

(use-package flycheck
  :config
  (setq flycheck-check-syntax-automatically '(mode-enabled save))
  :init
  (global-flycheck-mode))

```
</details>

Just try to use the [default-text-scale package](https://github.com/purcell/default-text-scale) (binding to zoom should be `C-M-=` based off vanilla minimal above. I normally zoom to 140ish on a 15 in screen).

**Environment:**
 - OS and version: Manjaro 18.0.4 Illyria and macOS High Sierra
 - Emacs Version: 28.0.50 and 26.3 (respectively for OS above)
 - Configuration: minimal configuration should be enough
 - Package version: The elpa folder has `20200319.1613` appended to the package name 🤷 

**Additional context**
Just a couple of screenshots I shared on the doom server as well (note: they were taken with my custom config, but it should translate and showcase the issue fine).

[Dashboard](https://media.discordapp.net/attachments/603399769015975996/688836400040509455/2020-03-15-154040_1920x1080_scrot.png?width=1800&height=1013)
[Flycheck](https://media.discordapp.net/attachments/603399769015975996/688836528201531424/2020-03-15-154950_1920x1080_scrot.png?width=1800&height=1013)

A little tangential, but I suspect it could be related to #141 possibly? I could be totally wrong.

**Comment by seagle0128** [comment]
It's not related to #141. I think you should enable `default-text-scale-mode` before `doom-modeline-mode`.

**Comment by spicyriceball** [comment]
I see, so I would need to predefine the size in my init file like so:

```lisp
(default-text-scale-increase)
(default-text-scale-increase)
```
Is it possible to turn caching off or force overwrite? I sometimes have to use external monitors and would like to change my size on the fly.

**Comment by seagle0128** [comment]
It's not a good idea to turn off it. My recommendation is

1. Use `C-x C-=` to increase the font size manually.
1. Call `doom-modeline-refresh-font-width-cache` after `default-text-scale` functions.

**Comment by seagle0128** [comment]
I submitted a patch to address this issue. The solutions above still work.
