### ISSUE TITLE
[Question] Intigration of winds.el to doom-mode-line

### ISSUE THREAD

**Issue by CsBigDataHub** [seagle0128/doom-modeline#331]
@seagle0128 ,

I am testing [winds.el](https://github.com/Javyre/winds.el) as eyebrowse replacement and I am trying to integrate it with doom-mode-line. 

This was the suggestion in the package README.

 For a simple mode-line indicator, add this to your `mode-line-format`:

```emacs-lisp
    (:eval (format "%s|%s " (winds-get-cur-ws) (winds-get-cur-cfg)))
```

  For example (dumb example):

```emacs-lisp
    (setq mode-line-format
          `(,mode-line-format
            (:eval (format "%s|%s "
                           (winds-get-cur-ws)
                           (winds-get-cur-cfg)))))
```

How to do I integrate this with `doom-mode-line` in place of `eyebrowse`?

can `mode-line-misc-info` or `global-mode-string` do that, if so can you please point me to a example.

Thanks

**Comment by seagle0128** [comment]
`mode-line-misc-info` or `global-mode-string` does work, but if you want in place of `eyebrowse`, you should modify or redefine the `workspace-name` segment. The PR is welcome.

https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1385

**Comment by CsBigDataHub** [comment]
Thanks will try to do it.
