### ISSUE TITLE
Include mode <--> color table in readme.md

### ISSUE THREAD

**Issue by quickfold** [seagle0128/doom-modeline#332]
I can't find a listing of the meanings of the circle colors anywhere. As a total emacs newbie, it would be very helpful to know what modes are indicated by a grey or pink circle. Thanks!

**Comment by seagle0128** [comment]
I believe you can get the information in minibuffer, messages or tooltip (with mouse). Or `(setq doom-modeline-modal-icon nil).

**Comment by quickfold** [comment]
Thanks. THAT information should also be in the readme. Here it is - no harm in adding it if anyone knows how.

	- blue - insert OR emacs
	- green - normal
	- teal - motion state
	- pink - replace state
	- red - visual
	- gray - operator-pending

**Comment by seagle0128** [comment]
See #324.

**Comment by justinjk007** [comment]
Is there a way to add some padding to the state strings ?

![image](https://user-images.githubusercontent.com/12916795/80654197-be68b400-8a49-11ea-9650-57a3a68b0c26.png)

**Comment by seagle0128** [comment]
@justinjk007 How do you get the tag names? You can define your tags for evil.

**Comment by justinjk007** [comment]
Yes, I tried added some padding like this:
```
  (setq evil-operator-state-tag " OPERATOR "
	evil-normal-state-tag " NORMAL"
	evil-insert-state-tag " INSERT "
	evil-visual-state-tag " VISUAL "
	evil-replace-state-tag " REPLACE "
	evil-emacs-state-tag " EMACS "
	evil-motion-state-tag " MOTION " )
```

but can't the see the spaces on each side. Is there some face customization I can do ?

**Comment by jmromer** [comment]
> but can't the see the spaces on each side. Is there some face customization I can do ?

`propertize` works there. e.g.:

```elisp
(setq-default
 evil-emacs-state-tag        (propertize "[E]" 'face '(:background "SkyBlue2" :foreground "black"))
 evil-evilified-state-tag    (propertize "<E>" 'face '(:background "green" :foreground "black"))
 evil-hybrid-state-tag       (propertize "[H]" 'face '(:background "chartreuse3" :foreground "white"))
 evil-iedit-insert-state-tag (propertize "<I>" 'face '(:background "green" :foreground "black"))
 evil-iedit-state-tag        (propertize "<N>" 'face '(:background "green" :foreground "black"))
 evil-insert-state-tag       (propertize "[I]" 'face '(:background "chartreuse3" :foreground "white"))
 evil-lisp-state-tag         (propertize "[L]" 'face '(:background "green" :foreground "black"))
 evil-motion-state-tag       (propertize "[M]" 'face '(:background "plum3" :foreground "white"))
 evil-normal-state-tag       (propertize "[N]" 'face '(:background "DarkGoldenrod2" :foreground "black"))
 evil-operator-state-tag     (propertize "[O]" 'face '(:background "purple" :foreground "black"))
 evil-replace-state-tag      (propertize "[R]" 'face '(:background "green" :foreground "black"))
 evil-visual-state-tag       (propertize "[V]" 'face '(:background "gray" :foreground "black")))

```

**Comment by justinjk007** [comment]
![image](https://user-images.githubusercontent.com/12916795/80766453-78782280-8b13-11ea-93c1-3c51e0d4a1fe.png)

Even with or without propertize if I change the state strings it works, but the spaces at the strings does not work to add some padding.

**Comment by jmromer** [comment]
> the spaces at the strings does not work to add some padding.

You should not use leading/trailing whitespace in the string for that. See:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Format-Properties.html#Format-Properties

**Comment by seagle0128** [comment]
> ![image](https://user-images.githubusercontent.com/12916795/80766453-78782280-8b13-11ea-93c1-3c51e0d4a1fe.png)
> 
> Even with or without propertize if I change the state strings it works, but the spaces at the strings does not work to add some padding.
> 

string-trim is used to handle the tag names here.

**Comment by justinjk007** [comment]
@jmromer I tried this, no effect
```lisp
	(setq evil-normal-state-tag (propertize "NORMAL" 'display '(:margin left-margin)))
```

**Comment by seagle0128** [comment]
@justinjk007 The commit 515300f9846b1b1c92b50d388e161fbb08255c06 should address your issue. Please test.

**Comment by seagle0128** [comment]
> Thanks. THAT information should also be in the readme. Here it is - no harm in adding it if anyone knows how.
> 
> ```
> - blue - insert OR emacs
> - green - normal
> - teal - motion state
> - pink - replace state
> - red - visual
> - gray - operator-pending
> ```

I don't think it's a good idea. The colors are different in different themes, and the users are able to customize them as well.

**Comment by justinjk007** [comment]
Yep that worked.

**Comment by justinjk007** [comment]
> @justinjk007 The commit 515300f9846b1b1c92b50d388e161fbb08255c06 should address your issue. Please test.

Yep that worked.
