### ISSUE TITLE
A part of modeline is hidden

### ISSUE THREAD

**Issue by zongUMR** [seagle0128/doom-modeline#334]
**Describe**
Thanks for your awesome package, but a  part of modeline is hidden on my scrren

**Steps and Expected**
Open emacs, and see the modeline, I already installed  some packages(magit, flycheck...)
Expected: Show whole modeline

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

**Environment:**
 - OS and version: Mac OS 10.14.5
 - Emacs Version: 26.3
 - Configuration: [my own config](https://github.com/zongUMR/emacs_config)
 - Package version: latest

**Additional context**
The position for modeline config is: `core/config/pkg-view.el'

**You can see the error dispaly on bottom-right.**
![image](https://user-images.githubusercontent.com/11454175/80171403-ebb5fc00-861c-11ea-92f9-78c70fe4e69d.png)

**Comment by seagle0128** [comment]
It's related to the font family. Try other fonts in mode-line, or disabling battery icon. Or add more extra spaces at the last in the mode-line.
