### ISSUE TITLE
can't set height?

### ISSUE THREAD

**Issue by e190** [seagle0128/doom-modeline#336]
**Describe**
![图片](https://user-images.githubusercontent.com/39932163/80331789-99bee180-887b-11ea-915f-afad7ab8cdb8.png)
为什么不能调整 mode-line的 宽度？我想变窄一点
        doom-modeline-height 5
        doom-modeline-bar-width 1
感觉这两个设置一点效果都没有呢？

我想取消icon，我已经 设置   doom-modeline-modal-icon nil，但是 还是有图标显示呢？

**Steps and Expected**

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

**Environment:**
 - OS and version: [e.g. Windows 10]
 - Emacs Version: [e.g. 26.3]
 - Configuration: [e.g. Spacemacs/Doom/Centuar, or url]
 - Package version: [e.g. 201801228]

**Additional context**
 Screenshots, recordings, logs and messages...

**Comment by seagle0128** [comment]
Please read the docs carefully. See doom-modeline-icon.
