### ISSUE TITLE
Performance: doom-modeline-segment--word-count on large buffers

### ISSUE THREAD

**Issue by benmezger** [seagle0128/doom-modeline#338]
**Describe**
I have a not-so-large org-mode file (~2345 lines). It gets very slow when simply moving to the next line. My running `profiler` it seems that `doom-modeline-segment--word-count` is the bottleneck (`count-words`, more precisely).

Setting `doom-modeline-segment--word-count` to`nil` seems to fix the issue. 

**Steps and Expected**
1. Open a big org-file
2. move line by line.

Open up a big org-file and simple move to the next lines.

**Environment:**
 - OS and version: Darwin Bens-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Emacs Version: 26.3
 - Configuration: https://github.com/benmezger/dotfiles/tree/master/doom-emacs/.doom.d

**Additional context**
Video: https://youtu.be/mJRE6_sJnlU

**Comment by seagle0128** [comment]
Hi, did you check this

From README:
>;; Major modes in which to display word count continuously.
;; Also applies to any derived modes. Respects `doom-modeline-enable-word-count'.
;; If it brings the sluggish issue, disable `doom-modeline-enable-word-count' or
;; remove the modes from `doom-modeline-continuous-word-count-modes'.
(setq doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))

**Comment by benmezger** [comment]
@seagle0128 do I need to remove org-mode from `doom-modeline-continuous-word-count-modes`?

**Comment by seagle0128** [comment]
It's up to you. YES in this case.

**Comment by benmezger** [comment]
I can see some improvements. I will wait and see how it behaves during the day, and if the issue returns I will let you know. Thanks!
