### ISSUE TITLE
Add notmuch unread email support

### ISSUE THREAD

**Issue by rbutoi** [seagle0128/doom-modeline#339]
I use notmuch for email, and it doesn't look too hard to add support for it, as there is for mu4e -- just need to change the variable that is being checked. notmuch-unread can be depended on for this variable.

**Comment by seagle0128** [comment]
You are right. But I am not using notmuch. PR is welcome.

**Comment by rbutoi** [comment]
will do!

**Comment by yusi1** [comment]
`(doom-modeline-def-segment notmuch-unread
  "Displays unread emails for today using notmuch."
  (concat
   "\xf6ed "
   (shell-command-to-string "notmuch search -- tag:unread and tag:personal and date:today | wc -l | perl -pe 'chomp'")))

;; Define your custom doom-modeline
(doom-modeline-def-modeline 'my-line
  '(bar matches buffer-info remote-host buffer-position parrot selection-info)
  '(misc-info minor-modes notmuch-unread input-method buffer-encoding major-mode process vcs checker))

;; Add to `doom-modeline-mode-hook` or other hooks
(defun setup-custom-doom-modeline ()
  (doom-modeline-set-modeline 'my-line 'default))
(add-hook 'doom-modeline-mode-hook 'setup-custom-doom-modeline)

`

**Comment by bigodel** [comment]
hey, just chiming in to preset to you guys the [`notmuch-indicator`](https://git.sr.ht/~protesilaos/notmuch-indicator) package from Prot. the code for the notmuch unread count is there and very neatly organized as is usual of Prot's code.

**Comment by seagle0128** [comment]
@bigodel Cool. Thank you!

The `notmuch-indicatior` leverages `global-mode-string` to display the indicator in mode-line. It's compatible with `doom-modeline`, and it's unnecessary to implement a new segment. 
Of course you can make a new better one. The PR is always welcome!

Then I'm closing it.
