### ISSUE TITLE
Message buffer's modeline is without theme

### ISSUE THREAD

**Issue by DonHugo69** [seagle0128/doom-modeline#34]
Hey, thanks a lot for your great work.

I am experiencing the same issue as explained [here](https://github.com/syl20bnr/spacemacs/issues/11404), even though I am not using spacemacs.

Could you take a look at it?

**Comment by seagle0128** [comment]
Hi, this is the screenshot in my env. It looks fine. In the issue of `spacemacs`, seems no such issue with `doom-modeline`. so I don't understand your real issue.

![image](https://user-images.githubusercontent.com/140797/47141982-75805d00-d2f4-11e8-91a6-dd3d0b575ad4.png)

**Comment by DonHugo69** [comment]
Strange, I get this:
![grafik](https://user-images.githubusercontent.com/10484857/47142420-1e15c900-d2c3-11e8-9dc4-f00abec48ca7.png)

```el
;; Doom-modeline
(use-package doom-modeline
  :defer t
  :hook (after-init . doom-modeline-init))
```

**Comment by seagle0128** [comment]
Hi, I need more information to investigate.
1. OS
1. Emacs version
1. Emacs configurations
1. Errors/Exceptions
1. others

Would you please try this?
```elisp
;; Doom-modeline
(use-package doom-modeline
  :init (doom-modeline-init))
```

**Comment by DonHugo69** [comment]
Changing the use-package did the trick. Thanks!

1. Arch Linux
2. 27.0.50 (emacs-git AUR package)
3. https://gitlab.com/DonHugo/emacs.d (Documentation is still lacking in a lot of parts)
4. No errors

**Comment by seagle0128** [comment]
Glad to know it worked. 
I couldn't recreate this issue with Emacs 27.0.50 on Linux Mint 19. I am thinking your Emacs configurations might impact but not very sure. According to the snippet, the `*Messages*` buffer was set to `main` before emacs-init. Perhaps some hooks or advices impact this in your env?

Anyway I am closing this since it has been resolved. Thanks.

```elisp
(defun doom-modeline-init ()
  "Initialize doom mode-line."
  ;; Create bars
  (doom-modeline-refresh-bars)
  (unless after-init-time
    ;; These buffers are already created and don't get modelines. For the love
    ;; of Emacs, someone give the man a modeline!
    (dolist (bname '("*scratch*" "*Messages*"))
      (with-current-buffer bname
        (doom-modeline-set-modeline 'main)))))
```
