### ISSUE TITLE
spacemacs error message

### ISSUE THREAD

**Issue by hanm2019** [seagle0128/doom-modeline#346]
**Describe**
the message in spacemacs show that `Error during redisplay: (eval (doom-modeline-segment--buffer-position)) signaled (void-variable nyan-minimum-window-width) `, 

**Steps and Expected**
configuration in my init.el:
```
dotspacemacs-mode-line-theme '(doom)

```
and my theme is: 
```
dotspacemacs-themes '(monokai)
```
**Environment:**
 - ubuntu 18.04
 - 26.3
 - 20200513

**Additional context**
![Screenshot from 2020-06-01 10-03-07](https://user-images.githubusercontent.com/56673361/83369500-2450ae80-a3ef-11ea-8e03-b701f63bc936.png)

**Comment by seagle0128** [comment]
Check `nyan-minimum-window-width` var in `nyan-mode` package. It should be there. See https://github.com/TeMPOraL/nyan-mode/blob/06e67ab2c490756d3eeed4a68aba7c33e508a5d5/nyan-mode.el#L112.

**Comment by hanm2019** [comment]
i found the nyan.el in syl20bnr/spacemacs is a file 4years age, so there is no `nyan-minimum-window-width` var, the error disappear when i update  the file in spacemcas.
