### ISSUE TITLE
Icon for when CIDER/ some REPL is connected

### ISSUE THREAD

**Issue by ericdallo** [seagle0128/doom-modeline#347]
**Is your feature request related to a problem? Please describe.**
It is not easy to know if I have [CIDER](https://github.com/clojure-emacs/cider), a very useful Clojure tool for development, active for my current project, I need to run `cider-jack-in` and see if it responds with a message like `Already exists a session for this project`.

**Describe the solution you'd like**
Maybe have at modeline something similar to what we have with LSP:
![image](https://user-images.githubusercontent.com/7820865/83761079-354a2b80-a64c-11ea-9a1d-f6f2cc411337.png)
We could use an icon representing a REPL connected, and this could be useful for other languages in the future.

**Describe alternatives you've considered**

**Additional context**
If this makes sense I could help with the implementation.

**Comment by seagle0128** [comment]
![image](https://user-images.githubusercontent.com/7820865/83761079-354a2b80-a64c-11ea-9a1d-f6f2cc411337.png)

The icon is for LSP, like https://github.com/snoe/clojure-lsp, while not for CIDER, ROBE or something like that. I don't think it's common for other languages, but you can add it yourself. See  4 in https://github.com/seagle0128/doom-modeline#faq.

**Comment by ericdallo** [comment]
Yeah, I suggested doing something similar to the LSP icon.
I see... I thought that checking if CIDER is connected then showing an icon could be useful for more people, just like we show an icon for dap-mode while debugging.

**Comment by ericdallo** [comment]
Is it possible to inherit an already defined modeline? For example, define a `'custom-modeline` with `doom-modeline-def-modeline` inheriting the `'main` modeline?

**Comment by ericdallo** [comment]
We could use this "terminal" icon from `all-the-icons.el`  for example, for when the REPL is connected: 
![image](https://user-images.githubusercontent.com/7820865/83822995-12019980-a6a9-11ea-8ebb-4cafb8e2eae0.png)

I really think this is a good feature for emacs users showing when a REPL is connected, I don't mind in implementing that, I just need your "OK" :)

**Comment by seagle0128** [comment]
It's a good idea if it supports CIDER and other REPL. We'd better have a common segment like `REPL` segment to display the status of REPL in current buffer.

**Comment by ericdallo** [comment]
Agree, @seagle0128 do you mind I I Implement it as a REPL segment so?

**Comment by seagle0128** [comment]
Sure. PR is welcome. Please move forward.
