### ISSUE TITLE
doom-modeline color is wrong when has two Emacs frames on different screen

### ISSUE THREAD

**Issue by stardiviner** [seagle0128/doom-modeline#349]
**Describe**
doom-modeline color is wrong when has two Emacs frames on different screen

**Steps and Expected**
Open two Emacs frames, one on laptop screen, the other frame is on another display monitor screen.

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

**Environment:**
 - OS and version: Arch Linux
 - Emacs Version: `GNU Emacs 28.0.50`
 - Configuration: github.com/stardiviner/emacs.d
 - Package version: `20200530.700`

**Additional context**

![IMG_20200608_091909](https://user-images.githubusercontent.com/378699/83984762-3a1f2000-a969-11ea-924f-6f6db7462a63.jpg)

**Comment by seagle0128** [comment]
Oh, interesting. Will investigate.

**Comment by stardiviner** [comment]
Thanks

哦，哈哈哈，用来做淘宝店生意的。

**Comment by seagle0128** [comment]
Unfortunately I couldn't reproduce this issue.

**Comment by stardiviner** [comment]
I tried command `emacs -q --eval '(progn (package-initialize) (doom-modeline-mode))'` Can't reproduce this problem. I will investigate this problem deeper, thanks for testing.

**Comment by seagle0128** [comment]
Maybe it's related to your theme?

**Comment by stardiviner** [comment]
I tested with my theme `leuven` and without any theme, use default.
Here are two screencast:

链接: https://pan.baidu.com/s/115zkhcpONnN558U6Q_wZzg 提取码: sh2s

链接: https://pan.baidu.com/s/191Zy61yO31ojCYcM4bK4JA 提取码: 32km

**Comment by seagle0128** [comment]
我很好奇你的右边为什么多一块出来，而没有右对齐。是不是对mode-line的face或者字体进行过配置？

**Comment by stardiviner** [comment]
不是，还记得我上面的照片么？是两个屏幕 screen，但是是同一个虚拟桌面。 我录屏是用的 `simplescreenrecorder`, 它录制的是整个虚拟桌面，而我把第二屏幕设置了 旋转90度，所以才出现上面录屏中的样子。 在我的theme中确实对 mode-line face 做了设置。但是 默认theme里不应该也出现这个问题，这点很奇怪。我搜索了我的配置，也没有发现 mode-line 相关的 hook之类的设置。

**Comment by seagle0128** [comment]
我指的是modeline多出一块，正常的是右边的segment会右对齐，不会空余出来，唯一能解释的就是mode-line的字体或者face被修改了。你试试不修改mode-line face，看看有没有这个问题。

**Comment by stardiviner** [comment]
这个最右边的空白块应该是 doom-modeline 里面出来的，我 `disable-theme` 了, 应该和face没关系了，我查看了 `mode-line-format` 发现它的值如下，
```
Value: ("%e" (:eval (doom-modeline-format--main)))
Original value was 
("%e" mode-line-front-space mode-line-mule-info mode-line-client mode-line-modified mode-line-remote mode-line-frame-identification mode-line-buffer-identification "   " mode-line-position
 (vc-mode vc-mode)
 "  " mode-line-modes mode-line-misc-info mode-line-end-spaces)
Local in buffer Code.org; global value is 
("%e"
 (:eval
   (doom-modeline-format--main)))
```
我感觉有可能和 `mode-line-end-spaces` 有关. 但是我找不到 `doom-modeline-format--main` 函数的定义。

**Comment by stardiviner** [comment]
我下午试一下， `bug-hunter` bisect on my Emacs init files. 由于这个花时间，一直拖着。下午试一下。

**Comment by stardiviner** [comment]
终于花时间进行了以下 bug-hunter, 发现竟然是由于字体设置导致的，我贴以下我的字体设置init 文件。
```elisp
(let ((emacs-font-size 9)
      emacs-font-name)
  (cond
   ((or (eq system-type 'darwin) (featurep 'cocoa))
    (setq emacs-font-name "Monaco"))
   ((eq system-type 'gnu/linux)
    ;; "DejaVu Sans Mono", "Fira Code", "Hack", "Source Code Pro", "Noto Sans Mono", "Sarasa Gothic SC", "Sarasa Mono SC",
    ;; "Comic Neue", "Comic Sans MS", "FZSuXinShiLiuKaiS-R-GB", "sachacFonts"
    ;; "ETBembo", "ETBookOT", "Gabriola"
    (setq emacs-font-name "DejaVu Sans Mono")))
  (when (display-grayscale-p)
    ;; set default font
    (set-frame-font (format "%s-%s" (eval emacs-font-name) (eval emacs-font-size)))
    ;; set unicode font
    (set-fontset-font (frame-parameter nil 'font) 'unicode (eval emacs-font-name))))
```
当我 disable 这个init文件，Emacs没有这个问题。然后在Emacs成功启动完成后，我再次加载这个文件，没有出现这个问题。难道还和顺序有关系？

**Comment by stardiviner** [comment]
我又测试了以下我的字体配置，没想到和字体的size有关系。只有在 `DejvVu Sans Mono - 9` 这个size下才有这个问题。
我录制了一个视频。
链接: https://pan.baidu.com/s/1zX6bxOFhVguW_zICaWXy5A 提取码: ystx 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by stardiviner** [comment]
不用上面的 font init 设置的时候，我仅用如下设置
``elisp
(set-face-attribute 'default nil
                    :family "DejaVu Sans Mono"
                    :font "DejaVu Sans Mono"
                    :foundry "PfEd"
                    :height 90)
```
也会导致右边多出来空格的问题。猜测和字体高度变小导致的。

**Comment by seagle0128** [comment]
doom-modeline会按照字体size来计算宽度和显示位置。字体最好在doom-modeline加载之前设置好，否则字体来回变化可能导致计算失效，出现这个问题。

**Comment by stardiviner** [comment]
我试了下，关掉 doom-modeline，然后再打开，还是有这个现象，这个计算是在doom-modeline加载的时候一次性的么？能不能让他在 minor mode 里面启动的时候每次执行计算一次？

**Comment by stardiviner** [comment]
另外我的 font init文件加载确实是在  doom-modeline 的init文件加载之前的。

**Comment by seagle0128** [comment]
为了性能做了缓存处理，每次读取字体信息很慢的。

**Comment by stardiviner** [comment]
我可以在 Emacs 26.3 上重现，这是我Arch Linux系统里源安装的版本。

**Comment by seagle0128** [comment]
能看看这个变量`doom-modeline--font-width-cache`的值吗？

**Comment by seagle0128** [comment]
用`(set-face-attribute 'default nil :font "Monaco" :height 90))`.

**Comment by stardiviner** [comment]
> 能看看这个变量`doom-modeline--font-width-cache`的值吗？

Emacs `master` branch 和 Emacs 26.3 版本 的结果都是一样的。
```elisp
((((:family . unspecified)
   (:foundry . unspecified)
   (:width . unspecified)
   (:height . unspecified)
   (:weight . unspecified)
   (:slant . unspecified)
   (:underline . unspecified)
   (:overline . unspecified)
   (:strike-through . unspecified)
   (:box . unspecified)
   (:inverse-video . unspecified)
   (:foreground . unspecified)
   (:background . unspecified)
   (:stipple . unspecified)
   (:inherit . unspecified))
  . 19))
```

**Comment by stardiviner** [comment]
Anyway, 这个问题太难找了，代价太大，还是丢弃了。毕竟只是一个小问题。

**Comment by zane** [comment]
I'm also having this issue. Did you ever identify a workaround?

**Comment by zane** [comment]
Still occurs after `(set-face-attribute 'default nil :font "Monaco" :height 90)`. My `doom-modeline--font-width-cache`:

```emacs-lisp
((((:family . unspecified)
   (:foundry . unspecified)
   (:width . unspecified)
   (:height . unspecified)
   (:weight . unspecified)
   (:slant . unspecified)
   (:underline . unspecified)
   (:overline . unspecified)
   (:extend . unspecified)
   (:strike-through . unspecified)
   (:box . unspecified)
   (:inverse-video . unspecified)
   (:foreground . unspecified)
   (:background . unspecified)
   (:stipple . unspecified)
   (:inherit . unspecified))
  . 8))
```

**Comment by zane** [comment]
Other observations:
* The problem only occurs after:
  * A [projectile](https://github.com/bbatsov/projectile) project has been activated.
  * I have switched between two windows _using the keyboard_.
* The problem will occur, but will not persist _if the switching happens using the mouse_. 🤯 
  * The problem is present if the mouse is held down, but disappears when the mouse is released. 
  * The problem can be fixed by clicking in a window (presumably because it triggers a mouse-down followed by a mouse-up). I thought that this might be due to the fact that clicking triggers the `selection-info` segment to appear, but selecting a region with the keyboard does not alleviate the issue. 🤔 
* The problem can be alleviated by invoking `M-x` and then cancelling it with `C-g`. 🤔

**Comment by zane** [comment]
My system information:

**OS**: 10.15.7
**Emacs**: GNU Emacs 27.1 ([emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus))
**Distribution**: [Spacemacs](https://www.spacemacs.org/) ([develop](https://github.com/syl20bnr/spacemacs/tree/develop))

**Comment by zane** [comment]
The offending segment appears to be `persp-info`.
