### ISSUE TITLE
The modeline interval color of the inactive window is wired.

### ISSUE THREAD

**Issue by tshu-w** [seagle0128/doom-modeline#352]
**Describe**
The modeline interval color of the inactive window is wired.

**Steps and Expected**
- open emacs
- split-window-below(C-x 2)
- check the color of the inactive window
<img width="958" alt="Screen Shot 2020-06-12 at 3 28 19 PM" src="https://user-images.githubusercontent.com/13161779/84477524-4df8b800-acc2-11ea-9bf1-111201bb3bd6.png">

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.
```
;;; emacs -nw -Q -l test.el

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;; setup `use-package'
(unless (package-installed-p 'use-package)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (package-install 'use-package))

(eval-when-compile
  (setq use-package-always-defer  t
        use-package-expand-minimally t)
  (if init-file-debug
      (setq use-package-verbose t
            use-package-minimum-reported-time 0
            use-package-expand-minimally nil
            use-package-compute-statistics t
            use-package-inject-hooks t
            debug-on-error t))

  (require 'use-package))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-package doom-themes
  :ensure t
  :init (load-theme 'doom-one-light t))

(use-package doom-modeline
  :ensure t
  :hook (emacs-startup . doom-modeline-mode))
```

**Environment:**
 - OS and version: macOS 10.15
 - Emacs Version: 26.3
 - Configuration: 
 - Package version: 20200610.1447

**Additional context**
 Screenshots, recordings, logs and messages...
<img width="958" alt="Screen Shot 2020-06-12 at 3 28 19 PM" src="https://user-images.githubusercontent.com/13161779/84477304-fd815a80-acc1-11ea-9aad-53a1550a16b5.png">
<img width="609" alt="Screen Shot 2020-06-12 at 3 11 33 PM" src="https://user-images.githubusercontent.com/13161779/84477313-0114e180-acc2-11ea-838b-a81d67bc12f1.png">

**Comment by seagle0128** [comment]
This is a regression issue introduced by c90ae9d.
