### ISSUE TITLE
Wrong width when run on emacsclient and strange artifacts

### ISSUE THREAD

**Issue by Dr-Dd** [seagle0128/doom-modeline#354]
**Describe**
When opening a emacsclient instance, the bar has the wrong width in relation to frame size, and strange lines started appearing since the last update.

The wrong width bug was present even before this update, but the lines just showed up.

If i open emacs normally (without connecting to the daemon), then the width problem vanishes, but not the lines

This is my use-package snippet

````elisp
(use-package doom-modeline
  :ensure t
  :after (all-the-icons)
  :init
  (custom-set-faces
   '(mode-line ((t (:family "xos4 Terminus" :height 0.7 :box nil :weight bold))))
   '(mode-line-inactive ((t (:family "xos4 Terminus" :height 0.7 :box nil :weight bold)))))
  (setq doom-modeline-height 25)
  (setq doom-modeline-icon t)
  (doom-modeline-mode 1))
````
**Steps to reproduce**

- Start emacs daemon as a systemd user unit
- Load an emacsclient frame with `emacsclient -c -a "emacs"`

**Environment**
 - OS and version: [Arch Linux 5.7.4]
 - Emacs Version: [28.0.50 (GTK+)]
 - Configuration: [[config](https://github.com/Dr-Dd/.emacs.d)]
 - Package version: [20200618.1712]

**Additional Context**
The files related to this bug may be the [modeline](https://github.com/Dr-Dd/.emacs.d/blob/master/lisp/init-gui.el) one, and the one i use to initialize generic [gui](https://github.com/Dr-Dd/.emacs.d/blob/master/lisp/init-doom-modeline.el) elements

![pic1](https://i.imgur.com/rCk1Qqt.png)

![pic2](https://i.imgur.com/aYborlT.png)

I think it might be a regression related to #303 

**EDIT:** Added steps and some more info

**Comment by seagle0128** [comment]
Can you check the value of `doom-modeline--font-width-cache`? Then eval `doom-modeline-refresh-font-width-cache`. Check `doom-modeline--font-width-cache` again.

**Comment by Dr-Dd** [comment]
This is the value of `doom-modeline--font-width-cache` before refreshing it

````elisp
((((:family . unspecified)
   (:foundry . unspecified)
   (:width . unspecified)
   (:height . unspecified)
   (:weight . unspecified)
   (:slant . unspecified)
   (:underline . unspecified)
   (:overline . unspecified)
   (:extend . unspecified)
   (:strike-through . unspecified)
   (:box . unspecified)
   (:inverse-video . unspecified)
   (:foreground . unspecified)
   (:background . unspecified)
   (:stipple . unspecified)
   (:inherit . unspecified))
  . 1))
````

This is after evaluating `doom-modeline-refresh-font-width-cache`

````elisp
((((:family . unspecified)
   (:foundry . unspecified)
   (:width . unspecified)
   (:height . unspecified)
   (:weight . unspecified)
   (:slant . unspecified)
   (:underline . unspecified)
   (:overline . unspecified)
   (:extend . unspecified)
   (:strike-through . unspecified)
   (:box . unspecified)
   (:inverse-video . unspecified)
   (:foreground . unspecified)
   (:background . unspecified)
   (:stipple . unspecified)
   (:inherit . unspecified))
  . 10))
````

Only the bottom int gets changed to `10`

**Comment by Dr-Dd** [comment]
I've opened a pull request for the bug fix. As it turns out, `window-width` defaults to the correct width when using the emacsclient, while `window-font-width` works when using a standalone emacs instance, the problem is i'm not really sure why, but it works as inteded. 

#356

**Comment by seagle0128** [comment]
Please try this snippet: `(add-hook 'server-after-make-frame-hook #'doom-modeline-refresh-font-width-cache)`.

**Comment by Dr-Dd** [comment]
Works flawlessly, good stuff!
 
Should i modify this pull request, close it and open another one or you'll add the fix in the next commit?

**Comment by seagle0128** [comment]
No. I will commit and close that PR. One comment, this hook is introduced in 27.1.
