### ISSUE TITLE
Question concerning the Icons in daemon mode 

### ISSUE THREAD

**Issue by m0ll3art** [seagle0128/doom-modeline#357]
**Describe**
when using `emacsclient -c`   icons are not shown in the modeline. When using `emacs` icons are displayed. see the two screenshots. I'm using Emacs@28 and I know may be the issue and I will ry to check emacs@[26,27]
 
*Steps and Expected**
- at command line `$ emacs`  -> icons are shown 
- 1. `$ emacs --fg-daemon`
- 2. `$ emacsclient -c`   -> icons not shown 

**Environment:**
 - OS and version: macOs Catalina
 - Emacs Version: 28.0.50
 - Configuration: own config 
 - Package version: latest 

**Additional context**
perhaps useful as information, but the same setup with spaceline seems to be ok, the icons are shown also when Emacs is started in daemon mode.  That's why I suppose it may be related to a config issue. I followed your setup 

 Screenshots : 
**Emacs modline without icons**
![Emacs-NoIcons](https://user-images.githubusercontent.com/11415120/85590017-5cd95600-b644-11ea-801b-72437db9f065.png)

**Emacs modline with icons** 
![Emacs-WithIcons](https://user-images.githubusercontent.com/11415120/85590026-5f3bb000-b644-11ea-9569-68916942fef3.png)

**Comment by seagle0128** [comment]
See `doom-modeline-icon`.

**Comment by m0ll3art** [comment]
I further investigated the issue and when using Emacs in Server mode (using server package) I can connect to running instance and icons are preserved, i.e. are shown in the newly opened Emacs

**Comment by m0ll3art** [comment]
> I further investigated the issue and when using Emacs in Server mode (using server package) I can connect to running instance and icons are preserved, i.e. are shown in the newly opened Emacs

I already did and was looking for possible values, sorry not an emacs expert.. could you provide more insight, please

**Comment by m0ll3art** [comment]
> See `doom-modeline-icon`.


I already did and was looking for possible values, sorry not an emacs expert.. could you provide more insight, please

**Comment by m0ll3art** [comment]
> > See `doom-modeline-icon`.
> 
> I already did and was looking for possible values, sorry not an emacs expert.. could you provide more insight, please

ok setting `doom-modeline-icon t` does the job.. but is this a minimal solution?

**Comment by seagle0128** [comment]
Yes. `(setq doom-modeline-icon t)` is the solution.
