### ISSUE TITLE
Modeline is not correctly activated upon changing workspace in EXWM

### ISSUE THREAD

**Issue by Sbozzolo** [seagle0128/doom-modeline#358]
`doom-modeline` doesn't always follow the cursor across EXWM workspaces so the modeline remains gray-out most of the times.

**Steps and Expected**
I am working with Doom Emacs with a `config.el` that only contains `(enable-exwm)`. Create a new workspace: `exwm-workspace-add`, switch to that workspace `exwm-workspace-switch`, switch back to the first workspace. The modeline will be gray as if the buffer was not the active one.

I tried adding `doom-modeline-set-selected-window` to `exwm-workspace-switch-hook`, but it didn't solve the problem.

**Environment:**
 - OS and version: Gentoo Linux 
 - Emacs Version: 27.0.91
 - Configuration: Doom Emacs
 - Package version: commit 2b30885

**Additional context**
![2020-06-26:12:24:07](https://user-images.githubusercontent.com/9167485/85893583-f9683900-b7a7-11ea-98d0-292a734f3086.png)

**Comment by seagle0128** [comment]
Can you  try vanilla Emacs?

**Comment by Sbozzolo** [comment]
Yes, the bug is there with vanilla Emacs. Same steps as above.

**Comment by seagle0128** [comment]
I am not using exwm, so I need more time to investigate. And I am curious why `exwm-workspace-switch-hook` doesn't work here.

**Comment by Sbozzolo** [comment]
As a temporary workaround, it is possible to have the modeline always activated?

**Comment by seagle0128** [comment]
> As a temporary workaround, it is possible to have the modeline always activated?
```elisp
(defun doom-modeline--active ()
  t)
```

**Comment by MorganJamesSmith** [comment]
I had the exact same problem but adding  ```(add-hook 'exwm-workspace-switch-hook #'doom-modeline-set-selected-window)``` to my config fixed it.

emacs-exwm	0.24	
emacs-doom-modeline	2.8.2
emacs	27.0.91    c36c5a3

**Comment by MorganJamesSmith** [comment]
Update: I realized 2.8.2 is actually pretty out of date so I updated to doom modeline 3.0.0 and now the hook thing doesn't work anymore.

**Comment by seagle0128** [comment]
> Update: I realized 2.8.2 is actually pretty out of date so I updated to doom modeline 3.0.0 and now the hook thing doesn't work anymore.

Can you evaluate `(doom-modeline-set-selected-window)` in the buffer?

**Comment by MorganJamesSmith** [comment]
So I added this code to my config and now everything is wonderful. Why did you remove ```(force-mode-line-update)``` from the end of ```doom-modeline-set-selected-window``` sometime between 2.8.2 and 3.0.0? It seems to be important

```
  (require 'doom-modeline-core)
  (advice-add #'doom-modeline-set-selected-window :after #'force-mode-line-update)
  (add-hook 'exwm-workspace-switch-hook #'doom-modeline-set-selected-window)
```

**Comment by MorganJamesSmith** [comment]
Update: things just work today, and I'm sure why. Booting a fresh Emacs with this config does NOT have this bug, but if I remove the add-hook line, the bug reappears. I know this is contradictory to what I said yesterday, but I'm not sure what changed. The advice from my previous post doesn't hurt, but it doesn't look like it's needed.

```
(require 'doom-modeline)
(doom-modeline-mode 1)


(require 'exwm)
(setq exwm-input-global-keys
   `(([?\s-1] . ,(lambda () (interactive) (exwm-workspace-switch-create 0)))
     ([?\s-2] . ,(lambda () (interactive) (exwm-workspace-switch-create 1)))))
(add-hook 'exwm-workspace-switch-hook #'doom-modeline-set-selected-window)
(exwm-enable)
```

**Comment by Sbozzolo** [comment]
I tested with fresh Emacs and found that the new version works. However, on Doom Emacs (updated to ffbaaee) and the problem is not solved completely: I have to "switch twice" to the workspace to have the modeling selected. If I switch only one:
```
(doom-modeline-set-selected-window) -> #<window 3 on (Chromium) Modeline is not correctly act...>
```
Same with the other function. This is the buffer I am seeing, but the modeline is greyed out.  if I press `s-0` again, the modeline gets correctly colored. 

@MorganJamesSmith does ffbaaee work for you in Doom Emacs?

**Comment by seagle0128** [comment]
@Sbozzolo do you mean it works with Vanilla Emacs? I guess some hooks in doom-emacs change the behaviors.

**Comment by Sbozzolo** [comment]
Yes, with Emacs 27.1 with the latest versions of all the packages from MELPA. Emacs -Q started with
```
     --eval "(require 'doom-modeline)" \
     --eval "(doom-modeline-mode 1)" \
     --eval "(require 'exwm)" \
     --eval "(require 'exwm-config)" \
     --eval "(exwm-config-default)" \
     --eval "(add-hook 'exwm-workspace-switch-hook #'doom-modeline-set-selected-window)" \
     --eval "(exwm-enable)";
```

**Comment by seagle0128** [comment]
so pls inquiry to the author of doom-emacs.

**Comment by SebastienWae** [comment]
@seagle0128 @Sbozzolo 
I have the same issue with vanilla emacs when using `display-battery-mode`

**Comment by seagle0128** [comment]
> @seagle0128 @Sbozzolo
> I have the same issue with vanilla emacs when using `display-battery-mode`
> 
> —-
> Edit:
> Actually it seems to be related to `all-the-icons`, if I disable the icons I can use `display-battery-mode`

Same issue? This issue is related to EXWM. This is totally different IMO. What I am missing?

**Comment by SebastienWae** [comment]
> > @seagle0128 @Sbozzolo
> > I have the same issue with vanilla emacs when using `display-battery-mode`
> > —-
> > Edit:
> > Actually it seems to be related to `all-the-icons`, if I disable the icons I can use `display-battery-mode`
> 
> Same issue? This issue is related to EXWM. This is totally different IMO. What I am missing?
> I didn't get your point. What's the problem exactly?

With EXWM if `(setq doom-modeline-icon t)` then when I switch to a workspace the mod line will not activate.

**Comment by seagle0128** [comment]
> With EXWM if `(setq doom-modeline-icon t)` then when I switch to a workspace the modeline will not activate.

Oh, it's clear to me. But I have no idea why icon will impact the window activation.

**Comment by SebastienWae** [comment]
> > With EXWM if `(setq doom-modeline-icon t)` then when I switch to a workspace the modeline will not activate.
> 
> Oh, it's clear to me. But I have no idea why icon will impact the window activation.

Me neither but it explains why the issue is present on Doom emacs, which has `all-the-icons` enabled by default and not on vanilla emacs (as long as you don't install `all-the-icons`.
