### ISSUE TITLE
Just installed it and ... (void-function eldoc-in-minibuffer-mode)

### ISSUE THREAD

**Issue by j3kyl** [seagle0128/doom-modeline#36]
Hey, 

Requiring doom-modeline gives me these errors:

**(require 'doom-modeline)**

```
Debugger entered--Lisp error: (void-function eldoc-in-minibuffer-mode)
  eldoc-in-minibuffer-mode(1)
  byte-code("\301\020\302\303!\207" [eldoc-in-minibuffer-show-fn doom-modeline--show-eldoc eldoc-in-minibuffer-mode 1] 2)
  require(doom-modeline)
  eval((require 'doom-modeline) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  #<subr call-interactively>(eval-last-sexp nil nil)
  apply(#<subr call-interactively> eval-last-sexp (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eval-last-sexp nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eval-last-sexp nil nil))
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
---------------------
I did some investigation:
There is no such a function **eldoc-in-minibuffer-mode**  in `eldoc-eval.el`  because the downloaded eval file is an older version of it! 

Even though it is marked to download 0.1 version of eldoc-eval! 

**gist with the downloaded eldoc-eval file**: https://gist.github.com/j3kyl/9374851dfb7a59610648a0d2b19f62a4

Emacs 26.1
Fedora

**Comment by seagle0128** [comment]
Please use MELPA to install the package and the decencies. Or download the latest version from https://github.com/thierryvolpiatto/eldoc-eval. The manual installation is not recommended.
