### ISSUE TITLE
doom-modeline--debug-dap should show the name of the session instead of an icon

### ISSUE THREAD

**Issue by shackra** [seagle0128/doom-modeline#360]
**Describe**
currently, the segment `doom-modeline--debug-dap` shows the name of the session in the echo area upon being hovered, however this is not optimal for newcomers to dap-mode using doom-modeline (see https://github.com/emacs-lsp/dap-mode/issues/305 )

**Steps and Expected**
having doom-modeline activated, start a debugging session with dap-mode and then open another project and start a new debugging session there, the segment will still show an icon.

**Environment:**
- happens regardless of environment

**Additional context**
None.

**Comment by seagle0128** [comment]
Why? The session details are displayed in tooltip while moving the mouse on the icon.

**Comment by shackra** [comment]
if you work debugging multiple services that need each other this feature
becomes a hassle as you need to hover the icon in order to know which
session are you sending debugging commands

**Comment by seagle0128** [comment]
The solutions are below.
1. `(setq doom-modeline-minor-modes t)`.
1. `(add-to-list 'global-mode-string '((:eval (dap-mode-line))))`.
1. Customize mode-line with `doom-modeline-def-modeline`.

Refer to https://github.com/seagle0128/doom-modeline#faq (5).
