### ISSUE TITLE
declare the proper type for doom-modeline-continuous-word-count-modes

### ISSUE THREAD

**Issue by enikar** [seagle0128/doom-modeline#361]
Hi,
in doom-modeline-core.el, the defintion of this variable should be
```
(defcustom doom-modeline-continuous-word-count-modes
  '(markdown-mode gfm-mode org-mode)
  "Major modes in which to display word count continuously.

It respects `doom-modeline-enable-word-count'."
  :type 'sexp
  :group 'doom-modeline)
```

Notice the `:type 'sexp`. 'list doesn't work this way (see elisp(Customization/Customization Types) in info manual).
Else in the Customization buffer this variable is in mismatch state.

**Steps and Expected**
Just load the package, and go to Cutomization group doom-modeline, then
select the variable `doom-modeline-continuous-word-count-modes`.

**Environment:**
 - OS and version: Linux 5.7
 - Emacs Version: 26.3 and 27.0.91 (vanilla emacs, no spacemacs and no doom)
 - Configuration:  https://gist.github.com/enikar/4744fbd21c895310aedcb27866cf032e
 - Package version: 20200701.1717

**Comment by seagle0128** [comment]
What's the problem here? `'list` is used in many packages. The functionality works as expected.

**Comment by enikar** [comment]
The problem is that confuses the emacs customization system (I known, not
everybody use it, but sometimes it's still handy).

And the fact that many packages use `:type 'list` as in doom-modeline, don't
prove that is the proper way to use it. The correct type for the variable is
`'sexp`.

The functionnality provides by the variable works, but not in customize.
And the elisp info manual says:
For `'list`
> ‘(list ELEMENT-TYPES...)’
>     The value must be a list with exactly as many elements as the
>     ELEMENT-TYPES given; and each element must fit the corresponding
>    ELEMENT-TYPE.
>
>    For example, ‘(list integer string function)’ describes a list of
>     three elements; the first element must be an integer, the second a
>     string, and the third a function.
>
>   In the customization buffer, each element is displayed and edited
>     separately, according to the type specified for it.

For `'sexp`
> ‘sexp’
>      The value may be any Lisp object that can be printed and read back.
>      You can use ‘sexp’ as a fall-back for any option, if you don’t want
>      to take the time to work out a more specific type to use.

The name of the type `'list` is misleading to a bad use, imho.

**Comment by seagle0128** [comment]
I don't think `sexp` is a proper type here. Fixed it anyway.

**Comment by enikar** [comment]
Indeed, it's not the better solution, just the lazy one. Your change is right way to do it.
Thanks for your nice job.
