### ISSUE TITLE
Display-time-mode on inactive modelines

### ISSUE THREAD

**Issue by dasistkeintest** [seagle0128/doom-modeline#363]
**Describe**
When using display-time-mode, the time is only shown on the modeline of the active window. I would expect it to be displayed on all modelines. This is the behaviour of the default modeline. 

**Environment:**
 - OS and version: Ubuntu 20.04 via WSL
 - Emacs Version: 26.3
 - Configuration: none
 - Package version: 20200704.1056

**Comment by seagle0128** [comment]
```elisp
(doom-modeline-def-segment misc-info
  "Mode line construct for miscellaneous information.
By default, this shows the information specified by `global-mode-string'."
      '("" mode-line-misc-info))
```
