### ISSUE TITLE
How to properly init doom-modeline?

### ISSUE THREAD

**Issue by pRot0ta1p** [seagle0128/doom-modeline#364]
I'm using use-package and put all codes under the :init section, but when I launch emacs say, 
from terminal, the custom modeline won't apply except I manually call the function setup-custom-modeline AND create 
a new buffer.

If I hook the custom modeline function setup-custom-modeline  to emacs-startup-hook, then it will work, so is it necessary to hook the funtion to both doom-modeline-mode-hook and emacs-startup-hook?

my config:
```emacs-lisp
(use-package doom-modeline
  :straight t
  :init
  (doom-modeline-mode 1)
  (doom-modeline-def-modeline 'myline
	'(workspace-name buffer-info major-mode pdf-pages vcs remote-host selection-info matches)
	'(misc-info buffer-size media-info buffer-position buffer-encoding checker))

  (defun setup-custom-modeline ()
	(interactive)
	(doom-modeline-set-modeline 'myline 'default))

  (add-hook 'doom-modeline-mode-hook 'setup-custom-modeline)

  (setq doom-modeline-height 20
		doom-modeline-bar-width 10
		doom-modeline-project-detection 'project
		doom-modeline-buffer-file-name-style 'truncate-all
		doom-modeline-icon t
		doom-modeline-major-mode-icon nil
		doom-modeline-major-mode-color-icon nil
		doom-modeline-percent-position '(-3 "%p")
		doom-modeline-buffer-state-icon t
		doom-modeline-buffer-modification-icon t
		doom-modeline-unicode-fallback nil
		doom-modeline-minor-modes nil
		doom-modeline-enable-word-count nil
		doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode)
		doom-modeline-buffer-encoding t
		doom-modeline-checker-simple-format nil
		doom-modeline-number-limit 99
		doom-modeline-vcs-max-length 12
		doom-modeline-persp-name t
		doom-modeline-display-default-persp-name nil
		doom-modeline-lsp t
		doom-modeline-modal-icon nil
		doom-modeline-mu4e nil
		doom-modeline-env-version t
		doom-modeline-env-python-executable "python" ; or `python-shell-interpreter'
		doom-modeline-env-ruby-executable "ruby"
		doom-modeline-env-perl-executable "perl"
		doom-modeline-env-go-executable "go"
		doom-modeline-env-elixir-executable "iex"
		doom-modeline-env-rust-executable "rustc"
		doom-modeline-env-load-string "..."
		doom-modeline-before-update-env-hook nil
		doom-modeline-after-update-env-hook nil))
```

**Comment by seagle0128** [comment]
Enable doom-modeline-mode after the hook.

**Comment by agzam** [comment]
I confirm, it doesn't work for me either. There's something strange going on. I can't seem to be able to set up a custom modeline, it only applies if I manually call or eval (doom-modeline-mode). I can't find a way to set it up automatically, it *always* ignores the custom mode-line setup and uses the default.

**Comment by seagle0128** [comment]
@agzam Enable `doom-modeline-mode` after customizing mode-line.

**Comment by agzam** [comment]
I get it. It still doesn't work. I'm not sure what's so messed up in my config, but I think I finally solved it by using a different hook:

```emacs-lisp
(use-package doom-modeline
    :defer t
    :init
    (doom-modeline-mode 1)
    (doom-modeline-def-modeline
      'agcustom
      '(window-number workspace-name persp-name matches word-count parrot selection-info buffer-info)
      '(objed-state misc-info battery grip irc mu4e debug repl lsp major-mode process checker buffer-position))

    (defun setup-custom-doom-modeline ()
      (doom-modeline-set-modeline 'agcustom))

    (add-hook 'find-file-hook 'setup-custom-doom-modeline 90))
  ```

**Comment by pRot0ta1p** [comment]
@agzam 
> I get it. It still doesn't work. It doesn't matter if you call it before or after. It only works if you open a file, and then set the mode.
> I'm not sure what's so messed up in my config, but I think I finally solved it by using a different hook:

I think the deal here is that you cant use emacs background daemon, which was my setup back then, which also explained why the modeline on scratch buffer is not displayed correctly but new buffer have correct modeline.

I suggest try foreground  daemon `M-x server-start`.

It has been too long and I actually dont use modeline anymore (now I use awesome-tray), but hope this help.

**Comment by seagle0128** [comment]
@agzam Try this?

```elisp
(use-package doom-modeline
  :defer t
  :hook (after-init . doom-modeline-mode)
  :init
  (doom-modeline-def-modeline
    'agcustom
    '(window-number workspace-name persp-name matches word-count parrot selection-info buffer-info)
    '(objed-state misc-info battery grip irc mu4e debug repl lsp major-mode process checker buffer-position))
  (doom-modeline-set-modeline 'agcustom t))
```

**Comment by agzam** [comment]
@seagle0128 no Vincent, that didn't work. It only works for me when I have both hooks:

    (add-hook 'doom-modeline-mode-hook 'setup-custom-doom-modeline 90)
    (add-hook 'find-file-hook 'setup-custom-doom-modeline 90)

At some point maybe I'll try to repro it on a clean config. I sense that Spacemacs still interfering - even after removing the related bloat, switching to `spacemacs-base` distribution, and removing `spacemacs-modeline` layer (which includes doom-modeline initialization).

I am still not sure what's causing it (I hate it, when I have no clues). And per @pRot0ta1p 's suggestion - I am indeed using the foreground daemon. I'm glad, it now seems to be working for me. Sorry for seeming angry tone earlier, perhaps I should've used more elucidated language to describe my problem.
