### ISSUE TITLE
display `isearch` counts

### ISSUE THREAD

**Issue by bgwines** [seagle0128/doom-modeline#365]
**Is your feature request related to a problem? Please describe.**
When searching with `isearch-forward` or `isearch-backward` (commonly `C-s` and `C-r`, respectively), I don't know how many occurrences there are in the buffer, nor do I know which one I am on (i.e. the *i*th out of *n* total).

**Describe the solution you'd like**
I think it'd be just swell to have a user-configurable variable to display this info in the modeline, in a concise manner that doesn't take up much horizontal space (e.g. a simple *i/n*). Thanks so much! 🙌 

**Describe alternatives you've considered**
(none)

**Additional context**
I'd be happy to make the change myself and issue a PR if you can point me in the right direction, if you approve of the idea :)

**Comment by seagle0128** [comment]
Is this what you want?

![image](https://user-images.githubusercontent.com/140797/87566280-5dba5080-c6f5-11ea-9f71-22c882822624.png)

**Comment by bgwines** [comment]
ah; that's perfect. Thanks so much; I didn't know about those and assumed it wouldn't be provided by a package other than this one. Closing :)
