### ISSUE TITLE
Integration with dired-narrow

### ISSUE THREAD

**Issue by condy0919** [seagle0128/doom-modeline#368]
[`dired-narrow`] indicator like `narrow-to-defun` does but in `dired-mode`.

[`dired-narrow`]: https://github.com/Fuco1/dired-hacks/blob/master/dired-narrow.el

**Comment by seagle0128** [comment]
Honestly I didn't test with `dired-hacks`.  Please try the latest version.

**Comment by condy0919** [comment]
Version: doom-modeline-20200722.714

![image](https://user-images.githubusercontent.com/4024656/88206578-1269ea00-cc81-11ea-99f2-574d01bce8b1.png)

``` emacs-lisp
(bound-and-true-p dired-narrow-mode)
```

returns `t` in `dired-mode`.

No indicator in modeline :'(

**Comment by seagle0128** [comment]
Now it should be.

**Comment by condy0919** [comment]
Thanks, it works
