### ISSUE TITLE
doom-modeline-segment--lsp signaled wrong-type-argument

### ISSUE THREAD

**Issue by zoechi** [seagle0128/doom-modeline#369]
**Describe**
Since 2 days I get lots of such messages

```
Invalid face attribute :family nil
Invalid face attribute :height nil
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
```

**Steps and Expected**
Not sure yet how to track this down.
I hoped to get some hints what to look for before I start disabling all packages and re-enabling one-by-one.

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

**Environment:**
 - OS and version: Debian Buster
 - Emacs Version: 28.0.50
 - Configuration: plain/custom
 - Package version: commit d7f187efc6ae965e7a01902754dee3a4557110ff

**Additional context**
 Screenshots, recordings, logs and messages...

**Comment by seagle0128** [comment]
`doom-modeline-lsp-success` is a face. It seems the package is incomplete in your env. Please reinstall.

**Comment by zoechi** [comment]
I deleted all installed packages and reinstalled them (first I tried reinstalling doom-modeline individually)
but this didn't change anything.

**Comment by seagle0128** [comment]
Please use `emacs -Q` to reproduce.

**Comment by zoechi** [comment]
I'll have a closer look the next day, I have some work to get done.
I have no functions redefined. Only the package loaded without any additional config except the icon disabled.

**Comment by j0ni** [comment]
I can confirm this, in a freshly build master emacs, also using straight.el.

Nothing redefined, but I see a lot of this in *Messages*:

```
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
```
Like @zoechi I gotta get back to work, so I'm going to try switching to a "stable" emacs for a while.

**Comment by seagle0128** [comment]
I don't see any error on GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73)). Any other details?

**Comment by ocelaiwo** [comment]
I'm on GNU Emacs 28.0.91 and have the following configuration of doom-modeline:
```(use-package doom-modeline
  :config
  (setq doom-modeline-icon nil)
  (setq doom-modeline-enable-word-count t)
  (setq doom-modeline-height 1)
  (setq doom-modeline-checker-simple-format nil)
  (set-face-attribute 'mode-line nil :height 100)
  (set-face-attribute 'mode-line-inactive nil :height 100)
  (doom-modeline-mode 1))
```

I also experience those messages, I loaded Emacs, opened up a C++ project and waited for a while, after which I got the following:
```Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--lsp)) signaled (wrong-type-argument plistp doom-modeline-lsp-success)
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (wrong-type-argument plistp doom-modeline-info)
Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)
Invalid face attribute :family nil
Invalid face attribute :height nil
Invalid face attribute :family nil
Invalid face attribute :height nil
Invalid face attribute :family nil
Invalid face attribute :height nil
```

I can't pinpoint the reason for those, but a pair of `Invalid face attribute` messages pops up every time I switch focus to a different program. Also, a weird indicator appeared on the modeline (yellow number 3 on the very left):
![image](https://user-images.githubusercontent.com/57271510/88933002-41dbb080-d298-11ea-9e75-b89d9b903697.png)
This number seems to display the total amount of flycheck warnings in all opened buffers (but I already have per-buffer flycheck statistics on the right):
![image](https://user-images.githubusercontent.com/57271510/88933255-9a12b280-d298-11ea-8875-5a6978452f38.png)

**Comment by seagle0128** [comment]
@ocelaiwo what OS and version? And are you sure you are using GNU Emacs 28.0.91?

>This number seems to display the total amount of flycheck warnings in all opened buffers (but I already have per-buffer flycheck statistics on the right):

The left numbers are displayed by lsp-mode.

**Comment by seagle0128** [comment]
I think I found the root course. It's introduced by 1f3956f. Fixing it
