### ISSUE TITLE
performance issues in Windows

### ISSUE THREAD

**Issue by willbush** [seagle0128/doom-modeline#37]
Hello, I'm having crushing performance issues in Windows 10 with doom-modeline enabled. However, I also use it in Linux without any issues.

Took me a while to track down the issue because I had my `gc-cons-threshold` turned up higher than the default. I had changed some things in [my config](https://github.com/willbush/system/blob/master/emacs/.emacs) and thought something I added was giving me intense lag, but it turned out to be me setting the `gc-cons-threshold` back to the default, which exposed I had a different issue going on. Then I had to painstakingly comment out packages until I found what was causing it.

The issue is when I open a file and perform any movements Emacs will slow to the point of becoming unresponsive at times. Curiously, I don't have an issue in the Emacs Tutorial.

In Windows, my version of emacs was installed using MSYS2 as described [here](https://www.gnu.org/software/emacs/download.html#windows)

```
This is GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)
 of 2018-05-30
```

A minimal Emacs config file can be used to verify the issue:

```elisp
(require 'package)

(setq package-enable-at-startup nil)

(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(package-initialize)

(require 'doom-modeline)
(doom-modeline-init)
```

Here is a gif demonstrating the issue with the above minimal config. In the gif I'm holding down `C-n` to move down and `C-p` to move up. It's hard to see from this just how unresponsive it is to my pressing of the keys, but you can see it jumping around.

![doom-modeline-lag](https://user-images.githubusercontent.com/2023546/47893565-81f3d200-de2b-11e8-9af6-b82e5a966100.gif)

**Comment by seagle0128** [comment]
Thanks for the detailed report!
I believe this issue is related to garbage collection (gc-cons-threshold). I enabled `all-the-icons` on Windows recently, but unfortunately the default value of fonts bring the performance issue. Please add this configuration to address it. I will add it to readme as well.

```elisp
(setq inhibit-compacting-font-caches t) ; Don’t compact font caches during GC.
```
BTW: don't set `gc-cons-threshold` too large.

**Comment by willbush** [comment]
Thanks! I can verify that adding that setting works.

**Comment by seagle0128** [comment]
Welcome! Glad to know it works. 
Already updated README.
