### ISSUE TITLE
Total number of flycheck errors started showing up on the modline

### ISSUE THREAD

**Issue by hisnawi** [seagle0128/doom-modeline#372]
After a recent update to the doom-modeline I started seeing the total number of errors across all visited files started showing up. I didn't change anything in the configuration and not sure the reason for this.
I already have the checker errors/warnings at the far right side but not sure why this total number started showing up and not sure how to get rid of it.

![image](https://user-images.githubusercontent.com/8878871/91897323-f2015800-ec4e-11ea-8caa-c384fb053820.png)

**Comment by hisnawi** [comment]
@seagle0128 Do you know how do I disable the flycheck left indicator in doom-modeline? Why am I seeing two of them?
The on the left is the tally of all errors and the one on the right is for the errors in the current file.

**Comment by seagle0128** [comment]
It's displayed by lsp-mode.
```elisp
(setq lsp-modeline-code-actions-enable nil
          lsp-modeline-diagnostics-enable nil)
```

**Comment by hisnawi** [comment]
Thank you. That worked.
