### ISSUE TITLE
doom-modeline breaks which-func mouse-2 "toggle rest visibility" on Linux emacs 27.1 under Gnome using sloppy mouse focus

### ISSUE THREAD

**Issue by bk138** [seagle0128/doom-modeline#373]
**Describe**
doom-modeline breaks which-func mouse-2 "toggle rest visibility on emacs 27.1

**Steps and Expected**
* start emacs with this config:

```
;;
;; bootstrap use-package as per http://cachestocaches.com/2015/8/getting-started-use-package/
;;
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(if (string-equal system-type "gnu/linux")
    (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")) ; make default https elpa usable again
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; configure use-package
(eval-when-compile
  (require 'use-package)
  (setq use-package-compute-statistics t)
  (require 'use-package-ensure)
  (setq use-package-always-ensure t))

;; make elpa usable again
(use-package gnu-elpa-keyring-update)


;; way faster than spaceline and more to my liking than powerline, not as basic as moodline
(use-package doom-modeline
  :init
  (doom-modeline-mode 1)
  )


;;
;; emacs-core-related config
;;
(use-package emacs
  :config
  ;; show current function or similar thing in modeline
  (which-function-mode 1)
  )
```
* open some C source code
* move cursor inside function, which-func displays correct function
* click mouse-2 on which-func display
* expected: only selected functions is displayed, rest of the code hidden
* bug behavior:  nothing happens 

**Environment:**
 - OS and version: Debian Buster
 - Emacs Version: 27.1 
 - Configuration:see snippet above
 - Package version: 20200827.1710

**Additional context**
:exclamation: It works with emacs 26.1.

**Comment by seagle0128** [comment]
Quick questions since I couldn't reproduce with 27.1 on my env (macOS).

1. Does it work after disabling doom-modeline?
1. Does the issue exist on 28.0.50?

**Comment by bk138** [comment]
>     1. Does it work after disabling doom-modeline?

If I remove the doom-modeline use-package stanza, yes it works with emacs 27.1 then.

> 
>     2. Does the issue exist on 28.0.50?

Yes. I am using https://hub.docker.com/r/andreacorallo/emacs-nativecomp there, started with a rather lengthy `docker run -ti --network host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  -u $UID -e "HOME=$HOME" -v "$HOME:$HOME" -v "/etc/passwd:/etc/passwd:ro" -v "/etc/shadow:/etc/shadow:ro" -v "/etc/group:/etc/group:ro" -v "/etc/sudoers.d:/etc/sudoers.d:ro" -v "$PWD:$PWD" -w "$PWD" -v /usr/bin:/usr/bin:ro   andreacorallo/emacs-nativecomp emacs`

**Comment by seagle0128** [comment]
Any screenshot or recording?

I am not using emacs-nativecomp build, so I have no idea so far.

**Comment by bk138** [comment]
> Any screenshot or recording?

Yeah, [here](https://drive.google.com/file/d/1DbuHHgz5wN-dtAzrLD1FQxcNg8LeYOkj/view?usp=sharing).
 

> I am not using emacs-nativecomp build, so I have no idea so far.

Please note that the screencast was recorded with Emacs 27.1, without nativecomp. I was just using the nativecomp docker image to verify the issue with Emacs 28.0.50.

**Comment by seagle0128** [comment]
I tested on Windows, Linux, macOS, and couldn't reproduce the issue. This feature is from which-function-mode itself, and I don't think it's impacted by doom-modeline.

**Comment by bk138** [comment]
Maybe it's a toolkit issue as the emacs 27.1 I'm using is linked against gtk3 ("GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-08-29, modified by Debian"). I'm [linking the build here for reference](https://drive.google.com/drive/folders/1RzHm6ub-alhyglqOQTmWDNSYLt8UItJD?usp=sharing). I'll also try again with https://www.flathub.org/apps/details/org.gnu.emacs and post the results here.

**Comment by bk138** [comment]
I do encounter the issue with the flatpak build "GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21) of 2020-09-01" as well.

**Comment by seagle0128** [comment]
Can you try the official Emacs package or build it yourself?

See https://www.emacswiki.org/emacs/EmacsSnapshotAndDebian

**Comment by seagle0128** [comment]
Couldn't reproduce with GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-09-08

**Comment by seagle0128** [comment]
![emacs](https://user-images.githubusercontent.com/140797/92506121-88c5aa00-f237-11ea-8ef6-67710b75f821.gif)

**Comment by bk138** [comment]
> Can you try the official Emacs package or build it yourself?
> 
> See https://www.emacswiki.org/emacs/EmacsSnapshotAndDebian

Using the build from http://emacs.ganneff.de/ (GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-08-31, unofficial emacs-snapshot build: http://emacs.ganneff.de/, git commit 04578c10636fbbd1c1a924404a955eb37ffefd8f) I get the issue as well. I'll try with another desktop environment (using Gnome 3.30.2 here).

**Comment by bk138** [comment]
FWIW, it works with Xfce 4.12. Probably a Gnome issue. As doom-modeline is not causing the issue but seems only part of a setup that exhibits this behaviour, feel free to close. I'll post my findings here for reference.

**Comment by bk138** [comment]
Found it :tada: : the bug behaviour happens when using emacs >= 27.1 and [Gnome sloppy mouse focus enabled](https://askubuntu.com/questions/978401/how-do-i-set-focus-follows-mouse-in-ubuntu-17-10-and-later-with-gnome-3), used with the .emacs snippet I posted earlier.
