### ISSUE TITLE
Weird mode line display while doom-modeline configured with use-package

### ISSUE THREAD

**Issue by hekinami** [seagle0128/doom-modeline#374]
**Describe**
If we try to configure doom-modeline with use-package, the modeline (the right part) cannot be displayed completely.

**Steps and Expected**
1. In the configuration file (the settings.org file in my case)
`
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))
`
2. start emacs

![image](https://user-images.githubusercontent.com/10599084/92585655-d25dd580-f2c7-11ea-8c31-0c603938c841.png)

You can see the 'Lisp Interaction' part is  not displayed completely

And if we don't use use-package, i.e. we comment out the use-package snippet after we installed the doom-modeline package, and run manually by 

M-x doom-modeline-mode

![image](https://user-images.githubusercontent.com/10599084/92585897-2799e700-f2c8-11ea-81b3-ffc1bd2946f9.png)

Then you may noticed that the 'Lisp Interaction' part is displayed correctly.

Not sure if this is an issue cause by use-package or doom-modeline ifself. But it must be related to doom-modeline loading mechanism I think, so I file this issue here first.

**Environment:**
 - OS and version: Linux Mint  20
 - Emacs Version: 27.1
 - Configuration: https://github.com/hekinami/dotemacs
 - Package version: doom-modeline-20200827.1710

**Additional context**
 N/A

**Comment by hekinami** [comment]
Well, after some research, I think I found the solution.

use the following snippet instead.

```lisp
(use-package doom-modeline
  :ensure t
  :hook (window-setup . doom-modeline-mode)
  )
```

As the conclusion, I think it's an issue about the timing to start doom-modeline-mode, not related to use-package itself. I think the timing was not an issue when we use emacs 26.x with doom-modeline-mode, but it seems matter in emacs 27.1.

If someone else could have the same problem, it  might be a good idea to update the readme file with the window-setup-hook  stuff.

**Comment by seagle0128** [comment]
I think `after-init-hook` works in this case. Please try it.

BTW, did you install all-the-icons fonts via `all-the-icons-install-fonts`?

**Comment by hekinami** [comment]
I  used after-init-hook in my old configuration. However it doesn't work in emacs 27. We must use window-setup-hook.

And it is not like an issue related to the fonts. (and yes I have all icon fonts installed with all-the-icons-install-fonts)

**Comment by seagle0128** [comment]
From the screenshot, the icons are incorrect.

**Comment by hekinami** [comment]
![image](https://user-images.githubusercontent.com/10599084/92640435-dad9fe80-f30f-11ea-9378-544f3f16f464.png)

Do you think this one is with correct icons?

Well,  I think that's because I use this workaround #278 (which was also filed by  me), and the fonts order I specified may not  be exactly the same with your original design. If we just specify 'FontAwesome', then we could get the best(?) result.

Is 'FontAwesome' the only icon font used by doom-modeline? If other fonts are used too, I think we can still optimize by adjusting the order of the fonts for unicode chars.

**Comment by seagle0128** [comment]
`doom-modeline` uses [all-the-icons](https://github.com/domtronn/all-the-icons.el).

**Comment by hekinami** [comment]
when you say all-the-icons, you mean the package, right? 

As the font itself, according to https://github.com/domtronn/all-the-icons.el/tree/master/fonts, several fonts are used by all-the-icons, including fontawesome. 

I cannot confirm the sequence all-the-icons installed these fonts and have no idea when we specify a unicode character how will the system choose the font.

I am afraid I cannot use describe-char to confirm the actual font the icon uses, any idea?

**Comment by seagle0128** [comment]
All fonts may be used for the buffers.
