### ISSUE TITLE
Icons on a per frame basis

### ISSUE THREAD

**Issue by MagicRB** [seagle0128/doom-modeline#375]
**Is your feature request related to a problem? Please describe.**
When emacs is started in daemon mode, the assumption is made that only terminal frames will be created, therefore `doom-modeline-icon` must be set to non-nil, or icons wont work. Issue is that when both terminal and GUI frames exist, the setting applies to all globally

**Describe the solution you'd like**
I want to be able to manually set whether icons should be enabled on a per frame basis, ideally programmatically 

**Describe alternatives you've considered**
There are no alternatives as currently icons can be enabled or not

**Additional context**
None needed

**Comment by seagle0128** [comment]
I am not sure if I understand your request completely. You may try this.
```elisp
(make-variable-buffer-local 'doom-modeline-icon)
(add-hook 'after-make-frame-hook
 (lambda ()
    (setq doom-modeline-icon (display-graphic-p))))
```

**Comment by MagicRB** [comment]
i do have it globally set to always display as if it were in a GUI frame, but i want to mix gui and tui

**Comment by seagle0128** [comment]
Did you try the snippet?

**Comment by seagle0128** [comment]
Any update?

**Comment by rjhwelsh** [comment]
```emacs-lisp
(make-variable-buffer-local 'doom-modeline-icon)
(add-hook 'server-after-make-frame-hook
 (lambda ()
     (setq doom-modeline-icon (display-graphic-p))))
```
The original snippet did not work for me. I had to change `after-make-frame-hook` with `server-after-frame-make-hook`.
As documented [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Frames.html)

This switches the icons on/off globally **not locally**, so I don't think it 100% solves MagicRB's issue.
This fits my usecase though.
Thanks.

**Comment by rjhwelsh** [comment]
I spoke too soon... 
```emacs-lisp 
(make-variable-buffer-local 'doom-modeline-icon)
```
appears to make all subsequent buffers default to showing no icons.
So leave that part out.

**Comment by seagle0128** [comment]
@rjhwelsh `after-make-frame-hook` is just an example. You can use other hooks in your cases. I just mean buffer-local var should be fine for this request.

**Comment by seagle0128** [comment]
I believe this snippet does work according my tests recently.

```elisp
(make-variable-buffer-local 'doom-modeline-icon)
(add-hook 'server-after-make-frame-hook
 (lambda ()
     (setq doom-modeline-icon (display-graphic-p))))
```

**Comment by noctuid** [comment]
That will not work. Setting the variable on every buffer create or switch would be better, but buffer-local variables cannot correctly solve this because the same buffer can be visited by both a GUI and terminal frame.

**Comment by seagle0128** [comment]
Now just use `(setq doom-modeline-icon t)`, and icons will be displayed in GUI automatically.
