### ISSUE TITLE
How to add 'git-gutter' like features into the modeline? (git update changelog)

### ISSUE THREAD

**Issue by edward0im** [seagle0128/doom-modeline#376]
Hello authors,

Thank you for providing such a cool modeline package :-)

I just have a simple question, I'd like to add the **git update changelog** feature into the modeline, but I couldn't.

how to add this feature like you introduced in README.md?

- README.md
<img width="152" alt="01" src="https://user-images.githubusercontent.com/18214498/93063951-edf32280-f6b1-11ea-9486-680cbc9582b4.png">

- Mine
<img width="132" alt="02" src="https://user-images.githubusercontent.com/18214498/93063958-f0557c80-f6b1-11ea-9eb5-6227c23b3478.png">

Thank you in advance!

**Comment by seagle0128** [comment]
```elisp
(setq doom-modeline-icon nil)
(setq doom-modeline-checker-simple-format nil)
```

**Comment by edward0im** [comment]
Thanks for the reply @seagle0128,


But after I apply the codes you give, 'git-gutter' like modification log is not shown. 

![Selection_001](https://user-images.githubusercontent.com/18214498/93098070-5efdfe80-f6e1-11ea-8e8e-a21152fea65b.png)

I'd like the [added/modified/deleted] notification like git-gutter.

**Comment by seagle0128** [comment]
No. it's for flycheck, not for git.

**Comment by edward0im** [comment]
@seagle0128 

Oh, I see. I thought that is the feature like 'git-gutter' mode. 

Thank you for the reply. I'll close it.
