### ISSUE TITLE
Telega.el make the modeline unable to align and display wrong icon in termianl

### ISSUE THREAD

**Issue by shrubbroom** [seagle0128/doom-modeline#377]
**Describe**
Telega.el make the modeline unable to align and display wrong icon in termianl

**Steps and Expected**
These are my doom-modeline and telega configuration
``` lisp

(use-package telega
  :ensure t
  :config
  ;;  (evil-define-key '(normal) telega-msg-button-map (kbd "k") #'evil-previous-line)
  ;;  (unbind-key (kbd "k") 'telega-msg-button-map)
  (define-key telega-msg-button-map (kbd "k") nil)
  (define-key telega-msg-button-map (kbd "k") 'evil-previous-line)
  (define-key telega-msg-button-map (kbd "l") nil)
  (define-key telega-msg-button-map (kbd "l") 'evil-forward-char)
  (setq-default telega-use-images t)
  (setq telega-proxies
        (list
         '(:server "127.0.0.1" :port 1088 :enable t
                   :type (:@type "proxyTypeSocks5"
                                 :username "" :password ""))))
  )

(use-package doom-modeline
  :ensure t
  :init
  (doom-modeline-mode 1)
  :config
  (setq doom-modeline-buffer-file-name-style 'buffer-name)
  (setq doom-modeline-project-detection 'projectile)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-unicode-fallback t)
  (display-time-mode)
  )
```

**Environment:**
 - OS and version: Arch Linux
 - Emacs Version: 28.0.50
 - Configuration: 
 - Package version: 20190909, 20190903 for telega

**Additional context**
![图片](https://user-images.githubusercontent.com/49093544/93695195-bb7c7600-fb46-11ea-8e5e-52c3164dd526.png)

The modeline misalign here since the center line doesn't match with the modeline's center line

**Comment by seagle0128** [comment]
I don't understand the issue and don't see any issue in the screenshot. No icon in terminal, it's as designed.

**Comment by shrubbroom** [comment]
Sorry for that confusement I have caused. As you have seen in the screenshot, the red-line in the modeline and the red-line in the buffer doesn't match (which can be illustrated better by the following image).
![图片](https://user-images.githubusercontent.com/49093544/94257254-94b2ab00-ff5d-11ea-8902-7eb47187509c.png)

The icon in the terminal(I enabled the unicode fallback) also acts weird. This icon 
![图片](https://user-images.githubusercontent.com/49093544/94257522-012daa00-ff5e-11ea-8423-cd32d6aad224.png)
 doesn't disappear even if I have C-x C-s the file.
![Peek 2020-09-25 18-31](https://user-images.githubusercontent.com/49093544/94257640-2d492b00-ff5e-11ea-9be8-6d3fa271fdc7.gif)

**Comment by seagle0128** [comment]
are you using `doom-emacs` or vanilla emacs?

**Comment by shrubbroom** [comment]
I am using vanilla emacs. I found that it is evil who together with telega causes this probelm.
This is my minimum configuration to reproduce the issue.
```
(use-package evil
  :ensure t
  :init
  (add-hook 'after-init-hook 'evil-mode)
  )
(use-package doom-modeline
  :ensure t
  :init
  (doom-modeline-mode 1)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-unicode-fallback t)
  )
(use-package telega
  :ensure t
  :config
  )

```
The misalignment may not occur in the default theme of Emacs. However the problem with the icon in modeline still exists in this minimun configuration.

**Comment by seagle0128** [comment]
1. The misalignment issue is related to the theme and font.
1. No idea for the icon issue. How about disabling evil and/or telega? The issue still occurs? The workaround is `(setq doom-modeline-buffer-modification-icon nil)`.

**Comment by shrubbroom** [comment]
Turning off one of evil and telega solves the icon issue(I am now turning off the telega). And I have found the mininum configuration to reproduce the misalignment, this can occur in default theme.
``` lisp
(use-package evil
  :ensure t
  :init
  (add-hook 'after-init-hook 'evil-mode)
  )
(use-package winum
  :ensure t
  :init
  (setq winum-auto-setup-mode-line nil)
  (add-hook 'after-init-hook 'winum-mode))
(use-package doom-modeline
  :ensure t
  :init
  (doom-modeline-mode 1)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-unicode-fallback t)
  )
(use-package telega
  :ensure t
  )
```
Interestingly, the winum package cause the misalignment If evil and doom-modeline are loaded.

**Comment by seagle0128** [comment]
I think it may be related to the terminal. The issue doesn't exist in iterm on macOS.
