### ISSUE TITLE
[ASK] How to hide buffer precentage?

### ISSUE THREAD

**Issue by azzamsa** [seagle0128/doom-modeline#379]
Any way to hide buffer precentage? I don't find it in customize.

![image](https://user-images.githubusercontent.com/17734314/93872533-7f8a1200-fcfa-11ea-82da-9c67337e55d0.png)

Thanks a lot for doom-modeline!

**Comment by azzamsa** [comment]
I struggle to find the solution based on "buffer precentage modeline" search keyword.

But after few times, changing the keyword to "percent position", I landed in [23.4.4 Variables Used in the Mode Line](https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode-Line-Variables.html#Mode-Line-Variables). Then I search for `modeline percent` variable and I got `doom-modeline-percent-position`.

Setting it to `(setq doom-modeline-percent-position '(-3 ""))` solves my problem.

**Comment by seagle0128** [comment]
You should customize `mode-line-percent-position`.

**Comment by azzamsa** [comment]
I found both `doom-modeline-percent-position` and `mode-line-percent-position`. Changing the the doom variable works too. Any reason to prefer the default value?

**Comment by seagle0128** [comment]
It's fine if `doom-modeline-percent-position` works. it's a variable while not a option, so I prefer mode-line-percent-position.
