### ISSUE TITLE
invalid function: (win (frame-selected-window)

### ISSUE THREAD

**Issue by hello-code** [seagle0128/doom-modeline#38]
Backtrace:

Debugger entered--Lisp error: (invalid-function (win (frame-selected-window)))
  (win (frame-selected-window))()
  doom-modeline-set-selected-window()
  run-hooks(focus-in-hook)
  handle-focus-in((focus-in #<frame *Backtrace* 0a079510>))
  funcall-interactively(handle-focus-in (focus-in #<frame *Backtrace* 0a079510>))
  call-interactively(handle-focus-in nil [(focus-in #<frame *Backtrace* 0a079510>)])
  command-execute(handle-focus-in nil [(focus-in #<frame *Backtrace* 0a079510>)] t)

(use-package doom-modeline
  :ensure t
  :defer t
  :hook (after-init . doom-modeline-init)
)

Windows 7
GNU Emacs 26.1 (build 1, i686-w64-mingw32)

**Comment by seagle0128** [comment]
Are you using official GNU Emacs 26.1? I think you should use x64 build.

![image](https://user-images.githubusercontent.com/140797/47998375-15821700-e13a-11e8-8b4c-570f09cfdd89.png)

Can you evel `when-let` and `frame-selected-window` in your env?

**Comment by hello-code** [comment]
1. The same thing with **GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)** ;
2. (when-let)
   `Debugger entered--Lisp error: (void-function when-let)
  (when-let)
  eval((when-let) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)`

   (frame-selected-window)
   `#<window 3 on *scratch*>`

**Comment by seagle0128** [comment]
Wired! Emacs 26.1 has `when-let` function. Did you download from official website https://ftp.gnu.org/gnu/emacs/windows/emacs-26/emacs-26.1-x86_64.zip? I tested on Windows 10 and it works well. 

Otherwise, please use 
```elisp
(use-package doom-modeline
  :ensure t
  :defer t
  :preface (defalias 'when-let 'when-let*)
  :hook (after-init . doom-modeline-init)
)
```

**Comment by hello-code** [comment]
Yes on Windows 10 is works well,But on Windows 7 is  not!
I download from official website;
I tried your :
(use-package doom-modeline
  :ensure t
  :defer t
  :preface (defalias 'when-let 'when-let*)
  :hook (after-init . doom-modeline-init)
)

But still not working...

Debugger entered--Lisp error: (invalid-function (win (frame-selected-window)))
  (win (frame-selected-window))()
  doom-modeline-set-selected-window()
  run-hooks(focus-in-hook)
  handle-focus-in((focus-in #<frame *Backtrace* 0000000400a69a50>))
  funcall-interactively(handle-focus-in (focus-in #<frame *Backtrace* 0000000400a69a50>))
  call-interactively(handle-focus-in nil [(focus-in #<frame *Backtrace* 0000000400a69a50>)])
  command-execute(handle-focus-in nil [(focus-in #<frame *Backtrace* 0000000400a69a50>)] t)

**Comment by seagle0128** [comment]
I believe it's an emacs bug on WIndows7.

Please check if `when-let` exists in `./lisp/emacs-lisp/subr-x.el`. If YES, try this:
```elisp
(use-package doom-modeline
:ensure t
:defer t
:hook (after-init . doom-modeline-init)
:config (require 'subr-x)
)
```

Otherwise try `(defalias 'when-let 'let)`.

**Comment by hello-code** [comment]
subr-x.el in here: C:\Emacs\share\emacs\26.1\lisp\emacs-lisp\subr-x.el

still not working...
Windows 7 BUG?

**Comment by seagle0128** [comment]
I tested on Windows7 and there is no such issue. Please test with the bare Emacs `emacs -Q`. I think the issue exists in your configurations.

![image](https://user-images.githubusercontent.com/140797/48068418-b7beff00-e20d-11e8-9dcb-2bf0e441afeb.png)

**Comment by hello-code** [comment]
The same issue even install doom-modeline on bare Emacs. Anyway,thank you very much!

**Comment by seagle0128** [comment]
If `when-let` is not defined, many packages will not work. So you should ensure `when-let` is defined in your environment, or file a bug for Emacs. But please make sure 100% before filing the issue, because in my laptop it does work well.
