### ISSUE TITLE
disable major mode segment?

### ISSUE THREAD

**Issue by eeshugerman** [seagle0128/doom-modeline#381]
>NOTE: This is more of a request for help than a feature request, but there was no template for that.

**Is your feature request related to a problem? Please describe.**
I'd like to disable the major mode segment (not the icon, but the major mode name as text which gives a menu when clicked). 

**Describe the solution you'd like**
I'd appreciate a toggle for this of course, but I understand you can't just add a toggle for everything.

**Describe alternatives you've considered**
Can this be done with `doom-modeline-def-modeline`? I'm guessing it can, but I don't know where to start because I can't find the default value, which I otherwise like -- perhaps it's `doom-modeline--default-format`, but evaluating this gives me some strange non-text value. Also I don't understand why `doom-modeline-def-modeline` takes two lists :thinking:.

**Comment by seagle0128** [comment]
Just removing major-mode segment from the mode-line. e.g.

```elisp
(doom-modeline-def-modeline 'main
  '(bar workspace-name window-number modals matches buffer-info remote-host buffer-position word-count parrot selection-info)
  '(objed-state misc-info persp-name battery grip irc mu4e gnus github debug repl lsp input-method indent-info buffer-encoding major-mode process vcs checker))
```
