### ISSUE TITLE
Mu4e alert replacement does not have mouse actions

### ISSUE THREAD

**Issue by tecosaur** [seagle0128/doom-modeline#382]
I'm assuming that the prettier mu4e icon is designed to function as a nice-looking replacement of the default if not this counts as a feature request.

**Steps and Expected**
mu4e-alert includes [mouse actions](https://github.com/iqbalansari/mu4e-alert/blob/91f0657c5b245a9de57aa38391221fb5d141d9bd/mu4e-alert.el#L311-L314) to view unread emails when the status icon is clicked. This does not happen when using the status icon provided in this package.

**Environment:**
 - OS and version: Linux (OpenSuse Tumbleweed)
 - Emacs Version: 27.1
 - Configuration: Doom (https://tecosaur.github.io/emacs-config/config.html)
 - Package version: ffbaaee

**Comment by seagle0128** [comment]
Please test the latest version.

**Comment by tecosaur** [comment]
Yep, just checked and this seems to work :+1:
