### ISSUE TITLE
win10下以C:\Software\GNU\emacs\bin\emacsclientw.exe -n -c -a "" 命令启动 emacs  Daemon，modeline图标不显示

### ISSUE THREAD

**Issue by yyangdid** [seagle0128/doom-modeline#383]
**Describe**
win10下以`C:\Software\GNU\emacs\bin\emacsclientw.exe -n -c -a ""` 命令启动 emacs  Daemon，modeline 文件类型图标不显示，evil模式显示变成字母了，下图：
![Snipaste_2020-10-09_21-32-49](https://user-images.githubusercontent.com/10922667/95589213-04a15500-0a77-11eb-9461-f7b502e320ef.png)

其他插件（比如treemacs）的icons正常显示，all-the-icons应该是没有问题的

**Environment:**
 - Windows 10
 - 27.1
 - 20201005

**Comment by seagle0128** [comment]
```elisp
(setq doom-modeline-icon t)
```
