### ISSUE TITLE
Larger indicator for evil state

### ISSUE THREAD

**Issue by MithicSpirit** [seagle0128/doom-modeline#385]
### Is your feature request related to a problem? Please describe.
The tiny circle that indicates the evil state is too small to easily distinguish the current mode in some lower-contrast themes (which I use because I find them easier on the eyes) and doesn't provide that much information, meaning that I need to memorize what the different colors mean.

### Describe the solution you'd like
I would like there to be an option to use a larger indicator for the evil state that includes some text for the current state, similar to [vim powerline](https://github.com/powerline/powerline#vim-statusline).

### Describe alternatives you've considered
I have been using [telephone line](https://github.com/dbordak/telephone-line), which works well for this but is missing some other much-appreciated segments from doom modeline.

### Additional context
Some screenshots of the evil status indicator from my setup in telephone line (taken from the left edge of the modeline):
![image](https://user-images.githubusercontent.com/24192522/95792284-2be36680-0cb1-11eb-9788-1fb660556444.png) ![image](https://user-images.githubusercontent.com/24192522/95792306-3998ec00-0cb1-11eb-851c-204935de5330.png) ![image](https://user-images.githubusercontent.com/24192522/95792325-44ec1780-0cb1-11eb-8f15-a69ddb339699.png) etc.

**Comment by seagle0128** [comment]
See `doom-modeline-modal-icon`?

**Comment by MithicSpirit** [comment]
Ohhh I thought setting that to `nil` that would just remove the dot altogether... still a bit small IMO but a lot better than before. Is there some way to reconfigure what text it shows for each state?

**Comment by loki7990** [comment]
I apologize, I'm new to emacs so I'm not sure what I'm doing exactly. I tried including that block in your last comment and nothing seems to happen. I tried putting in the full block from your linked comment so that the complete block in my `config.el` is:
```
(require 'doom-modeline)
(doom-modeline-def-segment evil-state
  "The current evil state.  Requires `evil-mode' to be enabled."
  (when (bound-and-true-p evil-local-mode)
    (s-trim-right (evil-state-property evil-state :tag t))))
(doom-modeline-def-modeline main
                            (workspace-number window-number bar evil-state matches " " buffer-info buffer-position  " " selection-info)
                            (buffer-encoding major-mode vcs flycheck global))

(doom-modeline-def-modeline special
                            (window-number bar evil-state matches " " buffer-info-simple buffer-position " " selection-info)
                            (buffer-encoding major-mode flycheck global))
(setq evil-normal-state-tag   (propertize "[Normal]" 'face '((:background "green" :foreground "black")))
      evil-emacs-state-tag    (propertize "[Emacs]" 'face '((:background "orange" :foreground "black")))
      evil-insert-state-tag   (propertize "[Insert]" 'face '((:background "red") :foreground "white"))
      evil-motion-state-tag   (propertize "[Motion]" 'face '((:background "blue") :foreground "white"))
      evil-visual-state-tag   (propertize "[Visual]" 'face '((:background "grey80" :foreground "black")))
      evil-operator-state-tag (propertize "[Operator]" 'face '((:background "purple"))))
```
I now get this error:
```
Warning (initialization): An error occurred while loading ‘/home/barbarossa/.emacs.d/init.el’:

Error in private config: config.el, (void-variable main)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

I'm using DOOM emacs, which is probably why I'm having problems...

**Comment by loki7990** [comment]
Oof, Now I see. Just needed to set `(setq doom-modeline-modal-icon nil)` and the block you posted here. Sorry about that!
