### ISSUE TITLE
Wrong advice for `select-window' which must has WINDOW as return value

### ISSUE THREAD

**Issue by c0001** [seagle0128/doom-modeline#386]
https://github.com/seagle0128/doom-modeline/blob/86d91e891b7d587b6680b19eda5ce2ca3df5b0ab/doom-modeline-segments.el#L1505

The function `doom-modeline-update-persp-name` can not be the after advice for internal function `select-window` whcih must has an WINDOW as return, which must be using `around` advice patched it with `prog1' for example.

**Comment by seagle0128** [comment]
Thank you! According to documents, I use buffer-list-update-hook instead.
