### ISSUE TITLE
writeroom - blank modeline - vertical padding

### ISSUE THREAD

**Issue by french-maxime-he** [seagle0128/doom-modeline#389]
Hello,

I'm sorry for asking, here. But I really have no idea how to get this right.

**distribution**: doom emacs. 
**module**: `zen`

**goal**: The idea is to have vertical padding in `writeroom-mode` (in `zen` module). Top padding with header-line configuration works. 

**problem**: bottom part of the padding, tweaking since 24h, no success at modeline becoming a blank modeline (with same background color as default, with some specified height).

I still want to have the regular modeline when not using `writeroom-mode`. Hooks and `writeroom-mode-line` variable might be of use.

Thanks in advance.

**Comment by seagle0128** [comment]
Sorry! I don't think I understand the question completely.

> Top padding with header-line configuration works.

Can you show a screenshot or something else?
What's bottom part of the padding?

**Comment by french-maxime-he** [comment]
Thank you for answering so fast!

I got it to work, using directly `writeroom`'s variables and `header-line` face.

![image](https://user-images.githubusercontent.com/32144496/100054399-3cdfd580-2e22-11eb-99c9-042722b8c12f.png)

the hacky code (I'm not proficient in configuring and dvp on Emacs yet):
```
(after! writeroom-mode
  (setq
   writeroom-header-line "  "
   writeroom-mode-line `(,(propertize "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "
                                      'face '(:height 2.5 :inherit 'header-line)))
   writeroom-major-modes '(".*")
   writeroom-width 120)
  )
(global-writeroom-mode)

(custom-set-faces
 '(header-line ((t (:height 2.0)))))
```

At this point, it is maybe worth improving on:
- the long empty string
- making it more idiomatic wrt. how Emacs is supposed to be configured/extended

**Comment by seagle0128** [comment]
I think it's a question for `writeroom-mode` and `doom`. Closing it.
