### ISSUE TITLE
Error on loading doom-modeline

### ISSUE THREAD

**Issue by qleguennec** [seagle0128/doom-modeline#39]
The following `use-package` form gives me that error:

```
(use-package doom-modeline
  :straight (doom-modeline :host github :repo "seagle0128/doom-modeline")
  :hook (after-init . doom-modeline-init))
```

`Error (use-package): doom-modeline/:catch: Cannot open load file: No such file or directory, ./data/data-alltheicons.el`

**Comment by seagle0128** [comment]
Can you please make sure `all-the-icons` package is installed correctly? This package is the dependency of `doom-modeline`.

**Comment by seagle0128** [comment]
Or, reinstall `all-the-icons` package, please.

**Comment by qleguennec** [comment]
Fixed, thought I am not sure how.

**Comment by seagle0128** [comment]
This may be the network issue. I will close it.
Please feel free to reopen if you still have the issue.
