### ISSUE TITLE
persp options don't seem to have any effect

### ISSUE THREAD

**Issue by cmacrae** [seagle0128/doom-modeline#390]
Hi @seagle0128 👋 

For some reason, when using doom-modeline the `doom-modeline-persp` options have never seemed to work for me.  
I'm finally getting around to reporting it.

Here's the configuration I use:
```elisp
(use-package doom-modeline
  :hook (window-setup . doom-modeline-mode)
  :config
  (setq doom-modeline-persp-name              t
        doom-modeline-persp-icon              t
        doom-modeline-buffer-encoding         nil
        doom-modeline-icon                    t
        doom-modeline-buffer-file-name-style  'truncate-with-project))
```

The `persp` section of my modeline always looks like this:
![image](https://user-images.githubusercontent.com/3392199/101284599-c5725480-37d8-11eb-971c-e3055485990b.png)

I've tried initiating doom-modeline a multitude of ways (using `:init (doom-modeline-mode 1)`, `:hook (after-init . doom-modeline-mode)`, etc.), but none seem to fix this issue.

I'd really appreciate some advice on what I'm doing wrong here.  
Thanks in advance!

**Comment by seagle0128** [comment]
The default perspective name isn't displayed by default.

Try `(setq doom-modeline-display-default-persp-name t)`.

**Comment by cmacrae** [comment]
Sorry, but that's not the issue. If you look at the screenshot I provided, you can see the standard perspective list is rendered, rather than the doom-modeline version.  
I tried setting `(setq doom-modeline-display-default-persp-name t)` but it made no difference.

**Comment by seagle0128** [comment]
Are you using `persp-mode' or `perspective'? Only persp-mode is supported, and I couldn't reproduce this issue locally.

**Comment by cmacrae** [comment]
Thanks for getting back to me so quickly :) I am using `persp-mode` (like so):
```elisp
   (use-package perspective
     :config
     (defun cm/persp-neo ()
       "Make NeoTree follow the perspective"
       (interactive)
       (let ((cw (selected-window))
             (path (buffer-file-name))) ;; save current window and buffer
             (progn
               (when (and (fboundp 'projectile-project-p)
                          (projectile-project-p)
                          (fboundp 'projectile-project-root))
                 (neotree-dir (projectile-project-root)))
               (neotree-find path))
             (select-window cw)))

     :hook
     (after-init . persp-mode)
     (persp-switch . cm/persp-neo))

   (use-package persp-projectile
     :after (perspective)
     :bind
     ("C-c x" . hydra-persp/body)
     :config
     (defhydra hydra-persp (:columns 4
                            :color blue)
       "Perspective"
       ("a" persp-add-buffer "Add Buffer")
       ("i" persp-import "Import")
       ("c" persp-kill "Close")
       ("n" persp-next "Next")
       ("p" persp-prev "Prev")
       ("k" persp-remove-buffer "Kill Buffer")
       ("r" persp-rename "Rename")
       ("A" persp-set-buffer "Set Buffer")
       ("s" persp-switch "Switch")
       ("C-x" persp-switch-last "Switch Last")
       ("b" persp-switch-to-buffer "Switch to Buffer")
       ("P" projectile-persp-switch-project "Switch Project")
       ("q" nil "Quit")))
```

Of course a lot of this is unrelated (I'm simply calling `persp-mode` in after init) but I figured I'd include it just in case

**Comment by seagle0128** [comment]
No. `perspective` is not supported. Only support [https://github.com/Bad-ptr/persp-mode.el](persp-mode). They are different.

**Comment by cmacrae** [comment]
Ohhh, my sincere apologies. I didn't realise this existed!
Thank you for taking the time to look at this and point it out :)
