### ISSUE TITLE
Option to remove git branch name

### ISSUE THREAD

**Issue by ericdallo** [seagle0128/doom-modeline#392]
**Is your feature request related to a problem? Please describe.**
I would like to have the modeline without the git branch name, only the icon.

**Describe the solution you'd like**
Set a variable to remove the branch name.

**Comment by mohkale** [comment]
Not really an option but you can do:

```lisp
(advice-add #'doom-modeline-update-vcs-text :override #'ignore)
```

**Comment by ericdallo** [comment]
Thanks @mohkale , I'll try it

**Comment by ericdallo** [comment]
It removes the git icon but it works, I'll use it that way but I'll keep this issue open for users that want just the text removed

**Comment by mohkale** [comment]
@ericdallo

It should remove just the icon :/

...

Okay it's failing because https://github.com/seagle0128/doom-modeline/blob/af5f61888e7eb0aa521d2d29b42221302b717915/doom-modeline-segments.el#L691-L710 has a `when-let` clause which means both the icon and test should be non-nil otherwise both will be hidden. Maybe try

```lisp
(advice-add #'doom-modeline-update-vcs-text :override
            (defun doom-modeline-update-vcs-text+ ()
              (setq setq doom-modeline--vcs-text "")))
```

**Comment by ericdallo** [comment]
It works indeed :) 
I just replace with `(advice-add #'doom-modeline-update-vcs-text :override (lambda () (setq doom-modeline--vcs-text "")))` since is in configuration.
Thank you!

**Comment by mohkale** [comment]
@ericdallo I don't recommend using lambdas for advice (or hooks), it makes removing them a pain in my experience. But to each their own :smile:.

**Comment by ericdallo** [comment]
Yes, agree, but as I said is for configuration only, but I got your point

**Comment by seagle0128** [comment]
Actually you can try this: `(setq doom-modeline-vcs-max-length 0)`.

**Comment by ericdallo** [comment]
@seagle0128 that was how I was trying, but it reduce the name of the branch for something like `mast...` and does not get rid of the entire name `master`.

**Comment by seagle0128** [comment]
@ericdallo please try `(setq vc-display-status nil)`.

**Comment by ericdallo** [comment]
It worked @seagle0128 :D
Thanks, closing this, but we could add this mention in readme somewhere :)
