### ISSUE TITLE
 Git branch name is partly hidden by branch icon.

### ISSUE THREAD

**Issue by fleimgruber** [seagle0128/doom-modeline#393]
**Describe**
Git branch name is partly hidden by branch icon.

**Steps and Expected**

- latest Spacemacs on development branch.
- install via `dotspacemacs-mode-line-theme 'doom`.
- `M-x all-the-icons-install-fonts`.
- manually install the fonts.
- open buffer in a git repo with changes on master branch.

**Environment:**
 - OS and version: Windows 10
 - Emacs Version: 27.1
 - Configuration: Spacemacs
 - Package version: 20201212.1823

**Additional context**

![image](https://user-images.githubusercontent.com/7400038/102930894-a1339a80-449d-11eb-9b56-82c4ddfc93af.png)

**Comment by seagle0128** [comment]
can you check the variable `doom-modeline-vcs-max-length`?

**Comment by fleimgruber** [comment]
Thanks for checking back and sorry for the noise, I should have reviewed previous mode-line customizations pre-switch to doom-modeline - full disclosure, I used [this](https://www.reddit.com/r/emacs/comments/5fjri7/how_to_use_git_logo_in_modeline_instead_of/daldh5p/?utm_source=reddit&utm_medium=web2x&context=3).
