### ISSUE TITLE
Make mode specific mode-lines optional or configurable

### ISSUE THREAD

**Issue by mohkale** [seagle0128/doom-modeline#394]
**Is your feature request related to a problem? Please describe.**
This confused me somewhat but it looks like doom-modeline has different mode-lines configured for different modes, and it automatically overrides any default mode-lines you define yourself with these special one when `doom-mode-line-mode` is active.

For example in `dired-mode` `doom-modeline-set-project-modeline` is called overriding your default mode-line. I didn't see any mention of this in the README (perhaps I overlooked it) but this behaviour is pretty confusing out of the gate.

This would be fine but personally I don't like the look of the default mode-line (doesn't work with my theme very-well) so I've changed quite a lot of it. Now there's a bunch of modes which use mode-lines resembling the default while the rest use mine and I find the difference between the two jarring.

**Describe the solution you'd like**
I'd like to suggest disabling these mode-specific modelines by default or at the very least adding an option to let users do so if they prefer. Perhaps make a customizeable alist containing mode-specific bindings you're OK with doom-modeline setting up and then running through it to add the appropriate hooks.

**Describe alternatives you've considered**
At the moment I'm getting around it by using this:

```lisp
  (dolist (it '(doom-modeline-format--dashboard
                doom-modeline-format--project
                doom-modeline-format--message
                doom-modeline-format--org-src))
    (when (symbol-function it)
      (defalias it (symbol-function 'doom-modeline-format--mohkale))))
```

I plan to add more mode-lines as I encounter them.

**Additional context**

**Comment by seagle0128** [comment]
Please see `doomd-modeline-mode`.

**Comment by seagle0128** [comment]
You can redefine `doom-modeline-mode`.

**Comment by mohkale** [comment]
Okay... that was dumb of me. I never even considered just redefining a minor-mode. Thanks :smile:.
