### ISSUE TITLE
Respect all-the-icons-font-families

### ISSUE THREAD

**Issue by mohkale** [seagle0128/doom-modeline#395]
**Is your feature request related to a problem? Please describe.**
`doom-modeline-icon` only supports the 5 default font-families (icon-sets) that come with all-the-icons. This means user defined extensions to these families aren't supported.

**Describe the solution you'd like**
Specifically in `doom-modeline-icon` I'd like you to respect the icon identifiers present in `all-the-icons-font-families` instead of just the 5 defaults which're known to come with all-the-icons.

**Describe alternatives you've considered**
None that I can think of.

Implementation wise I'm considering adding a default case to this pcase statement: https://github.com/seagle0128/doom-modeline/blob/af5f61888e7eb0aa521d2d29b42221302b717915/doom-modeline-core.el#L1045-L1055

which performs a subsequent check in `all-the-icons-font-families`. That should maintain the current performance for most users while allowing the flexibility of custom font-families.

**Additional context**
Personally I've defined extra font-families for nerd-fonts (and it's many pieces) so being unable to use them with `doom-modeline-icon` is undesireable.

**Comment by seagle0128** [comment]
Can you please let me know how do you define extra font families? Actually all fonts are hard-coded in doom-modeline currently.

**Comment by mohkale** [comment]
All-the-icons itself just uses the `all-the-icons-define-icon` macro to define the builtin font families. For example:

```lisp
(all-the-icons-define-icon alltheicon all-the-icons-data/alltheicons-alist    "all-the-icons")
```

Expanding this macro gives:

```lisp
(progn
  (add-to-list 'all-the-icons-font-families 'alltheicon)
  (add-to-list 'all-the-icons-font-names '"all-the-icons.ttf")
  (defun all-the-icons-alltheicon-family nil "all-the-icons")
  (defun all-the-icons-alltheicon-data nil all-the-icons-data/alltheicons-alist)
  (defun all-the-icons-alltheicon
      (icon-name &rest args)
    (let
        ((icon
          (cdr
           (assoc icon-name all-the-icons-data/alltheicons-alist)))
         (other-face
          (when all-the-icons-color-icons
            (plist-get args :face)))
         (height
          (* all-the-icons-scale-factor
             (or
              (plist-get args :height)
              1.0)))
         (v-adjust
          (* all-the-icons-scale-factor
             (or
              (plist-get args :v-adjust)
              all-the-icons-default-adjust)))
         (family "all-the-icons"))
      (unless icon
        (error
         (format "Unable to find icon with name `%s' in icon set `%s'" icon-name 'alltheicon)))
      (let
          ((face
            (if other-face
                `(:family ,family :height ,height :inherit ,other-face)
              `(:family ,family :height ,height))))
        (propertize icon 'face face 'font-lock-face face 'display
                    `(raise ,v-adjust)
                    'rear-nonsticky t))))
  (defun all-the-icons-insert-alltheicon
      (&optional arg)
    "Insert a all-the-icons icon at point."
    (interactive "P")
    (all-the-icons-insert arg 'alltheicon)))
```

Observe that `all-the-icons` adds the symbol of every font family defined to `all-the-icons-font-families` and you can use `all-the-icons--function-name` to convert a symbol from this font-family list to the equivalent function that returns that icon. Eg. 

```lisp
(all-the-icons-alltheicon "go")
;; is equivalent to
(funcall (all-the-icons--function-name 'alltheicon) "go")
```

Lastly here's how I added extra fonts from nerd-fonts onto all-the-icons.

```lisp
(use-package nerd-fonts
  :straight (nerd-fonts :type git :host github :repo "mohkale/nerd-fonts.el")
  :after all-the-icons
  :demand t
  :config
  (defvar nerd-fonts-families+
    (seq-uniq
     (cl-loop with pos = nil
              for (icon . _) in nerd-fonts-alist
              do (setq pos (cl-loop with count = 0
                                    for char across icon
                                    when (eq char ?-)
                                    return count
                                    else
                                    do (setq count (1+ count))))
              collect (substring icon 0 pos))))

  (defmacro all-the-icons-nerd-font-family+ (family)
    (let* ((nerd-family (concat "nerd-" family))
           (font-alist (intern (concat "all-the-icons-data/" nerd-family "-alist")))
           (name (intern nerd-family)))
      `(progn
         (defvar ,font-alist
           (eval-when-compile
             (cl-loop for (name . icon) in nerd-fonts-alist
                      when (string-prefix-p ,family name)
                      collect (cons (substring name ,(1+ (length family)))
                                    icon))))

         (all-the-icons-define-icon ,name ,font-alist ,nerd-family
           ;; The font on my linux machine, maybe needs updating depending on platform
           "Symbols-2048-em Nerd Font Complete.ttf"))))

  (dolist (it nerd-fonts-families+)
    (eval
     `(all-the-icons-nerd-font-family+ ,it))))
```

I haven't tested this last part out on GUI yet (seeing as I only really care about ttys for now) but hopefully that gives a general gist of the logic.

**Comment by seagle0128** [comment]
I don't think doom-modeline is able to support customized icons. Because it should know the specific icons are used for specific segments.

**Comment by mohkale** [comment]
> Because it should know the specific icons are used for specific segments.

Why?

Regardless all the default families should still be present (all-the-icon, faicon, fa, etc.) it's just if none of those are applicable but more are defined (in `all-the-icons-define-icon`) doom-modeline should use them rather than fail.

For example I've got the following segment:

```lisp
  (doom-modeline-def-segment meta-icons+
    "Icons indicating various kinds of states related to the current buffer.
Think minor-mode list except not full text."
    (let* ((face (if (doom-modeline--active)
                     'doom-modeline-panel
                   'mode-line-inactive))
           (icons (string-join
                   (delq
                    nil (list (cond ((bound-and-true-p lsp-mode)
                                     doom-modeline--lsp)
                                    ((bound-and-true-p eglot--managed-mode)
                                     doom-modeline--eglot)
                                    ((bound-and-true-p anaconda-mode)
                                     (doom-modeline--anaconda-server)))
                              (and (buffer-narrowed-p)
                                   (doom-modeline-icon 'nerd-mdi "json" "{}" "{}" :face face))))
                   (doom-modeline-spc))))
      (unless (string-empty-p icons)
        (concat ;; (doom-modeline-spc)
                icons))))
```

It uses nerd-mdi to show a JSON icon when the current buffer is narrowed. Specifically `(doom-modeline-icon 'nerd-mdi "json" "{}" "{}")` If I run this on the current master branch `doom-modeline-icon` will fail with an `Debugger entered--Lisp error: (args-out-of-range 0 0)`. With this patch:

```diff
@@ -1060,7 +1060,11 @@ ARGS is same as `all-the-icons-octicon' and others."
                      ('alltheicon
                       (apply #'all-the-icons-alltheicon icon-name args))
                      ('fileicon
-                      (apply #'all-the-icons-fileicon icon-name args)))))
+                      (apply #'all-the-icons-fileicon icon-name args))
+                     (t
+                      (let ((func (all-the-icons--function-name icon-set)))
+                        (when (fboundp func)
+                          (apply func icon-name args)))))))
          (doom-modeline-propertize-icon icon face)))
      ;; Unicode fallback
      (and doom-modeline-unicode-fallback
```

It works as expected.

![Screenshot_20201227_161607](https://user-images.githubusercontent.com/23294780/103175049-09e49380-485f-11eb-851a-ee32eeed6447.png) The icon is right nexxt to the minor-mode list.

**Comment by seagle0128** [comment]
I understood. That means it just works for the new segments. I can make a patch for it.

**Comment by mohkale** [comment]
Yep. I'm still curious what you meant by this though?

> Because it should know the specific icons are used for specific segments.

Do you mean that the existing segments **rely** on the default all-the-icons font families and therefore any new font-families won't be used directly?

**Comment by seagle0128** [comment]
Yes, I mean in the existing segments, many hard-coded icons are used. 

For example,
```elisp
(defun doom-modeline-buffer-file-state-icon (icon unicode text face)
  "Displays an ICON of buffer state with FACE.
UNICODE and TEXT are the alternatives if it is not applicable.
Uses `all-the-icons-material' to fetch the icon."
  (doom-modeline-icon 'material icon unicode text
                      :face face
                      :height  1.1
                      :v-adjust -0.225))
```

Unless you create a new segment with new font families, or override material font family.

**Comment by mohkale** [comment]
Yeah. That's not what this issue is about. I'm purely interested in adding more families (for my own personal use), not replacing the existing ones :smile:.

**Comment by seagle0128** [comment]
I am also interested in it. Another option is merge your configuration about nerd font to upstream `all-the-icons`?

**Comment by mohkale** [comment]
> Another option is merge your configuration about nerd font to upstream all-the-icons

See [#220](https://github.com/domtronn/all-the-icons.el/issues/220). There's some desire to support nerdfont but atm the devs are waiting for nerd-fonts to add some emacs (and other desirable) logos. I can kinda see their point, why start a migration when what you have works and what you're moving to doesn't (yet). Plus there's a considerable overlap between nerdfonts and all-the-icons so keeping both (like I'm doing) is probably not the best in-terms of memory usage. Maybe if there's enough desire for it I can send a PR with nerdfont support but I don't imagine it'll get merged any time soon.

**Comment by seagle0128** [comment]
Yeah, I was involved in nerd-fonts/#342.
