### ISSUE TITLE
More consistent spacing control

### ISSUE THREAD

**Issue by mohkale** [seagle0128/doom-modeline#398]
**Is your feature request related to a problem? Please describe.**
Doom modeline seems to be surrounding most of the builtin segments with spaces which means when you mix-and-match segments you sometimes get the seperated by two-spaces or one-space and the result is kind of unpredictable. Is there some sort of recommended approach or design guid for this? Seeing as I'm working mostly from a tty space is a valuable resource. Having extra redundant spaces isn't really something I'd like if possible.

**Describe the solution you'd like**
A few options come to mind:
1. Only put spaces on the left on left-side side segments so they can be stacked together (similarly for the right), this'll make sure you never end up with double spacing but it makes adding left-side segments to the right-side tricky :/.

2. Remove all surrounding spacing from all segments. Expect users to fill in the space themselves. This would be the most versatile approach but it'll break a lot of users mode-lines.

Users would add this segment wherever they'd like to spread things out or we could use this with option 1 to force double-spacing like now.

```lisp
(doom-modeline-def-segment space+
  (doom-modeline-spc))
```

**Describe alternatives you've considered**

I've mostly just been advising existing segments to truncate themselves.

```lisp
(defmacro string-truncate-left! (str count)
  `(and ,str
        (if (> (length ,str) ,count)
            (substring ,str ,count)
          "")))

(defmacro string-truncate-right! (str count)
  `(and ,str
        (let ((len (length ,str)))
          (if (> len ,count)
              (substring ,str 0 (- len ,count))
            ""))))

(defmacro string-truncate! (str left right)
  `(and ,str
        (let ((len (length ,str)))
          (if (> len (+ ,left ,right))
              (substring ,str ,left (- len ,right))
            ""))))

(defun doom-modeline-truncate-right+ (val)
  (string-truncate-left! val 1))

(defun doom-modeline-truncate-left+ (val)
  (string-truncate-right! val 1))

(defun doom-modeline-truncate+ (val)
  (string-truncate! val 1 1))

(advice-add 'doom-modeline-segment--buffer-position :filter-return
            #'doom-modeline-truncate+)

(advice-add #'doom-modeline--anzu             :filter-return #'doom-modeline-truncate+)
(advice-add #'doom-modeline--iedit            :filter-return #'doom-modeline-truncate+)
(advice-add #'doom-modeline--symbol-overlay   :filter-return #'doom-modeline-truncate+)
(advice-add #'doom-modeline--evil-substitute  :filter-return #'doom-modeline-truncate+)
(advice-add #'doom-modeline--multiple-cursors :filter-return #'doom-modeline-truncate+)
```

**Additional context**

**Comment by seagle0128** [comment]
I have to say it's a good suggestion, but it's a big refactoring work, I think.
