### ISSUE TITLE
doom-modeline is not on MELPA

### ISSUE THREAD

**Issue by xvrdm** [seagle0128/doom-modeline#4]
Hi all,

Thanks a lot for extracting the modeline into a standalone package!

I cannot see it on MELPA. Is it just temporary?

![image](https://user-images.githubusercontent.com/3109069/41919112-0752805a-795e-11e8-838f-6c3ed61f4902.png)

**Comment by seagle0128** [comment]
The PR https://github.com/melpa/melpa/pull/5550 is still on processing.

**Comment by seagle0128** [comment]
Already merged. You can install from melpa.
