### ISSUE TITLE
Make doom-modeline-lsp-icon configurable

### ISSUE THREAD

**Issue by mohkale** [seagle0128/doom-modeline#403]
**Is your feature request related to a problem? Please describe.**
Okay so this is a weird and annoying issue. The default rocket icon from the fontawesome family that doom-modeline is using seems to mess up the width calculations of the mode-line on the terminal (making it one character too short).  My best guess is that this is because of unicode (wide-character) issues but I don't really have the means or resources to diagnose it atm. Switching the lsp-icon from the default to the equivalent `nerd-oct` icon seems to fix the issue for me so I'd like an upstream option to just configure the icon.

See the effect with the current icon and the modified one:

![Screenshot_20210105_231315](https://user-images.githubusercontent.com/23294780/103710286-9522ff00-4fac-11eb-93c8-f51dec1fd50a.png)

![Screenshot_20210105_231255](https://user-images.githubusercontent.com/23294780/103710282-92c0a500-4fac-11eb-9438-8a8ee356a4e8.png)

**Describe the solution you'd like**
I'd like an customize option, perhaps an alist of `(family . icon)` or just a list of arguments including face-spec `(family icon ...spec)` which `doom-modeline-lsp-icon` can use instead of the default rocket icon.

NOTE: Notice that the window seperator is one character off in the original.

**Describe alternatives you've considered**
```lisp
(advice-add #'doom-modeline-lsp-icon :override
            (defun doom-modeline-lsp-icon+ (text face)
              (doom-modeline-icon 'nerd-oct "rocket" "🚀" text
                                  :face face :height 1.0 :v-adjust -0.0575)))
```

NOTE: This also depends on [this fork](https://github.com/mohkale/doom-modeline/tree/support-all-the-icons-font-families) of doom-modeline and expects nerd-icons support in the base all-the-icons package.

**Additional context**

**Comment by seagle0128** [comment]
It seems the workaround works well in this case. I have no idea of the root cause so far, and I don't think it makes sense that make lsp-icon configurable. It will make the things complicated.

My guess is it's related to https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-core.el#L105, but I am not very sure. The octicon "rocket" is not in this list.

I am curious why it displays icons in terminal on the screenshots above. What's the value of `(display-graphic-p)` in your env?

**Comment by mohkale** [comment]
> My guess is it's related to https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-core.el#L105, but I am not very sure.

You're correct, adding the following to my config fixes the issue. I didn't know you can configure characters to take up different widths.

```lisp
(advice-add 'doom-modeline--set-char-widths :override #'ignore)
```

It'd be nice if there was some-way to set the widths on GUI frames and exclude ttys but seeing as emacs has removed frame-local-variables and doom-modeline isn't designed to support terminal icons I'm OK with this fix. Thanks for your help :smile:.

> I am curious why it displays icons in terminal on the screenshots above. What's the value of (display-graphic-p) in your env?

It's nil, but I'm using a custom variable to detect whether icons are available or not based on my environment (atm it's always true, even in the terminal) and I'm overriding `doom-modeline-icon` with this value.

```lisp
(setq doom-modeline-icon (or (display-graphic-p)
                             +icons-available))
```

I'm also getting around truncation issues by advising `doom-modeline-icon` to add a trailing space when on the terminal.

```lisp
(advice-add 'doom-modeline-icon :filter-return
            (defun doom-modeline--pad-icon-on-terminal+ (value)
              (if (and (not (display-graphic-p))
                       value)
                  (let ((props (text-properties-at 0 value)))
                    (apply 'propertize
                           (concat (substring-no-properties value)
                                   " ")
                           props))
                value)))
```

This works well enough for my use-cases. I already have the all-the-icons fonts and patched nerdfonts enabled by my terminal emulator (st) so the only real issues I have is getting other packages that're designed only for GUI emacs to work reasonably with the terminal.

![Screenshot_20210106_165605](https://user-images.githubusercontent.com/23294780/103797370-4c1c8a80-5040-11eb-8673-3b1a431ed245.png)

It's not perfect, but it's usable :smile:.
