### ISSUE TITLE
Hope can support keycase package

### ISSUE THREAD

**Issue by stardiviner** [seagle0128/doom-modeline#405]
When I start keycase-mode https://github.com/tarsius/keycast
It dynamically insert after `mode-line-buffer-identification`.
Here is it reported error message:
```
user-error: Cannot turn on keycast-mode.  mode-line-buffer-identification not found in mode-line-format.  Try customizing keycast-insert-after. [2 times]
```

**Comment by seagle0128** [comment]
Duplicated with #122.

**Comment by DarkBuffalo** [comment]
> Duplicated with #122.

the problem seems to have reappeared
I have the same problem

**Comment by seagle0128** [comment]
@DarkBuffalo did you look into #122?

**Comment by Gleek** [comment]
@DarkBuffalo can you check my comment to the original issue and see if it works for you. https://github.com/seagle0128/doom-modeline/issues/122#issuecomment-780683648

**Comment by DarkBuffalo** [comment]
> @DarkBuffalo can you check my comment to the original issue and see if it works for you. [#122 (comment)](https://github.com/seagle0128/doom-modeline/issues/122#issuecomment-780683648)
Thanks. This works.
`(use-package! keycast
  :hook (after-init . keycast-mode) ;; démarrer le mode apres le démarrage d'emacs
  :commands keycast-mode
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
        (progn
          (add-hook 'pre-command-hook 'keycast--update t)
          (add-to-list 'global-mode-string '("" mode-line-keycast " ")))
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (remove '("" mode-line-keycast " ") global-mode-string))))
  (custom-set-faces!
    '(keycast-command :inherit doom-modeline-debug
                      :height 0.9)
    '(keycast-key :inherit custom-modified
                  :height 1.1
                  :weight bold)))`
