### ISSUE TITLE
Add option to show an indicator when god/ryo/etc mode is not active

### ISSUE THREAD

**Issue by marcora** [seagle0128/doom-modeline#406]
**Is your feature request related to a problem? Please describe.**
I use Ryo and, when not active (i.e., in "normal" mode) doom-modeline does not show any indicator (e.g., a colored bullet). However, when the Ryo mode is active, I see a green colored bullet.

The appearance/disappearance of the bullet is distracting to me because it shift the left-aligned modeline content to the right.

**Describe the solution you'd like**
Give user the option to show a differently colored bullet (e.g., a gray color or something else based on color theme) when Ryo (or other modal) mode is inactive. I believe doom-modeline already behaves in this way with Evil mode.

**Comment by seagle0128** [comment]
I don't think it's a good idea to display an icon when the mode is inactive. Actually, even for evli-mode, no icon is displayed when it's inactive. How to know which mode the user will use? Or user never uses any model mode?

**Comment by marcora** [comment]
I understand that some people might prefer that behavior and I am not asking to change it, it should remain the default. What i am asking is an option (config variable) to be able to turn on an inactive (gray for for example) indicator when a modal mode is installed but not active (or I should say "active" in standard mode to help conceptualize what i am thinking).

**Comment by seagle0128** [comment]
OK. Let's think about this case. If the user installed several modal modes, e.g. evil, god and ryo, but he might just want to enable god-mode after he completes the editing with standard mode. Now, what icon should be displayed? `god-mode` has no standard or command mode, not like evil-mode. It's difficult to figure out which modal mode the user will enter. Thought?

**Comment by marcora** [comment]
What I was suggesting was to display something like a gray icon any time no
modal package is active/enabled to intercept keys and thus Emacs is just
behaving as it normally does if modal package was not active or even
installed.

**Comment by seagle0128** [comment]
Many users don't use modal modes.

**Comment by marcora** [comment]
Isn't it possible to check whether a user has a modal mode package running
in their emacs environment?

**Comment by seagle0128** [comment]
That's the point. IMO it‘s nearly possible to detect if all kinds of modal modes are running or not. Please let me know if you happen to know. Thanks!
