### ISSUE TITLE
How to show the R file icon when using ESS?

### ISSUE THREAD

**Issue by fountainer** [seagle0128/doom-modeline#407]
The doom-modeline does not show the R file icon for the ESS[R] major  mode.

**Comment by seagle0128** [comment]
It's an issue of `all-the-icons`, which only supports "\\.r[ds]?x?$" files.

You may need this snippet.
```elisp
(add-to-list 'all-the-icons-mode-icon-alist
             '(ess-mode all-the-icons-octicon "R" :face all-the-icons-lblue))
```
