### ISSUE TITLE
battery charge tested on an iMAC 

### ISSUE THREAD

**Issue by algon-ns** [seagle0128/doom-modeline#408]
**Describe**
The Battry-update happends on my iMac

**Steps and Expected**
see attached picture
the yellow "N/A%" is showing all the time
![NA](https://user-images.githubusercontent.com/58687687/104560271-efbff900-5645-11eb-9d90-ca1ca8ef934e.png)

**Environment:**
 - OS and version: [MacOS 10.2 High Sierra]
 - Emacs Version: [28.0.50]
 - Configuration: [own config with "doom-modeline"]
 - Package version: [newest from git]

**Comment by seagle0128** [comment]
Sorry! I am not using iMac, and unable to reproduce this issue. More details and information, I'd like appreciate it.

**Comment by seagle0128** [comment]
Sorry! I am not using iMac, and unable to reproduce this issue. More details and information, I'd like appreciate it.

**Comment by algon-ns** [comment]
Aktually, then I'm not sure, if doom-modeline test the battery, but I gets that ugly Yellow "N/A%" on the modeline, and a iMAC does not have a battery.  The vaiable " display-battery-mode" is nil (line 2528 in "doom-modeline-segments.el".
If I manually set "battery-status-function" to nil then the yellow "N/A%" goes away.

**Comment by algon-ns** [comment]
It works as expectet on my Macbook Air (which have a battery)

**Comment by seagle0128** [comment]
Can you please evaluate these snippets in your iMac?

```elisp
(funcall battery-status-function)
(eval 'doom-modeline--battery-status)
(eval 'display-battery-mode)
```

**Comment by algon-ns** [comment]
I changed my conf back, so I removed the line (setq battery-status-function nil) and set debug-on-error  to "t"
Then I run "M-x eval-buffer" your lines one by one 
(funcall battery-status-function) did not react , neither in the minibuffer nor in the messages-file.
(eval 'doom-modeline--battery-status) wrote "reference to free variable ‘battery-status-function’" in message file
(eval 'display-battery-mode) no reacting

I think, that you are aware of my configuration in https://github.com/algon-ns/nec.emacs.d, as it might be as simple as an error in my setup the use af doom-modeline?

**Comment by seagle0128** [comment]
I committed a patch. Please test the latest version. If it doesn't work yet, eval `(eval 'battery-status-function)`, please.

**Comment by algon-ns** [comment]
I loaded your patch, which did not change anything.
I'm just an old grumphy man, so I do know if I'm eval right: I set battery-status-function in *Scratch* and make a M-x, I also tried to put  in *Scratch* with the same result: nothing ....

**Comment by seagle0128** [comment]
Wired! Did you set `battery-status-function`? If `battery-status-function` is nil, nothing will be displayed in the mode-line.

**Comment by algon-ns** [comment]
That is the solution I did find and set. It works on my iMAC, I've build anoter version for my MacBook Air, where the intended behaviour works OK (it shows the actual percent)
As my iMAC i old and are due for a new (when Apple release the new iMAC with the M1X chip), I think we should close the isuue here, as resources used is not justified for my old iMAC)
Thanks
