### ISSUE TITLE
How to show that the R is running in inferior ess R mode

### ISSUE THREAD

**Issue by fountainer** [seagle0128/doom-modeline#410]
When I use the default spaceline in spacemacs, the spaceline will show an icon that is rotating in inferior ess R mode, indicating the R is running. How can I configure doom-modeline to achieve similar functionality?

**Comment by seagle0128** [comment]
Since I am not using R, I am not sure if I understand the request. I did a quick check the codes of spaceline and ess-mode. If ess-mode is using `mode-line-process`, doom-modeline will display the status correctly, unless the default mode-line is re-defined.

**Comment by fountainer** [comment]
The following is the screenshot when there is no job running.
<img width="719" alt="Screen Shot 2021-01-21 at 7 02 31 PM" src="https://user-images.githubusercontent.com/5546074/105343465-9eeb6a00-5c1c-11eb-8aa5-11a259b040dc.png">
When R is running a job, an additional item appears in the mode line (in the red circle)
![Screen Shot 2021-01-21 at 7 02 57 PM](https://user-images.githubusercontent.com/5546074/105343629-d4905300-5c1c-11eb-9f64-c570a5a79167.jpg)
When no job is running, the screenshot using doom-modeline is like this:
<img width="744" alt="Screen Shot 2021-01-21 at 6 57 54 PM" src="https://user-images.githubusercontent.com/5546074/105344149-89c30b00-5c1d-11eb-8f81-8040b66fa49e.png">
When there is a job running, the screenshot is
<img width="737" alt="Screen Shot 2021-01-21 at 6 59 55 PM" src="https://user-images.githubusercontent.com/5546074/105344287-b545f580-5c1d-11eb-897f-ac2c6c585b81.png">
Actually, there is no difference between the mode lines whether there is a running job or not. However, spaceline can show a rotating icon (character)  indicating that there is a running job.

**Comment by seagle0128** [comment]
The process indicator is at the end of the mode-line. The status is from ess-mode. See https://github.com/emacs-ess/ESS/blob/1c77e93c9f810e95afe75b7f908bbc3aa50e219b/lisp/ess-mode.el#L307.

![image](https://user-images.githubusercontent.com/140797/105386097-f60a3280-5c4e-11eb-8396-e6cea04dc3ff.png)

**Comment by fountainer** [comment]
> The process indicator is at the end of the mode-line. The status is from ess-mode. See https://github.com/emacs-ess/ESS/blob/1c77e93c9f810e95afe75b7f908bbc3aa50e219b/lisp/ess-mode.el#L307.
> 
> ![image](https://user-images.githubusercontent.com/140797/105386097-f60a3280-5c4e-11eb-8396-e6cea04dc3ff.png)

This indicator just shows "run" when there is a process. It cannot tell whether R is computing or not. In the third screenshot, the R is not computing, because it can accept new commands. In the fourth screenshot, the R is computing, it cannot execute new commands for now. However, there is no difference between the two cases. It just shows "run" in both cases. With spaceline, when R is computing, the icon in the red circle appears. The icon does not show when R is not computing.

**Comment by seagle0128** [comment]
Honestly I don't know where is the status of spaceline from.

**Comment by wenjie2wang** [comment]
It is probably related to the variable `mode-line-buffer-identification`: https://github.com/emacs-ess/ESS/blob/b1d299c96e73dc892b0065c1617205dd4b9f8ab8/lisp/ess-tracebug.el#L597

**Comment by seagle0128** [comment]
Thanks, @wenjie2wang !

If so, `doom-modeline` doesn't support it. IMO it's tricky to modify `mode-line-buffer-identification` directly. It's better display the status in `mode-line-process` or `global-mode-string`. 

e.g.

```elisp
(add-to-list 'mode-line-process '(:eval (nth ess--busy-count ess-busy-strings)))
```

**Comment by wenjie2wang** [comment]
Thanks for the hint, @seagle0128 !   The following works for me:
```elisp
(advice-add 'inferior-ess-mode :after (lambda () (add-to-list 'mode-line-process '(:eval (nth ess--busy-count ess-busy-strings)))))
```
Not sure if it is the best way though.

**Comment by seagle0128** [comment]
@wenjie2wang I think it's better to use hook. Is there `inferior-ess-mode-hook`?

**Comment by wenjie2wang** [comment]
> @wenjie2wang I think it's better to use hook. Is there `inferior-ess-mode-hook`?

Yes.  Would you suggest the following?  It also works for me.
```elisp
(add-hook 'inferior-ess-mode-hook
          (lambda ()
            (add-to-list 'mode-line-process '(:eval (nth ess--busy-count ess-busy-strings)))))
```

**Comment by seagle0128** [comment]
Right! That's what I was suggesting. I will add this to FAQ.
