### ISSUE TITLE
Modification icon and major-mode icon are not uniform in height

### ISSUE THREAD

**Issue by brsvh** [seagle0128/doom-modeline#411]
**Describe**

I use the `modus-operandi` theme which is Emacs 28 built-in theme, and it has a border for the modeline by default. When I turn on `doom-modeline-buffer-modification-icon` and modify the buffer, the height of the modification icon causes a blank space above the bar to be displayed.

**Steps and Expected**

1. Enable `modus-operandi` theme.
![2021-01-23-173656_976x165_scrot](https://user-images.githubusercontent.com/63050399/105574773-c881ce00-5da1-11eb-9158-6e75699ce47d.png)

2. And create some modification
![2021-01-23-173706_976x165_scrot](https://user-images.githubusercontent.com/63050399/105574923-a3418f80-5da2-11eb-895d-751cb0347915.png)

The expected behavior is blank area are not appear.

**Environment:**
 - OS and version: Linux
 - Emacs Version: 28.0.50
 - Configuration: Vanilla Emacs
 - Package version: 20210116.2344

**Additional context**
NULL

**Comment by seagle0128** [comment]
Try set `doom-modeline-height` to bigger, e.g. `(setq doom-modeline-height 30)`.

**Comment by brsvh** [comment]
This option looks much better, I looked at the code and the history issue to get the reason of why icons are set up this way. Thanks for your reply!
