### ISSUE TITLE
The modeline has a big space in the middel, so the text to the right is truncated

### ISSUE THREAD

**Issue by algon-ns** [seagle0128/doom-modeline#413]
**Describe**
I'm not sure if it's a user error og something else, but it look like the window is too narrow

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

**Environment:**
 - OS and version: MacOS 10.12 High Sierra
 - Emacs Version: 28.0.50
 - Configuration: own conf https://github.com/algon-ns/nec.emacs.d
 - Package version: ?

**Additional context**
 Screenshots.
![modeline](https://user-images.githubusercontent.com/58687687/105735579-27774c80-5f34-11eb-8da3-af247e101fee.png)
.

**Comment by seagle0128** [comment]
This is a known issue. The root cause is the width of the icons are different, and the calculation is inaccurate.  

Try this snippet:
```elisp
(defun doom-modeline--set-char-widths (alist)
  "Set correct widths of icons characters in ALIST."
  (while (char-table-parent char-width-table)
    (setq char-width-table (char-table-parent char-width-table)))
  (dolist (pair alist)
    (let ((width 1)
          (chars (cdr pair))
          (table (make-char-table nil)))
      (dolist (char chars)
        (set-char-table-range table char width))
      (optimize-char-table table)
      (set-char-table-parent table char-width-table)
      (setq char-width-table table))))

(when (display-graphic-p)
  (doom-modeline--set-char-widths doom-modeline-rhs-icons-alist))
```
or set another font to mode-line. e.g.
```elisp
(with-eval-after-load 'doom-modeline
    (set-face-attribute 'mode-line nil :font "Menlo-12")
    (set-face-attribute 'mode-line-inactive nil :font "Menlo-12"))
```

**Comment by algon-ns** [comment]
Setting the width did not work, even by increase it to 2 and 3 (I did not try less than 1)
however setting the font did work, 
so thanks, I'm closing this issue here, but would like an enhancement, so I freelycould choose my font.

BTW. doom-modeline require the function "shrink-path", which my system did not require by default

**Comment by seagle0128** [comment]
> Setting the width did not work, even by increase it to 2 and 3 (I did not try less than 1)
> however setting the font did work,
> so thanks, I'm closing this issue here, but would like an enhancement, so I freelycould choose my font.
> 
> BTW. doom-modeline require the function "shrink-path", which my system did not require by default

Yes. `shrink-path` is required for shrinking the path of the buffer names. It's installed automatically via `package-install` from melpa.
