### ISSUE TITLE
Modeline gets misaligned and mispadded when adjusting frame font size and using multiple frames

### ISSUE THREAD

**Issue by thomasheartman** [seagle0128/doom-modeline#414]
**Describe**
When I resize a frame's font size (using `set-face-attribute`), this causes issues with doom modeline, pushing certain parts of the modeline outside of the buffer. Further, when using different font sizes in different frames, doom modeline seems to share the padding between the frames (with different font sizes), causing the mode line to fluctuate in size. The attached screen shot shows both of these issues.

**Steps and Expected**

**Reproduced with `emacs -Q`**. No configuration. Used straight for package fetching.

Steps:
1. start Emacs
2. install doom-modeline and activate it
3. create an extra frame
4. resize the font size in one of the frames using `(set-face-attribute 'default (selected-frame) :height <number>)`.
5. If you increase the font size, part of the modeline will be pushed to the right of the buffer edge.
6. Also, the modeline on the other frame might gain extra padding. I haven't been able to reproduce this 100%, but it happens often.

Please reproduce with `emacs -Q` and provide the minimal configurations and
steps.

**Environment:**
 - OS and version: Linux nixos 5.4.94 x86_64 GNU/Linux / NixOS 20.09
 - Emacs Version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)
 - Configuration:
   [Custom](https://github.com/thomasheartman/dotfiles/blob/main/.emacs.d/config.org),
   but reproduced with `emacs -Q`
 - Package version: `116c733fd580f729e275d3b6b3954667d5dfdd5a`

**Additional context**

This image shows the issue as it appears in an unconfigured Emacs instance. Notice the two white Emacs frames and ignore th erest of the image. The left one has increased font size, while the right one has the original size intact. The left frame's mode line cuts off, while the right frame's line has additional padding added.

![2021-02-05-172653_5040x4320_scrot](https://user-images.githubusercontent.com/17786332/107060544-62e90500-67d7-11eb-8517-997d65acbdc4.png)

This issue comes up because I use EXWM in a multi-monitor setup. As can be seen from the screenshot above, two of the monitors are the same resolution. However, they are very different in size. One is 16", while the other is 32". So while I like using a size of about 200 on the top one, I prefer 300 for the bottom one. Further, the monitor to the left looks tiny, but it's just a regular HD monitor. So while it looks smaller, it isn't actually, and I prefer reducing the size on that one to about 125. This mish-mash of frame sizes is why I've come across this issue. 

Also, because the modeline ends up flickering sometimes (due to resizing), this causes buffers and X windows to flicker too, which is quite annoying.

-----

Thanks for your time and input!

**Comment by teeann** [comment]
https://github.com/seagle0128/doom-modeline/issues/404

**Comment by seagle0128** [comment]
@thomasheartman You should set-face-attribute for mode-line and mode-line-inactive.

**Comment by thomasheartman** [comment]
Hey! 🙋🏾 Thanks for the input and sorry for the delay in getting back to you.

Does that trick work with relative font sizes? I tried it with a constant number and that seemed to work, but because the screen resolutions and sizes are so different, I'd like to be able to use a size relative to the frame font size.

Using relative sizes, I get the same issue again:

![2021-05-05-230344_2563x2093_scrot](https://user-images.githubusercontent.com/17786332/117209110-3785ae80-adf6-11eb-81c4-f261242a688a.png)

**Comment by seagle0128** [comment]
@thomasheartman Did you set `doom-modeline-height` as well? What's the values of `doom-modeline-height` and `(face-attribute 'mode-line :height)`?

**Comment by thomasheartman** [comment]
@seagle0128 I haven't changed it from the default, so `doom-modeline-height` is 25. 

It seems similar things happen with both relative and absolute font heights.

This is with a relative height of 0.8 
![2021-05-06-091926_3838x2091_scrot](https://user-images.githubusercontent.com/17786332/117257554-50b94a00-ae4c-11eb-9cb7-49c23ec706e4.png)


This is with an absolute height of 125:
![2021-05-06-092313_3838x2091_scrot](https://user-images.githubusercontent.com/17786332/117257931-b574a480-ae4c-11eb-86d2-39a0011d5d89.png)

To be clear, I'm using this piece of code to set the face attributes (mostly copied from #404):

```emacs-lisp
(set-face-attribute 'mode-line nil :height 125)
(set-face-attribute 'mode-line-inactive nil :height 125)
```

Also, I realize I might not have been clear about the outcome I'm looking for; sorry. What I'd want ideally is for the mode line to have height that's relative to its frame default face height and to adjust to the window width. If a relative height is problematic, then an absolute height is also a good solution.

Thanks again for your help! :pray:

**Comment by seagle0128** [comment]
According to the screenshots, you have two frame with different font size, correct?
So the solution should be like this:

```elisp
(set-face-attribute 'default (selected-frame) :height <number>)
(set-face-attribute 'mode-line (selected-frame) :height 0.8)
(set-face-attribute 'mode-line-inactive (selected-frame) :height 0.8)
```

Also, you can change `doom-modeline-height` accordingly if need.

**Comment by thomasheartman** [comment]
Yes, that's correct: two frames with different font sizes.

With what you suggest, I still get unexpected results:

![2021-05-06-121453_3837x2062_scrot](https://user-images.githubusercontent.com/17786332/117282165-b9acbc00-ae64-11eb-9cc2-256dc09fab17.png)

The padding and font sizes seem to vary rather wildly, and it's also strange how the font height sometimes becomes tiny for inactive windows.

**Comment by seagle0128** [comment]
Again, try 
```elisp
(setq doom-modeline-height 1)
```
or
```elisp
(defun doom-modeline--font-height ()
  "Calculate the actual char height of the mode-line."
    (frame-char-height))
```

**Comment by thomasheartman** [comment]
Alright! Sorry, didn't catch that. Here's with that line too (doesn't seem to make things much better):

![2021-05-07-130025_3839x2091_scrot](https://user-images.githubusercontent.com/17786332/117440325-35c20500-af34-11eb-9959-e1a0c8134786.png)

Am I doing something wrong? Maybe I'm missing something.

By the way, I used this bit of code to change the font sizes:

```emacs-lisp
  (defun my-change-frame-font-size-doom-modeline ()
    (interactive)
    (set-face-attribute 'default (selected-frame)
                        :height (string-to-number
                                 (read-string "Font height:")))
    (set-face-attribute 'mode-line (selected-frame) :height 0.8)
    (set-face-attribute 'mode-line-inactive (selected-frame) :height 0.8)
    (setq doom-modeline-height 1))
```

I also tried defining `doom-modeline--font-height`, but that didn't seem to change anything.

**Comment by seagle0128** [comment]
No idea. I couldn't reproduce on my MacBook. Just use absolute heights instead of relative heights.

**Comment by thomasheartman** [comment]
Huh, strange. I tried with absolute heigths too, but doesn't seem to make a difference, and I'm still experiencing both irregular padding and mode line text that runs outside of the window width.

Updated the code snippet to use this code instead:

```emacs-lisp
(defun my-change-frame-font-size-doom-modeline ()
  (interactive)
  (let ((frame (selected-frame)))
    (set-face-attribute 'default frame
                        :height (string-to-number
                                 (read-string "Font height:")))
    (let ((new-height (ceiling (* .8 (face-attribute 'default :height frame))))))
    (set-face-attribute 'mode-line (selected-frame) :height new-height)
    (set-face-attribute 'mode-line-inactive (selected-frame) :height new-height)
    (setq doom-modeline-height 1)))
```

Anyway: if you can't reproduce it and don't know what's going on, I'm just going to leave it be for now. Again: thank you very much for your help and for your patience! :pray:
