### ISSUE TITLE
Can't find buffer/file name in modeline

### ISSUE THREAD

**Issue by jingxlim** [seagle0128/doom-modeline#415]
Hello

**Describe**
I can't find the buffer/file name in my modeline when viewing `.el`, `.py`, `.org` and probably any other file. 

**Steps and Expected**

1. Opened doom, saw `~/doom.d/` displaying fine on the modeline.
![image](https://user-images.githubusercontent.com/16644710/107891346-0d55dc00-6eec-11eb-9d57-96dc2a643d3d.png)

2. Opened my doom `config.el` file but don't see file name in the modeline.
![image](https://user-images.githubusercontent.com/16644710/107891317-d2ec3f00-6eeb-11eb-80a8-744d2aa02081.png)

3. Launched doom emacs in a sandbox Doom + modules - your private config (M-x doom/sandbox C-c C-p) and then opened `config.el` as above -- was able to see file name in the modeline. At this point, I thought this issue has something do with my my private config files, so I sought to obtain a fresh install of doom.

4. Fresh install of doom (I followed instructions for using Doom emacs alongside other distribtions: https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-use-doom-alongside-other-emacs-configs). At this point, I have fresh emacs-doom directory and default .doom.d `config.el`, `packages.el` and `init.el` files.

5. Opened `config.el` and was not able to find file name in the modeline.

6. Once again, tried to launch doom emacs in sandbox and was able to once again find file name in the modeline.

Comparison of (left) fresh install of doom and (right) sandbox:

![image](https://user-images.githubusercontent.com/16644710/107894947-7004a300-6eff-11eb-89a5-fffe228f7ae3.png)

I did notice that the red debug spider is also missing...

Any help would be appreciated!

**Environment:**
 - OS and version: Windows 10 running Ubuntu 20.04 on WSL 1
 - Emacs Version: 27.1
 - Configuration: Doom
 - Package version: doom ui/modeline v2.0.9

**Additional context**

`M-x doom/info`: https://pastebin.com/T1sgUus6

**Comment by seagle0128** [comment]
You'd better inquiry in doom-emacs community firstly.

**Comment by oschonrock** [comment]
I have the same issue, since recent update of packages

**Comment by seagle0128** [comment]
@oschonrock Can you provide more information? e.g. logs, warnings, messages, backtrace, etc. And, please reproduce with `emacs -Q`.

**Comment by oschonrock** [comment]
@seagle0128 
I have pruned down this down to the minimum reproducible case:

`~/.emacs_minimal.el`
```lisp
(require 'package)

(package-initialize)

(require 'use-package)

(use-package doom-modeline
  :init (doom-modeline-mode +1))
```

`hello.cpp`
```c++
#include <iostream>

int main() {
  std::cout << "hello world\n";
}
```

and then 
```bash
emacs -Q -l ~/.emacs_minimal.el ~/.emacs_minimal.el hello.cpp
```

leads to this...

![Screenshot from 2022-03-10 12-15-52](https://user-images.githubusercontent.com/1681962/157659921-1e496b43-a3a4-45a2-8cce-cc2db736d868.png)

Note that the `lisp-mode` buffer has the filename but the `c++-mode` one does not. 

This is with

```
emacs --version
GNU Emacs 27.1
```
Standard ubuntu 20.04 build from repos.

**Comment by seagle0128** [comment]
Can you please evaluate this snippet and check the messages/warnings and the value of `doom-modeline--buffer-file-name` in your env?

```elisp
(defun doom-modeline-update-buffer-file-name (&rest _)
  "Update buffer file name in mode-line."
  (setq doom-modeline--buffer-file-name
          (save-match-data
            (if buffer-file-name
                (doom-modeline-buffer-file-name)
              (propertize "%b"
                          'face 'doom-modeline-buffer-file
                          'mouse-face 'mode-line-highlight
                          'help-echo "Buffer name
mouse-1: Previous buffer\nmouse-3: Next buffer"
                          'local-map mode-line-buffer-identification-keymap)))))
```

**Comment by oschonrock** [comment]
I wasn't quite sure how you wanted me to do this, but I ran emacs as shown in my last comment, and then, while in the c++ buffer I ran `M-:` (`eval-expression`) and pasted your snippet. 

That produced the following in the `*Messages*` buffer. 

```
doom-modeline-update-buffer-file-nameError during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (void-function project-root)
Error during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (void-function project-root)
user-error: Minibuffer window is not activeError during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (void-function project-root)

```
which sounds like that might be steering us into a useful direction? Can't find `project-root`?

**Comment by seagle0128** [comment]
@oschonrock Yes. That's what I want. Are you using the latest version of `doom-modeline`?

**Comment by oschonrock** [comment]
@seagle0128 
`M-x package-list-packages` 

```
...
  doom-modeline      20220310.335  available  melpa      A minimal and modern mode-line
...

```
is there a better way to check what is actually running?

**Comment by seagle0128** [comment]
Check`doom-modeline--project-root`. it should be 

```elisp
(defun doom-modeline--project-root ()
  "Get the path to the root of your project.
Return nil if no project was found."
  (or doom-modeline--project-root
      (setq doom-modeline--project-root
            (pcase (if (eq doom-modeline-project-detection 'auto)
                       (cond
                        ((fboundp 'ffip-get-project-root-directory) 'ffip)
                        ((fboundp 'projectile-project-root) 'projectile)
                        ((fboundp 'project-current) 'project)
                        (t 'default))
                     doom-modeline-project-detection)
              ('ffip
               (let ((inhibit-message t))
                 (ffip-get-project-root-directory)))
              ('projectile
               (projectile-project-root))
              ('project
               (when-let ((project (project-current)))
                 (expand-file-name (if (fboundp 'project-root)
                                       (project-root project)
                                     (cdr project)))))))))
```

**Comment by oschonrock** [comment]
@seagle0128  confusingly for me.. the `emacs -Q ...minimal` command above produces a slightly different `doom-modeline` version to the above (which I got from my "full-fat" `.emacs.el`). 

```
  doom-modeline      20220304.1816 installed  A minimal and modern mode-line

```
and as for your next question (tested in the "minimal" emacs in the c++ buffer)
`M-x describe variable` `doom-modeline--project-root`
```
doom-modeline--project-root is a variable defined in ‘doom-modeline-core.el’.
Its value is nil

  Automatically becomes buffer-local when set.

```
does that make sense? is `describe variable` the correct way to check for the existence of a `defun`?

**Comment by oschonrock** [comment]
@seagle0128 OK, I `package-delete`d 3 versions of `doom-modeline`, and then let `use-package` reinstall it....

problem gone. Thanks for your help. Sorry to waste your time.
