### ISSUE TITLE
Focus does not change properly on switching buffers.

### ISSUE THREAD

**Issue by simurgh9** [seagle0128/doom-modeline#416]
**Describe**
Upon switching buffers, the modeline in the buffer we switched to is not properly focused and the modeline we switched from is still in focus.
**Steps and Expected**

Run `emacs -Q -load path/to/testinit.el` with the content of `testinit.el` being the following,

```lisp
(package-initialize)
(require 'doom-modeline)
(doom-modeline-mode 1)
(add-hook 'after-init-hook #'doom-modeline-mode)
(global-set-key (kbd "C-o") '(lambda () (interactive) (other-window 1)))
```
**Environment:**
 - OS and version: Ubuntu 20.04.2 LTS
 - Emacs Version: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.13) of 2019-12-24
 - Configuration: Mi-own.
 - Package version: 20210124.1610

**Additional context**
![Peek 2021-02-17 15-07](https://user-images.githubusercontent.com/43047754/108274740-eccf9100-713a-11eb-897e-a176b26b7f9a.gif)
![pt](https://user-images.githubusercontent.com/43047754/108275048-5780cc80-713b-11eb-8303-3d6f264a0d04.gif)

**Comment by seagle0128** [comment]
Unfortunately I couldn't reproduce this issue on both Ubuntu and macOS.

Can you try this minimal configuration and provide more details?

```elisp
(package-initialize)
(require 'doom-modeline)
(doom-modeline-mode 1)
```

**Comment by simurgh9** [comment]
Here is the behaviour with the configs you gave ran with `emacs -Q -load path/to/testinit.el`.

![doom](https://user-images.githubusercontent.com/43047754/109075890-5e6d8900-76bf-11eb-96a0-021e17df1a85.gif)

As you can see, with mouse click, the modeline focus does not change at all. But, with the `C-x o`, the buffer you exit from gets incorrectly focused.

What more details could I provide?

**Comment by seagle0128** [comment]
Can you try this on your env?

```elisp
(add-hook 'buffer-list-update-hook #'doom-modeline-set-selected-window)
```

**Comment by simurgh9** [comment]
Yeah that fixes the issue!

**Comment by simurgh9** [comment]
When should I expect to see this update in melpa/elpa repositories?

**Comment by seagle0128** [comment]
Already in the latest version of melpa.
