### ISSUE TITLE
Modeline looks unfocused when using exwm

### ISSUE THREAD

**Issue by juacq97** [seagle0128/doom-modeline#417]
**Describe**
When using exwm, the modeline looks unfocused, you can see colors nor specific info that only appears on focused frames. Sometimes works again, mostly after creating a new frame.

**Steps and Expected**
- Start exwm, I used both a personak configuration and the default one. The default modeline works fine

**Environment:**
 - OS and version: Arch Linux
 - Emacs Version: 27.1
 - Configuration: github.com/juacq97/dotfiles
 - Package version: 20210124.1610

**Additional context**
 Not mine, but here's an screenshot of the latest SystemCrafters video, where you can see how all the modelines appears unfocused, but one frame is focused

![Screenshot_20210220-182220_NewPipe](https://user-images.githubusercontent.com/7623047/108612984-7cc74200-73aa-11eb-88f2-ed6f16a9e0ed.png)

**Comment by seagle0128** [comment]
Can you please try this snippet?

```elisp
(add-hook 'after-make-frame-functions #'doom-modeline-set-selected-window)
```

**Comment by juacq97** [comment]
> Can you please try this snippet?
> 
> ```emacs-lisp
> (add-hook 'after-make-frame-functions #'doom-modeline-set-selected-window)
> ```

I tried and worked! Thanks!
