### ISSUE TITLE
Date in doom-modeline

### ISSUE THREAD

**Issue by algon-ns** [seagle0128/doom-modeline#418]
**Describe**
The date in doom-modeline comes like. "day month date time", even I told the configuration several places. that I live in Europe. (where it should be "day , date month time")

**Steps and Expected**
I can't find, where doom-modeline get the date sting.

**Environment:**
 - OS and version: MacOS 10.12.6 High Sierra]
 - Emacs Version: [27.1 (Build 14F2511 of 2020-08-12]
 - Configuration: [own configurationl]
https://github.com/algon-ns/nec.emacs.d

Note: this is not at real big problem, just a little irritating....

**Comment by seagle0128** [comment]
Check `display-time-mode`, `display-time-format`.

**Comment by algon-ns** [comment]
Hi,
(setq display-time-format "\"%a, %d. %B %Y\"") do give an US-names like "Tue, 23. Feb 2021 22:08), so it's propably an error in emacs as I've set 
 (setq calendar-day-abbrev-array
        ["søn" "man" "tirs" "ons" "tors" "fre" "lør"]) and thatt work all other places I can think of:
