### ISSUE TITLE
Doom-modeline displays strangely when lose focus to mini-frame

### ISSUE THREAD

**Issue by JimDBh** [seagle0128/doom-modeline#419]
**Describe**
I use the pacakge mini-frame to display minibuffer in a child frame. But when using it with doom-modeline, the modeline appears mixed when I invoke any minibuffer related commands (e.g. M-x).

**Steps and Expected**

(require 'doom-modeline)
(doom-modeline-mode 1)
(require 'mini-frame)
(mini-frame-mode 1)

Then do M-x

**Environment:**
 - OS and version: linux
 - Emacs Version: 27.1
 - Configuration: emacs -q
 - Package version: current head

**Additional context**
![Screen Shot 2021-02-25 at 3 47 00 PM](https://user-images.githubusercontent.com/12157621/109234634-e9628800-7780-11eb-8cdb-3d540ff28b1a.png)

**Comment by seagle0128** [comment]
mini-frame is tricky. Change the behaviors of `doom-modeline` to the same with default mode-line.
