### ISSUE TITLE
Current version completely breaks Emacs

### ISSUE THREAD

**Issue by kevinji** [seagle0128/doom-modeline#42]
Using the current version of doom-modeline completely breaks Emacs (i.e. Emacs is unusable) when you access your dotfile (SPC f e d); there's a Projectile "Switch to project" window that you can't move your cursor from or exit out of. (You have to `kill -9` the emacs process in order to quit. :() Switching to the normal Spacemacs modeline fixes the issue.

If you turn on the debugger, there's a "Variable binding depth exceeds max-specpdl-size" error message, which might be helpful. I suspect it's either an issue with 3018171bc9a9047df51f423ebce2e3ec7b9ad690 or a9847abd3eef8fc8173366621690234778e85b9f, but I haven't looked too deeply into the issue.

**Comment by mc10** [comment]
What backtrace do you want?

**Comment by seagle0128** [comment]
Thanks for the information. That's helpful.

Did you try the latest version and have the same issue?
According to the backtrace, it may be related `persp`. I don't get any clue about `doom-modeline`.  Can you scroll down a little and attach the screenshot again?
