### ISSUE TITLE
Package / Feature with line(w) status

### ISSUE THREAD

**Issue by shadowrylander** [seagle0128/doom-modeline#420]
Hello!

As the title implies, what package or feature does `line(w)` denote? When active, it deletes lines in `evil-insert-state` upon pressing enter and then `i` immediately after.

Thank you kindly for the information!

**Comment by seagle0128** [comment]
I don't think I understand your request fully. Can you describe more details?

**Comment by shadowrylander** [comment]
Right; [this](https://imgur.com/a/99UY59z) screenshot, bottom-right on your modeline! What package does it indicate? I'd like to disabled that package, or at least change its functionality a bit.

**Comment by shadowrylander** [comment]
Oops.

**Comment by seagle0128** [comment]
Sorry, no idea. That's the question for you self. I don't know what packages you are using. You can check `mode-line-format`, `global-mode-string` or `mode-line-misc-info`, and all installed packages.

**Comment by shadowrylander** [comment]
Ah; fair enough. Thanks anyway!

**Comment by shadowrylander** [comment]
Found it; the package was `objed`!
