### ISSUE TITLE
Mode icon is rendered improperly

### ISSUE THREAD

**Issue by haluk** [seagle0128/doom-modeline#426]
**Describe**
Mode icon has some glitches while rendering.

**Environment:**
 - OS and version: Artix
 - Emacs Version: gccemacs
 - Configuration: Doom
 - Package version: develop

**Additional context**
https://streamable.com/phdbbk

**Comment by seagle0128** [comment]
Sorry! I couldn't access the link. Can you please attach the screenshots?

**Comment by haluk** [comment]
![image](https://user-images.githubusercontent.com/183110/110989210-2610b080-8337-11eb-8589-a4803bb4b819.png)

![image](https://user-images.githubusercontent.com/183110/110989165-198c5800-8337-11eb-9776-03459d03f62b.png)

**Comment by seagle0128** [comment]
Duplicated with #328.
