### ISSUE TITLE
Version 0.7.0 causes regexp error on all file buffer events

### ISSUE THREAD

**Issue by humanfactors** [seagle0128/doom-modeline#43]
Running Spacemacs on Windows 10 with Emacs .
`GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30`

Any time I open a file in Windows under the latest build I get the following: `replace-regexp-in-string: Invalid regexp: "Invalid back reference"`. It appears to be due to how emacs handles Windows path seperators, but I'm not very good with elisp.

The last working version of doom-modeline I have is #1a2226b242453f44886943f091f21a82f6be435c

```emacs-lisp
Debugger entered--Lisp error: (invalid-regexp "Invalid back reference")
  string-match("^C:\\Users\\12722330A\\" "c:/Users/12722330A/.emacs.d/" 0)
  replace-regexp-in-string("^C:\\Users\\12722330A\\" "~" "c:/Users/12722330A/.emacs.d/")
  shrink-path--dirs-internal("c:/Users/12722330A/.emacs.d/" nil)
  shrink-path-dirs("c:/Users/12722330A/.emacs.d/")
  shrink-path-prompt("c:/Users/12722330A/.emacs.d/")
  shrink-path-file-mixed("c:/Users/12722330A/.emacs.d/" "c:/Users/12722330A/.emacs.d/" "c:/Users/12722330A/.emacs.d/README.md")
  doom-modeline--buffer-file-name("c:/Users/12722330A/.emacs.d/README.md" "~/.emacs.d/README.md" shrink)
  doom-modeline-buffer-file-name()
  doom-modeline-update-buffer-file-name()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer README.md> "~/.emacs.d/README.md" nil nil "~/.emacs.d/README.md" (844424930135331 1812112669))
  find-file-noselect("c:/Users/12722330A/.emacs.d/README.md" nil nil nil)
  find-file("c:/Users/12722330A/.emacs.d/README.md")
  dired-find-file()
  funcall-interactively(dired-find-file)
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)
```

Thank you for maintaining this great addition to my workflow!

**Comment by seagle0128** [comment]
Which version or commit are you using? Did you upgrade to `20181113.2020` to try?

**Comment by humanfactors** [comment]
Yes, the `doom-modeline-20181113.2020` was the version that seemed to cause this issue. This issue seems to be that that something was stubbornly refusing to replace my home directory with unix path seperators (`C:\\Users\\12722330A\\`).

I've seemed to fix the issue by forcing my `HOME` variable in `.spacemacs.env` to use unix path seperators rather than the windows path seperators. Still not sure why issue only arose in `20181113.2020`. 

Thanks for your help again!

**Comment by seagle0128** [comment]
The issue is related to `$HOME` definitely. It works well if you don't add `\` at the end, but I still think it's a minor issue and report it here https://gitlab.com/bennya/shrink-path.el/issues/2.
