### ISSUE TITLE
[Compiling] Tag for PDFView in Mode-line

### ISSUE THREAD

**Issue by tdstoff** [seagle0128/doom-modeline#430]
**Describe the solution you'd like**
Typically the mode-line in a PDFView buffer will display a tag that says `[Compiling]` while the associated PDF is being overwritten by TeX. Doom-modeline unfortunately seems to disable this. Is There a way to integrate it?

**Describe alternatives you've considered**
Unfortunately I'm not aware of how/where the `[Compiling]` tag is parsed. My config has `doom-modeline-minor-modes` set to `t` which doesn't appear to help.

**Additional context**
![image](https://user-images.githubusercontent.com/43076118/113144318-1b8d5c80-91fb-11eb-847b-658a3146ad87.png)

**Comment by seagle0128** [comment]
It may be displayed by other minor modes. Can you check what minor modes you are using?

**Comment by tdstoff** [comment]
Sure, here's the list of minor modes from the PDFView buffer when I have Doom-Modeline on:

`Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Column-Number Default-Text-Scale Desktop-Save
Diredfl-Global Doom-Modeline Electric-Indent File-Name-Shadow
Font-Lock Global-Auto-Complete Global-Eldoc Global-Font-Lock
Global-Git-Commit Global-Hl-Line Global-Undo-Tree Line-Number
Magit-Auto-Revert Menu-Bar Mouse-Wheel My-Keys Override-Global
Pdf-Annot Pdf-Cache-Prefetch Pdf-History Pdf-Isearch Pdf-Links
Pdf-Misc Pdf-Misc-Context-Menu Pdf-Misc-Menu-Bar
Pdf-Misc-Size-Indication Pdf-Occur-Global Pdf-Outline Pdf-Sync Pyvenv
Shell-Dirtrack Solaire Solaire-Global Tex-Pdf Tool-Bar Tooltip
Transient-Mark Treemacs-Filewatch Treemacs-Follow
Treemacs-Fringe-Indicator Treemacs-Git Undo-Tree Winner`

The only minor mode that disappears from the list when I turn Doom-Modeline off is the Doom-Modeline one.

**Comment by seagle0128** [comment]
`[Compiling]` seems an indicator of a process. I guess it's related to `tex-pdf-mode`? I am not using it, so cannot reproduce.

**Comment by seagle0128** [comment]
@tdstoff Would you please check the latest version? I suppose the tag is supported.

**Comment by tdstoff** [comment]
Sure, I just checked the latest version but it's still not there during a LaTeX compile. I see now that it comes from the variable `mode-line-modes`. Mine has this entry at the top:
```
((compilation-in-progress
  #("[Compiling] " 0 12
    (help-echo "Compiling; mouse-2: Goto Buffer" mouse-face mode-line-highlight local-map
               (keymap
                (mode-line keymap
                           (mouse-2 . compilation-goto-in-progress-buffer))))))
```
There a fairly recent [package](https://github.com/haji-ali/procress) which creates a Doom compatible modeline segment with more useful information. Using that has been a sufficient solution for me.

**Comment by seagle0128** [comment]
```elisp
((compilation-in-progress
  #("[Compiling] " 0 12
    (help-echo "Compiling; mouse-2: Goto Buffer" mouse-face mode-line-highlight local-map
               (keymap
                (mode-line keymap
                           (mouse-2 . compilation-goto-in-progress-buffer))))))
```

The same info has been added to `compilation` segment of `doom-modeline`.
Please check `mode-line-format` and `(doom-modeline-format--pdf)` in the pdf buffer, to see if `compilation` segment exists.

**Comment by tdstoff** [comment]
That did it! Thank you.

![Xnip2022-10-11_08-58-51](https://user-images.githubusercontent.com/43076118/195098580-f07b2cad-cf2b-430b-99da-ab25c46ceaa6.jpg)
