### ISSUE TITLE
Height problems with flycheck-mode on

### ISSUE THREAD

**Issue by wedens** [seagle0128/doom-modeline#44]
flycheck-mode off:
![image](https://user-images.githubusercontent.com/697162/48539823-e4000d00-e8ea-11e8-9978-67479caba47d.png)

flycheck-mode on:
![image](https://user-images.githubusercontent.com/697162/48539806-d185d380-e8ea-11e8-9564-4e6a6a9f7362.png)

Notice some padding on the top side.

I've tried with different fonts (Fantasque Sans Mono, Fira Code). all-the-icons fonts are installed with `all-the-icons-install-fonts`. Font size is 16.

If I set modeline height to >= 40 or set font size to <= 10, the problem goes away.

doom-modeline revision: 781ce1b
emacs: 26.1

**Comment by seagle0128** [comment]
Can you please set `doom-modeline-height` to 29 or above to try?

**Comment by wedens** [comment]
Yeah, I've already updated the description. Problem disappears with height >= 40.

**Comment by seagle0128** [comment]
Good! It's should be related to font size. I am closing it.

**Comment by wedens** [comment]
> I suppose you are using Linux, right?

Yes I do.

> Good! It's should be related to font size of all-the-icons. 

Sorry, but how can I adjust it? Changing `all-the-icons-scale-factor` doesn't seem to change size of flycheck mode icons in modeline (other icons (e.g. git branch) change).

Having modeline that high or font size that small is not a good option 😉

**Comment by wedens** [comment]
My _guess_ is that `doom-modeline-icon` hard-codes icon size or something.

**Comment by seagle0128** [comment]
Yes. It's hard coded.

Try evaluating this snippet:
```elisp
(defun doom-modeline-icon (icon &optional text face voffset)
  "Displays an ICON with FACE, followed by TEXT.
Uses `all-the-icons-material' to fetch the icon."
  (concat (if vc-mode " " "  ")
          (when icon
            (concat
             (doom-modeline-icon-material icon :face face :height 0.9 :v-adjust (or voffset -0.2))
             (if text doom-modeline-vspc)))
          (if text (propertize text 'face face))
          (if vc-mode "  " " ")))
```

**Comment by wedens** [comment]
The problem doesn't go away completely, but changing `:height` to smaller value makes it less noticeable.

**Comment by wedens** [comment]
Some arbitrary combination of `doom-modeline-height` and `:height` in `doom-modeline-icon` and removed  `:v-adjust` seems to make modeline height consistent and icons centered 😒

**Comment by seagle0128** [comment]
Do you mean keeping `:height` is 1.1 and removing `:v-adjust` address this issue? Does it impact other  segments?

**Comment by wedens** [comment]
Unfortunately, with the latest updates (I'm at `94b1aa2`)  this issue is back.

**Comment by wedens** [comment]
I think this https://github.com/seagle0128/doom-modeline/commit/8aeb80f32ded833908a425aa97ffb4d1688c5893 commit re-introduced the problem.

**Comment by seagle0128** [comment]
Sorry. It's really hard to adjust icons' position.

**Comment by SolitudeSF** [comment]
now the icons are not displayed at all.
