### ISSUE TITLE
Always display certain parameters on bottom modeline

### ISSUE THREAD

**Issue by lochlainn** [seagle0128/doom-modeline#440]
**Problem**
I use the time and battery settings on the modeline, and while they don't show on child frames, they move to whichever window I currently have selected. This is nice for features about the current window or buffer, but I prefer to always have the time and battery at the same place on my screen, no matter what I'm editing.

**Solution**
Is it possible to specify for certain modeline info/segments to be *always* displayed on the bottom-most buffer? This may already be a feature that I'm missing elsewhere.

**Comment by seagle0128** [comment]
I don't think there has been the feature. Honestly I am very clear of the requirement and what's the value. 
Anyway, you can redefine your own mode-line as described in FAQ 5.

**Comment by jonpalmisc** [comment]
I would also be interested in this feature, or more specifically, the ability to set a single modeline layout to apply to **all buffers**.

**Comment by seagle0128** [comment]
@jonpalmisc I know some package of displaying the mode-line in echo-area. They seem matching your requirement. You can google it. But it's not the goal of `doom-modeline`.
