### ISSUE TITLE
Modeline height stuck at minimum with modeline bar and modeline icons disabled

### ISSUE THREAD

**Issue by jacksonludwig** [seagle0128/doom-modeline#447]
**Describe**
When both modeline icons and modeline bar are disabled, the height of the modeline does not change. It seems to be "stuck" at whatever height the text is.

**Steps and Expected**
Using the following config, you can see the issue. Even though I set the height to some huge value, the modeline height is still just enough to fit the text.

```emacs
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq doom-modeline-bar nil)
(setq doom-modeline-icon nil)
(setq doom-modeline-height 100)
(straight-use-package 'doom-modeline)
(doom-modeline-mode)
```

**Environment:**
 - OS and version: ubuntu 20.04
 - Emacs Version: 28, native comp enabled
 - Package version: current master

**Comment by seagle0128** [comment]
I have to say it's as designed. The height of mode-line is kept by the bar/hud.
