### ISSUE TITLE
Doom-modeline-mode causes Dart-mode to eat a lot of memory and slow it down to crawl

### ISSUE THREAD

**Issue by natrys** [seagle0128/doom-modeline#449]
**Describe**
When doom-modeline is activated, even simple navigation (C-n/C-p) in a Dart-mode buffer causes huge amount of garbage collection, rendering Emacs nearly unusable.

**Steps and Expected**
This is an example Dart file: https://gist.github.com/natrys/d5316ad4b832afa60bc1956be40b8373

Dart-mode and Doom-modeline both installed from melpa (dart-mode-20210301.0 and doom-modeline-20210526.1833).

When run in `emacs -Q` with only this evaluated: 

``` elisp
(require 'package)
(setq package-user-dir (expand-file-name "elpa" user-emacs-directory))
(package-initialize)
```

Opening the dart file and doing C-n/C-p behaves expectedly. This is normal profiler report:

![before](https://user-images.githubusercontent.com/32647404/119738981-62b66780-bea3-11eb-8e28-277c1358050e.png)

With doom-modeline-mode enabled (e.g.)

``` elisp
(require 'doom-modeline)
(doom-modeline-mode 1)
```

Same file now is almost unusable:
![after](https://user-images.githubusercontent.com/32647404/119739159-9abdaa80-bea3-11eb-950c-bcb057b1d21e.png)

The effect on `line-move` function seems particularly grievous in the profiler report.

**Environment:**
 - OS and version: Void Linux
 - Emacs Version: GNU Emacs 28.0.50 (build 1, x86_64-unknown-linux-gnu, X toolkit, cairo version 1.16.0) of 2021-05-16 (with nativecomp)
 - Package version: 20210526.1833

**Comment by seagle0128** [comment]
I couldn't reproduce in my local env. And, according to the profile reports above, I didn't see any clue. Actually there is no any `doom-modeline` functions in the backtrace.

**Comment by natrys** [comment]
Ugh, I just built Emacs git head and ran it from clean profile, still can reproduce. And indeed there is none of doom-modeline functions in backtrace, so this can only be due to some sort of side-effect I guess (which cleans itself up as the problem goes away when I disable doom-modeline in same session).

**Comment by natrys** [comment]
Actually fully expanded backtrace does show doom-modeline functions in the problem chain.

![new](https://user-images.githubusercontent.com/32647404/119812538-0fc3cb00-bf0a-11eb-9d56-81336568d30b.png)

**Comment by seagle0128** [comment]
In the backtrace, `doom-modeline` consumes 0% CPU.

**Comment by natrys** [comment]
Yeah it's most likely trigger of unintended side-effect elsewhere than a bug in doom-modeline per se. Perhaps Dart-mode tracker would be more appropriate place for the issue if I can't solve it, seeing this doesn't happen anywhere else. 

I hope it's fine if I leave this open for a bit here in case someone else can reproduce (or not).
