### ISSUE TITLE
Half of Flymake icon is rendered outside the screen

### ISSUE THREAD

**Issue by MintSoup** [seagle0128/doom-modeline#450]
**Describe**
The Flymake icon gets cut off.

**Steps and Expected**
Enable Flymake.

Here, the `1` is clipped off.
![doom1](https://user-images.githubusercontent.com/15715189/119981529-ca1d0600-bfce-11eb-928e-aea1be27b312.png)
And here, when we have no errors, the tickmark is barely displayed, most of it gets cut off from the screen.
![doom2](https://user-images.githubusercontent.com/15715189/119981534-cb4e3300-bfce-11eb-8f5e-9bb83748df47.png)

The screenshots are from the bottom right corner of my screen. From #211 it appears that the icon has 2-char width, which messes up the modeline's width calculations. [One of the solutions](https://github.com/seagle0128/doom-modeline/issues/211#issuecomment-523808957) suggested adding the icon to `doom-modeline-rhs-icons-alist`, but I don't know how I can get the id/number of the icon. I believe a better solution would be to fix the font issue, but isn't that an error in `all-the-icons`, instead of a user-selected font?

**Comment by seagle0128** [comment]
What minor modes are you using? Are able to reproduce with `emacs -Q`?

**Comment by MintSoup** [comment]
@seagle0128 
```company-mode lsp-completion-mode flymake-mode lsp-diagnostics-mode lsp-headerline-breadcrumb-mode lsp-modeline-code-actions-mode lsp-modeline-diagnostics-mode lsp-modeline-workspace-status-mode eldoc-mode lsp-managed-mode font-lock-mode lsp-ui-sideline-mode lsp-ui-mode lsp-mode evil-local-mode evil-collection-unimpaired-mode evil-snipe-local-mode evil-snipe-override-local-mode evil-surround-mode anzu-mode visual-line-mode display-line-numbers-mode rainbow-delimiters-mode highlight-numbers-mode auto-save-mode``` are enabled.

When I disable lsp-mode, the icon comes back into the screen, so it's almost like the lsp icon is "pushing" the flymake icon out of the screen.

**Comment by seagle0128** [comment]
Can you try the latest version? Or try other fonts?

**Comment by MintSoup** [comment]
@seagle0128 Updating to the latest version seems to have fixed the issue. Thanks.
