### ISSUE TITLE
Is there a way to reduce the padding on the top and bottom?

### ISSUE THREAD

**Issue by linwaytin** [seagle0128/doom-modeline#453]
Thanks for this great package!
I've used it for a long time. Everything is fine but I always feel it is "thick" in the vertical direction.
The height is controlled by the font size, but I don't want to reduce the font size.
I think there are some padding on the top and bottom of the bar.
Is there a way to reduce the padding?
Or any other way to make it thinner but keep the font size the same?

**Comment by seagle0128** [comment]
Did you try `doom-modeline-height` option?

**Comment by linwaytin** [comment]
Yes, but it's limited by my font size.

**Comment by seagle0128** [comment]
You have two solutions:

1. Remove bar segment and disable icons.
2. Use smaller font.

**Comment by linwaytin** [comment]
Ok thanks.

**Comment by memeplex** [comment]
Anyway, even if I'm still interested in the answer to question 2, I've been debugging a bit and I believe there might be a problem with `doom-modeline--font-height`:

```elisp
     (* (if (and (>= emacs-major-version 27)
                 (not (eq system-type 'darwin)))
            1.0
          (if doom-modeline-icon 1.68 1.25))
```

my system type is darwin and I haven't disabled the modeline icons altogether, but 1.68 seems like a lot to hardcode there, take a look a the icons in the screenshots above, they are far from being that big. Where is that number coming from? Why just for macOS?

**Comment by memeplex** [comment]
For now I'm working around this with

```elisp
  (defun my-doom-modeline-advice (fun &rest args)
    (let ((system-type 'not-darwin))
      (apply fun args)))
  (advice-add #'doom-modeline--font-height :around #'my-doom-modeline-advice)
```
but I would like to help finding a better solution to the issue. Compare the initial situation with the "not-darwin" one:

![image](https://user-images.githubusercontent.com/2845433/136680134-1cd32a3e-5349-41f3-80e8-1053e6a801de.png)

This is by all means saner.

**Comment by memeplex** [comment]
```elisp
(setq doom-modeline-height 0
      doom-modeline-width 0)
```

Nop. In fact nothing short of changing that hardcoded 1.68 will do it. I believe that's the issue, 1.68 scaling factor is like a lot and no icon I've seen so far seems to require such amount of padding. Having to disable icons just to get 1.25 is an all-or-nothing proposition. I'd suggest adding a max height scaling or whatever option, but it's probably worth discussing why such a large scaling is the default before adding new options.
