### ISSUE TITLE
maybe  the latest affect the normal use of eglot

### ISSUE THREAD

**Issue by xwkwh** [seagle0128/doom-modeline#454]
**Describe**
There is a problem with the plug-in. When emacs uses eglot reconnect gopls, the following error will be reported through binary search and sorting. After binary search, doom-modeline is blocked. This phenomenon no longer occurs. I hope developers will update and solve it as soon as possible.

```
error,Process EGLOT (***) not running
```

**Environment:**
 - Mac OS 11.3.1
 - Emacs Version:  GNU 27.1
 - Configuration: eglot 
 - Package version: lastest
 
**Additional context**

**Comment by seagle0128** [comment]
I am confused, Does this issue exist or not? How to reproduce? Please provide more details.

**Comment by seagle0128** [comment]
I can confirm elgot+gopls does work well in Centaur. Please check your own env.
