### ISSUE TITLE
Modeline items do not fit under emacsclient

### ISSUE THREAD

**Issue by abbec** [seagle0128/doom-modeline#455]
**Describe**
When using doom-modeline in emacsclient, the modeline items do not fit.

**Steps and Expected**
In an emacsclient frame it looks like this:

![emacsclient](https://user-images.githubusercontent.com/455022/122472808-5795b980-cfc1-11eb-9990-d7c3788c6f72.png)

or

![image](https://user-images.githubusercontent.com/455022/122473880-b9a2ee80-cfc2-11eb-8a6e-6f9d64627d5f.png)

(note how the green checkmark is not fully visible)

whereas in emacs it looks like this:

![emacs](https://user-images.githubusercontent.com/455022/122472887-6f6d3d80-cfc1-11eb-8617-e164b316744d.png)

Another example:

Here is the same file in emacs (top) and emacsclient (bottom). Both windows are the exact same size.

![image](https://user-images.githubusercontent.com/455022/122474728-e9062b00-cfc3-11eb-91cb-dfe752e8408a.png)

**Environment:**
 - OS and version: Fedora 34
 - Emacs Version: 27.2
 - Configuration: n/a
 - Package version: latest with straight

**Comment by abbec** [comment]
Note that I can only reproduce this when running emacs as a daemon (not with `server-start`).

**Comment by abbec** [comment]
Narrowing it down further, the issue seems to be these lines:

```elisp
(add-to-list 'default-frame-alist
             '(vertical-scroll-bars . nil))

(add-to-list 'default-frame-alist
             '(horizontal-scroll-bars . nil))
```

That I use to remove the scrollbars. If I do not have those, the modeline works fine. Is this expected?

**Comment by abbec** [comment]
Thanks! Much appreciated! 😊

**Comment by seagle0128** [comment]
@abbec I made a minor patch just now. Please try the latest version.
