### ISSUE TITLE
doom-modeline-mu4e literally doesn't work?

### ISSUE THREAD

**Issue by hrqmonteiro** [seagle0128/doom-modeline#456]
I'm trying to set the `setq doom-modeline-mu4e t` to show my mu4e notifications and it simply won't work.

I have mu4e set properly and it runs on the background, i have `mu4e-alert` but it doesn't show any notification in any buffer.

**Comment by seagle0128** [comment]
@seanfarley Is it working for you? Can you please take a look at this issue?

**Comment by seanfarley** [comment]
Yes? I haven't had any problems but it seems two things are being conflated here: the number of unread emails and a notification (perhaps alert.el) of new emails, yes? The modeline only shows the number of unread emails like so:

<img width="266" alt="Screen Shot 2021-06-19 at 12 15 34 PM" src="https://user-images.githubusercontent.com/20887/122650370-0e945100-d0f8-11eb-8cd6-18b3a32fd6b7.png">

Is that number not showing up in the modeline? You might want to also check that some emails are unread. I think the segment doesn't display at all if there are no unreads.

**Comment by hrqmonteiro** [comment]
> Yes? I haven't had any problems but it seems two things are being conflated here: the number of unread emails and a notification (perhaps alert.el) of new emails, yes? The modeline only shows the number of unread emails like so:
> 
> <img alt="Screen Shot 2021-06-19 at 12 15 34 PM" width="266" src="https://user-images.githubusercontent.com/20887/122650370-0e945100-d0f8-11eb-8cd6-18b3a32fd6b7.png">
> 
> Is that number not showing up in the modeline? You might want to also check that some emails are unread. I think the segment doesn't display at all if there are no unreads.

Well i have a lot of unread e-mail, probably more than a thousand.

I have to do anything else than having mu4e-alert installed and `(setq doom-modeline-mu4e t)`?

**Comment by seanfarley** [comment]
Hmmm, you'll probably have to start debugging to see where the problem is. Try inspecting the value of `mu4e-alert-mode-line`.  Are you using Doom Emacs? Or just this package alone?

**Comment by seagle0128** [comment]
@hrqmonteiro Any update?

**Comment by hrqmonteiro** [comment]
> Hmmm, you'll probably have to start debugging to see where the problem is. Try inspecting the value of `mu4e-alert-mode-line`. Are you using Doom Emacs? Or just this package alone?

> @hrqmonteiro Any update?

Sorry for the delay, i was off for a little while.

As of today, i have this set:

```
(setq mu4e-alert-notify-repeated-mails t)
(setq mu4e-alert-enable-notifications t)
``'

And, on the modeline configs, i have:

```
(after! doom-modeline
  (setq doom-modeline-mu4e t))
```

But it doesn't show the notifications icon.

Although, if i manually do: `M-x` > `mu4e-alert-enable-mode-line-display` it does shows the icon:

![~mu4e](https://user-images.githubusercontent.com/17055027/127167756-62cf3ebf-6cea-45da-9f7a-c589ae5152c5.png)

So, any tips on how do i set this to be shown automatically and with no need of setting it manually everytime?

**Comment by seanfarley** [comment]
> Although, if i manually do: `M-x` > `mu4e-alert-enable-mode-line-display` it does shows the icon:
 
Ah, yes, that is indeed needed to activate it ... though, I don't remember why it isn't done in `doom-modeline`? @seagle0128 do you remember why or was it an oversight?

**Comment by seagle0128** [comment]
No idea. But I thought it was designed.

**Comment by seanfarley** [comment]
Ah, right, I think it was so projects like this and Doom could put in the mu4e modeline segment without having a dependency on mu4e or mu4e-alert.

**Comment by seagle0128** [comment]
@seanfarley so, maybe FAQ should be updated for mu4e? would you please add something?

**Comment by seanfarley** [comment]
Sure, I can do that

**Comment by seagle0128** [comment]
Thank you, folks! 👍🏻
