### ISSUE TITLE
How to show org-clock in modeline for all mode?

### ISSUE THREAD

**Issue by wztdream** [seagle0128/doom-modeline#457]
Hi, doom-modeline is great, but seems can not show org-clock, so is it possible to show org-clock in doom-modeline?

**Comment by seagle0128** [comment]
`org-clock` is displayed in `doom-modeline`, via `org-mode-line-string` and `global-mode-string`.
See the screenshot below.

![image](https://user-images.githubusercontent.com/140797/124507432-62917c00-de00-11eb-9354-2dcf642be365.png)

If you don't like this style, you can define your own segment to replace it.

**Comment by wztdream** [comment]
> `org-clock` is displayed in `doom-modeline`, via `org-mode-line-string` and `global-mode-string`.
> See the screenshot below.
> 
> ![image](https://user-images.githubusercontent.com/140797/124507432-62917c00-de00-11eb-9354-2dcf642be365.png)
> 
> If you don't like this style, you can define your own segment to replace it.

My mistake, the issue is in python mode, the org-clock is gone, so it is better to show org-clock in all modes, how to do that?

**Comment by seagle0128** [comment]
`org-clock` is displayed everywhere unless it's removed from `global-mode-string` or `mode-line-misc-info`.
Simply,  eval `(doom-modeline-set-main-modeline)` in python buffers.

**Comment by wztdream** [comment]
Thank you, but eval `(doom-modeline-set-main-modeline)` not work, there is still no org-clock. And the value of `global-mode-string` is:
```
((t
  (:eval lsp-modeline--code-actions-string))
 (t
  (:eval
   (lsp-modeline--diagnostics-update-modeline)))
 (t
  (:eval
   (-keep #'lsp--workspace-status-string
          (lsp-workspaces)))))
Local in buffer test.py; global value is 
("" org-mode-line-string)
```
value of `mode-line-misc-info` is:
```
((which-function-mode
  (which-func-mode
   (#1="" which-func-format " ")))
 (global-mode-string
  (#1# global-mode-string " "))
 (eyebrowse-mode
  (:eval
   (eyebrowse-mode-line-indicator))))
```
It seems in python mode the `global-mode-string` is modified as buffer local value, but I have no idea which package or layer did that, any idea?

**Comment by wztdream** [comment]
@seagle0128 
I reported this issue to lsp-mode too, but when I use spacemacs mode-line, there is no such issue, so maybe doom-mode-line should update the buffer-local value of `global-mode-string` too? I am not sure this should be done in doom-mode-line or in lsp-mode?

**Comment by seagle0128** [comment]
I am using lsp-mode and doom-modeline, and org-clock is displayed correctly as below.
Are you able to reproduce with `emacs -Q`?

If you are using `doom-emacs` or your personal configuration, you should check your configurations.

![image](https://user-images.githubusercontent.com/140797/124636938-b01eef00-debb-11eb-8c22-69f9fabe04ff.png)

**Comment by wztdream** [comment]
> I am using `lsp-mode `and `doom-modeline`, and `org-clock` is displayed correctly as below.
> Are you able to reproduce with `emacs -Q`?
> 
> The value of `global-mode-string` is:
> 
> ```emacs-lisp
> (((t lsp-java-progress-string))
>  org-mode-line-string)
> ```
> 
> If you are using `doom-emacs` or your personal configuration, you should check your configurations.
> It seems `lsp-mode` modified `global-mode-string` in your env.
> 
> ![image](https://user-images.githubusercontent.com/140797/124636938-b01eef00-debb-11eb-8c22-69f9fabe04ff.png)

I use spacemacs, bellow is how you can reproduce it:
1. close emacs
2. open emacs
3. open .py file  ;; here lsp-mode will create buffer local setting (**this step must first**)
4. open .org file
5. clock in a task in .org file ;; clock in only modify global value, so no org-clock in .py file

bellow is test results:

1. emacs -Q   ;; no issue
2. emacs -q -l lsp-start-plain.el ;; no org-clock
3. use spacemacs only install python layer (which will install lsp layer) remove all personal configuration ;; no org-clock

**Comment by seagle0128** [comment]
I am not using spacemacs. But, I took a look at the source codes of `spaceline`. `spaceline` defines a new `org-clock` segment to display. I suggest to check if the value of `global-mode-string` is same as with `doom-modeline`. The root cause is `lsp-mode` modified `global-mode-string`. That's why you was not able to reproduce with `emacs -Q`.

So, the solution may be:
1. Report and track the issue of `lsp-mode`.
2. Define `org-clock` segment in `doom-modeline`.
3. Change the lsp-mode configurations. Refer to [here](https://github.com/seagle0128/.emacs.d/blob/78f1d7e806162344c7e3f6011bfeba1ff85b1d1f/lisp/init-lsp.el#L121-L134)
