### ISSUE TITLE
Emacs in daemon mode still has mis-alignment

### ISSUE THREAD

**Issue by victorolinasc** [seagle0128/doom-modeline#459]
First of all: thanks a lot for this package and all of your work on Emacs! Really appreciate it.

**Describe**

When starting Emacs with doom-modeline in daemon mode (through systemd user unit) it shows with plenty of glitches. Here is a sample after opening the emacsclient graphical frame:

![image](https://user-images.githubusercontent.com/376386/125287401-3e97d400-e2f3-11eb-9fe3-d18657b61e14.png)

Then, I disable the modeline and re-enable it (with M-x doom-modeline-mode) and it shows like this:

1. After disabling:

![image](https://user-images.githubusercontent.com/376386/125287556-74d55380-e2f3-11eb-830f-7caa2b55a30c.png)

2. Adter re-enabling (notice it does not fit properly):

![image](https://user-images.githubusercontent.com/376386/125287630-8b7baa80-e2f3-11eb-88df-461fd37f27a2.png)

So, trying to get it to show properly I close the emacsclient and open a new instance and then it shows correctly Oo (now it looks awesome):

![image](https://user-images.githubusercontent.com/376386/125287748-aea65a00-e2f3-11eb-8afc-881eb11eadfc.png)

Not sure exactly what is going on here and not even sure if this is a doom-modeline bug. I decided to post this here because I am trying to make package developers more aware of daemon bugs.

**Steps and Expected**

- Install doom-modeline from MELPA (below is my `use-package` configuration)
- Configure emacs daemon mode with systemd unit file (I can post the unit contents here if desired)
- add this configuration

```elisp
(use-package doom-modeline
  :hook (window-setup . doom-modeline-mode)
  :custom
  (doom-modeline-height 35)) ; this is me trying to fix the FIRST time I open the frame
```
- start the emacsclient graphical frame

**Environment:**
 - OS and version: Linux Manjaro KDE kernel 5.11 amd64
 - Emacs Version: built from master (28.0.xxx)
 - Configuration: custom
 - Package version: 20210706.604

**Comment by seagle0128** [comment]
If you are using daemon, please try this snippet

```elisp
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  :custom  (doom-modeline-height 35)) 
```

or 

```elisp
(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom  (doom-modeline-height 35)) 
```

**Comment by victorolinasc** [comment]
Tried them both and they all have the exact same behaviour in my case.

**Comment by seagle0128** [comment]
Can you please eval this snippets and provides the results?

```elisp
;; See return values
(daemonp)
(frame-parameter nil 'client)

;; See var value
C-h v after-make-frame-functions

;; Check mode-line after eval
(doom-modeline-set-char-widths)
```

**Comment by victorolinasc** [comment]
Sure!

Doing that after I've done de disabling and reenabling and closed and opened a new frame (which shows everything correctly):

```elisp
(daemonp) => t
(frame-parameter nil 'client) => #<process server <4>>

;; See var value
C-h v after-make-frame-functions => 
(doom-modeline-refresh-font-width-cache
 doom-modeline-set-selected-window
 doom-modeline-set-char-widths
 x-dnd-init-frame)

;; Check mode-line after eval
(doom-modeline-set-char-widths) => nil
```

Re-initializing the server through `systemctl --user restart emacs.service`

Re-checking values without re-enabling de modeline:

```elisp
(daemonp) => t
(frame-parameter nil 'client) => #<process server <1>>

;; See var value
C-h v after-make-frame-functions => 
(doom-modeline-refresh-font-width-cache
 doom-modeline-set-selected-window
 doom-modeline-set-char-widths
 x-dnd-init-frame)

;; Check mode-line after eval
(doom-modeline-set-char-widths) => nil
```

**Comment by seagle0128** [comment]
Any changes of mode-line before and after evaluating `(doom-modeline-set-char-widths) ` ?

**Comment by victorolinasc** [comment]
Nope! No visual changes at all.

**Comment by seagle0128** [comment]
I couldn't reproduce on Ubuntu and macOS, with 28.

**Comment by victorolinasc** [comment]
I'll see what part of my configuration might be changing that!

In any case, thanks for digging into this. Since it is not reproducible should I close this?

**Comment by seagle0128** [comment]
Yes. Please close it, but feel free to reopen if you find any new clues. Thanks!

**Comment by victorolinasc** [comment]
I've kinda found the issue... 

I was setting my faces in a `server-after-make-frame-hook` hook to have the same color of the cursor in TUI and GUI. After removing that it worked out of the box.

Sorry for the noise and once again thanks for your awesome work!

**Comment by victorolinasc** [comment]
Just to give the example here:

I had something like this:

```elisp
;; Ensure cursor has the same color when run on daemon or not
(defun vn/customize-frame ()
  (set-face-attribute 'default nil :font "Fira Code" :height 170)

  ;; Set the fixed pitch face
  (set-face-attribute 'fixed-pitch nil :font "Fira Code" :height 170)

  ;; Set the variable pitch face
  (set-face-attribute 'variable-pitch nil :font "Droid Sans" :height 170 :weight 'regular)

  (set-cursor-color "DeepSkyBlue"))

(if (daemonp)
    (add-hook 'server-after-make-frame-hook #'vn/customize-frame)
    (vn/customize-frame))
```

Now it is like this:

```elisp
(set-face-attribute 'default nil :font "Fira Code" :height 170)

;; Set the fixed pitch face
(set-face-attribute 'fixed-pitch nil :font "Fira Code" :height 170)

;; Set the variable pitch face
(set-face-attribute 'variable-pitch nil :font "Droid Sans" :height 170 :weight 'regular)

;; Ensure cursor has the same color when run on daemon or not
(defun vn/customize-frame ()
  (set-cursor-color "DeepSkyBlue"))

(if (daemonp)
    (add-hook 'server-after-make-frame-hook #'vn/customize-frame)
    (vn/customize-frame))
```

**Comment by seagle0128** [comment]
Thanks for your update!
