### ISSUE TITLE
God-mode indicator

### ISSUE THREAD

**Issue by mtellezj** [seagle0128/doom-modeline#46]
Since there is an evil-state indicator, how about a god-mode indicator? #8

**Comment by seagle0128** [comment]
I am not using `god-mode`. I am trying to make a similar indicator as `evil-state`.
If you have any idea, please let me know. Will commit soon.

**Comment by mtellezj** [comment]
Hi, the indicator when you are in God mode is only a minor-mode name, but as doom-modeline hide the minors mode names you can tell for sure. This is how appear on a vanilla modeline:

![imagen](https://user-images.githubusercontent.com/17144927/48877232-fb963480-edc7-11e8-91ec-6f5a96a71832.png)

From the docs, there is a function to change the cursor when you are in god mode or not:

```lisp
(defun my-update-cursor ()
  (setq cursor-type (if (or god-local-mode buffer-read-only)
                        'box
                      'bar)))

(add-hook 'god-mode-enabled-hook 'my-update-cursor)
(add-hook 'god-mode-disabled-hook 'my-update-cursor)
```

but it would be nice having an indicator on doom-modeline. I think you can use this hooks to known when god mode is active or not, and as you are doing with evil mode show a `<G>` for active and a `<I>` for inactive (or insert mode). By the way, good job on doom-modeline, I tried several alternatives and this fill my needs. Cheers!

**Comment by seagle0128** [comment]
Thanks for your suggestion!
You want `<G>` and `<I>` like `evil-state`, right? The hooks look fine. But I am thinking how to remove the indicator if you won't use `god-mode`? And another case is using both `evil` and `god`. How to handle it? What's your thoughts?

**Comment by mtellezj** [comment]
I think that `evil` and `god` should not be activate at the same time, because both modes made the same thing but with diferent approach (I'll never activate both at the same time by the way). And, as you said, probably the best thing is not show an indicator at all when `god` is not active, because if this mode is not active on startup, you have no way to find out (maybe checking minors mode names). Hope this help.

**Comment by seagle0128** [comment]
Okay. Then all are clear. I believe the current implementation is good. Same behavior for `roy-modal`. Thanks.
