### ISSUE TITLE
Emacs totally freezes with doom-modeline + python buffer

### ISSUE THREAD

**Issue by trev-dev** [seagle0128/doom-modeline#465]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

If I open any python buffer, small or large, empty or not, my Emacs completely freezes. 

I narrowed this down by disabling parts of my config until it ultimately came down to doom-modeline.

### Steps to reproduce

1. Load up Emacs with my config(?)
2. Open a python file or start a python buffer
3. Things completely freeze up.

### Expected behavior

1. Open emacs with my config
2. Open a python file or buffer
3. Proceed to write Python without a problem

### OS

Linux

### Emacs Version

27

### Emacs Configurations

https://github.com/trev-dev/emacs/blob/main/config.org#doom

### Error callstack

```emacs-lisp
I can't seem to create a debug callstack in either case here. C-g just leaves emacs hanging on "Entering debugger". So does toggle-debug-on-error. So there is an error, it's just so spectacular that the GUI ceases to render any further information
```

### Anything else

I can replicate this in the terminal with `emacs -nw` - so the bug is not exclusive to Xorg.

**Comment by trev-dev** [comment]
I guess some system info probably would not hurt!

```bash
 OS: Fedora 
 Kernel: x86_64 Linux 5.13.12-200.fc34.x86_64
 Uptime: 13h 55m
 Packages: 2170
 Shell: zsh 5.8
 Resolution: 3520x1080
 DE: GNOME 40.0
 WM: Mutter
 WM Theme: 
 GTK Theme: Adwaita-dark [GTK2/3]
 Icon Theme: Papirus-Dark
 Font: Cantarell 11
 Disk: 336G / 960G (35%)
 CPU: Intel Core i7-7700HQ @ 8x 3.8GHz [59.0°C]
 GPU: Mesa Intel(R) HD Graphics 630 (KBL GT2)
 RAM: 4687MiB / 15716MiB
```

Python version via `python --version`:  3.9.6

**Comment by seagle0128** [comment]
Can you reproduce the issue with `emacs -Q`?

**Comment by trev-dev** [comment]
> Can you reproduce the issue with `emacs -Q`?

As I cannot reproduce this by simply commenting out my doom-modeline config, I also cannot reproduce this by using `emacs -Q`

**Comment by seagle0128** [comment]
I couldn't reproduce the issue. Can you please provide the python samples?

**Comment by trev-dev** [comment]
The Python file doesn't seem to matter except the extension and the automatic use of python-mode. I've tried opening multiple different files. I stopped testing with a new empty temporary python buffer, which also triggers the issue for me. 

If you cannot reproduce it I will start eliminating other pieces of config and see if I can find a conflict.

**Comment by seagle0128** [comment]
I am not using doom-emacs. It's better to narrow the scope, otherwise I can do nothing.

**Comment by trev-dev** [comment]
Neither am I.

I made this issue because the problem went away when I disabled doom-modeline.

I think at this point doom-modeline is colliding with something else in my config.

I'm currently not automatically doing anything with Python files explicitly, so it makes this challenging for me, too. Bare with me while I try to narrow it down.

**Comment by trev-dev** [comment]
@seagle0128 Thanks for waiting. I've narrowed it own to `doom-modeline` interacting poorly with [ligature.el](https://github.com/mickeynp/ligature.el). When a Python document loads, the mode at the bottom shows "Python ..."

The ellipsis (...) are a ligature with Fira Code. My best guess is this is what is screwing things up. I can avoid setting `global-ligature-mode` for now, but I'm wondering if there's a better work around for this?

**Comment by trev-dev** [comment]
I've decided to go back to Source Code Pro and remove `ligature.el` from my config for now. Ligatures isn't worth this sort of unexpected behavior, so I'd rather take the opportunity to lighten my config. This is "resolved" for me.
