### ISSUE TITLE
Org mode unicode needed

### ISSUE THREAD

**Issue by ashincoder** [seagle0128/doom-modeline#466]
Sorry for making a shitty issue but my request can I borrow the orgmode unicode used in the modeline. I really like and I would like to use it. 
Sorry for bothering. 
Thank you for time.
Great plugin I love it.

**Comment by seagle0128** [comment]
I am not sure if I understand what do you mean. The icon is `(all-the-icons-fileicon "org"  :v-adjust 0.0 :face all-the-icons-lgreen)`.

**Comment by ashincoder** [comment]
sorry I checked the source code and realized it was in the all-the-icons repo.
