### ISSUE TITLE
[Bug] Flymake must be loaded before loading doom-modeline

### ISSUE THREAD

**Issue by Stebalien** [seagle0128/doom-modeline#469]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

https://github.com/seagle0128/doom-modeline/pull/468 breaks flymake if doom-modeline is loaded _before_ flymake (because `flymake--backend-state` isn't defined yet). That code needs to be wrapped in a `(with-eval-after-load 'flymake ...)` to make sure we don't check if the symbol exists before it's defined.

### Steps to reproduce

1. Load doom-modeline.
2. Enable flymake.

### Expected behavior

Flymake works?

### OS

Linux

### Emacs Version

gccemacs-28

### Error callstack

```emacs-lisp
Disabling backend eglot-flymake-backend because (void-variable flymake--state)
```

**Comment by seagle0128** [comment]
Please test the latest version.

**Comment by Stebalien** [comment]
The fix looks correct. Unfortunately, I've upgraded emacs since so I'll have to let someone else file an issue if it's still a problem.
