### ISSUE TITLE
Is it possible to update doom-modeline less frequently or cache the string for less CPU usage?

### ISSUE THREAD

**Issue by Gira-X** [seagle0128/doom-modeline#471]
**Is your feature request related to a problem? Please describe.**
I often hold down keys in order to scroll and when the modeline has many CPU intensive segments it can slow down, so I wondered if the modeline content can be cached or simply updated way less frequently.

Personally I don't mind if the modeline is only updated on an idle timer of say 0.15 seconds.

One can of course just manually build a cache for performance sensitive segments and update it on an idle timer, but I wondered if the same can be done for the entire modeline string because it would very convenient.

---

I have tried to implement such a thing myself (note that only `(doom-modeline-format--main)` is used) but it has issues on switching windows apparently.
With the code below sometimes the mode line from the left ends up on the right side and vice versa (even with a `(force-mode-line-update)` call on switching the window.

For a single window it works nicely:

```lisp
(defvar dima-doom-modeline-cache '())

(defun dima-doom-modeline-update-cache ()
  (add-to-list 'dima-doom-modeline-cache
               `(,(get-buffer-window) . ,(format-mode-line
                                          (doom-modeline-format--main))))
  (force-mode-line-update t))

(run-with-idle-timer 0.12 t #'dima-doom-modeline-update-cache)

(defun dima-doom-modeline-fetch-cache ()
  (cdr (assoc (get-buffer-window) dima-doom-modeline-cache)))

(defun doom-modeline (key)
  `(:eval (dima-doom-modeline-fetch-cache)))
```

Maybe someone knows of a quick fix though?

**Comment by Gira-X** [comment]
With a hook on `window-state-change-hook` this actually works really well, even for multiple windows now:

```lisp
(defvar dima-doom-modeline-cache '())

(defun dima-doom-modeline-update-cache ()
  (when-let ((window (get-buffer-window)))
    (add-to-list 'dima-doom-modeline-cache
                 `(,window . ,(format-mode-line
                               (doom-modeline-format--main))))
    (force-mode-line-update t)))

(run-with-idle-timer 0.12 t #'dima-doom-modeline-update-cache)

(defun dima-doom-modeline-fetch-cache ()
  (when-let ((window (get-buffer-window)))
    (cdr (assoc window dima-doom-modeline-cache))))

(defun doom-modeline (key)
  `(:eval (dima-doom-modeline-fetch-cache)))

(add-hook 'window-state-change-hook #'dima-doom-modeline-update-cache)
```

I suppose this is fine for me right now and I am leaving this open should anyone else be interested.

**Comment by Gira-X** [comment]
The code above does not work correctly because `(current-buffer)` should be used instead for proper updating when buffer changes in the current window.

Here is the fixed code:

```lisp
(defvar dima-doom-modeline-cache '())

(defun dima-doom-modeline-update-cache ()
  (when-let ((buffer (current-buffer)))
    (add-to-list 'dima-doom-modeline-cache
                 `(,buffer . ,(format-mode-line
                               (doom-modeline-format--main))))
    (force-mode-line-update t)))

(run-with-idle-timer 0.12 t #'dima-doom-modeline-update-cache)

(defun dima-doom-modeline-fetch-cache ()
  (when-let ((buffer (current-buffer)))
    (cdr (assoc buffer dima-doom-modeline-cache))))

(defun doom-modeline (key)
  `(:eval (dima-doom-modeline-fetch-cache)))
```

With this, no other hooks are necessary and so far it works nicely!

**Comment by Gira-X** [comment]
Ah my, this has the issue that `(doom-modeline--active)` always returns true which is not acceptable.

Plus it also does not seem to always update the mode-line even with the `(run-with-idle-timer)` or more hooks (even sometimes on moving the point), so my implementation should certainly not be used but it still is an idea ;)

**Comment by seagle0128** [comment]
I don't think it's a good idea to cache all and update via a timer. It will bring some negative impacts. It's fine if this trick works for you, but it's not a common method. If you observe CPU high usage, I suggest to optimize the segments or remove them from the mode-line.
