### ISSUE TITLE
dired+ : Not correct show marked dirs/files in doom-modeline

### ISSUE THREAD

**Issue by alexei-28** [seagle0128/doom-modeline#473]
Linux Mint 20

Emacs 27.2

package: doom-modeline, dired+

I  my Temp folder I has **3** folders and **4** files.

In dired mode in the bottom right corner has:

`Dired/name 7`

OK.

I mark one folder (**m**). 
Result 
`Dired/name 1* 2/7`

Then I mark (m) one more folder.  
Result:
`Dired/name 1* 2/7`

As you can see the text not change.
I think it must be:

`Dired/name 2* 2/7`

Then I unmark all (**U**). But again nothing change:
`Dired/name 2* 2/7`

**Comment by alexei-28** [comment]
> No idea. `doom-modeline` does't define a segment for dired-k. I don't know which package controls the marked dirs and files. Are you using both `smart-mode-line` and `doom-modeline`?

If I'm not use package `dired+` the problem is gone. The correct show marked files/dires in dired mode.

**Comment by seagle0128** [comment]
So please file an issue for dired+.
