### ISSUE TITLE
no icon for major mode even if `doom-modeline-icon` is true

### ISSUE THREAD

**Issue by a13** [seagle0128/doom-modeline#48]
I think it would be great to see it somewhere near the filename

**Comment by seagle0128** [comment]
Hmm, this seems like a new feature. Actually `doom-modeline` was extracted from `doom-emacs`. To keep the compatibility and speed, no icons for major modes. Only a few icons, for buffer info, flycheck and vcs. It's as designed.

**Comment by a13** [comment]
thanks!

**Comment by seagle0128** [comment]
Commit. New variable `doom-modeline-major-mode-icon' to control.
nil is the default value.

**Comment by a13** [comment]
Nice, thanks!
