### ISSUE TITLE
[Bug] Clipped org mode tag menu

### ISSUE THREAD

**Issue by memeplex** [seagle0128/doom-modeline#480]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I'm reporting this again because it is not fixed: https://github.com/seagle0128/doom-modeline/issues/291

https://user-images.githubusercontent.com/2845433/137429697-b169da03-031f-46ba-b3fc-9a253ebe86a8.mov

### Steps to reproduce

1. Start emacs with only doom-modeline installed, just the vanilla config
2. Create an org file with the contents below
3. Press `C-c C-c` over the first line
4. Press `C-c C-q` over the text "headline"
5. Press `C-g` to exit the tag popup
6. Repeat step 4

```
#+TAGS: @work(w)  @home(h)  @tennisclub(t)  laptop(l)  pc(p)

* headline
```

### Expected behavior

org-mode tag menu is properly presented.

### OS

MacOS

### Emacs Version

28

### Anything else

This happens with and without icons enabled.

Once it happens it stays there until restart.

Whatever is being done by doom-emacs to fix it is a downstream hack and not a proper solution.

**Comment by tarsius** [comment]
It's kinda funny that the video is of no help of me (on firefox) because the part where the mode-line is covering parts of the above buffer is in turn covered by the video players controls. :rofl:
