### ISSUE TITLE
[Feature Request] Document behaviour in -nw mode

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [seagle0128/doom-modeline#482]
I am using emacs via SSH terminal - it means in `-nw` mode.

It looks like that doom-modline works in `-nw` also. Of course it looks a bit different then the graphical version.

I can not find anything about that in the documentation. Please update the documentation and explain a bit about what doom-modeline does when used without a window system (`-nw`) and what are the major differences between the graphical and terminal mode.

**Comment by josephmturner** [comment]
I would also like to see this please :)

**Comment by seagle0128** [comment]
Basically no icons and bars (image) are displayed in TUI. See `doom-modeline-icon-displayable-p`.

**Comment by josephmturner** [comment]
@seagle0128 Thank you!
