### ISSUE TITLE
[Feature Request] How to place absolute buffer position (row:col) at the right of nyan cat/relative position (%) like in the README?

### ISSUE THREAD

**Issue by daanturo** [seagle0128/doom-modeline#488]
**Is your feature request related to a problem? Please describe.**
By default, there is nothing to indicate Nyan cat's destination, which makes it hard to determine the relative position in current buffer.

**Describe the solution you'd like**
Allow placing `row:col` indicator at the end of Nyan cat's path/relative buffer position

**Describe alternatives you've considered**
Current workaround: use `parrot` just to know Nyan cat's end.

**Additional context**
Default: it's impossible to deduce relative position
![image](https://user-images.githubusercontent.com/32123754/140546730-a3410742-e746-4029-8abb-21ae0cb167f9.png)
Desired: like in the README:
![image](https://user-images.githubusercontent.com/140797/51301061-da209480-1a68-11e9-9f64-905d889df9d6.png)

**Comment by seagle0128** [comment]
I think I have the better solution to address your issue.
Regarding the positions of the segments, you can define the mode-line via `doom-modeline-def-modeline` like `doom-modeline.el`.
