### ISSUE TITLE
void-function file-local-name in spacemacs

### ISSUE THREAD

**Issue by kepi** [seagle0128/doom-modeline#49]
I have latest develop version of *spacemacs* and latest version of *doom-modeline*, Emacs version 25.2.2. In any file buffer I don't see name of current file and message buffer says:

    Error during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (void-function file-local-name)

Looks like `file-local-name` function is missing in my emacs version. I found that it was added [long time ago](https://lists.gnu.org/archive/html/emacs-diffs/2016-11/msg00159.html) - and its weird as it seams it was added in time before 25.2.2 release but when I define it, everything works:

    (defun file-local-name (file)
      "Return the local name component of FILE.
    It returns a file name which can be used directly as argument of
    `process-file', `start-file-process', or `shell-command'."
      (or (file-remote-p file 'localname) file))

Not sure if you want to address this somehow, it is solved for me, but maybe others can hit it too.

**Comment by seagle0128** [comment]
Thanks very much for the reporting!

I guess you are using Emacs 25.1 or 25.2. Since `doom-modeline` is clarified for 25.1+ for now, I should keep the compatibility. I add some codes and will commit soon.
