### ISSUE TITLE
[Bug] modeline font face chaged after upgrading to GNU Emacs 29.0.50 (c13b49a110)

### ISSUE THREAD

**Issue by azzamsa** [seagle0128/doom-modeline#491]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Normally, without using `set-face-attribute` the mode-line font is inherited from ` default-frame-alist font`. But after upgrading to GNU Emacs 29.0.50 (c13b49a110) the font face is not inherited anymore.

![image](https://user-images.githubusercontent.com/17734314/144525434-0ef0dbed-bb80-4b01-ad44-32f7bb896b10.png)

![image](https://user-images.githubusercontent.com/17734314/144525445-51abd5ca-a827-4f44-9b40-fcbf8456f364.png)

### Steps to reproduce

``` bash
mkdir /tmp/dooms
touch /tmp/dooms/init.el
# then copy the code below into `init.el`

# starts emacs with non-interactive mode to see any error messages
# and check if all the packages downloaded successfully
emacs -q -l test-case/init.el --batch

# starts emacs inactively
emacs -q -l test-case/init.el
```

```elisp
;; set user-emacs-directory to the directory where this file lives
;; do not read or write anything in $HOME/.emacs.d
(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))

;; set custom-file to write into a separate place
(setq custom-file (concat user-emacs-directory ".custom.el"))
(when (file-readable-p custom-file) (load custom-file))

;; configure melpa (and other repos if needed)
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(setq package-enable-at-startup nil)
(package-initialize)
(when (not package-archive-contents)
    (package-refresh-contents))

;; bootstrap `use-package'
(setq package-pinned-packages
      '((bind-key           . "melpa")
        (diminish           . "melpa")
        (use-package        . "melpa")))

(dolist (p (mapcar 'car package-pinned-packages))
  (unless (package-installed-p p)
    (package-install p)))

;; install and configure packages

;; set font and size
(setq default-frame-alist '((font . "Fira Code 15")))
;; fallback fonts for unicode icons
(set-fontset-font "fontset-default" nil
                  (font-spec :size 20 :name "FontAwesome5Free"))
                  
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))
```

### Expected behavior

The font should be inherited without setting additional font-face.

### OS

Linux

### Emacs Version

gccemacs-28

### Emacs Configurations

https://github.com/azzamsa/emacs.d

### Anything else

But, it works fine after I added:

```diff
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
 + (set-face-attribute 'mode-line nil :family "Fira Code" :height 150)
 + (set-face-attribute 'mode-line-inactive nil :family "Fira Code" :height 150))
 ```
 
 So I put here just for information. Maybe it can help someone.
 
 ```
 GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-12-01
c13b49a110 (HEAD -> master, origin/master, origin/HEAD) 2 days ago update_autogen: Remove deprecated -I flag (Stefan Kangas)

OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-9-amd64 x86_64
```

**Comment by azzamsa** [comment]
So I put here just for information. Maybe it can help someone.

**Comment by seagle0128** [comment]
Thank you! The related post is https://lars.ingebrigtsen.no/2021/11/24/the-most-controversial-change-in-emacs-history/ .
The feature is experimental, and I don't think it's a good idea. You can set the fonts in `custom.el`.

**Comment by azzamsa** [comment]
I skimmed the article days ago. I thought the changes were only the margin between the text. Turns out it was also the font.

Vincent, thanks for the doom-modeline.

**Comment by seagle0128** [comment]
@azzamsa welcome and enjoy 😄
