### ISSUE TITLE
[Bug] Causes flashing of wrong buffer when opening new window

### ISSUE THREAD

**Issue by dominikh** [seagle0128/doom-modeline#495]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using doom-modeline, commands that open a new window to display a buffer briefly display an old buffer. The longer it takes to display the new buffer, the longer the old buffer is displayed. This is especially obvious with `magit-status`, which is fairly slow.

This issue doesn't reproduce without doom-modeline.
This issue does reproduce with a vanilla Emacs configuration running only doom-modeline, although it is difficult to demonstrate, because the flash of old content is very brief for built-in commands.

I've attached two videos, both running a minimal configuration of Emacs with only magit and doom-modeline in them, executing `magit-status` and demonstrating the difference.

Another great way of seeing the difference is to run `(with-displayed-buffer-window "*Messages*" nil nil (sleep-for 2))` without and with doom-modeline enabled. Without, Emacs will immediately freeze for 2 seconds, then display the new window. With, Emacs first displays the new window, showing the old buffer, then freezes for 2 seconds, and finally displays the `*Messages*` buffer. It feels like doom-modeline is forcing redisplay at an unexpected time.

(Arguably, with-displayed-buffer-window _shouldn't_ freeze before displaying the new window, as per its documentation, but it does in vanilla Emacs...)

https://user-images.githubusercontent.com/39825/147266106-4f67f597-e081-4de6-81bb-779d466eb083.mp4

https://user-images.githubusercontent.com/39825/147266111-d1d290b6-6cfe-4f6e-adb3-b7ff69b8728b.mp4

### Steps to reproduce

1. Have a single window open
2. Run any command that creates a new window, such as describe-function or magit-status

### Expected behavior

No flashing.

### OS

Linux

### Emacs Version

27

**Comment by dominikh** [comment]
Looking at the code, this behavior isn't all too surprising:

```
(advice-add 'split-window :after #'doom-modeline-redisplay))
```

This will end up forcing redisplays in the middle of functions (whenever they call split-window). This is quite unexpected, as the normal Emacs behavior is to redisplay when waiting for input, which makes most functions appear atomic in their execution.

**Comment by seagle0128** [comment]
See the details in https://github.com/seagle0128/doom-modeline/pull/484. It's an issue of Emacs itself. This is just a workaround, and the issue has been fixed in Emacs 29.

**Comment by dominikh** [comment]
Feel free to close this issue if you believe there is no other workaround than to wait for Emacs 29.

**Comment by seagle0128** [comment]
If you don't mind the cut-off of minibuffer in some cases (e.g. `org-capture`), just remove the advice.

```elisp
(advice-add 'split-window :after #'doom-modeline-redisplay))
```

**Comment by seagle0128** [comment]
@dominikh I decided to address the flashing issue, but it may bring the side effect. If so, it will be reverted. But any way, please help to test.
