### ISSUE TITLE
[Feature Request] relative-from-project-without-subfolders

### ISSUE THREAD

**Issue by sebastiaanspeck** [seagle0128/doom-modeline#499]
**Describe the solution you'd like**
Relative from project without subfolders

Given ~/Projects/FOSS/emacs/lisp/comint.el we would like emacs/comint.el as filename style

**Comment by seagle0128** [comment]
I'm not sure if I understand the requirement. IMO `truncate-from-project` is enough for these cases. `relative-from-project-without-subfolders` will confuse the users.
