### ISSUE TITLE
Compiler warning about undefined `follow-all-followers'

### ISSUE THREAD

**Issue by dr-scsi** [seagle0128/doom-modeline#502]
Emacs 29.0.50 complains when it is native-compiling `doom-modeline-segments.el`:

```
doom-modeline-segments.el:2952:22: Warning: the function `follow-all-followers' is not known to be defined.
```
which is about this part:
https://github.com/seagle0128/doom-modeline/blob/b1726bf6b3328763851dfa1d343e4b2f1ccad125/doom-modeline-segments.el#L2950-L2952

It should be fixed with the following line added to the `Externals` at the beginning of the file:

```
(declare-function follow-all-followers 'follow)
```

**Comment by seagle0128** [comment]
Thank you! Will fix soon.

**Comment by dr-scsi** [comment]
Thanks for the quick fix 👍
