### ISSUE TITLE
[Bug] dired icon & god-mode indicator conflict

### ISSUE THREAD

**Issue by actondev** [seagle0128/doom-modeline#503]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When being in dired mode, god-mode indicator doesn't show. However after disabling doom-modeline & then re-enabling it, now god-mode indicator shows up! When I do this note that the dir/folder icon changes

### Steps to reproduce

- enter a directory
- enable/disable god-mode: god-mode indicator doesn't show
- disable doom-modeline
- enable/disable god-mode: god-mode indicator no does show

### Expected behavior

ditto

### OS

Linux

### Emacs Version

27

### Anything else

![doom-modeline-dired-god-mode](https://user-images.githubusercontent.com/1299928/154680990-89339461-fce8-43a0-8c2a-d9d3d27eac37.gif)

**Comment by seagle0128** [comment]
Actually it's as designed. In dired buffers, project mode-line is applied, without `objed-state` segment. I am thinking maybe it should be added.
