### ISSUE TITLE
[Feature Request] Use `minions-mode-line-lighter` value when fallback to ASCII text.

### ISSUE THREAD

**Issue by fernandodemorais-jf** [seagle0128/doom-modeline#506]
Hello!

First of all, thanks for this great package!

---
**Is your feature request related to a problem? Please describe.**
`doom-modeline` doesn't respect my custom `minions-mode-line-lighter` value when fallback to ASCII text.

**Describe the solution you'd like**
I believe that the problem is in [line #620 of `doom-modeline-segments.el` file](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L620), where the default fallback is `";-"`, instead of `minions-mode-line-lighter` var value.

```elisp
;; ...
            (:propertize ("" ,(doom-modeline-icon 'octicon "gear" "⚙" ";-" ; <-- This little guy
;; ...
```
---

Thanks!

**Comment by seagle0128** [comment]
I've committed a patch to address it. The side-effect is the fallback may not be ASCII characters if `minions-mode-line-lighter` is set to unicode characters. But the default value is fine.
