### ISSUE TITLE
[Bug] Modal icon for xah-fly-keys won't display

### ISSUE THREAD

**Issue by FlyfishO25** [seagle0128/doom-modeline#507]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Modal icon won't display after I start emacs even if I restart xah-fly-keys and doom-modeline

### Steps to reproduce

1. start emacs
2. there is no modal icon in modeline and I'm sure that doom-modeline-modal-icon is t

### Expected behavior

Icons should be display correctly like README

### OS

MacOS

### Emacs Version

gccemacs-28

### Emacs Configurations

https://github.com/FlyfishO25/.emacs.d

### Error callstack

```emacs-lisp
No callstack
```

**Comment by seagle0128** [comment]
I believe it's working well with `xah-fly-keys` in my env. Can you try with `emacs -Q`?

**Comment by FlyfishO25** [comment]
The problem still exist, it seems happed after [this commit](https://github.com/FlyfishO25/.emacs.d/commit/880a8e84da95161338b04a9702d98931eaf92a32) but I don't know why.

**Comment by seagle0128** [comment]
Sorry! I am not using `evil-mode`, and cannot help on it.

**Comment by ch8ng3r** [comment]
Hi. I can confirm this behaviour and I **don't** use evil-mode.
I also get an error message: 

> Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable xah-fly-insert-state-p)

It occured right after b1726bf6b3
I can confirm this behaviour on Mac and Linux. Tested with a clean config, only xah-fly-keys and doom-modeline loaded.
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26

**Comment by seagle0128** [comment]
You need to upgrade `xah-fly-keys`. `xah-fly-insert-state-q` doesn't exist in the latest version.

**Comment by ch8ng3r** [comment]
Thanks for your time @seagle0128
