### ISSUE TITLE
[Feature Request] Optional to hide filepath/filename and file icon

### ISSUE THREAD

**Issue by konrad1977** [seagle0128/doom-modeline#511]
I would like to have the option to hide the filepath/filename and the icon. 

**Why?**
I am using centaur-tabs so the information is already in the same window.

**Describe the solution you'd like**
Simple toggle nil/t for show filename, default on.

**Comment by seagle0128** [comment]
Add an option `doom-modeline-buffer-name` to display/hide buffer names, and `doom-modeline-major-mode-icon` is to control buffer icons.

**Comment by konrad1977** [comment]
You mean its already possible today without any updates? How do I configure that?

**Comment by konrad1977** [comment]
Wow that was quick. Thanks!
