### ISSUE TITLE
[Feature Request] Support for overriding vspc-face when modeline is inactive

### ISSUE THREAD

**Issue by geza-herman** [seagle0128/doom-modeline#516]
I'd like to be able to fully override the look of the space character that `doom-modeline-vspc` puts. Currently there is no solution if I'd like to change the background color of it because of how the inactive case is defined:
```
'(:inherit (doom-modeline-vspc-face mode-line-inactive))
```
`doom-modeline-vspc-face` has the background color when the mode-line is active, that's OK. But, if the mode-line goes inactive, it will still use the background color of `doom-modeline-vspc-face` instead of `mode-line-inactive`. So, `doom-modeline-vspc-face` cannot contain background color currently.

The reason I need this is related to my mode-line modification: I change the color of the mode-line when there is a flycheck error. I use `face-remap-add-relative` to do that. With Emacs 28, this worked OK, I just needed to modify `mode-line` and `mode-line-inactive`. With Emacs 29, this doesn't work anymore for some reason, so I have to add more mode-line related faces into `face-remap-add-relative`. And this is where my problem is, because even if I add `doom-modeline-vspc-face` into `face-remap-add-relative`, it doesn't work properly, it will have a wrong background color when the mode-line is inactive.

Possible solutions could be:
1. Have a separate face for inactive vspc, like `doom-modeline-vspc-face-inactive`, so I can set the background color of it separately
2. Make `doom-modeline-vspc` a `defun` instead of `defsubst`, so I can override it
3. Swap the order of `doom-modeline-vspc-face` and `mode-line-inactive` in the `:inherit` list. This improves on the situation, but not a 100% solution (it works for most cases, but not always - I suspect that there is an Emacs 29 bug related to this, Emacs forgets to update the modeline in certain cases).

Here's how my modeline looks when it's inactive, the vspc characters still have the active background color (the darker "st" part is by design, the problem is the brighter spaces between the icon and text):
![image](https://user-images.githubusercontent.com/27892988/159443864-47eac786-d8e5-4f8a-8243-9e519c20edeb.png)

**Comment by seagle0128** [comment]
As I said in #486, I don't recommend 29 until it's stable. The changes broke many things and quite unstable.

**Comment by geza-herman** [comment]
Fair enough. Maybe I'm just using a fortunate commit of emacs master, it's stable for me. I don't have any problems, this is the only exception.

Maybe they changed how the list of `:inherit` works? It seems that it works exactly the opposite what the doc says: "If a list of faces is used, attributes from faces earlier in the list override those from later faces.". Anyways, I just swapped the order in my `doom-modeline-core.el`, and it works. That's why that I'd be good if `doom-modeline-vspc` was a `defun` and not a `defsubst`, because then I could just override it in my `init.el`. I suppose it's a `defsubst` because of performance reasons?

**Comment by seagle0128** [comment]
> I suppose it's a defsubst because of performance reasons?

Yes. Inline functions run faster, but reduce the flexibility.

**Comment by seagle0128** [comment]
Two new faces were added: `doom-modeline-spc-inactive-face` and `doom-modeline-vspc-inactive-face`.

**Comment by seagle0128** [comment]
The  inactive faces above were removed. Both `mode-line` and `mode-line-active` should be handled in 29.
