### ISSUE TITLE
[Bug] Some symbols not showing on mu4e headers

### ISSUE THREAD

**Issue by et2010** [seagle0128/doom-modeline#518]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

![image](https://user-images.githubusercontent.com/11584902/160220178-edaa7a3b-8189-44bb-9bc5-aa6667707261.png)

Some symbols not showing on mu4e headers

### Steps to reproduce

Have all-the-icons font installed

Have symbola font installed

### Expected behavior

Show the symbol correctly

### OS

Linux

### Emacs Version

27

### Emacs Configurations

Spacemacs

**Comment by seagle0128** [comment]
Check the icon in your env: type "C-x 8 RET e0be"

<img width="733" alt="image" src="https://user-images.githubusercontent.com/140797/160286978-1b2039a5-ae4d-4361-b298-51b2428ef82c.png">

**Comment by et2010** [comment]
This is what I got:

![image](https://user-images.githubusercontent.com/11584902/160297569-60ecd068-7bd3-4788-8d65-a85b0a68e870.png)

**Comment by seagle0128** [comment]
So it's related to your font configuration of spacemacs. The Sarasa Mono font overrides Material icons.

**Comment by et2010** [comment]
OK, thank you for the info. But how do you use two fonts at the same time? The font (Sarasa Mono) was set to be used everywhere. @seagle0128

**Comment by seagle0128** [comment]
Try loading the icons fonts after the main font.
