### ISSUE TITLE
[Feature Request] Show match count when searching with evil-search

### ISSUE THREAD

**Issue by DevJac** [seagle0128/doom-modeline#519]
I would like doom-modeline to show how many matches are found when I perform a search using evil-search.

I suspect this is already implemented, because it's mentioned in the README, but I can't get it to work. None of the screenshots show this feature, and I haven't found any mention of it besides the one line in the README.

When I search for a word with evil-search, I want the modeline to show something like "1/4" somewhere to show me that there are 4 matches, and I'm currently looking at the first match.

**Comment by seagle0128** [comment]
It has already been implemented. If you tried, you should get like this:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/140797/162925065-0ffe40fd-1efd-469b-bf09-c62fe2d22fd2.png">

**Comment by DevJac** [comment]
In my experience, this only works if `anzu` or `evil-anzu` is installed. After I installed `anzu` it was very robust and worked with a few different `evil` configurations, but I couldn't get it to work until I installed `evil-anzu`.

Thank you for your help. It is working for me now.

**Comment by seagle0128** [comment]
Right. I've updated the FAQ.
