### ISSUE TITLE
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable xah-fly-insert-state-p)

### ISSUE THREAD

**Issue by ItsNilDev** [seagle0128/doom-modeline#520]
### Bug description

I get bunch of these warnings when I open emacs.

### Steps to reproduce

install xah-fly-keys modal package
open up emacs, and there you go.

I'm using Arch linux with `Linux 5.15.33-1-lts`
and Emacs version is
 ```
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-10
```
I also have checked similar issues #307 #308 #309 but non of them were helpful

**Comment by seagle0128** [comment]
Are you use the latest `xah-fly-keys`? `xah-fly-insert-state-q` was changed to `xah-fly-insert-state-p`.  See #501 .

**Comment by ItsNilDev** [comment]
I'm using `xah-fly-keys-20210919.1355` which is the latest ig

**Comment by seagle0128** [comment]
The latest version is `17.5.20220416101054`. `xah-fly-insert-state-q` is deprecated from `16.0.20211106142546`.
