### ISSUE TITLE
Weird colors on 29.1

### ISSUE THREAD

**Issue by dangom** [seagle0128/doom-modeline#522]
Hadn't seen this issue before. Colors look off:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/7881842/163869646-6a2fbd04-99ff-410f-943c-6e8b41226256.png">

Using modus-themes. Just reinstalled doom-modeline after playing with nano-modeline for the past 6 months or so.

Any ideas of what could be going on? (Issue appears when changing focus away from Emacs, reverts to normal after a couple of seconds)

Emacs 29.0.50

**Comment by seagle0128** [comment]
29 is changed a lot and not stable currently. Will take a look when I am available.

**Comment by seagle0128** [comment]
Can you try the latest versions of emacs and doom-modeline?

**Comment by dangom** [comment]
seems fixed. I'll report back if the issue appears again.
Thank you!

**Comment by seagle0128** [comment]
Then I am closing it. Please reopen if you observe again.

**Comment by dangom** [comment]
The color issue is fixed, but there must be a regression somewhere since doom-modeline is now slowing down my Emacs. Profiler-report says 71% of cpu is spent on `doom-modeline-segment--buffer-info`. Any ideas what could be going on there?

![image](https://user-images.githubusercontent.com/7881842/169646451-8300f50c-4f1f-4244-96af-7fb08ac00ff6.png)

**Comment by seagle0128** [comment]
@dangom are you using `all-the-icons` and enable `doom-modeline-icon`?

**Comment by dangom** [comment]
No,

this is what I had in my init:

```elisp
(use-package doom-modeline
  :init (setq doom-modeline-height 14
              doom-modeline-bar-width 2)
  :hook (after-init . doom-modeline-mode))

```
