### ISSUE TITLE
[Bug] buffer name missing in mode line in ess-r-mode

### ISSUE THREAD

**Issue by ggebbie** [seagle0128/doom-modeline#523]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

This must be related to #9 in the FAQ. Also I suspect that it is solved here or in the ESS issues, but I can't find it.

When loading a minimal configuration (attached below), the doom modeline shows buffer names properly. Then when I load a *R file and enter ess-r-mode, the buffer name disappears in the modeline. I must be doing something wrong in my config. Thanks for the help or pointing me in the right direction.

doom-modeline 20220412.853

### Steps to reproduce

1. emacs -Q -l init.el
2. open *r or *R file

init.el configuration 
```
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

(use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 10)))

(use-package ess
  :defer t)
```

### Expected behavior

expect to see buffer name in left hand side of doom modeline

### OS

Linux

### Emacs Version

27

### Emacs Configurations

vanilla

**Comment by seagle0128** [comment]
No idea what issue it is. The R buffer names are displayed in my env. Please check messages, logs and errors, and provide more details.

**Comment by ggebbie** [comment]
I have narrowed the case where the buffer name is not displayed. The bug only happens for me when in a git repository. It doesn't matter if the buffer is tracked by git. 

The variable `doom-modeline-buffer-file-name-style` is set to `auto`. If changed to `buffer-name` or `file-name`, the name reappears in the mode line.  Seems like I could set a hook to make this behavior automatic, although I don't understand the root cause.

**Comment by seagle0128** [comment]
Again, I still cannot reproduce this issue on my local env. `demo.r` is in a git repo. The only difference is macOS and 28.

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/140797/168136144-4a84733f-0dc4-44d7-a13b-c448cc1f3055.png">

**Comment by ggebbie** [comment]
thanks @seagle0128 for your time and helping me with a problem that might be my own. I appreciate it!

I ran `M-: (doom-modeline-project-root)`  in a buffer that doesn't show the buffer name and received an error. ~/junk/open-ocean-science is a git repo. 

'''
Debugger entered--Lisp error: (cl-no-applicable-method project-root (vc . "~/junk/open-ocean-science/"))
  signal(cl-no-applicable-method (project-root (vc . "~/junk/open-ocean-science/")))
  cl-no-applicable-method(#s(cl--generic :name project-root :dispatches ((0 #s(cl--generic-generalizer :name cl--generic-head-generalizer :priority 80 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fef43bf51e7>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fef43bf51d7>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fef43b6844b>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fef43b6843b>)))) :method-table (#s(cl--generic-method :specializers ((head ess-r-project)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) "Return the project root for ESS R projects." #<bytecode 0x158c2d456361>)) #s(cl--generic-method :specializers ((head ess-r-package)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) "Return the project root for ESS R packages" #<bytecode 0x158c2da7abb5>))) :options nil) (vc . "~/junk/open-ocean-science/"))
  apply(cl-no-applicable-method #s(cl--generic :name project-root :dispatches ((0 #s(cl--generic-generalizer :name cl--generic-head-generalizer :priority 80 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fef43bf51e7>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fef43bf51d7>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fef43b6844b>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fef43b6843b>)))) :method-table (#s(cl--generic-method :specializers ((head ess-r-project)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) "Return the project root for ESS R projects." #<bytecode 0x158c2d456361>)) #s(cl--generic-method :specializers ((head ess-r-package)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) "Return the project root for ESS R packages" #<bytecode 0x158c2da7abb5>))) :options nil) (vc . "~/junk/open-ocean-science/"))
  #f(compiled-function (&rest args) #<bytecode 0x158c2da85609>)((vc . "~/junk/open-ocean-science/"))
  apply(#f(compiled-function (&rest args) #<bytecode 0x158c2da85609>) (vc . "~/junk/open-ocean-science/") nil)
  project-root((vc . "~/junk/open-ocean-science/"))
  doom-modeline--project-root()
  doom-modeline-project-root()
  eval((doom-modeline-project-root) t)
  eval-expression((doom-modeline-project-root) nil nil 127)
  funcall-interactively(eval-expression (doom-modeline-project-root) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
'''

**Comment by ggebbie** [comment]
upgraded to emacs 28.1.50, problem appears to be solved, is not showing up anymore. Ok with me to close this -- thanks again.

**Comment by seagle0128** [comment]
Glad to know it's resolved. I think you should install the latest `project` package from elpa in 27.
