### ISSUE TITLE
[Bug] Mu4e and Circe indicators don't react on mouse clicks

### ISSUE THREAD

**Issue by jumper047** [seagle0128/doom-modeline#526]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Unread mail (mu4e) and chat messages (circe) icons ignores mouse clicks. Major mode and buffer name segments works as expected though. Bug appears when I updated doom-modeline package

### Steps to reproduce

Install doom-modeline, mu4e, mu4e alert, set them all up, set doom-modeline-mu4e to 't, receive some emails, click on mail icon on modeline, nothing happens

### Expected behavior

Appearance of the mu4e buffer.

### OS

Linux

### Emacs Version

gccemacs-28

### Anything else

I rolled back to commit f39129e and all became fine again. Seems like something went wrong with refactoring.

**Comment by seagle0128** [comment]
Did you observe any error messages?

**Comment by jumper047** [comment]
Flycheck indicator also ignores clicks. Regarding errors - there were no errors at all, like action just unbinded from click

**Comment by jumper047** [comment]
Just noticed although circe indicator works fine, mu4e still broken (not sure when it starts - maybe because I updated my emacs packages first time at this month)
