### ISSUE TITLE
[Bug] Can't properly set height after update

### ISSUE THREAD

**Issue by jakebox** [seagle0128/doom-modeline#531]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

After updating doom-modeline from MELPA the other day the modeline is stuck at a larger size than I'd like. Previously I could set the height using `(setq doom-modeline-height 10)`, for example. What I would do is set the number to something small like 1, and then the modeline height would be determined by the text height of the modeline. This worked well as I like the modeline to be pretty small. This functionality no longer works.

I tried installing a commit from two weeks ago (https://github.com/seagle0128/doom-modeline/commit/60412d8b4df87b0440169567df73c2f57669f7d7) and the behavior is how it should be.

### Steps to reproduce

1. Install doom-modeline
2. Attempt to set height

### Expected behavior

I expected the modeline to change height.

### OS

MacOS

### Emacs Version

gccemacs-28

### Emacs Configurations

https://github.com/jakebox/jake-emacs (my own config)

**Comment by seagle0128** [comment]
The latest works well on my macOS. I saw you set height for `mode-line` and `mode-line-inactive` faces. Try set `doom-modeline` and `doom-modeline-inactive`.

**Comment by jakebox** [comment]
I tried. Results are strange. Set both to a small value for visible effect:

![Screen Shot 2022-05-30 at 9 25 15 PM](https://user-images.githubusercontent.com/26366643/171080527-daa890f8-4102-4020-99b1-db1ae7556e30.png)

Some of the modeline is sized properly, and other parts are not.

I will try to narrow down which commit caused this issue in a few hours.

**Comment by seagle0128** [comment]
Other faces are also needed to set, e.g. `doom-modeline-emphasis`, `doom-modeline-buffer-file`, etc.

**Comment by jakebox** [comment]
Are you saying that now to make the height smaller I'll need to change all of these faces? That seems annoying given two weeks ago that wasn't necessary.

**Comment by seagle0128** [comment]
Yes, If you want to set height correctly, you have to do that. But the simple and best way is

```elisp
(set-face-attribute 'mode-line nil :height 100)
(set-face-attribute 'mode-line-inactive nil :height 100)
```

**Comment by jakebox** [comment]
I don't mean to be rude but that seems silly, that leaves most items in the modeline at the previous height (line and column numbers, size indication, etc).

Can the old functionality return?

**Comment by seagle0128** [comment]
Doesn't it work for you? BTW, you should remove other faces settings of doom-modeline.

```elisp
(set-face-attribute 'mode-line nil :height 100)
(set-face-attribute 'mode-line-inactive nil :height 100)
```

**Comment by jakebox** [comment]
Strangely I can set the font size correctly but not the modeline height. Here is `doom-modeline-height 0`:
![Screen Shot 2022-06-06 at 2 14 42 PM](https://user-images.githubusercontent.com/26366643/172231298-137509a6-ddd4-4eb2-8cdd-b9d76baa2457.png)
And here is `doom-modeline-height 1` (which means the modeline height should be set by font height, right?):
![Screen Shot 2022-06-06 at 2 14 49 PM](https://user-images.githubusercontent.com/26366643/172231316-d2ba3e5f-287a-4653-97ae-3fca326073a9.png)

**Comment by seagle0128** [comment]
The height of mode-line is the max of `doom-modeline-height` and font/icon height.

**Comment by seagle0128** [comment]
Try the latest version.

**Comment by jakebox** [comment]
Almost perfect!! On latest version, setting just `mode-line` and `mode-line-inactive` adjusts the height of everything. Amazing. Only strange behavior is that setting `doom-modeline-height` does not seem to work properly. Here is a small modeline text height and `doom-modeline-height` at 1 (so modeline height should be set by font height, no?
![Screen Shot 2022-06-07 at 10 30 10 PM](https://user-images.githubusercontent.com/26366643/172525673-ea7886a2-fe3e-42b5-a909-8fa4a65fdab6.png)

I wonder if it is at all related to `doom-modeline-bar-width`, or if there is some interaction there. If I set bar-width to 0 I get this:
![Screen Shot 2022-06-07 at 10 31 28 PM](https://user-images.githubusercontent.com/26366643/172525827-58a2837e-5fc5-4c0f-a578-cb15750054e4.png)
Sort of weird.

Thank you for your progress and help!

**Comment by seagle0128** [comment]
It should be fixed as well.

**Comment by seagle0128** [comment]
I believe it's working. When `doom-modeline-bar-width` is set to 0, the height will be smaller or same. If icon is enabled, almost same so no change; if icon is nil, you can see the height is smaller.

**Comment by tshu-w** [comment]
Hi, I cannot get the height of modeline smaller if `doom-modeline-bar-width` is not 0 in latest doom-modeline.
```emacs-lisp
;;; emacs -Q -l ~/.config/emacs/test.el

(setq package-archives '(("melpa"        . "https://melpa.org/packages/")
                         ("gnu"          . "https://elpa.gnu.org/packages/")
                         ("nongnu"       . "https://elpa.nongnu.org/nongnu/")))

(package-initialize)

(package-install 'doom-modeline)

(doom-modeline-mode)

(setq inhibit-compacting-font-caches t

      doom-modeline-height 0
      ;; doom-modeline-bar-width 0
      doom-modeline-buffer-file-name-style 'auto
      doom-modeline-project-detection 'project

      doom-modeline-gnus nil
      doom-modeline-icon nil
      doom-modeline-irc nil
      doom-modeline-persp-name nil)

(set-face-attribute 'mode-line nil :height 0.7)
(set-face-attribute 'mode-line-inactive nil :height 0.7)
```
`doom-modeline-bar-width 4`:
<img width="1057" alt="Screen Shot 2022-06-13 at 14 42 55" src="https://user-images.githubusercontent.com/13161779/173294813-49f2d6ba-5998-4994-93cf-81f59b1ef4d0.png">
`doom-modeline-bar-width 0`:
<img width="1057" alt="Screen Shot 2022-06-13 at 14 42 08" src="https://user-images.githubusercontent.com/13161779/173294857-0f787d0b-38fb-477e-bde2-806186983dea.png">

**Comment by tshu-w** [comment]
@seagle0128 Thx, it works now.

**Comment by jakebox** [comment]
@seagle0128 Yes, things are finally fixed! Thanks for your work.

**Comment by kauesena** [comment]
The code which @tshu-w uses has no effect on my machine, not even when adding 
`(setq doom-modeline-bar-width 0)`. (I use doom emacs, btw.)

**Comment by kauesena** [comment]
I have a 4K display and need to set `doom-font` size to 40. It makes the modelling look way too tall:
![modeline too tall](https://user-images.githubusercontent.com/30255100/177658811-64eccd85-3996-471b-b42a-200e9782aab5.png)

**Comment by seagle0128** [comment]
@kauesena Check your configuration first and try reproduce with `emacs -Q`. `doom-modeline-height` is not set in `doom-emacs` by default.
