### ISSUE TITLE
[Feature Request] Graceful degradation of segments according to space

### ISSUE THREAD

**Issue by johnhamelink** [seagle0128/doom-modeline#533]
**Is your feature request related to a problem? Please describe.**

I often find myself in a situation where I have lots of small windows open in a large, single Emacs frame. This works great for me, but one thing that this workflow exposes is how doom-modeline interacts with windows which have a small width.

At half the width of my monitor, the modeline looks fantastic!

![image](https://user-images.githubusercontent.com/101739/172059075-aa6d6433-c70e-4195-8dda-fb5e1d9399b1.png)

If I split the window in half within the same frame:

![image](https://user-images.githubusercontent.com/101739/172059128-36183722-ffe1-4af8-a69e-d46b2797fdab.png)

**Describe the solution you'd like**
What I'd like here is for the bar to prioritise the display of some content over others.

For example, for my situation I'd like:

- The filename to take priority over the whole or abbreviated path
- Flymake & mu4e-alert should have highest priority
- Things like the buffer position, emms, IRC notifications should be lowest priority

Maybe this is already possible, if so then it'd be great to provide some examples to see how to do it!

Thanks!

**Comment by seagle0128** [comment]
Hi, thanks for the idea! Did you try `doom-modeline-window-width-limit`? I understand it may not the best solution, but it works for the most of scenarios.

**Comment by seagle0128** [comment]
Please try `(setq doom-modeline-window-width-limit 85)`.

**Comment by johnhamelink** [comment]
@seagle0128 sorry! I missed your reply somehow, I did play around with that variable before, but it didn't seem to help, but I will try your suggestion out today and see how I fare. Thank you 🎉

**Comment by johnhamelink** [comment]
@seagle0128 Hey, I've been using that setting for a while now, and honestly its really not making much of a difference:

![image](https://user-images.githubusercontent.com/101739/176780917-4ba262ee-9e16-4b44-9e89-058add02ff84.png)

I'd really like to be able to see my Flycheck errors when I split the frame on the x axis.

**Comment by seagle0128** [comment]
@johnhamelink 85 is an example. You should change the limit value to adapt your env, e.g. 0.6 or 100, etc.

**Comment by johnhamelink** [comment]
Ok, I sat down for 5 minutes and bisected my way to 117. I will try and hide more minor modes and the combination of the two will satisfy me I think. Thanks for your help :)
