### ISSUE TITLE
[Question] How to add an underline/overline to blank space in modeline?

### ISSUE THREAD

**Issue by jojojames** [seagle0128/doom-modeline#537]
Hey, wondering what's the right way to add a border/line to the modeline. Tried something like below but no dice, thanks!

```(let* ((border-color (face-foreground 'window-divider (selected-frame) t))
         (underline `(:color ,border-color))
         (overline `(:color ,border-color)))
    (set-face-attribute 'doom-modeline-spc-face
                        nil :underline underline :overline overline)
    (set-face-attribute 'doom-modeline-spc-inactive-face
                        nil :underline underline :overline overline)
    (set-face-attribute 'doom-modeline-vspc-face
                        nil :underline underline :overline overline)
    (set-face-attribute 'doom-modeline-vspc-inactive-face
                        nil :underline underline :overline overline))```

**Comment by seagle0128** [comment]
Something like

```elisp
(set-face-attribute 'mode-line nil :underline t :overline t)
```

**Comment by jojojames** [comment]
<img width="868" alt="Screen Shot 2022-06-15 at 11 18 27 PM" src="https://user-images.githubusercontent.com/1227856/173983887-43114e68-d3e7-4175-befb-22ce098f48a4.png">

Lines are disconnected.

**Comment by jojojames** [comment]
With:

```
(set-face-attribute 'mode-line nil
                      :underline nil
                      :overline nil
                      :box '(:line-width -1 :style released-button))
```

The top overline doesn't appear.

With:

```
(set-face-attribute 'mode-line nil
                      :underline nil
                      :overline nil
                      :box '(:line-width -1 :style nil))
```

Borders can now be seen but the modeline doesn't respect doom-modeline-height anymore.

**Comment by seagle0128** [comment]
Not sure what's your actual requirement. But obviously it's related to faces setting.

**Comment by jojojames** [comment]
Desired, settable using just mode-line faces.

<img width="1028" alt="Screen Shot 2022-06-18 at 12 30 09 PM" src="https://user-images.githubusercontent.com/1227856/174448018-e2faab68-7fb8-47f7-9c67-735b42d7d38a.png">

With doom-modeline, seemingly not feasible at the moment.

<img width="1028" alt="Screen Shot 2022-06-18 at 12 30 53 PM" src="https://user-images.githubusercontent.com/1227856/174448019-2b0c2309-8168-4c6d-ade7-a2037b73b5e6.png">

> But obviously it's related to faces setting.

Right, question seems to be whether or not it's possible to do with doom-modeline at the moment.

**Comment by seagle0128** [comment]
In my env, it's working well. 

Emacs 20 on macOS

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/140797/174450641-777e706c-67f1-4970-9e43-7b3a1ac1b126.png">

**Comment by seagle0128** [comment]
PS: on 29,  should use `mode-line-active`.
