### ISSUE TITLE
[Bug] Doom-modeline hides battery in tab-bar-mode

### ISSUE THREAD

**Issue by zhenhua-wang** [seagle0128/doom-modeline#543]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Enabling doom-modeline would hide the battery in tab-bar-mode.

### Steps to reproduce

1. set `tab-bar-format` to show battery information.
  ```
(setq tab-bar-format '(tab-bar-format-history
		       tab-bar-format-tabs
		       tab-bar-separator
		       tab-bar-format-align-right
		       tab-bar-format-global))
```
2. enable `display-battery-mode` and `tab-bar-mode`
```
(display-battery-mode 1)
(tab-bar-mode 1)
```
3. install and load doom-modeline
```
(use-package doom-modeline
  :hook
  (after-init . doom-modeline-mode))
```

### Expected behavior

Without doom-modeline, a battery information would show at the right side of the tab bar (See the top right corner of the picture).
<img width="1486" alt="Screen Shot 2022-06-25 at 1 30 24 AM" src="https://user-images.githubusercontent.com/11971417/175761498-64bd44b8-7c84-4652-8a52-1a34d571b86d.png">

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

Emacs with minimal configuration.

### Anything else

I am actually using emacs-29, but there is no option for this.

**Comment by seagle0128** [comment]
It's by design. Try

```elisp
(remove-hook 'display-battery-mode-hook #'doom-modeline-override-battery-modeline)
(remove-hook 'doom-modeline-mode-hook #'doom-modeline-override-battery-modeline)
```

**Comment by zhenhua-wang** [comment]
Thank you! This works great for me.

**Comment by eeowaa** [comment]
May I ask why this is by design? IMO the modeline should not influence the tab bar, as they are completely separate aspects of the UI.

**Comment by seagle0128** [comment]
@eeowaa I added  a new option  `doom-modeline-battery`.

**Comment by eeowaa** [comment]
Thank you!
