### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by nicolasdespres** [seagle0128/doom-modeline#544]
**Is your feature request related to a problem? Please describe.**
I often need to quickly check if the length or the line of code I am writing is not exceeding the limit accepted by the guidelines of the project I am working one. This is often 80 or 76 characters.

**Describe the solution you'd like**
I'd like to have the column number displayed in red in the mode line when the limit is exceeded. Ideally, the limit could be customized in my configuration file through a variable with default value set to nil, which would mean the behavior is deactivated (i.e. never show in red). The possibility to customize the font face used to display the column number when it exceeds the limit would be great too.

**Describe alternatives you've considered**
I like this approach because it is simple to implement and is not too visually invasive while still being informative enough. In some project, the max line length limit is a soft rule so no need for a stricter warning sign.

I tried to add the following code (which was the customization to my mode-line prior to switch to doom-modeline) in my `init.el` file without success :

```elisp
(setq-default mode-line-position
              '((line-number-mode
                 ("%3l"
                  (column-number-mode
                   (":"
                    ; Column number in in red if column-limit is exceeded.
                    (3 (:eval
                        (propertize "%c"
                                    'face (and (> (current-column)
                                                  mode-line-column-limit)
                                               'mode-line-column-limit-warning)
                                    )))
                    ))))))
```

Alternatively, I did not succeed to use [Modeline-region](https://www.emacswiki.org/emacs/ModeLineRegion) (referenced in [EmacsWiki: Eighty Column Rules](https://www.emacswiki.org/emacs/EightyColumnRule)) with doom-modeline. Additionnaly, it provides much more features that I do not need.

**Additional context**
That's the only custom feature I had in my mode-line before I switched to doom-modeline which I find really great so far! It would be even better with this simple feature.

Thanks for reading.

**Comment by seagle0128** [comment]
I think you can define your own `buffer-position` segment. See https://github.com/seagle0128/doom-modeline#faq (item 5), and https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1648.

And, I don't think it's a best way to warn longer line. `global-display-fill-column-indicator-mode` seems better.

**Comment by nicolasdespres** [comment]
Indeed `global-display-fill-column-indicator-mode` is a great way to deal with this. Thanks for the tip!
