### ISSUE TITLE
[Bug] modeline is cutoff or has extra spaces at the right end depending on font size

### ISSUE THREAD

**Issue by sdycjsj** [seagle0128/doom-modeline#545]
### Thank you for the bug report

- [x] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

If modeline font size is larger (smaller) than buffer font size, the modeline is cutoff (has extra spaces) at the right end.
It looks like the calculation of the width of the spaces in the middle is wrong.

### Steps to reproduce

`(set-face-attribute 'mode-line nil :height XXX)` and `(set-face-attribute 'mode-line-inactive nil :height XXX)` to change font size.
`(doom-modeline-redisplay)` to refresh the modeline.
Depending on the height chosen, the right end of modeline behaves differently, as stated above. 

### Expected behavior

The right end of modeline should not be cutoff or have extra spaces

### OS

MacOS

### Emacs Version

gccemacs-28

**Comment by seagle0128** [comment]
If enable `doom-modeline-icon`, unable to calculate the mode-line width accurately, unless `all-the-icons` makes all icons same size. See https://github.com/domtronn/all-the-icons.el/issues/82.

**Comment by sdycjsj** [comment]
Well, this issue has nothing to do with icons.
You can try with `emacs -Q` and set `doom-modeline-icon` to nil

**Comment by seagle0128** [comment]
@sdycjsj Sorry for the regression issue! It has been fixed in 2ff72d7.

**Comment by sdycjsj** [comment]
> @sdycjsj Sorry for the regression issue! It has been fixed in [2ff72d7](https://github.com/seagle0128/doom-modeline/commit/2ff72d794d6a7ed4c5c5ac8b0b314704424150bd).

I can confirm that it has been fixed.
It seems compatibility takes some effort. Thanks :)
