### ISSUE TITLE
[Bug] agenda view 或者 deft 下 modeline 字体太小

### ISSUE THREAD

**Issue by LuciusChen** [seagle0128/doom-modeline#548]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

<img width="771" alt="image" src="https://user-images.githubusercontent.com/4947981/177045636-b867500d-282a-4f80-9e8f-77ef21f578e4.png">
进入 Deft 或者 agenda 之后，字体大小如图。

### Steps to reproduce

进入 agenda view 或者 deft 必现

### Expected behavior

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/4947981/177045703-71d7e31d-8138-4123-b422-961d06b041f3.png">
org 下正常

### OS

MacOS

### Emacs Version

gccemacs-29

### Emacs Configurations

https://github.com/LuciusChen/dotfiles/tree/master/.doom.d

**Comment by seagle0128** [comment]
deft和org agenda有特殊配置吗？用`emacs -Q`能重现吗？

**Comment by LuciusChen** [comment]
> deft和org agenda有特殊配置吗？用`emacs -Q`能重现吗？

对不起，经过配置文件排查，发现是 modus-vivendi 主题的问题。
