### ISSUE TITLE
Visual-Fill-Column mode add empty spaces to the right of the modeline [Bug] 

### ISSUE THREAD

**Issue by zhenhua-wang** [seagle0128/doom-modeline#550]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The newest version of doom-modeline would add empty spaces to the right when visual-Fill-Column mode is enabled. 
<img width="1433" alt="Screen Shot 2022-07-04 at 4 22 00 PM" src="https://user-images.githubusercontent.com/11971417/177217620-20592942-4a1c-4bb2-89af-6c772f8019f7.png">

<img width="1433" alt="Screen Shot 2022-07-04 at 4 22 10 PM" src="https://user-images.githubusercontent.com/11971417/177217621-43e55cad-5171-492b-b896-f22135106bfc.png">

### Steps to reproduce

1. Install both doom-modeline and Visual-Fill-Column mode. 
2.  
```  
(setq-default visual-fill-column-center-text t
		 visual-fill-column-width 100)
```
4. Enable `Visual-Fill-Column mode`

### Expected behavior

No spaces shown at the right side of the modeline.

### OS

MacOS

### Emacs Version

28

**Comment by tshu-w** [comment]
I'm facing similar issue with writeroom-mode:
```emacs-lisp
;;; emacs -Q -l ~/.config/emacs/test.el

(setq package-archives '(("melpa"        . "https://melpa.org/packages/")
                         ("gnu"          . "https://elpa.gnu.org/packages/")
                         ("nongnu"       . "https://elpa.nongnu.org/nongnu/")))

(package-initialize)

(package-install 'doom-modeline)
(package-install 'writeroom-mode)

(doom-modeline-mode)

(setq writeroom-width 128
      writeroom-bottom-divider-width 0
      writeroom-fringes-outside-margins nil
      writeroom-fullscreen-effect nil
      writeroom-major-modes '(text-mode prog-mode conf-mode special-mode Info-mode dired-mode)
      writeroom-major-modes-exceptions '(process-menu-mode proced-mode)
      writeroom-maximize-window nil
      writeroom-mode-line t
      writeroom-mode-line-toggle-position 'mode-line-format)

(global-writeroom-mode)
```
<img width="2008" alt="Screen Shot 2022-07-05 at 11 09 08" src="https://user-images.githubusercontent.com/13161779/177241992-d4c9cb63-3b58-4f31-ada4-61768154f07c.png">
