### ISSUE TITLE
[Bug] the right side of modeline is cut if LSP "rocket" icon is visible

### ISSUE THREAD

**Issue by dsh2dsh** [seagle0128/doom-modeline#551]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Hi,

With doom-modeline-lsp t and visible rocket icon the modeline looks weird:
![Screenshot_20220710_181318](https://user-images.githubusercontent.com/993498/178153049-2c5771a2-629f-4236-a511-b663e824f8e0.png)

After changing it to doom-modeline-lsp nil the modeline looks correct:
![Screenshot_20220710_181433](https://user-images.githubusercontent.com/993498/178153072-3f96301a-b2df-484a-ab68-b67df907d5eb.png)

Thanks.

### Steps to reproduce

Open any file with lsp-mode.

### Expected behavior

The modeline should look like on my last screenshot. The checkmark should be fully visible.

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Just a vanilla emacs

**Comment by seagle0128** [comment]
1. Use emacs 29.
2. Add spaces at the last of the mode-line.
3. Use other fonts or size.

**Comment by dsh2dsh** [comment]
@seagle0128 thanks, I like this advise
> Add spaces at the last of the mode-line.

Could you suggest how to do that?

**Comment by seagle0128** [comment]
See FAQ 5 in README.
