### ISSUE TITLE
[Bug] doom-modeline causes oversized which-key window

### ISSUE THREAD

**Issue by FuzzyWuzzyBMP** [seagle0128/doom-modeline#553]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using both which-key and doom-modeline, the which-key window opens too large (half the height of the active window) for a split second, before shrinking back to its expected size.

While distracting on its own, it is made worse if the point is on the bottom half of the window, that gets covered by the which-key window, causing the active window to scroll to keep the point visible. In my experiments, setting `doom-modeline-height` to < 19 resolved the issue.

I don't know if the root cause lies in doom-modeline or which-key.

### Steps to reproduce

Open a text file with enough lines in emacs. With point near the top of the window, press `C-x` to make the which-key window appear. Move the point to 1-2 lines above the top of the which-key window, close the which-key window, then re-open it with `C-x`. That should cause it to momentarily cover the point and scroll the active window.

Configuration used in testing:
```
; early-init.el
(setq package-enable-at-startup nil)
```
```
; init.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package which-key
  :config (which-key-mode))

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  ; :config (setq doom-modeline-height 1)  ; Uncomment to fix the bug.
)
```

### Expected behavior

No different than without doom-modeline - the which-key window opens at its final size immediately, and does not cover half the active window before shrinking.

### OS

Linux

### Emacs Version

27

### Emacs Configurations

Vanilla emacs

**Comment by seagle0128** [comment]
1. Can you please provide recordings or screenshots?
2. Try `(advice-remove #'fit-window-to-buffer :before #'doom-modeline-redisplay)`, please.

**Comment by FuzzyWuzzyBMP** [comment]
Recording of this issue attached.

Appending `(advice-remove #'fit-window-to-buffer :before #'doom-modeline-redisplay)` to init.el produces a `Wrong number of arguments: (2 . 2), 3` error during loading, and the issue persists.

https://user-images.githubusercontent.com/13451773/180484893-4b554179-bc65-40d2-bc9b-b4ff2dcd773e.mp4

**Comment by seagle0128** [comment]
Sorry, try `(advice-remove #'fit-window-to-buffer #'doom-modeline-redisplay)`.

**Comment by FuzzyWuzzyBMP** [comment]
The workaround works, and resolves the issue, thank you.

**Comment by seagle0128** [comment]
> The workaround works, and resolves the issue, thank you.

Reminder, removing the workaround will cause other issues.
