### ISSUE TITLE
[Bug] Icon is not shown correctly

### ISSUE THREAD

**Issue by dr-scsi** [seagle0128/doom-modeline#555]
### Thank you for the bug report

- [X] I am using the latest version of `doom-mode` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

First of all, many thanks for providing this package.

The latest version (doom-modeline-20220726.822) landed from MELPA and the modeline looks like this when I open `doom-modeline.el` file from my local git repo:

![doom](https://user-images.githubusercontent.com/59777257/181004515-26a31945-9b66-4528-be6c-4c5974ba59e6.png)

### Steps to reproduce

1. emacs -Q
2. Eval the following forms in `scratch`:  
  ```
  (package-initialize)
  (setq display-time-24hr-format t)
  (display-time-mode 1)
  (doom-modeline-mode 1)
  ```
3. <kbd>C-x C-f path/to/doom-modeline.el RET</kbd>

### Expected behavior

Get the correct icon in the modeline.

### OS

Windows

### Emacs Version

gccemacs-28

### Emacs Configurations

Vanilla Emacs 29 from git-master (0f9c28f008)

**Comment by seagle0128** [comment]
Please check if `all-the-icons` fonts (`fontawesome`) are installed correctly.

@Peter-Chou Can you please look into this issue? Since it's related to #554.

**Comment by seagle0128** [comment]
@Peter-Chou  I committed a patch. Please test the latest version.

**Comment by Peter-Chou** [comment]
@seagle0128 it also works for me 😄
