### ISSUE TITLE
[Feature Request] Make the time segment optional

### ISSUE THREAD

**Issue by arunkmv** [seagle0128/doom-modeline#557]
**Is your feature request related to a problem? Please describe.**
I would like to make the time segment in the modeline optional even if `display-time-mode` is enabled. Earlier this could be achieved by removing certain hooks from `display-time-mode-hook`. But #554 made it such that the new time segment is automatically displayed when `display-time-mode` is enabled.

**Why have an additional option? Why not just disable `display-time-mode`?**
Displaying time in the modeline is great but it's not possible to do so when windows are split. To overcome this I use the tab-bar to display the `global-mode-string`. This makes it possible to have a single time display in a given frame. I cannot speak on the popularity of this method, but it seems like at least a few folks do it this way. Since `display-time-mode` needs to be enabled for doing this as well, it causes a duplicate time display in both the tab-bar and modeline.

<img width="1680" alt="Screenshot 2022-08-12 at 8 59 40 PM" src="https://user-images.githubusercontent.com/52396436/184392305-3d81fefb-87f9-4a18-9e12-dbba805d2725.png">

**Solution**
Adding a new custom variable `doom-modeline-time` should do the trick. I can see two ways in which this could be done.

*Approach 1*
The user has to set the new `doom-modeline-time` variable as well as enable `display-time-mode` to display the time segment in the modeline. This could make things confusing but adequate documentation should take care of it.  Here's what it could look like:
```elisp
(doom-modeline-def-segment time
  (when (and doom-modeline-time
             (bound-and-true-p display-time-mode)
             (not doom-modeline--limited-width-p))
    (concat
     doom-modeline-spc
     (when doom-modeline-time-icon
       (concat
        (doom-modeline-icon 'octicon "calendar" "📅" ""
                            :face 'doom-modeline-time
                            :v-adjust -0.05)
        (and (or doom-modeline-icon doom-modeline-unicode-fallback)
             doom-modeline-spc)))
     (propertize display-time-string
                 'face (doom-modeline-face 'doom-modeline-time)))))

```
*Approach 2*
The user has to only set  the new `doom-modeline-time` variable to display the time segment in the modeline. Internally `display-time-mode` is automatically enabled when the variable is set. Here's what it could look like:
```elisp
(doom-modeline-def-segment time
  (when (and doom-modeline-time
             (not doom-modeline--limited-width-p))
    (when (not (bound-and-true-p display-time-mode))
      (display-time-mode))
    (concat
     doom-modeline-spc
     (when doom-modeline-time-icon
       (concat
        (doom-modeline-icon 'octicon "calendar" "📅" ""
                            :face 'doom-modeline-time
                            :v-adjust -0.05)
        (and (or doom-modeline-icon doom-modeline-unicode-fallback)
             doom-modeline-spc)))
     (propertize display-time-string
                 'face (doom-modeline-face 'doom-modeline-time)))))
```
I see one immediate problem that could arise from this approach. If the user unsets `doom-modeline-time`, `display-time-mode` would continue to be unnecessarily enabled. Also, I'm not sure about any other side-effects that could arise from doing things this way.

Please let me know if this seems like a necessary feature and which approach could be taken or any alternate approaches that you have in mind. I could start working on a PR.

Thank you for your continued efforts in developing and maintaining this great package.

**Comment by seagle0128** [comment]
Thanks for the detailed report!

I think the option 1 is simple and easy to understand. The option 2 may bring more side-effects, thus will confuse the users. I will implement it and submit soon.

**Comment by arunkmv** [comment]
Thanks for the quick response and fix!
