### ISSUE TITLE
Issues with height and padding.

### ISSUE THREAD

**Issue by theherk** [seagle0128/doom-modeline#558]
I would like to have my modeline be no taller than its contents, but I can't sort where the padding is coming from. It is just massive; ideally it would be just one line tall.

Here is my font configuration:

```elisp
(setq
  doom-font (font-spec :family "VictorMono Nerd Font" :size 20)
  doom-big-font (font-spec :family "VictorMono Nerd Font" :size 24)
  doom-variable-pitch-font (font-spec :family "VictorMono Nerd Font" :size 20))
```

I started by setting `(setq doom-modeline-height 1)`, to ensure it was only as big as the smallest thing within. Here is what it looks like:

![normal](https://user-images.githubusercontent.com/3605078/185578766-6f600f54-3075-446e-8bd8-c36ef57560df.png)

I have tried with simply scaling down height (exaggerated) with:

```elisp
(custom-set-faces
  '(mode-line ((t (:height 0.2))))
  '(mode-line-inactive ((t (:height 0.2)))))
```

![lower height](https://user-images.githubusercontent.com/3605078/185578777-570e7296-2dc6-44de-9935-3c8918d96e10.png)

This correctly shrinks the content, but still leaves all the padding. I think this is sort of fine, because I don't expect it to be smaller than one line, but as soon as I size the height up, the padding becomes an issue again. The primary issue seems to be that the modeline extends beyond the bar section. If you zoom in you can see the bar indicator on the left is actually smaller than the modeline.

I have also tried the approach listed in #187 and #453:

```elisp
(defun my-doom-modeline--font-height ()
  "Calculate the actual char height of the mode-line."
  (+ (frame-char-height) 2))
(advice-add #'doom-modeline--font-height :override #'my-doom-modeline--font-height)
```

![advice](https://user-images.githubusercontent.com/3605078/185578787-4ec19b51-e568-4fbc-82fb-eaff7166e137.png)

But this still has padding at the top. I'm not sure what I'm doing wrong here, but how can one configure this modeline to be the same height as every other line in the editor? I know this has been talked about quite a bit, but I'm still not clear if there is a solution, and if so is in this package or elsewhere in my configuration.

**Comment by seagle0128** [comment]
The height of mode line is the max value of font height and `doom-modeline-height`. And you may need to set `doom-modeline-bar-width` to 0, and set `doom-modeline-height` to 1.

**Comment by theherk** [comment]
Thank you for the response. Even with both of these settings the modeline still extends above the bar. Even when my font is very tiny.

**Comment by theherk** [comment]
I'm going to close this so I'm not clogging up the tracker with trivial issues, but if anybody stumbles in here with a solution I haven't considered, please share.

**Comment by seagle0128** [comment]
I am suggesting to reproduce with `emacs -Q`, since I am not sure if doom emacs modifies something. And I am also suggesting NOT to use float for fonts in mode-line.
