### ISSUE TITLE
can't install doom-modeline due to compat package unavailable

### ISSUE THREAD

**Issue by robin2003** [seagle0128/doom-modeline#563]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

can't install doom-modeline
```
Package doom-modeline is incompatible.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa-stable
    Version: 3.3.1
     Commit: 156b02445c3360added80009ab3c1a33dd88c5d9
    Summary: A minimal and modern mode-line
   Requires: emacs-25.1, compat-28.1.1.1 (not available), shrink-path-0.2.0
   Homepage: https://github.com/seagle0128/doom-modeline
   Keywords: faces mode-line 
 Maintainer: Vincent Zhang <seagle0128@gmail.com>
     Author: Vincent Zhang <seagle0128@gmail.com>

```

### Steps to reproduce

1. list all available packages in emacs;
2. locate "doom-modeline"
3. install

### Expected behavior

it can be install succesfully.

### OS

Linux

### Emacs Version

27

**Comment by seagle0128** [comment]
You should add http://elpa.gnu.org/packages/ into the archives list. `compat` is released to elpa.

**Comment by philippludwig** [comment]
Here is the real solution: This happens if the `elpa` repository is unavailable to you. Set `(setq package-check-signature nil)` to avoid the non-working signature check, then run `package-refresh-contents`.
