### ISSUE TITLE
allow icons to be configurable with other unicode characters

### ISSUE THREAD

**Issue by sethen** [seagle0128/doom-modeline#564]
**Describe the solution you'd like**
doom modeline requires that you use all the icons to display certain icons in the modeline.  I have my own font that I've made and use these unicode characters in my directory navigation.  It would be nice if doom modeline would allow changing of the icons with other unicode characters of the users choosing like treemacs does.

**Comment by seagle0128** [comment]
It's a good idea, but needs big changes. I need to think over carefully. If you have good thoughts, please let me know. PRs are always welcome.

**Comment by sethen** [comment]
@seagle0128 Are you seeking help to bikeshed an API for this or technical help on the elisp side?  I am not the greatest elisper

**Comment by seagle0128** [comment]
No. It's not a  technical issue, while efforts challenge. And I am not sure if it's worth to do that.
