### ISSUE TITLE
Modeline not working as expected when mouse hover a frame in an out

### ISSUE THREAD

**Issue by iris-garcia** [seagle0128/doom-modeline#565]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Probably this bug only happens in Linux (GTK) and maybe only with specific Windows Managers.
I'm using Qtile as Window Manager.

The bug is the following: moving the mouse out of a frame leaves the modeline in a half-state (active-inactive) and it behaves different if the the mouse hovers another Emacs frame or a different App.

Pictures:
1. Moving mouse from Frame 1 to different App:
![image](https://user-images.githubusercontent.com/3024945/188427340-008a7b3f-6760-4b13-a2e3-5bdec74a3c9f.png)
2. Moving mouse from Frame 1 to Frame 2:
![image](https://user-images.githubusercontent.com/3024945/188427450-6a89dc4f-ff85-40b7-ba1b-0e1208a63595.png)
3. Moving mouse from Frame 1 to Frame 2 then clicking on Frame 2 (modeline looks good in this case, but a click is needed)
![image](https://user-images.githubusercontent.com/3024945/188427715-ada567f7-89d0-4162-b6b6-72521943d425.png)

### Steps to reproduce

Use doom-emacs and a tiling windows manager.

### Expected behavior

When focus is lost on a frame the modeline should be inactive.
When focus is gain on a frame the modeline should be fully active (not needing an extra click).

### OS

Linux

### Emacs Version

29 (gccemacs-dev)

### Emacs Configurations

Doom Emacs

**Comment by iris-garcia** [comment]
> Please try `(advice-add #'select-window :after #'force-mode-line-update)` and/or `(add-function :after after-focus-change-function #'force-mode-line-update)`.

Something not working as it should with: `(advice-add #'select-window :after #'force-mode-line-update)`
```
apply: Wrong number of arguments: #<subr force-mode-line-update>, 2
```

**Comment by seagle0128** [comment]
Not sure what happen to your DE. Try this snippet

```elisp
(advice-add #'select-window :after (lambda (&rest _) (force-mode-line-update)))
(advice-add #'handle-switch-frame :after #'doom-modeline-set-selected-window)
(add-function :after after-focus-change-function #'doom-modeline-set-selected-window)
```

**Comment by iris-garcia** [comment]
> No idea what happen to your WM. Try this snippet
> 
> ```emacs-lisp
> (advice-add #'select-window :after (lambda (&rest _) (force-mode-line-update)))
> (advice-add #'handle-switch-frame :after #'doom-modeline-set-selected-window)
> (add-function :after after-focus-change-function #'doom-modeline-set-selected-window)
> ```

No luck with the snippet above :(.

Adding this one:
```
(defun do-click ()
  (interactive)
  (mouse-drag-region '(0))
  (mouse-set-point 'click nil))

(global-set-key (kbd "<f9>") 'do-click)
```
When I press <f9> it fixes the modeline but there are still issues when the frame loses the focus (modeline not getting the inactive face)

**Comment by seagle0128** [comment]
I think it's related to Emacs 29 and/or WM. I tested on macOS 12.5, Windows 10/11, Ubuntu KDE/Mate, Linux Mint Cinnamon, etc. It's working well.

**Comment by iris-garcia** [comment]
> I think it's related to Emacs 29 and/or WM. I tested on macOS 12.5, Windows 10/11, Ubuntu KDE/Mate, Linux Mint Cinnamon, etc. It's working well. It seems face remapping is not working in your env. How about vanilla Emacs (`emacs -Q`)?

If you mean the default modeline without any extra configuration, that works as expected.

Vanilla Emacs + doom-modeline is something I haven't tried yet.

**Comment by seagle0128** [comment]
Yes. I mean `Vanilla Emacs + doom-modeline`.

**Comment by iris-garcia** [comment]
Ok, I confirm `Vanilla Emacs + doom-modeline` works as expected, I'll try to find out what is causing the issues in `doom`.

Thank you @seagle0128
