### ISSUE TITLE
[Bug] Strange Icon Artifacts (Emacs 28.2)

### ISSUE THREAD

**Issue by yusi1** [seagle0128/doom-modeline#567]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I have strange artifacts in doom-modeline, icons have a weird "overlay" thing, I cannot explain it that well, so here's a screenshot:

![Screenshot_2022-09-12_20-57-51](https://user-images.githubusercontent.com/82241382/189744548-d22deec7-88e4-4c92-b6b2-a15ceada9642.png)

(another screenshot, but with a larger font) (look at the strange artifacting on the modal indicator on the left of the modeline)
![Screenshot_2022-09-12_21-38-44](https://user-images.githubusercontent.com/82241382/189754138-04825313-8893-4a22-b272-82f18e3827a8.png)

What the screenshot shows is the modal indicator in doom-modeline, it has a weird grayish overlay that seems to appear or disappear randomly.

### Steps to reproduce

I don't know.

### Expected behavior

A normal looking icon without artifacts.

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Irrelevant (This happened on vanilla Emacs too, with doom-modeline)

**Comment by seagle0128** [comment]
See #328 .
