### ISSUE TITLE
[Feature Request] Status indicator for active compilation buffer

### ISSUE THREAD

**Issue by Thaodan** [seagle0128/doom-modeline#568]
**Is your feature request related to a problem? Please describe.**
The compilation buffer as no status indicator when it is running like the builtin mode line does.

**Describe the solution you'd like**
An indicator about the compilation buffer to be active similar to the lsp indicator.

**Describe alternatives you've considered**
Use some minor mode to show the status.

**Additional context**
- https://www.emacswiki.org/emacs/CompilationMode

**Comment by seagle0128** [comment]
Hi, can you describe more details? It's better add detailed steps and screenshots/recordings. 

Actually `doom-modeline` supports `mode-line-process` as below.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/140797/193645952-ca1d4540-e8d9-49ad-9f2a-26e683d644b8.png">

BTW, lsp leverages `global-mode-string`.

**Comment by Thaodan** [comment]
> Hi, can you describe more details? It's better add detailed steps and
> screenshots/recordings.

1. M-x `compile`
2. Choose command
3. Enter

Now using the standard modeline there's a **compile** indicator.
Read here for more:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation.html

**Comment by seagle0128** [comment]
Don't you mean `mode-line-process`? This is not what you need? Any screenshot?

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/140797/193650159-fb9a1f45-dc22-47b9-8ebd-e20e16e65668.png">

**Comment by Thaodan** [comment]
> Don't you mean `mode-line-process`? It's exactly same as the vanilla. This is not what you need? Any screenshot?
> 
> <img alt="image" width="1060" src="https://user-images.githubusercontent.com/140797/193650159-fb9a1f45-dc22-47b9-8ebd-e20e16e65668.png">

Just disabled doom-modeline for a sec and you'll see.

But in any case this is the indicator that exits in the stock modeline when you have a compile buffer active and visit another buffer:

![Screenshot_20221004_001507](https://user-images.githubusercontent.com/1747359/193684130-2469307a-c1d4-4508-9ee0-2adb58b86937.png)

**Comment by seagle0128** [comment]
A new segment is added. The screenshot is below.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/140797/193930064-cab24b9b-a639-425c-a8be-6b9da01bf82a.png">

**Comment by Thaodan** [comment]
> A new segment is added. The screenshot is below.
> 
> <img width="475" alt="image"
> src="https://user-images.githubusercontent.com/140797/193930064-cab24b9b-a6
> 39-425c-a8be-6b9da01bf82a.png">
> 

I noticed that now the indicator is also active when M-x find-grep is used I'm 
not sure if that's intended.

**Comment by seagle0128** [comment]
The expected behaviors should be as same as vanilla mode-line.
