### ISSUE TITLE
Uniquify(?) in a buffer name

### ISSUE THREAD

**Issue by wedens** [seagle0128/doom-modeline#57]
![image](https://user-images.githubusercontent.com/697162/49354157-f86a4500-f6f3-11e8-80c2-8582cd1e4996.png)

If I have multiple buffers with the same name (e.g. multiple `init.el` from different locations), buffer name in a modeline becomes `dotfiles/.e/init.el[.emacs.d/init.el]`. It doesn't happen when I have a single `init.el` buffer opened.

I think it's probably being added by uniquify, but I don't see such thing in `ivy-switch-buffer`.

The only uniquify-related configuration I have is `(setq uniquify-buffer-name-style 'forward)`.

I'm not sure whether it's a bug or feature, but is it possible to disable appending [...] to a buffer name in a modeline?

emacs 27.0.50
doom-modeline: HEAD

**Comment by wedens** [comment]
`doom-modeline-buffer-file-name-style` is set to `truncate-with-project` 

doom-modeline fac54da

I can consistently reproduce it by opening multiple buffers with the same name.

When I set `uniquify-buffer-name-style`  to `nil`, it no longer reproduces, so it's definitely related to uniquify.

**Comment by seagle0128** [comment]
Okay. I can confirm it's because of your configuration `(setq uniquify-buffer-name-style 'forward)`. If set to `post-forward-angle-brackets` or `nil`, all look fine.

Well, I will see if it can be optimized...

**Comment by wedens** [comment]
I think I can just change it to `post-forward-angle-brackets`.

You can close the issue if you think handling `'forward` specifically doesn't worth it.
