### ISSUE TITLE
[Bug] The color of bar do not changed when the themes sync with system appearance. 

### ISSUE THREAD

**Issue by mzwlevi** [seagle0128/doom-modeline#570]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The color of bar do not changed when the themes sync with system appearance. 

### Steps to reproduce

* I am using this code to sync themes with system appearance:
```emacs-lisp
(defun mac-apply-system-appearance ()
  (let ((appearance (plist-get (mac-application-state) :appearance)))
    (cond ((equal appearance "NSAppearanceNameAqua")
           (load-theme 'ef-spring t)
	   (custom-set-faces '(line-number-current-line ((t (:foreground "#90e8b0"))))))
          ((equal appearance "NSAppearanceNameDarkAqua")
           (load-theme 'ef-night t)
	   (custom-set-faces '(line-number-current-line ((t (:foreground "#00397f"))))))
	  ((equal appearance nil)
           (load-theme 'ef-spring t)
           (custom-set-faces '(line-number-current-line ((t (:foreground "#90e8b0")))))))))
(add-hook 'after-init-hook 'mac-apply-system-appearance)
(add-hook 'mac-effective-appearance-change-hook 'mac-apply-system-appearance)
```
When the theme changed with system appearance, the color of bar do not changed.

* Comparison
![Screen Shot 2022-09-21 at 14 05 33](https://user-images.githubusercontent.com/78029539/191426798-e56cf05b-938c-4e6e-9c58-c52c5d3fa510.png)
![Screen Shot 2022-09-21 at 14 05 26](https://user-images.githubusercontent.com/78029539/191426808-12fab71f-f249-4080-9c0b-c8b36890bdd8.png)

* Normal
![191426131-cf0b7716-491f-40e4-86b9-16050b3e65c0](https://user-images.githubusercontent.com/78029539/191426223-a1ad6fe9-8866-41ac-8280-fa1828190a2b.png)

### Expected behavior

The color can be showed normal

### OS

MacOS

### Emacs Version

28

**Comment by seagle0128** [comment]
`doom-modeline-refresh-bars` should be called while the theme is changed.
