### ISSUE TITLE
[Bug] Sep 23, 2022 version creates display issues with `list-packages`, `dired`

### ISSUE THREAD

**Issue by emacsomancer** [seagle0128/doom-modeline#571]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Some change of Sep 23, 2022 seems to create display issues when trying to use `list-packages` or `dired`. `list-packges` will seem to execute, but the screen fails to update. Disabling `doom-modeline` resolves the issue. As does reverting to the Sep 20, 2022 version of `doom-modeline`.

### Steps to reproduce

enable the latest version of `doom-modeline`, try to do `M-x list-packages`.

### Expected behavior

not interfere with display

### OS

Linux

### Emacs Version

28 (gccemacs)

**Comment by deifactor** [comment]
I'm seeing the same thing in some lsp-mode buffers. Also, sometimes emacs just completely freezes on start. I think a1411d5e and a1668877 should be reverted.

**Comment by gopar** [comment]
Yups same, Emacs screen no longer updates after starting. Took a while to find out what it was since I do batch updates
