### ISSUE TITLE
[Feature Request] Allow customising doom-modeline-mode-alist

### ISSUE THREAD

**Issue by nbarrientos** [seagle0128/doom-modeline#574]
**Is your feature request related to a problem? Please describe.**

Following the [README](https://github.com/seagle0128/doom-modeline/blob/4a2151738d87b6332019b74028e63d8f26fbc0ca/README.md?plain=1#L416), I was configuring `doom-modeline` so I could have my custom modeline with the segments of my liking, something like:

```emacs-lisp
  (doom-modeline-def-modeline 'my-modeline
    '(bar matches buffer-info remote-host buffer-position)
    '(misc-info time irc debug input-method major-mode process checker))
  (add-hook 'doom-modeline-mode-hook
            (lambda nil
              (doom-modeline-set-modeline 'my-modeline 'default)))
```

However I realised that in buffers with certain major modes enabled (like `magit-mode`) my preferences were not respected and another modeline configuration was being used. Looking at the code I stumbled upon [`doom-modeline-mode-alist`](https://github.com/seagle0128/doom-modeline/blob/4a2151738d87b6332019b74028e63d8f26fbc0ca/doom-modeline.el#L188) which wins over my custom configuration. What I did to force my modeline configuration in *all* buffer types was to basically:

```emacs-lisp
(setq doom-modeline-mode-alist nil)
```

**Describe the solution you'd like**

* Document this behaviour better in the README, particularly in the section titled "How can I define my own mode-line?".
* Turn `doom-modeline-mode-alist` into a `defcustom` as the major mode and modeline mapping is something that the end-user might have to customise.

Thanks for considering this request.

**Comment by seagle0128** [comment]
Basically users can use `doom-modeline-mode-alist` or old method in README to customize users' mode lines. `doom-modeline-mode-alist` was introduced recently and I'd like testing for more, then change to an option.

Thanks for reporting this anyway!
