### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dickby** [seagle0128/doom-modeline#575]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Eglot changed eglot--major-mode to eglot--major-modes.
Doom-modeline extends that function and throws an error now.
It's an easy fix.

### Steps to reproduce

Well use eglot and doom-modeline

### Expected behavior

Should work

### OS

Linux

### Emacs Version

29 (dev)

**Comment by Dickby** [comment]
Thanks!

**Comment by seagle0128** [comment]
See https://github.com/joaotavora/eglot/commit/d0a657e81c5b02529c4f32c2e51e00bdf4729a9e.
