### ISSUE TITLE
[Bug] Wrong buffer name being displayed

### ISSUE THREAD

**Issue by nbarrientos** [seagle0128/doom-modeline#578]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Since recent commits (likely to be [`deca7aebc5013b2ece6454ba984447d15bd8c655`](https://github.com/seagle0128/doom-modeline/commit/deca7ae)) but I haven't had time yet to bisect and debug further, sometimes the buffer name segment is not the one it should be.

For example this is a `exwm-mode` buffer containing an instance of the Telegram desktop application, however the buffer name is:

![image](https://user-images.githubusercontent.com/131893/193404408-bcd77703-a111-41d1-9a32-348eb202cb89.png)

`*mu4e-headers*` is the name of another existing buffer.

Emacs-wise everything seems correct:

```
λ> (ielm-change-working-buffer "Telegram")
"The current working buffer is: Telegram"
λ> (buffer-name)
"Telegram"
λ> (buffer-file-name)
nil
λ> major-mode
exwm-mode
λ> doom-modeline--buffer-file-name
#("*mu4e-headers*" 0 14
  (face mode-line-buffer-id help-echo "Buffer name
mouse-1: Previous buffer
mouse-3: Next buffer" mouse-face mode-line-highlight local-map
(keymap
 (header-line keymap
              (mouse-3 . mode-line-next-buffer)
              (down-mouse-3 . ignore)
              (mouse-1 . mode-line-previous-buffer)
              (down-mouse-1 . ignore))
 (mode-line keymap
            (mouse-3 . mode-line-next-buffer)
            (mouse-1 . mode-line-previous-buffer)))))
```

If I run `M-x doom-modeline-mode`, the buffer name is okay:

![image](https://user-images.githubusercontent.com/131893/193404491-9861b84a-0042-41a6-b918-ee6f0afc04cd.png)

but if I re-enable it again it's still wrong:

![image](https://user-images.githubusercontent.com/131893/193404522-c26b3d45-5b42-496f-8960-93c29720d66f.png)

If I execute `(doom-modeline-update-buffer-file-name)` manually when the buffer with the wrong name is active the name is correctly set:

![image](https://user-images.githubusercontent.com/131893/193404694-d490dcd9-8b58-471a-95e8-5b89b75f6aee.png)

Of course killing the buffer and creating it again also works. So far I haven't seen this happening in buffers with other major modes, so it might well be that something has been introduced that's not playing nicely with how EXWM renames buffers based on the X title windows :thinking: 

My configuration is:

```emacs-lisp
(use-package doom-modeline
  :config
  (set-face-attribute 'mode-line nil :height 100)
  (set-face-attribute 'mode-line-inactive nil :height 100)
  (set-face-attribute 'doom-modeline-time nil
                      :inherit 'doom-modeline-buffer-minor-mode)
  (setq doom-modeline-mode-alist nil)
  (doom-modeline-def-modeline 'my-modeline
    '(bar matches buffer-info remote-host buffer-position)
    '(misc-info time irc debug input-method major-mode process checker))
  (add-hook 'doom-modeline-mode-hook
            (lambda nil
              (doom-modeline-set-modeline 'my-modeline 'default)))
  (doom-modeline-mode 1)
  :custom
  (doom-modeline-height 30)
  (doom-modeline-buffer-modification-icon nil)
  (doom-modeline-irc-buffers t)
  (doom-modeline-buffer-file-name-style 'relative-from-project)
  (doom-modeline-time-icon nil))
```

I don't have more information at the moment. I'll try to distill a reproducer but I'm reporting the issue already just in case it rings a bell. For the moment I'll just run [`13748fe`](https://github.com/seagle0128/doom-modeline/commit/13748fe) for a while to see if the problem surfaces.

### Steps to reproduce

Unclear yet.

### Expected behavior

`(buffer-name)` being always honored.

### OS

Linux

### Emacs Version

28

**Comment by nbarrientos** [comment]
After downgrading to [`13748fe`](https://github.com/seagle0128/doom-modeline/commit/13748fe) (from [`b1fa665`](https://github.com/seagle0128/doom-modeline/commit/b1fa6659b2487e6a7cf86c96f72b6b96f1715e50)) and heavily using the system for two hours I couldn't reproduce the issue above. All buffer names were always displayed correctly in the modeline, regardless of the major mode.

**Comment by seagle0128** [comment]
Can you try the latest version 5dbb43411e79c1c67cdcd05e04c037c229c8ea87?

**Comment by nbarrientos** [comment]
Hi,

Thanks for answering.

It happens too using 5dbb434, unfortunately.

``` emacs-lisp
λ> (set-buffer "Telegram")
#<buffer Telegram>
λ> (buffer-name)
"Telegram"
λ> (buffer-file-name)
nil
λ> mode-line-buffer-identification
(#("%12b" 0 4
   (face mode-line-buffer-id help-echo "Buffer name
mouse-1: Previous buffer
mouse-3: Next buffer" mouse-face mode-line-highlight local-map
(keymap
 (header-line keymap
              (mouse-3 . mode-line-next-buffer)
              (down-mouse-3 . ignore)
              (mouse-1 . mode-line-previous-buffer)
              (down-mouse-1 . ignore))
 (mode-line keymap
            (mouse-3 . mode-line-next-buffer)
            (mouse-1 . mode-line-previous-buffer))))))

λ> doom-modeline--buffer-file-name
#(" *Minibuf-1*" 0 12
  (face mode-line-buffer-id help-echo "Buffer name
mouse-1: Previous buffer
mouse-3: Next buffer" mouse-face mode-line-highlight local-map
(keymap
 (header-line keymap
              (mouse-3 . mode-line-next-buffer)
              (down-mouse-3 . ignore)
              (mouse-1 . mode-line-previous-buffer)
              (down-mouse-1 . ignore))
 (mode-line keymap
            (mouse-3 . mode-line-next-buffer)
            (mouse-1 . mode-line-previous-buffer)))))
```

If I manually execute:

``` emacs-lisp
(format-mode-line mode-line-buffer-identification)
```

With the current buffer the one that's broken, the output is the
expected one:

``` text
#("Telegram    " 0 8 (local-map (keymap (header-line keymap ... ... ... ...) (mode-line keymap ... ...)) mouse-face mode-line-highlight help-echo "Buffer name...
```

**Comment by nbarrientos** [comment]
> I have the impression that it's kind of a race condition, if at the time of setting the modeline of the buffer another buffer is active. For instance, if I launch the Telegram app and before it's fully ready I do something else.

My take is that EXWM buffer names can change asynchronously if the (X) window title changes so when the advised `rename-buffer` is ultimately called by EXWM, and hence `doom-modeline-update-buffer-file-name` too, the active window/buffer does not necessarily have to be the one that's getting its buffer name changed.

As you're using now `format-mode-line` to format buffer titles in non-file buffers, this applies:

```
Signature
(format-mode-line FORMAT &optional FACE WINDOW BUFFER)

Documentation
Format a string out of a mode line format specification.

First arg FORMAT specifies the mode line format (see mode-line-format
for details) to use.

By default, the format is evaluated for the currently selected window.
...
Optional third and fourth args WINDOW and BUFFER specify the window
and buffer to use as the context for the formatting (defaults
are the selected window and the WINDOW's buffer).
```

**Comment by nbarrientos** [comment]
How to reproduce:

1. Create a buffer called `*foo*`
2. `M-x ielm`

```emacs-lisp
λ> (set-buffer "*foo*")
#<buffer *foo*>
λ> (buffer-name)
"*foo*"
λ> (rename-buffer "*bar*")
"*bar*"
λ> (buffer-name)
"*bar*"
```

With `13748fe` the buffer name in the modeline is correctly changed to `*bar*`, with `5dbb434` the name displayed is `*ielm*` (buffer name of the active buffer in the active window)

**Comment by nbarrientos** [comment]
This fixes to problem for me:

``` diff
diff --git a/doom-modeline-segments.el b/doom-modeline-segments.el
index ab08b62..d705ea2 100644
--- a/doom-modeline-segments.el
+++ b/doom-modeline-segments.el
@@ -326,7 +326,11 @@ doom-modeline-update-buffer-file-name
           (save-match-data
             (if buffer-file-name
                 (doom-modeline-buffer-file-name)
-              (format-mode-line mode-line-buffer-identification))))))
+              (format-mode-line
+               mode-line-buffer-identification
+               nil
+               nil
+               (current-buffer)))))))
 (add-hook 'find-file-hook #'doom-modeline-update-buffer-file-name)
 (add-hook 'after-save-hook #'doom-modeline-update-buffer-file-name)
 (add-hook 'clone-indirect-buffer-hook #'doom-modeline-update-buffer-file-name)
```

**Comment by seagle0128** [comment]
Before I use `mode-line-buffer-identification` instead of `%b` for backward compatibility, but it seems `mode-line-buffer-identification` is not updated timely. Your fix looks good, and I will commit a patch soon.

**Comment by nbarrientos** [comment]
Thanks.
