### ISSUE TITLE
Major mode is shown twice

### ISSUE THREAD

**Issue by drrlvn** [seagle0128/doom-modeline#58]
Icon is shown on the left and on the right:

![image](https://user-images.githubusercontent.com/38856/49443859-2e7ff580-f7d6-11e8-92b5-a7c1c7023d56.png)

My configuration:

```emacs
(use-package doom-modeline
  :ensure
  :config
  (doom-modeline-init)
  (setq doom-modeline-python-executable nil))
```

**Comment by seagle0128** [comment]
Hi, which version are you using? Only first icon is displayed in my env.
Are you using other package, e.g. `major-mode-icons`?

**Comment by seagle0128** [comment]
I checked your config, and I found you are using `mode-icons`.

https://github.com/drrlvn/.emacs.d/blob/64ceb7a0453c284b6a30568af3cb0143816a63ab/lisp/config-looks.el#L36

I believe that package cause this issue. It's not useful (only show icons for a few major modes), and should be removed.

**Comment by drrlvn** [comment]
Whoops, you're right!

I'm terribly sorry for wasting your time, should have spent more time investigating.

Thanks!

**Comment by seagle0128** [comment]
Welcome! Glad to know your issue has been addressed.
