### ISSUE TITLE
[Bug] doom-modeline-modal-icon doesn't do anything

### ISSUE THREAD

**Issue by Sleepful** [seagle0128/doom-modeline#582]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

doesn't matter what I set `doom-modeline-modal-icon` to, it still displays, I checked the source and `doom-modeline-modal-icon` is only used once here: https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1747
so I guess it makes sense that it doesn't do anything, but now I have no way of disabling the display of my evil-mode current modality

### Steps to reproduce

a

### Expected behavior

a

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

doom

**Comment by seagle0128** [comment]
`doom-modeline-modal-icon` is called to control the modal icon. Why do you think it doesn't do anything? 

1. It only handles `all-the-icons`, wihle not unicode icon. 
2. Please use `emacs -Q` to reproduce, since doom-emacs does many tricks..

**Comment by BoltsJ** [comment]
I think the issue they are having is that `(setq doom-modeline-modal-icon nil)` doesn't hide the modal icon, which I'm also experiencing, but also based on your response, it sounds like hiding the modal icon isn't what that setting is used for?

**Comment by seagle0128** [comment]
It's as designed. `<I>` is not an icon while simple text, right?

**Comment by BoltsJ** [comment]
Oh, I see. Is there a way to hide the indicator altogether?

**Comment by seagle0128** [comment]
I add a new option: `doom-modeline-modal`.
