### ISSUE TITLE
[Bug] Modeline isn't setup correctly after helm candidates update

### ISSUE THREAD

**Issue by lerouxrgd** [seagle0128/doom-modeline#584]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using a helm command that has dynamic candidates (`helm-ag` or `helm-fd` for instance), the doom-modeline is displayed/setup correctly at start:

![image](https://user-images.githubusercontent.com/6103291/197391598-f39037b7-bca0-4757-b8f5-f251b6dcfbfe.png)

But when I type some input that yields candidates, then the modeline is displayed/setup without doom-modeline:

![image](https://user-images.githubusercontent.com/6103291/197391640-6440fbf1-75bf-4256-ab60-187ca1307bbd.png)

Note that if I move (line up/down) then the modeline is displayed correctly. If there are no candidates after my input, the modeline is also displayed correctly:

![image](https://user-images.githubusercontent.com/6103291/197392162-aebecc2a-d439-47d9-9478-334a9ed29b84.png)
![image](https://user-images.githubusercontent.com/6103291/197392182-c7643fc2-8e49-406c-8a3f-c1ccedab0080.png)

### Steps to reproduce

Type:
```elisp
;; M-x eval-expression
(helm-do-ag (cdr (project-current)))

;; M-x eval-expression
(helm-fd-1 (cdr (project-current)))
```
Then type some input

### Expected behavior

The modeline should be displayed with doom-modeline settings after candidates update.

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Vanilla

### Anything else

My config is as follows:

```elisp
(use-package doom-modeline
  :hook (window-setup . doom-modeline-mode)
  :config
  (setq doom-modeline-icon t
        doom-modeline-major-mode-icon nil
        doom-modeline-minor-modes t
        doom-modeline-buffer-file-name-style 'relative-from-project
        doom-modeline-buffer-encoding nil)
  (add-hook 'helm-minibuffer-set-up-hook
            (lambda () (advice-add #'doom-modeline--active :override (lambda () t))))
  (add-hook 'helm-cleanup-hook
            (lambda () (advice-remove #'doom-modeline--active (lambda () t))))
)
```

**Comment by seagle0128** [comment]
Why do you setup these?

```elisp
(add-hook 'helm-minibuffer-set-up-hook
            (lambda () (advice-add #'doom-modeline--active :override (lambda () t))))
  (add-hook 'helm-cleanup-hook
            (lambda () (advice-remove #'doom-modeline--active (lambda () t))))
```

**Comment by lerouxrgd** [comment]
This is as per [your advice](https://github.com/seagle0128/doom-modeline/issues/114#issuecomment-462402947), otherwise I have the same  graphic bug as #114

Note that I tried removing them, I still have the bug described in this issue

**Comment by seagle0128** [comment]
I tested with `helm-rg` since I am not using ag. The functionality is fine.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/140797/197397041-99cfb826-c864-4ab3-a834-3a8cafacecaa.png">

Please test with `emacs -Q` to make sure your private configurations won't impact..  I don't think `helm-do-ag` or `helm-fd-1` is a proper step to reproduce.

**Comment by lerouxrgd** [comment]
I used to use `helm-rg` too, sadly it is now unmaintained and therefore I stopped using it. I tried it quickly again and indeed the issue does not happen.

However `helm-ag` is maintained as part of [ Emacs Orphanage ](https://github.com/emacsorphanage) and `helm-fd` is part of `helm` itself. Therefore they are both more up to date regarding official `helm` and as such `helm-do-ag` and `helm-fd-1` are actually better steps to reproduce that `helm-rg` which is outdated (I suspect this is why the issue is not happening with it).

I will try to reproduce with a configuration from scratch, but honestly I don't think there is anything special in my config that interacts with doom-modeline.

**Comment by seagle0128** [comment]
Got you! I think there may be some special handles of mode-line in helm. Will check later.

**Comment by seagle0128** [comment]
After I research for a while, I realized the mode-line-format was set by helm after an async process finished. I am afraid it is not able to override the behaviors.

**Comment by lerouxrgd** [comment]
Thank you for narrowing it down.

Indeed it looks like there isn't much we can do for `helm-fd` therefore I opened a PR there.

As for `helm-ag` this can actually be fixed with:
```elisp
(setq helm-ag-show-status-function nil)
```
Maybe this can be set in `doom-modeline-segments.el` at the Helm section ?

**Comment by seagle0128** [comment]
Yes. I can handle helm-ag, but nothing to do for others, liks `helm-fd`, `helm-grep`, `helm-locate`, etc.

**Comment by lerouxrgd** [comment]
Actually since my PR has been merged in helm, for `helm-fd` you can now do:
```elisp
(setq helm-fd-mode-line-function nil)
```

**Comment by seagle0128** [comment]
My solution is `(advice-add #'helm-display-mode-line :after #'doom-modeline-set-helm-modeline)`.

It's better if you can submit some PRs for other helm functions, to add some hooks or something like that.
