### ISSUE TITLE
Option to make segments visible in inactive windows

### ISSUE THREAD

**Issue by FrostyX** [seagle0128/doom-modeline#587]
First of all, thank you all for your work on `doom-modeline`. 
Much appreciated, `doom-modeline` is great.

**Is your feature request related to a problem? Please describe.**

Some segments are displayed only in active windows. Personally, I tested and am interested in `mu4e` segment but looking at the code, this should be the case for `gnus`, `irc`, `battery`, etc as well. I believe this behavior applies to all segments that start with  `(when (and (doom-modeline--active)`.

I believe this works perfectly for many users, and I can imagine wanting the same behavior on a small laptop screen or when using Emacs inside of a small window. But it IMHO falls short when you have a larger screen estate. My standard situation is two fullscreen Emacs frames split into ~8 windows. I don't want to clutter my active window modeline with all the not-immediately-needed information such as the number of unread emails, the number of unread RSS articles, IRC buffers, etc when there is a lot of other windows visible.

**Describe the solution you'd like**

I would like to display my `mu4e` segment in my `mu4e-headers` window, `irc-buffers` segment in my `irc-channel-mode` windows, and so on. This can easily be done via `doom-modeline-mode-alist` but the segments are displayed only for active windows. I want to display them for inactive windows as well.

**Describe alternatives you've considered**

I considered overriding `(doom-modeline--active)` to always return `t` and go from there. But that's just too hacky and probably will break many things, and I would like to believe that I am not the only one wanting this feature.

**Additional context**

I am imagining the following implementation but feel free to completely ignore it if you prefer something different.

We could add `doom-modeline-always-visible` variable that would be user-defined. In my case I would do e.g. `(setq doom-modeline-always-visible '(mu4e irc-buffers))`. And we would change all the segments to check `(or (doom-modeline--active) (member 'mu4e doom-modeline-always-visible))` instead of current `(doom-modeline--active)`.

What do you think?

**Comment by seagle0128** [comment]
> We could add `doom-modeline-always-visible` variable that would be user-defined. In my case I would do e.g. `(setq doom-modeline-always-visible '(mu4e irc-buffers))`. And we would change all the segments to check `(or (doom-modeline--active) (member 'mu4e doom-modeline-always-visible))` instead of current `(doom-modeline--active)`.

I think it's a good idea. Can you please submit a PR to make it?

**Comment by FrostyX** [comment]
Hello @seagle0128,
thank you for the reply.

> Can you please submit a PR to make it?

I will be happy to. I just didn't want to submit a PR straight away without having a blessing :-)
