### ISSUE TITLE
doom-modeline 3.3.1 and eglot+gopls issue

### ISSUE THREAD

**Issue by Cerebus** [seagle0128/doom-modeline#590]
Not sure where the issue actually lies, so putting this here for discussion.

`doom-modeline@b66d5e5` in doom emacs works fine.  3.3.1 breaks (autocomplete doesn't work or returns incorrect returns; selection of completion inserts at the wrong point).  The root cause seems to be that golsp isn't getting buffer updates except when the buffer is saved or loaded--if I save with an partial expression and reload the buffer (and golsp), I can autocomplete that expression properly.  If I add anything else without saving, it breaks (wrong suggestions and inserts at wrong point).

This also shows up in crafted-emacs with 3.3.1 (harder to regress b/c crafted leverages melpa).  If I don't *load* doom-modeline, eglot+gopls works fine.  If doom-modeline is loaded but *disabled*, eglot+lsp still breaks.

However, a `-Q` startup with manual install of doom-modeline, eglot, and go-mode ... seems to work OK.  So I don't get it.

**Comment by seagle0128** [comment]
I guess it's related to aa0e2dd. `eglot` introduced some break changes recently and `doom-modeline` has to change to adapt, so 3.3.1 doesn't work with the latest eglot. Please upgrade to the latest of `doom-modeline`.

**Comment by Cerebus** [comment]
Confirmed, thanks.
