### ISSUE TITLE
[Bug] modeline not focused when switching back to a buffer from a buffer opened by emacsclient

### ISSUE THREAD

**Issue by vincentbernat** [seagle0128/doom-modeline#591]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When an unfocused frame gains focus through emacsclient opening a new buffer in it, the buffer which was originally here will have an unfocused modeline.

### Steps to reproduce

1. Start Emacs → the modeline is focused
2. Get to a nearby terminal → the modeline is unfocused
3. Open another file using emacsclient -n -q init.el → the modeline is focused (Emacs grabs the focus)
4. Kill the opened buffer with C-x k → the modeline is unfocused

### Expected behavior

The modeline should be focused because the frame is focused.

### OS

Linux

### Emacs Version

28 (gccemacs)

### Emacs Configurations

Doom Emacs

### Anything else

I assume the modeline is per-buffer and the sequence of actions is:
1. frame loses the focus while buffer A is displayed, modeline becomes unfocused
2. emacsclient opens buffer B in the frame while unfocused
3. emacs steal the focus back, modeline of buffer B becomes focused
4. when switching back to buffer A, there is no focus-in event, nor a frame-switch event, so the modeline stays unfocused

**Comment by vincentbernat** [comment]
As a workaround, I use:

```elisp
(after! doom-modeline
  (remove-function after-focus-change-function #'doom-modeline-focus-change))
```

**Comment by seagle0128** [comment]
> As a workaround, I use:
> 
> ```emacs-lisp
> (after! doom-modeline
>   (remove-function after-focus-change-function #'doom-modeline-focus-change))
> ```

This will disable the feature: gray out while unfocusing the frame.

**Comment by vincentbernat** [comment]
Yes, this is not a general workaround.

**Comment by seagle0128** [comment]
I recreated in my local env. It seems a bug of emacs self.

```elisp
(doom-modeline-unfocus)
(face-remap-remove-relative '(doom-modeline-project-dir . mode-line-inactive))
(face-remap-remove-relative '(doom-modeline-buffer-file . mode-line-inactive))
```

Run the snippet above, I got this:

![image](https://user-images.githubusercontent.com/140797/219326505-27af6a6d-eeef-4a80-8af0-cfd40dd26b00.png)

**Comment by seagle0128** [comment]
I recreated in my local env. It seems a bug of emacs self.

```elisp
(doom-modeline-unfocus)
(face-remap-remove-relative '(doom-modeline-project-dir . mode-line-inactive))
(face-remap-remove-relative '(doom-modeline-buffer-file . mode-line-inactive))
```

Run the snippet above, I got this:

![image](https://user-images.githubusercontent.com/140797/219326505-27af6a6d-eeef-4a80-8af0-cfd40dd26b00.png)

**Comment by seagle0128** [comment]
The solution is hacky, but works for me. Please test.

**Comment by seagle0128** [comment]
The solution is hacky, but works for me. Please test.

**Comment by dr-scsi** [comment]
@seagle0128 - Thanks.  IIUC the solution doesn't work for users who aren't running `pulse`, right?

**Comment by seagle0128** [comment]
@dr-scsi Yes or no. `pulse` is builtin since 25(?), and `pulse-momentary-highlight-region` is autoload.

**Comment by dr-scsi** [comment]
The problem I see is the guard:
https://github.com/seagle0128/doom-modeline/blob/60d54889854d52cedfbce11b9aba92542c96bf9c/doom-modeline-core.el#L1014

Eval'ing:
```
(featurep 'pulse)
```
returns for me `nil` since I don't require that package (or I don't use a package which requires it), so the solution doesn't work for me.  Maybe it is safer to replace that with:
```
(when (fboundp 'pulse-momentary-highlight-region)
  ...)
```
WDYT?

**Comment by seagle0128** [comment]
@dr-scsi I've made a patch and committed. Please check.

**Comment by dr-scsi** [comment]
@seagle0128 - Thanks, that seems to work 👍
