### ISSUE TITLE
[Bug] Eglot--spinner removed

### ISSUE THREAD

**Issue by koen-vg** [seagle0128/doom-modeline#594]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The function `eglot--spinner` has just been removed from the latest master branch of emacs (specifically, in commit 6b0179f790), see this thread for reference: https://lists.gnu.org/archive/html/emacs-devel/2022-11/msg01192.html

However, doom-modeline uses `eglot--spinner`, which now obviously leads to a `Symbol’s function definition is void: eglot--spinner` error. 

A new implementation of some kind of progress updating is being worked on at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=59149. I haven't had time to look into the details yet though.

Until the use of `eglot--spinner` is replaced by equivalent functionality, does anyone see any easy was of "disabling" this feature of doom-modeline for now in order to prevent the error from happening every time eglot is enabled?

### Steps to reproduce

1. Checkout and build latest master branch of emacs (or commit 6b0179f790).
2. Install and enable doom-modeline.
3. Run `eglot` (built into emacs).

### Expected behavior

Eglot status is shown in doom modeline.

### OS

Linux

### Emacs Version

29 (gccemacs-dev)

### Error callstack

```emacs-lisp
For example in a python buffer:

Debugger entered--Lisp error: (void-function eglot--spinner)
  eglot--spinner(#<eglot-lsp-server eglot-lsp-server-432ead6>)
  doom-modeline-update-eglot()
  run-hooks(eglot-managed-mode-hook)
  apply(run-hooks eglot-managed-mode-hook)
  eglot--managed-mode()
  eglot--maybe-activate-editing-mode()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(python-mode-hook)
  python-mode()
```

**Comment by zayfen** [comment]
eglot--spinner is not deleted, just renamed to eglot--progress-reporters
