### ISSUE TITLE
[Feature Request]  Add configuration variable for not changing file name's face when buffer is modified. Should be possible to make it buffer-local

### ISSUE THREAD

**Issue by hab25** [seagle0128/doom-modeline#596]
**Is your feature request related to a problem? Please describe.**
In my Doom Emacs config, I have
```emacs
(auto-save-visited-mode +1)
(customize-set-variable auto-save-visited-interval 0.1)
```
With the above configuration, the file name in doom-modeline is distracting; it keeps rapidly changing faces as the buffer rapidly switches back and forth from unmodified to modified (respectively green/blue/white to red)

**Describe the solution you'd like**
Implement a boolean variable named similar to `doom-modeline-change-file-face-when-modified` and supporting logic so that when the variable is `nil`, file names always show with the unmodified face(s).

**Additional context**
Right now I have this to get rid of that distraction. 
```emacs
(setq doom-modeline-buffer-state-icon nil)
(after! doom-modeline (custom-set-faces! '(doom-modeline-buffer-modified ( t . ( :inherit nil)))
                                         '(doom-modeline-project-dir  ( t . ( :inherit nil)))
                                         '(doom-modeline-project-root-dir  ( t . ( :inherit nil)))
                                         '(doom-modeline-project-parent-dir ( t . ( :inherit nil)))
                                         '(doom-modeline-buffer-file ( t . ( :inherit nil :bold nil)))
                                         '(doom-modeline-buffer-path  ( t . ( :inherit nil :bold nil)))))
```
I'm an emacs beginner, this is very bad code. Further, It is much worse than the proposed solution:
1) it affects all buffers, not just file-visiting ones.
2) if the `doom-modeline` project changes the names for these faces, this breaks.
3) it gets rid of `doom-modeline`'s bold green/blue/white face for the file project/path/name.

<details>
<summary>Details</summary>
The following is not directly relevant, but I am also using the below additional code, and am sharing it here just to show that there is a safe use-case for `auto-save-visited-mode`; the safety is provided by `magit-wip-mode` .

```emacs
(setq! magit-wip-mode +1)
(add-hook! 'find-file-hook (if (eq (vc-backend buffer-file-name) 'Git)
                               (progn (make-local-variable 'doom-modeline-buffer-state-icon)
                                      (setq doom-modeline-buffer-state-icon nil)
                                      (make-local-variable 'save-silently)
                                      (setq save-silently t))
                               (progn (make-local-variable 'auto-save-visited-mode)
                                      (setq auto-save-visited-mode nil))))
```
</details>

**Comment by seagle0128** [comment]
I couldn't reproduce this issue with my configuration. Please reproduce with `emacs -Q` and `(require 'doom-modeline)`.

**Comment by seagle0128** [comment]
> Implement a boolean variable named similar to doom-modeline-change-file-face-when-modified and supporting logic so that when the variable is nil, file names always show with the unmodified face(s).

This behavior is wired and will confuse the users. I don't think it's a good idea. 

My suggestion is:
1. Make`auto-save-visited-interval` bigger.
2. Disable `auto-save-visited-mode`.
3. Customize faces as you did.

**Comment by hab25** [comment]
@seagle0128 
> This behavior is wired 

What does "wired" mean here? Impossible to change?

> will confuse the users

I don't think it's confusing, the reason you *may* think so is because it is uncommon to use `auto-save-visited-mode` and that *may* be making you uncomfortable with that behaviour. 
In any case, you can address this by giving the variable a very descriptive name like `doom-modeline-modified-buffer-state-changes-file-name-faces` and indicating in the docstring that this pairs well with `auto-save-visited-mode`. Since the default should probably be `t` for consistency with default Emacs' modeline behaviour, any user that is not explicitly looking to configure this will won't be meaningfully affected.


> My suggestion is:
>1. Make`auto-save-visited-interval` bigger.
>2. Disable `auto-save-visited-mode`.
>3. Customize faces as you did.

All of these have downsides:
1. By doing that one loses a big advantage of having a small `auto-save-interval`: to quickly be able to run commands that operate on files, e.g. `make`, on the latest version of the file.
2. `auto-save-visited-mode`  is very useful for not having to run manual save commands. It also allows one, together with `magit-wip-mode`, to have a persistent, comprehensive and `git {diff,grep,log}`able history of their changes.
3.  As I wrote in the issue description,
> 1. it affects all buffers, not just file-visiting ones.
> 2. if the doom-modeline project changes the names for these faces, this breaks. 
> 3. it gets rid of doom-modeline's bold green/blue/white face for the file project/path/name.

**Comment by seagle0128** [comment]
The design is using RED names to indicate the buffer is modified. Not other unchanged/modified indicators in `doom-modeline`. That's why I said it might be confusing to users.

Indeed `auto-save-visited-mode` is not common, andit's not enabled by default. If adding `doom-modeline-modified-buffer-state-changes-file-name-faces`, the logic will getting complicated. But maybe `doom-modeline-unchange-buffer-name-when-modified` is a good idea. WDYT?
