### ISSUE TITLE
[Bug] Doom-modeline is too far to the right (so time gets cut off) in certain files.

### ISSUE THREAD

**Issue by JxJxxJxJ** [seagle0128/doom-modeline#597]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Doom-modeline gets cut off 'randomly', for example here in a `config.org` file
![image](https://user-images.githubusercontent.com/103049321/204735973-a873556b-b539-4ca6-9a2a-978492e3baa3.png)

But in a different .org file it can be different, like this 

![image](https://user-images.githubusercontent.com/103049321/204736016-6d4fbc17-9410-455e-98e5-804384bdb144.png)

It does not happen with other kind of files, here is an example with a `.txt` file

![image](https://user-images.githubusercontent.com/103049321/204736652-ff6b5164-3187-4d51-96bf-74f053bc0e4e.png)

### Steps to reproduce

Use Tecosaur's config. 

Open any org-mode file and it will be messed up a little. (I'm not certain of what makes it differ from `.org` file to `.org` file)

### Expected behavior

The time should not get cut

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs + Tecosaur's config (https://github.com/tecosaur/emacs-config)

### Anything else

I tried fix number 6 and 7 from [here](https://github.com/seagle0128/doom-modeline#faq): Both unfortunetely don't seem to work. 

I'll be glad to provide any other information needed.

**Comment by JxJxxJxJ** [comment]
Ended up tweaking more and setting a different font with `(setq all-the-icons-scale-factor 1.0)`. Ended up like this 
![image](https://user-images.githubusercontent.com/103049321/204926675-100895a1-214a-40ee-9fb6-7a160e7f4080.png)
I wonder why though it this `.org` file it looks like that, but in my config.org instead it looks good 
![image](https://user-images.githubusercontent.com/103049321/204926748-435b65b0-c812-4160-a4cc-0c4432567c0f.png)

**Comment by seagle0128** [comment]
The root cause is the icons have different size.

1. Upgrade to 29.
2. Redefine your own segments and modeline.

**Comment by JxJxxJxJ** [comment]
Thanks, I'll upgrade now. What do you mean by redefining though? I'll do it

**Comment by seagle0128** [comment]
You just need to choose one of the solutions.

>What do you mean by redefining though? 

Refer to FAQ 5.
