### ISSUE TITLE
[Feature Request] Show information of character under point

### ISSUE THREAD

**Issue by suliveevil** [seagle0128/doom-modeline#599]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Show character information like what describe-char does.

Take `a` as example, I want to show `#x61` or/and `#o141` in modeline.

```text
 character: a (displayed as a) (codepoint 97, #o141, #x61)
```

**Comment by seagle0128** [comment]
Thanks for reporting! PR is welcome.

**Comment by suliveevil** [comment]
🤣 I will figure it out.

**Comment by suliveevil** [comment]
For someone who have the same need

https://github.com/emacsmirror/modeline-char
