### ISSUE TITLE
[Feature Request] tree-sitter node querying

### ISSUE THREAD

**Issue by bagnaram** [seagle0128/doom-modeline#602]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Tree-sitter is about to be integrated into emacs 29 and offers a syntax tree that can be queried to get the file structure. For certain major modes like ini-mode, yaml-mode, json-mode etc this could be used to obtain the current node the cursor is highlighting. It would be a great addition to display this in the modeline.

https://emacsconf.org/2022/talks/treesitter/

https://blog.meain.io/2022/navigating-config-files-using-tree-sitter/

**Comment by seagle0128** [comment]
Sorry! I don't understand what should be implemented in `doom-modeline`. Do you want to display the `*-ts-mode`? Only the name of major-mode is displayed.

**Comment by seagle0128** [comment]
Sorry! I don't understand what should be implemented in `doom-modeline`. Do you want to display the `*-ts-mode`? Only the name of major-mode is displayed.

**Comment by bagnaram** [comment]
I was thinking about displaying the node after the filename but before the line number. Think of it as a specifier dilpsaying the current node in the tree of the file that the cursor is currently at.

Here is an example of what I mean.
![grim-2023-01-07_10-01-1673109281](https://user-images.githubusercontent.com/11695670/211161089-0d08306b-66c1-4293-90e3-1210f475776e.png)

**Comment by seagle0128** [comment]
> https://blog.meain.io/2022/navigating-config-files-using-tree-sitter/

In this blog, the function is just for yaml, json, nix files. The solution is not common. I don't think it's right time to add it to `doom-modeline`. If you need it you can add it to `global-mode-string`.

Of course, the PR is welcome.
