### ISSUE TITLE
[Bug] doom-modeline freezes Emacs when initialized in MacOS M1

### ISSUE THREAD

**Issue by david-alvarez-rosa** [seagle0128/doom-modeline#603]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

After update I'm not longer able to use `doom-modeline` in a MacOS M1 Monterey 12.6.1 in GNU Emacs 28.2.  Launching it with `doom-modeline-mode` completely freezes the program and a "Force Quit" is needed.

### Steps to reproduce

Start with a clean Emacs, install `doom-modeline` and run `doom-modeline-mode`. Emacs freezes completely. 

Watch video https://share.alvarezrosa.com/public/emacs.mov

### Expected behavior

Expected is that Emacs does not freeze.

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

Starting with clean Emacs.

### Error callstack

Not able to do this, because Emacs is completely frozen and I need to "Force Quit" from Mac.

### Anything else

Not really. Thank you!

**Comment by muihlinn** [comment]
emacs 28.2 + ubuntu 20.4  also freezes.

**Comment by Tdback** [comment]
I also was experiencing this issue, which was mentioned here in #601. Try updating your doom-modeline package to the most recent version (20230106.1427 -> 20230107.1433).

**Comment by seagle0128** [comment]
Duplicated with #601. Please update to the latest version.

**Comment by david-alvarez-rosa** [comment]
Much appreciated! Updating fixed the issue. This is the community we want :)
