### ISSUE TITLE
doom-modeline vterm error

### ISSUE THREAD

**Issue by getong** [seagle0128/doom-modeline#605]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Debugger entered--entering a function:
* eval((doom-modeline-segment--word-count))
  posn-at-point()
  mouse-avoidance-point-position()
  mouse-avoidance-too-close-p((#<frame *vterm* 0x7fd3a3184430> 151 . 18))
  mouse-avoidance-fancy()
  apply(mouse-avoidance-fancy nil)
  timer-event-handler([t 0 0 100000 t mouse-avoidance-fancy nil idle 0 nil])

### Steps to reproduce

I run vterm in emacs, then change to other software, like google chrome, and change back to emacs, emacs hangs, no response.

### Expected behavior

emacs continues to work.

### OS

MacOS

### Emacs Version

28

**Comment by getong** [comment]
another bug
```
Debugger entered--entering a function:
* eval((doom-modeline-segment--time))
  format-mode-line(("" (:eval (doom-modeline-segment--compilation)) (:eval (doom-modeline-segment--objed-state)) (:eval (doom-modeline-segment--misc-info)) (:eval (doom-modeline-segment--persp-name)) (:eval (doom-modeline-segment--battery)) (:eval (doom-modeline-segment--grip)) (:eval (doom-modeline-segment--irc)) (:eval (doom-modeline-segment--mu4e)) (:eval (doom-modeline-segment--gnus)) (:eval (doom-modeline-segment--github)) (:eval (doom-modeline-segment--debug)) (:eval (doom-modeline-segment--repl)) (:eval (doom-modeline-segment--lsp)) (:eval (doom-modeline-segment--minor-modes)) (:eval (doom-modeline-segment--input-method)) (:eval (doom-modeline-segment--indent-info)) (:eval (doom-modeline-segment--buffer-encoding)) (:eval (doom-modeline-segment--major-mode)) (:eval (doom-modeline-segment--process)) (:eval (doom-modeline-segment--vcs)) (:eval (doom-modeline-segment--checker)) (:eval (doom-modeline-segment--time))))
  doom-modeline-format--main()
  eval((doom-modeline-format--main))
  redisplay_internal\ \(C\ function\)()
```

**Comment by seagle0128** [comment]
What's your emacs config? Can you please reproduce with `emacs -Q`?

**Comment by getong** [comment]
```
(use-package doom-modeline
  :ensure t
  :demand
  :init
  (doom-modeline-mode 1)
  (setq doom-modeline-buffer-encoding nil)
  (setq doom-modeline-env-enable-python nil)
  (setq doom-modeline-height 15)
  (setq doom-modeline-project-detection 'projectile)
  :config
  (setq doom-modeline-battery nil)
  ;; (doom-modeline-mode 1)
  (set-face-attribute 'doom-modeline-evil-insert-state nil :foreground "orange")
  )

(setq display-time-format "%Y-%m-%d %H:%M:%S")
(setq display-time-interval 1)
(display-time-mode 1) 
(setq display-time-24hr-format t) 
(setq display-time-day-and-date t) 
(setq display-time-default-load-average nil)
```
I install the latest version, it often hangs.
My total emacs config is github.com/getong/.emacs.d

**Comment by seagle0128** [comment]
I cannot reproduce the issue with the snippet you provided above.

1. Did you try with `emacs -Q`?
2. Suggest not using `(setq display-time-interval 1)`. It will reduce the performance significantly. Or `(setq doom-moeline-time nil)`.

**Comment by getong** [comment]
Thanks
