### ISSUE TITLE
[Bug] Some parts of doom modeline in inactive windows are displayed using active fonts when Helm is enabled

### ISSUE THREAD

**Issue by taquangtrung** [seagle0128/doom-modeline#609]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When I run a Helm session, some parts of the modelines of other inactive windows (not Helm window) are displayed using the active modeline faces.

Below is an example, where the parts highlighted by the red rectangles are not correctly displayed. They should be displayed using the inactive modeline faces.

<img width="1147" alt="Screenshot 2023-02-10 at 10 38 12 PM" src="https://user-images.githubusercontent.com/193967/218119494-1203b46b-1cc3-49e0-beb5-de5f1c466892.png">

### Steps to reproduce

- Open Emacs and open some windows.
- Run a Helm session, which will open a new window at the bottom of the Emacs frame
- Then, the modeline of other inactive windows are displayed as the above screenshot.

### Expected behavior

- The modeline of all inactive windows should be displayed using the inactive modeline faces

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs

**Comment by taquangtrung** [comment]
I just installed the new newest commit but there is this error happens when Emacs is first opened: 

```
Warning (initialization): An error occurred while loading ‘/home/trungtq/.emacs.d/.local/etc/@/init.28.elc’:

Error caused by user's config or system: /home/trungtq/.doom.d/config.el, (error nil (void-variable doom-modeline-ellipsis))

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
Error (doom-after-init-hook): Error running hook "doom-modeline-mode" because: (void-variable doom-modeline-ellipsis) Disable showing Disable logging
```

**Comment by taquangtrung** [comment]
@seagle0128: it was fixed nicely! Thanks a lot for your efforts and this amazing doom-modeline package!

**Comment by seagle0128** [comment]
Cheers!
