### ISSUE TITLE
[Bug] error in doom-modeline-update-vcs-text on remote bzr repo

### ISSUE THREAD

**Issue by ahihi** [seagle0128/doom-modeline#613]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

when opening files in a remote bzr repository via tramp, i get the error `Wrong type argument: stringp, nil`

### Steps to reproduce

on remote machine:

```shell
mkdir ~/test
cd ~/test
bzr init
touch foo.txt
bzr add foo.txt
```

in emacs, locally:

```
M-x find-file RET /ssh:user@remote-machine:~/test/foo.txt
```

### Expected behavior

the file opens without an error

### OS

MacOS

### Emacs Version

28

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  regexp-quote(nil)
  vc-bzr-status("/home/foo/file")
  vc-bzr-state("/home/foo/file")
  apply(vc-bzr-state "/home/foo/file")
  vc-call-backend(Bzr state "/home/foo/file")
  vc-state-refresh("/home/foo/file" Bzr)
  vc-state("/home/foo/file" Bzr)
  doom-modeline-update-vcs-text()
  run-hooks(find-file-hook)
  after-find-file(nil nil t nil nil)
  revert-buffer--default(t nil)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  call-interactively(revert-buffer nil nil)
  command-execute(revert-buffer)
```

### Anything else

i noticed that the paths in the call stack are missing the tramp `/ssh:...` prefix, so is it trying to look for the file locally?

in `doom-modeline-update-vcs-text` i see [this line](https://github.com/seagle0128/doom-modeline/blob/5a927b8c2b0c1976f097edeb7d037888f1f874cc/doom-modeline-segments.el#L707) is calling `file-local-name` to strip the tramp prefix, so i tried removing it, and the code seems to work that way. however i dont know the reason the call is there in the first place, so not sure if this is a real fix. both versions of the code seem to work fine with remote git repos.

**Comment by seagle0128** [comment]
>i noticed that the paths in the call stack are missing the tramp /ssh:... prefix, so is it trying to look for the file locally?

See #463. Could you please test git via tramp as well?

**Comment by ahihi** [comment]
i just installed the latest version and can confirm that both git and bzr repos are working fine via tramp, including the state icon :) thanks!
