### ISSUE TITLE
[Bug] `success`, `warning` and `error` faces get remapped everywhere in the current window on focus loss

### ISSUE THREAD

**Issue by marienz** [seagle0128/doom-modeline#614]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The faces in `doom-modeline--remap-faces` are getting remapped everywhere in the current window if my Emacs frame loses focus, not just in the modeline. If I switch windows only the modeline changes, not the rest of the window (and if the Emacs frame loses focus, inactive windows do not get their faces remapped).

This behavior is probably not new: I started noticing it after commit a3f65d25b5a9002d455ab3577451eca798f167e5, which adds `success`, `warning` and `error` to `doom-modeline--remap-faces`. It's somewhat common for me to have these somewhere in my current window other than the modeline, because I have `hl-todo` enabled with "TODO" mapped to the `warning` face (the default from Doom Emacs). And it's annoying if all my TODOs get remapped because my `doom-modeline-inactive` face has `:box` set, so every time my Emacs frame loses focus all TODOs in the current window get a box added to them (which shifts the text below them down slightly).

### Steps to reproduce

- Use `hl-todo` with `hl-todo-keyword-faces` set to something like `(("TODO" warning bold))`
- Have a comment with the word "TODO" in it in the current window
- Make the Emacs frame lose focus

### Expected behavior

The modeline changes, but the rest of the buffer does not.

### OS

Linux

### Emacs Version

29 (dev)

### Emacs Configurations

Doom Emacs

### Anything else

I'm not sure how to fix this... would it be possible to replace the `success`, `warning` and `error` face with some more specific face like `doom-modeline-success` if they're used in the modeline, and then remap those more specific faces?

**Comment by seagle0128** [comment]
It's as designed. See `doom-modeline--remap-faces`.
