### ISSUE TITLE
[Bug]  Battery showing double percetage (10%%)

### ISSUE THREAD

**Issue by Nanank-kho** [seagle0128/doom-modeline#615]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Battery showing double percentage (10%%)
![Screenshot 2023-03-04 at 03 21 03](https://user-images.githubusercontent.com/12078569/222822691-99d09589-8c4e-44b5-b16d-e9d1ae91764a.png)

### Steps to reproduce

Load doom-modeline and evaluate (display-battery-mode).

### Expected behavior

the battery percentage shown 10%

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

Doom Emacs

**Comment by seagle0128** [comment]
Duplicated with #606. The latest version has already fixed it.
