### ISSUE TITLE
[Bug] height of modeline in a scheme-mode buffer gets increased

### ISSUE THREAD

**Issue by dadinn** [seagle0128/doom-modeline#619]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

This makes buffer mode-lines uneven, as it can be seen in this picture:

![image](https://user-images.githubusercontent.com/521910/234574606-17ea2c83-900b-466a-a77d-2ee13b3c526e.png)

I've raised [this issue](https://github.com/domtronn/all-the-icons.el/issues/357) with all-the-icons too, but I am not sure which package is responsible for it.

### Steps to reproduce

Install and load all-the-icons package.
Switch to `*scratch*` buffer.
Split window right.
Open any `.scm` file, while the other window still shows the `*scratch*` buffer.

### Expected behavior

Height of the mode-line shouldn't be increased in scheme-mode buffers.

### OS

Linux

### Emacs Version

27

### Emacs Configurations

my [init.el](https://github.com/dadinn/.emacs.d/blob/master/init.el#L398)

**Comment by seagle0128** [comment]
Increase the `doom-modeline-height` to address this issue.

**Comment by dadinn** [comment]
I've tried commit `9ce19994654b427679aad4bceb546afe64decb06`, and the mode-line doesn't look OK:

![image](https://github.com/seagle0128/doom-modeline/assets/521910/ef907380-ad6e-4f9a-b9f4-09c21eadf149)

**Comment by seagle0128** [comment]
@dadinn Did you install nerd fonts via `nerd-icons-install-fonts`?
