### ISSUE TITLE
doom-modeline disregards value of column-number-indicator-zero-based 

### ISSUE THREAD

**Issue by nsemrau** [seagle0128/doom-modeline#62]
First of all: Thank you for this package. I basically tried all of the new "modern" mode-lines for Emacs over the recent years and usually went back to the classic mode-line quickly. Not so with doom-modeline; I like everything about it and I will stay with it as the true successor to the classic mode-line. :)

Emacs 26.1 introduced the variable `column-number-indicator-zero-based`. When set to `nil`, `column-number-mode` shows `1` instead of `0` when point is on the leftmost column in a line.

This works as expected with the classic mode-line. Starting Emacs with doom-modeline enabled, however, `column-number-mode`s value of the leftmost column is `0`, regardless of `column-number-indicator-zero-based`s value.

I'm using Emacs 26.1 stable with the GTK3 toolkit, doom-modeline `20181206.1735` from MELPA with this setup:

```
(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-init)
  :init (setq doom-modeline-icon nil))
```

**Comment by seagle0128** [comment]
Hmm, I didn't realize this feature in 26.1. I tried some modelines but no lucky, except the vanilla mode-line. I am trying to implement that.

**Comment by seagle0128** [comment]
I realized it's from a PR and as designed. But I addressed it anyway. Please try.

**Comment by nsemrau** [comment]
doom-modeline now honors the value of `column-number-indicator-zero-based` and switches back and forth when I change the variable's value. Thank you for the instant fix. :+1:

**Comment by seagle0128** [comment]
Welcome and enjoy!
