### ISSUE TITLE
Emacs 27.1 crashing after installing doom modeline on Windows 11

### ISSUE THREAD

**Issue by mishrasubhajit** [seagle0128/doom-modeline#620]
Hi, I have been trying to configure GNU Emacs on Windows. However, Emacs crashes while installing the doom-modeline. I have already installed all-icon-fonts and Symbola manually. 

Here is the section of code in my config.el. 
```
(use-package all-the-icons
 	:ensure t)
(use-package doom-modeline
	:ensure t
	:hook (after-init . doom-modeline-mode))

```

With the config above, I get the following crash message. I have also attached the
[emacs_backtrace.txt](https://github.com/seagle0128/doom-modeline/files/11364674/emacs_backtrace.txt) file, generated after the crash.
![image](https://user-images.githubusercontent.com/13003528/235434134-d06354b6-431c-490f-8f7c-ff5eeb739ac6.png)

I am not an expert in debugging but by using the process id as suggested in the crash message, I have found the following. I am not sure what to make out of it.
![image](https://user-images.githubusercontent.com/13003528/235439730-627a4a13-2114-4df5-926a-260ba2128134.png)

It would be nice to get a solution to this. I believe due to this particular reason my doom-emacs was also crashing, Please let me know if any more info is needed. Thank you very much.

**Comment by seagle0128** [comment]
Sorry, I can do nothing for the crash issues without any further information. It may be an issue of Emacs itself. I suggest to try Emacs 28 or 29.

**Comment by mishrasubhajit** [comment]
Hi Vincent, it seems to work with Emacs 28.2 at the moment. Maybe it was a problem with 27.1 or my system. In any case, thanks a lot for your suggestion. Wish you all the best.
