### ISSUE TITLE
[Bug] flycheck display error

### ISSUE THREAD

**Issue by getong** [seagle0128/doom-modeline#623]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

![flycheck-error](https://user-images.githubusercontent.com/3949379/236118004-aa487ccf-d5cb-4496-9fe2-8dcf42abb44b.jpg)

### Steps to reproduce

```
(use-package doom-modeline
  :straight (doom-modeline :type git :host github :repo "seagle0128/doom-modeline")
  :demand
  :hook (after-init . doom-modeline-mode)

  :custom
  (doom-modeline-buffer-file-name-style 'relative-from-project)
  (doom-modeline-time-icon nil)
  (doom-modeline-unicode-fallback t)
  (doom-modeline-buffer-encoding nil)
  (doom-modeline-height 15)
  (doom-modeline-battery nil)
  (doom-modeline-icon t)
  (doom-modeline-buffer-file-name-style 'file-name)
  :init
  (doom-modeline-mode 1)
  (setq doom-moeline-time nil)
  (setq doom-modeline-env-enable-python nil)
  :config
  (setq flycheck-color-mode-line-face-to-color 'doom-modeline)
  (set-face-attribute 'doom-modeline-evil-insert-state nil :foreground "orange")
  (doom-modeline-def-modeline 'main
    '(modals matches buffer-info remote-host buffer-position)
    '(checker misc-info lsp time))
  )
```

### Expected behavior

display a normal icon

### OS

MacOS

### Emacs Version

29 (dev)

**Comment by seagle0128** [comment]
Install nerd fonts following the README.

**Comment by getong** [comment]
Thanks, I changed my font name.
