### ISSUE TITLE
all-the-icons 'broken' in doom-modeline [Bug] 

### ISSUE THREAD

**Issue by maxecharel** [seagle0128/doom-modeline#624]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Hi,
Just updated doom-modeline, and all-the-icons seems broken:
![Screenshot_20230505_012643](https://user-images.githubusercontent.com/61969138/236351511-2a1227f9-98a6-44aa-9aca-96fc46252dae.png)
(minions on the right)

No problem with dired or ibuffer.

Emacs: 28.1
Doom-modeline: 20230504.1755

### Steps to reproduce

1) Update doom-modeline
2) That's it!

### Expected behavior

I expected icons in doom-modeline to be perfectly displayed, as usual

### OS

Linux

### Emacs Version

28

### Emacs Configurations

GNU

**Comment by maxecharel** [comment]
Oh, I should have be more cautious before posting, I see that @seagle0128 made the choice of switching to nerd-icons

**Comment by maxecharel** [comment]
Ok, so with nerd-icons it works like a charm! sorry for not having read before going for an issue

**Comment by scmanjarrez** [comment]
I'm missing some icons as well, I'm using latest version of nerd-icons ([39df68f66f204b1a0680203a2b1483ed4a746987](https://github.com/rainstormstudio/nerd-icons.el/commit/39df68f66f204b1a0680203a2b1483ed4a746987))
![image](https://github.com/seagle0128/doom-modeline/assets/9284124/63201215-7315-4ec9-bea3-ff05e93cefbd)
