### ISSUE TITLE
[Feature Request] With the shift to nerd-fonts the LISP icon seems to be gone

### ISSUE THREAD

**Issue by emacsomancer** [seagle0128/doom-modeline#625]
I like having a LISP icon for .lisp files/LISP-mode files. Seems to be gone with the shift to nerd-fonts.

**Comment by seagle0128** [comment]
nerd-fonts doesn't support lisp files so far. See https://github.com/ryanoasis/nerd-fonts/issues/351.

**Comment by Finii** [comment]
Do you have any preferred existing icon for lisp? As far as I know there is no 'official' one.

**Comment by seagle0128** [comment]
AFAIK, no.

**Comment by seagle0128** [comment]
Maybe `nf-md-lambda`? You can create a MR in [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el).

**Comment by Finii** [comment]
Ah, I thought about adding "a Lisp icon" to Nerd Fonts (i.e. https://github.com/ryanoasis/nerd-fonts/issues/351), but then we already have it there via Material Design.

Anyhow, if you need any (new/different) icon, please let me know. The next days Nerd Fonts 3.1.0 will be released and I can certainly squeeze in one new glyph if need be.

**Comment by Finii** [comment]
clisp and scheme (just a lambda glyph) released in Nerd Fonts 3.1.0

**Comment by seagle0128** [comment]
> clisp and scheme (just a lambda glyph) released in Nerd Fonts 3.1.0

@rainstormstudio It seems `NFM.ttf` should be updated now. Please take a look. Thanks!
