### ISSUE TITLE
[Bug] Clock icon is cropped with nerd-icons

### ISSUE THREAD

**Issue by dr-scsi** [seagle0128/doom-modeline#626]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

With the latest version using `nerd-icons`, the clock in mode-line is cropped a little.

![display-time-icon](https://user-images.githubusercontent.com/59777257/236394112-6035f6a2-49c6-4c4b-ba66-8a96bd2c18d8.png)

This is with the latest [SymbolsNerdFontMono-Regular.ttf](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf)

### Steps to reproduce

Start Emacs with `-Q` and then:
```
M-x package-initialize RET
M-x doom-modeline-mode RET
M-x display-time-mode RET
```

### Expected behavior

The icon shouldn't be cropped.

### OS

Windows

### Emacs Version

29 (gccemacs-dev)

### Anything else

This is with Emacs from Git, master branch commit `605414d018`.

**Comment by seagle0128** [comment]
Can you please try other fonts and size?

**Comment by dr-scsi** [comment]
@seagle0128 - Thanks, the issue is fixed now 👍
