### ISSUE TITLE
[Bug] Visual glitches with nerd-icons

### ISSUE THREAD

**Issue by jimeh** [seagle0128/doom-modeline#627]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Nerd icons leads to various visual glitches and inconsistencies. I've tried this with various Nerd fonts, both Mono and non-Mono (double-width) fonts, and icons always look the same.

Mode icon for dired renders as a double-width icon, with the right side corrupted:

![Screen-Shot-2023-05-08-21-53-27 87](https://user-images.githubusercontent.com/39563/236934819-f4443515-7e61-4079-aaf2-7f07e6d3fda9.png)

Far right icon is corrupted, all three visible icons have different sizes, and adjusting the `nerd-icons-scale-factor` variable only affects the side of the far-right corrupted icon:

![Screen-Shot-2023-05-08-21-54-04 72](https://user-images.githubusercontent.com/39563/236934971-dc6b2902-1894-4359-b214-ad9e0a3729b3.png)

I initially suspected it could be due to the new Nerd Fonts v3.0.0 dropping a bunch of legacy icon code points, but switching back to v2.3.3 fonts did not help.

### Steps to reproduce

First of all, I'm running a nightly build of Emacs 30 from `master` ([this build](https://github.com/jimeh/emacs-builds/releases/tag/Emacs.2023-05-06.d5ab8b6.master)).

And I can re-produce it with a minimal configuration:

<details>
  <summary><code>init.el</code></summary>

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'doom-modeline)
(setq nerd-nerd-icons-font-family "FireCode Nerd Font") ;; or "FiraCode Nerd Font Mono"
(doom-modeline-mode 1)
```

</details>

This yields similar distortion, regardless of which nerd font I use:

![Screen-Shot-2023-05-08-22-21-42 41](https://user-images.githubusercontent.com/39563/236938108-1b05fb8a-f275-4709-a984-0a6fff364e05.png)

### Expected behavior

- Icons to render correctly without missing glyth symbols.
- All icon sizes in GUI to adhere `nerd-icons-scale-factor`.
- Single-width icons with Mono variants, double-width icons with non-Mono variants (assuming I've understood correctly how that works).

### OS

MacOS

### Emacs Version

29 (gccemacs-dev)

### Emacs Configurations

https://github.com/jimeh/.emacs.d

**Comment by Panadestein** [comment]
I experience the same behavior on Emacs 30.0.50, NixOS unstable, doom-modeline with straight:

![image](https://user-images.githubusercontent.com/15854703/236949764-85db5bb4-677d-48bc-a3a5-ba8683dc1cad.png)

**Comment by seagle0128** [comment]
Can you try the latest font via `nerd-icons-install-fonts` and `(setq nerd-icons-font-family "Symbols Nerd Font Mono"`?

**Comment by seagle0128** [comment]
Can you try the latest font via `nerd-icons-install-fonts` and `(setq nerd-icons-font-family "Symbols Nerd Font Mono"`?

**Comment by Panadestein** [comment]
In my case, I am using `all-the-icons`. After pulling all packages with `streight`, and `aal-the-icons-install-fonts` the glitches persists.

**Comment by bilboed** [comment]
Installing the fonts (via `nerd-icons-install-fonts`) did the trick for me. The `nerd-icons-font-family` already had the value of `Symbols Nerd Font Mono`

**Comment by tjgatward** [comment]
> 

This also resolved the issue for me, without having to set `nerd--icons-font-family`

**Comment by seagle0128** [comment]
@rainstormstudio Could you please take a look at this issue?

**Comment by seagle0128** [comment]
So I am closing it.

**Comment by jimeh** [comment]
@seagle0128 The `Symbols Nerd Font Mono` does indeed make it work correctly. Apologies for not testing that earlier 🤦‍♂️

I will need to to dig into why that font works fine and all other nerd fonts—including those I patch myself—do not work correctly.

**Comment by seagle0128** [comment]
@jimeh `doom-modeline` leverages [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el), which is compatible nerd fonts 3.x. Hope this thread is helpful.

**Comment by rainstormstudio** [comment]
@jimeh `Symbols Nerd Font Mono` uses `--variable-width-glyphs` when patching the font, which helps with the variable width of icons. reference [here](https://github.com/ryanoasis/nerd-fonts/issues/442#issuecomment-1263358904)
