### ISSUE TITLE
[Bug] Modal icons no longer shown (probably after nerd-icons switch)

### ISSUE THREAD

**Issue by Havner** [seagle0128/doom-modeline#628]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

doom-modeline no longer shows icons for modals. I'm personally using god-mode and overwrite-mode. None of these show.

`doom-modeline-modal` set
`doom-modeline-modal-icon` set

The indicator itself is working cause when I unset doom-modeline-modal-icon I can see the \<G\> and \<O\> properly. It's just the icons that are broken.

I installed nerd-icons and all other doom-modeline icons work fine for me.

### Steps to reproduce

1. Run emacs in graphical mode
2. Make sure `doom-modeline-modal` and `doom-modeline-modal-icon` are set
3. Enable god-mode or overwrite-mode
4. No icon shown

### Expected behavior

Modal icon shown

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

My own: https://github.com/Havner/emacs-config

**Comment by theophilusx** [comment]
Noticing the same behaviour with evil-mode on Linux. Was working previously.

**Comment by seagle0128** [comment]
Please try the latest version.

**Comment by genmeblog** [comment]
I think it might be related. `flycheck` icon is not visible with the latest version

**Comment by luisvgs** [comment]
Hi, I also have the same issue. Any chance you were able to solve it?

**Comment by diaevd** [comment]
Confirm, flycheck icons is broken

**Comment by seagle0128** [comment]
I can confirm the flycheck icons work well. Can you provide more details for troubleshooting?
