### ISSUE TITLE
Face of git info is not good with doom-one theme in term

### ISSUE THREAD

**Issue by TxGVNN** [seagle0128/doom-modeline#63]
Hi, Thanks for your nice package.
Recently, I saw you introduce doom-mode-line is faster. I tried and it's very good. But I see an issue that inconveniencing to me.
I'm using doom-one for my emacs theme. 
```
;; themes
(use-package doom-themes
  :ensure t
  :init (load-theme 'doom-one t))
;; modeline
(use-package doom-modeline
  :ensure t
  :init
  (setq doom-modeline-buffer-file-name-style 'relative-from-project)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-major-mode-icon nil)
  (setq doom-modeline-minor-modes t)
  :hook (after-init . doom-modeline-init))
```
I prefer emacs on terminal than GUI, as you see a screenshot, the git info has a color same as the background.
![1](https://user-images.githubusercontent.com/9713793/49681505-8ae45d00-fad5-11e8-9274-6ae9b7e3c437.png)
And I marked by mouse on the terminal
![doom](https://user-images.githubusercontent.com/9713793/49681488-36d97880-fad5-11e8-89f9-2d4987debcfa.png)

**Comment by seagle0128** [comment]
Hi, 

I checked this issue in my env today, and found it should be related to the color theme of the terminal.

Below are my test results in iTerm2 on macOS Mojave. You can see the same issue as yours in `One Dark` theme, but no issue with other themes. My suggestion is to try other color themes.

`One Dark`
![image](https://user-images.githubusercontent.com/140797/49688454-53b19280-fb4d-11e8-89c6-97cacbfb43f5.png)

`Molokai`
![image](https://user-images.githubusercontent.com/140797/49688464-85c2f480-fb4d-11e8-90d5-e4bb35d91772.png)

`Atom`
![image](https://user-images.githubusercontent.com/140797/49688462-7ba0f600-fb4d-11e8-910f-84349fdecea6.png)

**Comment by TxGVNN** [comment]
Thanks for your suggestion.
But perhaps the doom-one theme is better for me, I don't want to change. After checking the source, I customized this font face by
```
(custom-set-faces
'(font-lock-doc-face ((t (:foreground "cyan")))))  
```
So good
![doom-modeline](https://user-images.githubusercontent.com/9713793/49689179-14d10c00-fb50-11e8-8b98-4cfdb178a1fa.png)

**Comment by seagle0128** [comment]
I am suggesting changing the terminal colors, not emacs theme.

**Comment by TxGVNN** [comment]
Cool, thank you. This is the best solution, the right side is a new configuration
![nice](https://user-images.githubusercontent.com/9713793/49693330-1b886f00-fba2-11e8-9e74-178cbb058eb6.png)


Thanks again for your support

**Comment by seagle0128** [comment]
Welcome and enjoy 😄
