### ISSUE TITLE
[Bug] nf-oct-settings missing

### ISSUE THREAD

**Issue by mattiasdrp** [seagle0128/doom-modeline#630]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I'm using elpaca so I guess I'm pulling the latest updates. I installed all the fonts with `nerd-icons-install-fonts` but when hitting `M-x customize` it says that 

```
(eval (doom-modeline-segment--buffer-info)) signaled (error "Unable to find icon with name 'nf-oct-settings' in icon set 'octicon'")
```

### Steps to reproduce

`M-x customize` with the latest version of doom-modeline installed

### Expected behavior

The icon should exist

### OS

Linux

### Emacs Version

29 (dev)

**Comment by seagle0128** [comment]
It's an issue of [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el). It has been fixed and please update to the latest version.
