### ISSUE TITLE
[Bug] Icons for Evil states and flymake status are cropped

### ISSUE THREAD

**Issue by Dickby** [seagle0128/doom-modeline#632]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

As the title states, the icons are cropped similar to the clock face that was fixed.
The Evil state icon is not always cropped, often after changing the evil state it is displayed correctly, after redisplaying it cropped again most of the time.

### Steps to reproduce

Use doom-modeline and evil/flymake.

### Expected behavior

Icons should not be cropped.

### OS

Linux

### Emacs Version

29 (dev)

### Anything else

Under Emacs Versions i chose 29(dev), the version i use is really `GNU Emacs 30.0.50  of 2023-05-13`, but there is not an option for that.

**Comment by Dickby** [comment]
I fixed the displaying of the evil-state icons by setting the faces `:weight` to `'thin` after looking inside the fix for https://github.com/seagle0128/doom-modeline/issues/626

**Comment by seagle0128** [comment]
Can you please provide screenshots?

**Comment by Dickby** [comment]
Shure!
1. As stated the evil-state-icon is fine if i use 'thin for the :weight attribute. Without that:
![evil-state-icon](https://github.com/seagle0128/doom-modeline/assets/10100765/748acacb-d7d4-4351-99f1-94dd21888d47)
2. The flymake-icon:
![flymake-icon](https://github.com/seagle0128/doom-modeline/assets/10100765/d6127a6c-1aa4-45e4-8ffa-6c2d6ed73ca4)

**Comment by seagle0128** [comment]
@rainstormstudio Could you please take a look at this issue? I didn't observe this issue on my env. I guess it's related to the font or platform.

**Comment by whame** [comment]
Check that you are not overriding any faces in your config (e.g. custom themes). I believe this is occurring when you have `:weight bold` on faces for the modeline. Setting `:weight normal` should fix this.

**Comment by sewe2000** [comment]
I have the same issue. Besides, doom-modeline-mode slows my emacs configuration terribly.

**Comment by sewe2000** [comment]
Changing font weight didn't help.

**Comment by seagle0128** [comment]
> I have the same issue. Besides, doom-modeline-mode slows my emacs configuration terribly.

Please use `emacs -Q` to reproduce.

**Comment by sewe2000** [comment]
Here's my doom-modeline configuration in init.el:
``` elisp         
(use-package nerd-icons)
;; Setting up doom-modeline
(use-package doom-modeline
 :ensure t
 :config
 (if (facep 'mode-line-active)
 (set-face-attribute 'mode-line-active nil :family "Symbols Nerd Fonts Mono"
 :height 120 :weight 'normal) ; For 29+
(set-face-attribute 'mode-line nil :family "Symbols Nerd Fonts Mono"
                                 :height 120 :weight 'normal))
(set-face-attribute 'mode-line-inactive nil :family "Symbols Nerd Fonts Mono"
                               :height 120 :weight 'normal)
(doom-modeline-mode 1))

;; doom themes
 (use-package doom-themes
 :init
(load-theme 'doom-city-lights t)) ;; loading the theme
```

**Comment by sewe2000** [comment]
I'm using Arch Linux. After starting via `emacs -Q` and evaluating the snippet the problem has gone, so I assume the fault is on the side of my config.

**Comment by seagle0128** [comment]
So I am closing this issue. If you still encounter the issue , please feel free to reopen it.

**Comment by LukeDRussell** [comment]
Thanks for answering this @seagle0128 . I had the same issue in a different context. Fix was the same.

I had installed [Solarized Emacs](https://github.com/bbatsov/solarized-emacs). I couldn't figure out how to stop it from apply bold in the modeline, so I just disabled the theme.
