### ISSUE TITLE
New mu4e mode `mu4e-modeline-mode`

### ISSUE THREAD

**Issue by Dickby** [seagle0128/doom-modeline#633]
I'm not totally shure, but it seems like the introduction of `mu4e-modeline-mode` in mu4e 1.10 makes it possible to get rid of the mu4e-alert dependency for `doom-modeline-mu4e`

**Comment by seagle0128** [comment]
It's possible. I can make a patch, but I am not using mu4e so cannot test it. Do you have a favor to test it?

**Comment by Dickby** [comment]
Of course!
after the last commit i get this error at emacs startup:
`Error (use-package): doom-modeline/:init: Symbol’s value as variable is void: mu4e-modeline-mode-hook`

**Comment by Dickby** [comment]
In my config file doom-modeline is loaded before mu4e, if i change that order the errors become:
```
Error (use-package): doom-modeline/:init: Attempt to set a constant symbol: nil 
Error (use-package): doom-modeline/:catch: Attempt to set a constant symbol: nil
```

**Comment by Dickby** [comment]
There is an `'` missing in line 2480 in doom-modeline-segments.el:
```
(add-hook mu4e-modeline-mode-hook #'doom-modeline-override-mu4e-modeline)
```

**Comment by Dickby** [comment]
After adding that, it seems to work.
![20230515_20h48m24s_grim](https://github.com/seagle0128/doom-modeline/assets/10100765/0c00c97f-c1f4-4fbc-befe-c24f70246d55)

**Comment by Dickby** [comment]
There is this `C:0/0` which gives information about unread emails, the `C` can change depending on the mu4e state.
mu4e has a custom variable `mu4e-use-fancy-chars` that replace these letters (like `C` in this case) with icons, i think it would make sense to change those to nerd-icons.
Also other than with mu4e-alert , now the mu4e section is visible if there are no unread emails (like it's the case in the screenshot). 
Let me know if i can help with testing somehow.

**Comment by seagle0128** [comment]
> There is this `C:0/0` which gives information about unread emails, the `C` can change depending on the mu4e state. mu4e has a custom variable `mu4e-use-fancy-chars` that replace these letters (like `C` in this case) with icons, i think it would make sense to change those to nerd-icons. Also other than with mu4e-alert , now the mu4e section is visible if there are no unread emails (like it's the case in the screenshot). Let me know if i can help with testing somehow.

I've committed a patch to address the issue.

Regarding the fancy chars, I would like accept PRs since I am not using mu4e.

**Comment by Dickby** [comment]
> I've committed a patch to address the issue.

But where is it?

**Comment by seagle0128** [comment]
See 9d6a39f97055b6b92ea2c51decb9547bad5106dc.

**Comment by seagle0128** [comment]
> But there is still the problem that the Mail icon is showing all the time, not only if new/unread mail is present.

Oh, I didn't test it. Your PR should be perfect :-)
