### ISSUE TITLE
[Bug] "require: Symbol’s value as variable is void: mu4e-modeline-mode-hook"

### ISSUE THREAD

**Issue by yiyunliu** [seagle0128/doom-modeline#634]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I suspect it has to do with the latest mu4e feature: https://github.com/seagle0128/doom-modeline/commit/d3c2cba462398e594a04e5e3a16c171497836666#diff-0505629a410f96e739a924cc71c2ef537a25d27a64d97615e8e7ae3d06906130R2480

The variable `mu4e-modeline-mode-hook` is not defined in my emacs. I assume it would only work if you already have mu4e related packages installed.

### Steps to reproduce

Use the following init.el file:
```elisp
;; My .emacs.d


(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))


(straight-use-package 'use-package)

(use-package doom-modeline
  :straight t
  :custom
  (doom-modeline-icon t)
  (doom-modeline-major-mode-icon t)
  (doom-modeline-buffer-state-icon t)
  :hook (after-init . doom-modeline-mode))
```
Starting `emacs` and you can see the the error message about the mu4e modeline hook.

### Expected behavior

Emacs should start properly without giving that error.

### OS

Linux

### Emacs Version

28 (gccemacs)

### Emacs Configurations

Vanilla emacs + the config file from above

**Comment by ashlineldridge** [comment]
Also seeing this bug since upgrading to latest.

**Comment by Dickby** [comment]
It's a missing single quote of changes related to: https://github.com/seagle0128/doom-modeline/issues/633

**Comment by yiyunliu** [comment]
> It's a missing single quote of changes related to: #633

Can confirm that adding back the single quote fixed the problem.

**Comment by seagle0128** [comment]
It was a typo and I forgot to push. Sorry!
The fix has been committed.
