### ISSUE TITLE
[Bug] Flycheck icon is not visible

### ISSUE THREAD

**Issue by genmeblog** [seagle0128/doom-modeline#637]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Flycheck icon (and the other one, for window management) is displayed as a rectangle now.

![image](https://github.com/seagle0128/doom-modeline/assets/38646601/3511b55a-5813-4a69-bc0f-17a41d69481d)

### Steps to reproduce

Enable flycheck

### Expected behavior

There should be some icons displayed.

### OS

Linux

### Emacs Version

28

### Emacs Configurations

custom

### Anything else

init.el file: https://gist.github.com/genmeblog/fbec9d790ffd46aafdbf0cef7c69471d

**Comment by seagle0128** [comment]
`M-x nerd-icons-install-fonts` and restart.
