### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sethen** [seagle0128/doom-modeline#638]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Seeing garbage unicode on the modeline even when setting the icons to off.  Here is my code:

```elisp
(require 'use-package)

(use-package doom-modeline
  :commands (doom-modeline-mode)
  :init
  (setq doom-modeline-icon t)
  (doom-modeline-mode 1))

(provide 'sethen-doom-modeline)
```
Here is what I am seeing
![Screenshot from 2023-05-19 12-13-54](https://github.com/seagle0128/doom-modeline/assets/1493530/65746942-3e9c-4ad5-97c3-2c8cbe14bd07)

### Steps to reproduce

Updated to the latest version of doom-modeline and got this error.  Tried turning off the icons but it's not working for me for whatever reason.

### Expected behavior

No icons should show in the modeline according to the documentation.

### OS

Linux

### Emacs Version

26

**Comment by sethen** [comment]
Nevermind, ignore this -- changed `t` to `nil` and everything works as expected.  My bad.

**Comment by seagle0128** [comment]
Also see `doom-modeline-unicode-fallback`, please.
