### ISSUE TITLE
Feature Request - Improve visuals of  doom-modeline-checker when not in simple mode

### ISSUE THREAD

**Issue by ebiscaia** [seagle0128/doom-modeline#639]
Hi,

I am new to emacs and I am trying to set it to my tastes and then I am having problems to set the checker (the one that displays the flycheck info). So far, the best I could is turn off the simple mode and replace the "/" by spaces. However, what I want is to display the icon next to the error type. I know the icon carriers another function (it shows menu), but I think that can be solved by using another mouse button or C-click.

This is what I have so far, but I need a way to set that in the config.el and not in the package files (this is a VM for testing)
![22-35-23](https://github.com/seagle0128/doom-modeline/assets/74695273/77f7f2d5-af30-4989-8322-cbb2a0b868e0)

This is what I want (from Neovim)
![22-36-23](https://github.com/seagle0128/doom-modeline/assets/74695273/7f2a546b-df83-4352-bc21-9f1c7d67cf9b)

Thanks

**Comment by seagle0128** [comment]
If you want to customize your mode-line, you may need to define your own segments and modeline. See FAQ 5.

**Comment by ebiscaia** [comment]
Hi,

Thanks for your answer. Unfortunately it is a bit out of my knowledge right now as I just started my transition to Emacs. As soon as I learn a bit more of Elisp I will give that a shot.

**Comment by seagle0128** [comment]
Clear up issues.
