### ISSUE TITLE
[Bug] How do I enable symbol-overlay counts?

### ISSUE THREAD

**Issue by grolongo** [seagle0128/doom-modeline#642]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Can't see any symbol-overlay count in the doom mode line.  
I looked at the FAQ and customize group to find an option to set it on, but I can't find anything.  
Therefore, I thought that it might just activate by default if it detects `symbol-overlay` is installed/enabled, but nothing appears in the mode line.

### Steps to reproduce

This is the basic configuration I have for `doom-modeline` and `symbol-overlay`:

```elisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :custom (doom-modeline-icon nil))

(use-package symbol-overlay
  :ensure t
  :delight
  :hook (text-mode prog-mode fundamental-mode)
  :bind (("M-n" . symbol-overlay-jump-next)
         ("M-p" . symbol-overlay-jump-prev))
  :custom (symbol-overlay-idle-time 0.2))
```

### Expected behavior

The number count should be displayed automatically in the mode line.

### OS

Windows

### Emacs Version

29

### Emacs Configurations

vanilla Emacs with my own config

**Comment by seagle0128** [comment]
`M-x symbol-overlay-put`, and while the cursor is on the highlights, the counts will be displayed in mode-line.
