### ISSUE TITLE
[Bug] After #617 6ea0051, the first loading speed becomes very slow, and some icons cannot be right-aligned

### ISSUE THREAD

**Issue by BlindingDark** [seagle0128/doom-modeline#644]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

After #617 https://github.com/seagle0128/doom-modeline/commit/6ea0051a3b25b0fb9fc67d826f37d82884e5ffb9, I found that the right side of the modeline sometimes doesn't align. And there will be more than 1 second of freeze when starting for the first time.

### Steps to reproduce

I found that after specifying the face to `format-mode-line`, the original face will be overwritten. This may be causing alignment issues. 

You can test it with the following snippet in a buffer with lsp enabled, and then compare the difference between the two faces.

```emacs-lisp
(format-mode-line (cons "" '((:eval (doom-modeline-segment--lsp)))) 'mode-line)
#("  "
  0 1 (face (mode-line-active mode-line))
  1 2 (rear-nonsticky t display (raise 0.0)
       font-lock-face
       (:family "Symbols Nerd Font Mono" :height 1.0 :inherit doom-modeline-lsp-success)
       face
       (mode-line-active mode-line) ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; <-- this is the problem
       local-map (keymap (mode-line keymap ... ... ...

(format-mode-line (cons "" '((:eval (doom-modeline-segment--lsp)))))
#("  "
  0 1 (face mode-line-active)
  1 2 (rear-nonsticky t display (raise 0.0)
       font-lock-face
       (:family "Symbols Nerd Font Mono" :height 1.0 :inherit doom-modeline-lsp-success)
       face ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 👇🏻 normal one
       (:inherit (doom-modeline (:inherit (doom-modeline doom-modeline-lsp-success))) :family "Symbols Nerd Font Mono" :height 1.0)
       local-map (keymap (mode-line keymap ... ... ...
```

### Expected behavior

Can handle face correctly.

### OS

MacOS

### Emacs Version

30 (gccemacs)

**Comment by seagle0128** [comment]
https://github.com/seagle0128/doom-modeline/commit/6ea0051a3b25b0fb9fc67d826f37d82884e5ffb9 was reverted.
