### ISSUE TITLE
[Feature Request] Show treemacs workspace name in modeline for treemacs

### ISSUE THREAD

**Issue by sebastiaanspeck** [seagle0128/doom-modeline#649]
Right now the modeline for treemacs looks like this:

<img width="280" alt="image" src="https://github.com/seagle0128/doom-modeline/assets/12570668/89c122df-0912-48f9-9b6c-be1355334eb3">

In the source code for treemacs, I found:
`(doom-modeline-def-modeline 'treemacs '(bar " " major-mode))`

But I would like to append `(treemacs-workspace->name (treemacs-current-workspace))`. How can I make this? Do I need a doom-modeline-def-segment?

**Comment by sebastiaanspeck** [comment]
One possible workaround is this:
```
(use-package treemacs
  :hook
   (treemacs-mode . (lambda () (setq-local mode-line-format (format " Treemacs: %s" (treemacs-workspace->name (treemacs-current-workspace))))))
```

This results in:
<img width="239" alt="image" src="https://github.com/seagle0128/doom-modeline/assets/12570668/f139f657-3c26-4dea-93c5-ca869807117a">

This workaround overrules the doom-modeline and gets rid of the bar for instant.

Hopefully somebody has something like this but then integrated in the doom-modeline itself.

**Comment by seagle0128** [comment]
You can define a new segment and mode-line. Please see FAQ.

**Comment by sebastiaanspeck** [comment]
I was hoping to not have to re-invent the wheel again and maybe somebody could share their treemacs-modeline-segment.On 3 Aug 2023, at 17:15, Vincent Zhang ***@***.***> wrote:﻿
You can define a new segment and mode-line. Please see FAQ.

**Comment by sebastiaanspeck** [comment]
Why not add support for treemacs in the existing `doom-modeline-def-segment workspace-name`?

**Comment by seagle0128** [comment]
BTW, treemacs has implemented a doom-modeline segment.

**Comment by sebastiaanspeck** [comment]
Can we maybe make it compatible?

**Comment by seagle0128** [comment]
Please report to treemacs or hack yourself.

Please see https://github.com/Alexander-Miller/treemacs/blob/aa0944a29eee48302fd76b6c3a59c5aece114fa6/src/elisp/treemacs-mode.el#L229-L232.

My suggestion is :

```elisp
(doom-modeline-def-segment treemacs
  "Display treemacs."
  (treemacs-workspace->name (treemacs-current-workspace)))
(doom-modeline-def-modeline 'treemacs '(bar " " major-mode) '(treemacs))
(doom-modeline 'treemacs)
```

**Comment by sebastiaanspeck** [comment]
I have opened a PR at Treemacs:
https://github.com/Alexander-Miller/treemacs/pull/1043
