### ISSUE TITLE
[Bug] doom-modeline-def-segment results in void variable 

### ISSUE THREAD

**Issue by sebastiaanspeck** [seagle0128/doom-modeline#653]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using `(doom-modeline-def-segment)` outside of doom-modeline, it triggers the warning void variable. A good example is https://github.com/Alexander-Miller/treemacs/pull/1049. Maybe we need some help for this issue?

### Steps to reproduce

Define a new segment outside of doom-modeline.
The name for the segment creates the warning `void variable`

### Expected behavior

Defining a new segment outside of doom-modeline shouldn’t trigger the warning

### OS

Windows

### Emacs Version

29

**Comment by sebastiaanspeck** [comment]
When using `(doom-modeline-def-segment ‘name …)`, the segment can’t be used/found when creating the modeline:

`
Debugger entered--Lisp error: (error "'name is not a valid segment")
  error("%s is not a valid segment" 'name)
  doom-modeline--prepare-segments(('name))
  doom-modeline-def-modeline(custom (bar " " major-mode) ('name))
`

When looking at the `doom-modeline-var-alist`, the segment is in the alist:
`(('name. doom-modeline-segment--\'name)`

When using `(doom-modeline-def-segment “name” …)`, you can’t find/reference the segment anymore. 
`doom-modeline-def-modeline(custom (bar " " major-mode) `(“name”)` results in a segment with the string “name” instead of the segment.

Looking at the `doom-modeline-var-alist`, the segment with “name” looks okay, apart of the name:
`((”name”. doom-modeline-segment--name)`

**Comment by seagle0128** [comment]
Have you byte-compiled `doom-modeline`?

**Comment by sebastiaanspeck** [comment]
Yes, I did

**Comment by seagle0128** [comment]
I believe `doom-modeline-def-segment` does work. I tried on Windows, Linux and macOS, with Emacs 28 and 29. I also tested with `emacs -Q`, and it works well. Please provide all details to reproduce the issue. I didn't catch the points according to the descriptions above.  `void variable` or `name is not a valid segment`? What's the exact problem and backtrace?

**Comment by seagle0128** [comment]
See https://github.com/Alexander-Miller/treemacs/pull/1049#issuecomment-1678475664. Closing it.
