### ISSUE TITLE
Direnv integration

### ISSUE THREAD

**Issue by gekoke** [seagle0128/doom-modeline#654]
It would be nice if there was an integration with [emacs-direnv](https://github.com/wbolster/emacs-direnv) to show whether a direnv environment is currently loaded, and perhaps display some information about the loaded environment.

This is what the "modeline" looks like in VSCode
![image](https://github.com/seagle0128/doom-modeline/assets/63151928/c96ecd08-54b0-4d78-9c07-ae5cdeca3d35)
(added, changed, removed envvars)

**Comment by seagle0128** [comment]
Sorry, I am not using `direnv`.  PRs are welcome.

**Comment by mattiasb** [comment]
I put a PR [here](https://github.com/seagle0128/doom-modeline/pull/666) that should help.
