### ISSUE TITLE
[Bug] Null vertical padding after update

### ISSUE THREAD

**Issue by david-alvarez-rosa** [seagle0128/doom-modeline#656]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

After update to Emacs 29, and update of `doom-modeline` package, I see a null vertical padding in the mode line.

See the screenshot for reference.

![Null vertical padding mode line screenshot](https://share.alvarezrosa.com/public/Null_Vertical_Padding_Mode_Line.png)

### Steps to reproduce

Just open Emacs.

### Expected behavior

Expected behavior is to have some kind of vertical padding, so the mode line looks nice.

### Emacs Configurations

Vanilla.

**Comment by georgek** [comment]
Did you set `doom-modeline-height`?

**Comment by david-alvarez-rosa** [comment]
Nope, @georgek, I did not set the variable.  I'm not using it as I want the height of `doom-modeline` to adapt dynamically whenever I'm changing the font-size (using https://github.com/purcell/default-text-scale package).

**Comment by seagle0128** [comment]
@david-alvarez-rosa Try `(setq doom-modeline-height 21)`.

**Comment by david-alvarez-rosa** [comment]
Thank you @seagle0128 that works when I start my Emacs:

![Doom modeline large](https://share.alvarezrosa.com/public/DoomModelineLarge.png)

However, when I enlarge the text (using https://github.com/purcell/default-text-scale package), it still doesn't look:

![Doom modeline normal](https://share.alvarezrosa.com/public/DoomModelineNormal.png)

Perfect state for me would be to define the vertical padding / margin instead of the height, so it adapts dynamically.  But it's a problem actually, so what you mentioned helps. Thanks!

**Comment by seagle0128** [comment]
The padding is implemented with bar image actually. The height was changed to `(+ (frame-char-height) 4)` recently. You can increase the height if you like paddings.
