### ISSUE TITLE
[Bug] How to get rid of the <N>, <I>, <V> in the centre of the icons?

### ISSUE THREAD

**Issue by leafpool243** [seagle0128/doom-modeline#660]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

![圖片](https://github.com/rainstormstudio/nerd-icons.el/assets/63614345/cefa0178-d137-4017-9943-dc752d63e4da)

I dislike that there is a distracting letter in the middle of the evil mode status icon. Is it possible to change this? (I notice that none of the screenshots in the readme have that.)

(I hadn’t updated doom-modeline in awhile so I never noticed.)

### Steps to reproduce

1. Use evil mode
2. Use doom-modeline
```lisp
  (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                           ("melpa" . "https://melpa.org/packages/")))
  (require 'package)
  (package-initialize)
  (setq use-package-always-ensure t)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

(use-package evil
  :init (evil-mode 1))
(use-package doom-modeline
	:init (doom-modeline-mode t))
```
![圖片](https://github.com/seagle0128/doom-modeline/assets/63614345/79a42e00-6d85-44d5-a878-22c424bedd34)

### Expected behavior

There should not be an ugly letter in the middle

### OS

Linux

### Emacs Version

28

**Comment by seagle0128** [comment]
`(setq doom-modeline-modal-icon nil)`

or

```elisp
(defun doom-modeline--modal-icon (text face help-echo &optional icon unicode)
  (propertize (doom-modeline-icon
               'mdicon
               (and doom-modeline-modal-icon  "nf-md-record")
               (or unicode "●")
               text
               :face (doom-modeline-face face))
              'help-echo help-echo))
```

**Comment by seagle0128** [comment]
A new option `doom-modeline-modal-modern-icon`  is added.
