### ISSUE TITLE
[Bug] Resizing window with doom-dashboard increasingly cuts off right side of modeline

### ISSUE THREAD

**Issue by Jdogzz** [seagle0128/doom-modeline#668]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Right side of modeline on doom-dashboard screen becomes increasingly cut off when window is resized larger than default (so I'm not sure if this falls under FAQ #7). Other screens don't seem to cause problems with the modeline when the window is being resized.

### Steps to reproduce

1. Open emacs
2. Resize window larger and larger

### Expected behavior

Right side of modeline will adjust to stay visible.

### OS

Linux

### Emacs Version

28 (gccemacs)

### Emacs Configurations

Doom Emacs

### Error callstack

```emacs-lisp
N/A
```

### Anything else

Screencast:
[Screencast from 2023-09-25 05-40-05.webm](https://github.com/seagle0128/doom-modeline/assets/2792697/190b84aa-8afe-49a5-a583-b92d41f28c72)

doom info output of my minimal test system (I'm experiencing the same problem on my primary system with nixos):
https://pastebin.com/3NpYrRfA

(I unchecked the last checkbox after the fact since it's technically minimal in terms of doom emacs config, just unpinning the modeline to make sure the latest commit is used, but I didn't try emacs -Q minimal)

**Comment by seagle0128** [comment]
Can you reproduce this issue with `emacs -Q`? 
BTW: I strongly to recommend emacs 29.

**Comment by Jdogzz** [comment]
I have upgraded to emacs 29 on my primary and test systems but do still see the problem on my primary and test systems. The test system experiences the problem with out-of-the-box doom emacs installed on emacs 29.

I have investigated using emacs -Q but it doesn't seem like that will be practical to do as doom-dashboard appears to be intimately linked with doom emacs (i.e. there's not a package for the dashboard like there is for doom-modeline). I am happy to follow pointers to making the dashboard work starting from emacs -Q if anyone has them.

**Comment by seagle0128** [comment]
In any buffer, eval `(doom-modeline-set-modeline 'dashboard)` to set dashboard mode-line.

**Comment by Jdogzz** [comment]
Got it, thank you. I used that with the test system with emacs -Q and could not reproduce the issue I showed in the original video.

[Screencast from 2023-09-27 05-52-37.webm](https://github.com/seagle0128/doom-modeline/assets/2792697/59db3750-def1-4564-a348-ba65acd9f69f)

**Comment by seagle0128** [comment]
So you may need help from doom-emacs community?

**Comment by Jdogzz** [comment]
Sure thing, I can file a bug report there.

**Comment by keevee09** [comment]
I am having this issue with doom-emacs on both Windows 11 WSL2 Ubuntu 22.04 and Fedora 39.
What I found is that it happens with the primary modeline, but, if I create a new window (split horizontally with <SPC>-w-n), then the secondary modeline adjusts correctly as I change the size of the window frame, for both the cli and the gui versions of doom-emacs. The original doom-modeline still refuses to adjust, whether that frame is active or inactive.

**Comment by seagle0128** [comment]
@keevee09 Are you able to reproduce the issue with `emacs -Q` and the latest `doom-modeline`? If NOT, please file an issue for `doom-emacs`.

**Comment by keevee09** [comment]
@seagle0128 I will attempt to reproduce the issue with `emacs -Q` and the latest `doom-modeline`. So far, what I have seen, I suspect it is a `doom-emacs` issue but I am not certain.
The text: "DOOM v3.0.0-pre" is created in `$HOME/.config/emacs/modules/ui/doom-dashboard/config.el:176`:
175 `(define-derived-mode +doom-dashboard-mode special-mode`
176 `  (format "DOOM v%s" doom-version)`
177 `...`
The constant `doom-version` is created in:
`$HOME/.config/emacs/lisp/doom.el:167`:
167 `(defconst doom-version "3.0.0-pre"`
168 `...`
"DOOM v3.0.0-pre" is the text that anchors itself to the right, before any other entries and seems to cause the problem.
Please give me a day or two to follow up.

**Comment by seagle0128** [comment]
@keevee09 Which version of `doom-modeline` are you using?

**Comment by keevee09** [comment]
I am using version 20231222.636 of `doom-modeline`.
`git log` shows commit: `93f240f7a0bf35511cfc0a8dd75786744b4bcf77` from `Mon Sep 18 19:44:25 2023 +0800`, with comment `Improve macro segment.`

As you suggested, it appears to be a `doom-emacs` issue, not a `doom-modeline` one.

I noticed just now that when opening the readme files from within `$HOME/.config/emacs` in doom-emacs, that the text `DOOM 3.0.0-pre` is not displayed, and that the issue disappears. With `Doom Docs` or `GFM` displayed, rather than `DOOM 3.0.0-pre`, I can adjust the size of the doom-emacs window and the right side of the modeline adjusts to display as expected.

![Screenshot from 2023-12-27 07-11-22](https://github.com/seagle0128/doom-modeline/assets/2707371/3258e53c-b259-4921-b5ba-d92fb40cb2a4)


![Screenshot from 2023-12-27 07-37-56](https://github.com/seagle0128/doom-modeline/assets/2707371/77463e4c-6c43-4be6-959f-fb8abf297926)

**Comment by seagle0128** [comment]
It looks good! So can I close this issue now?

**Comment by keevee09** [comment]
Yes, thank you! It can be closed.
