### ISSUE TITLE
[Bug] Custom segment makes emacs lag

### ISSUE THREAD

**Issue by 0x4d6165** [seagle0128/doom-modeline#670]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Defining a custom segment results in emacs slowing to a crawl. I don't think my custom segment is overly complex but maybe it's being polled too much?

### Steps to reproduce

``` emacs lisp
(use-package doom-modeline
  :straight t
  :after nerd-icons
  :config
  (setq doom-modeline-battery t)
  (setq doom-modeline-time t)
  (add-hook 'doom-modeline-mode-hook
            (lambda ()
                (doom-modeline-set-modeline 'my-custom-modeline 'default)))
  (doom-modeline-def-segment todo-count
  "Display the remaining number of todo items."
  (let ((todo-count (count-todos-in-org-files)))
        (propertize (format " %s" todo-count)
                    'face '(:foreground "yellow")))) 
  (doom-modeline-def-modeline 'my-custom-modeline
  '(bar workspace-name window-number modals matches buffer-info remote-host buffer-position word-count parrot selection-info)
  '(objed-state misc-info persp-name grip todo-count irc mu4e gnus github debug input-method indent-info buffer-encoding lsp major-mode process vcs checker battery time))
  
  (setq doom-modeline-modeline 'my-custom-modeline)
  (add-hook 'doom-modeline-mode-hook
            (lambda ()
                (doom-modeline-set-modeline 'my-custom-modeline 'default)))
  :hook (after-init . doom-modeline-mode))
```

Define a custom segment and add it to the modeline.

### Expected behavior

I expected the current number of org todos to be output to the modeline without introducing noticeable latency

### OS

Linux

### Emacs Version

29

### Emacs Configurations

https://git.sr.ht/~x4d6165/.emacs.d

**Comment by seagle0128** [comment]
Do [profiling](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html#:~:text=Emacs%20has%20built-in%20support%20for%20this.%20To%20begin,%28cpu%20and%20memory%29%20that%20you%20chose%20to%20profile.), then you will find out the root cause. Is `count-todos-in-org-files` the bottle-neck?
