### ISSUE TITLE
[Bug] Missing icon for a common major mode (emacs-jupyter)

### ISSUE THREAD

**Issue by egr95** [seagle0128/doom-modeline#671]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using [emacs-jupyter](https://github.com/emacs-jupyter/jupyter), the `jupyter-repl` buffer shows a blank page. It would be nice to add an appropriate icon there. Alternatively, it could be allowed for the user to customize the icon displayed for a given major mode (apologies if this is already possible, but I wasn't able to find any pointers on this).

### Steps to reproduce

With `doom-modeline` and `emacs-jupyter` installed, open a `.py` file and run `jupyter-run-repl`. Then the modeline of the `.py` file will show the Python icon, but the jupyter REPL defaults to a blank page icon.

### Expected behavior

An appropriate icon should be displayed, e.g., a planet.

### OS

Linux

### Emacs Version

29

**Comment by seagle0128** [comment]
Please file the issue in [nerd-icons](https://github.com/rainstormstudio/nerd-icons.el/issues).

**Comment by egr95** [comment]
It seems to me from this [line](https://github.com/rainstormstudio/nerd-icons.el/blob/0262a8c4fa41541438e489572bba8f0b4b689ae7/nerd-icons.el#L172) that there is not yet a nerd-icon for Jupyter. However, I do see there is a different planet icon. Is it possible to manually specify that the jupyter-repl major mode should load this icon in my emacs config?

**Comment by seagle0128** [comment]
Yes. Just adding the icon into `nerd-icons-extension-icon-alist`.

For example,
```elisp
(add-to-list 'all-the-icons-mode-icon-alist  '("ipynb"  nerd-icons-faicon "nf-fae-planet" :face nerd-icons-orange))
```

**Comment by egr95** [comment]
Awesome, thank you!
