### ISSUE TITLE
[Bug] Modeline aligns with fill column in visual-fill-column-mode

### ISSUE THREAD

**Issue by deadcombo** [seagle0128/doom-modeline#672]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

![image](https://github.com/seagle0128/doom-modeline/assets/37187650/fe8c74bb-2cec-4cda-94dd-39388fcafb8c)
![image](https://github.com/seagle0128/doom-modeline/assets/37187650/1400d652-a96f-4cb3-8aac-0d64a0fa3593)

These are screenshots of Emacs with only `visual-fill-column` and `doom-modeline` installed, using `with-emacs.sh`.
When visual-fill-column is enabled, the modeline right align breaks and the modeline becomes aligned with the fill column.

### Steps to reproduce

1. Enable` doom-modeline-mode`
2. Enable `visual-fill-column-mode`

### Expected behavior

The modeline stays aligned to the right.

### OS

Linux

### Emacs Version

30 (gccemacs)

### Emacs Configurations

None.

### Anything else

I'm not sure whether this is an issue with visual-fill-column instead.

**Comment by Padraic-O-Mhuiris** [comment]
Am also replicating this

**Comment by seagle0128** [comment]
It's not a bug, while the feature of `visual-fill-column-mode`. Try `(setq mode-line-right-align-edge 'right-fringe)`.

**Comment by deadcombo** [comment]
> It's not a bug, while the feature of `visual-fill-column-mode`. Try `(setq mode-line-right-align-edge 'right-fringe)`.
> 
> Maybe I should introduce a new option `doom-modeline-right-align-edge`?

`mode-line-right-align-edge` does solve it. I don't think you should create a new option, rather the `visual-fill-column` author should document his changes affect the mode-line.
