### ISSUE TITLE
[Bug]  Emacs 29.1 - Warning (comp): doom-modeline-core.el:1098:37: Warning: reference to free variable ‘mode-line-right-align-edge’

### ISSUE THREAD

**Issue by alexei-28** [seagle0128/doom-modeline#678]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Given: 
Linux Mint 21.2
Emacs 29.1

When I install package **elpa/doom-modeline-4.0.1** it installed successfully but raise one warning:

`Warning (comp): doom-modeline-core.el:1098:37: Warning: reference to free variable ‘mode-line-right-align-edge’`

### Steps to reproduce

Linux Mint 21.1
Emacs 29.1

### Expected behavior

No warings

### OS

Linux

### Emacs Version

29

**Comment by seagle0128** [comment]
Which version are you using? I tested with the latest version and no warning.

**Comment by alexei-28** [comment]
> Which version are you using? I tested with the latest version and no warning.

doom-modeline                  4.0.1

**Comment by seagle0128** [comment]
Please upgrade to the latest version of `doom-modeline` with Emacs 29.1.2.

**Comment by alexei-28** [comment]
> Please upgrade to the latest version of `doom-modeline` with Emacs 29.1.2.

Installed doom-modeline-20231028.1505 and now it's working just fine.
Thanks.

**Comment by alexei-28** [comment]
> Please upgrade to the latest version of `doom-modeline` with Emacs 29.1.2.

Installed doom-modeline-20231028.1505 and now it's working just fine.
Thanks.

**Comment by alexei-28** [comment]
> Please upgrade to the latest version of `doom-modeline` with Emacs 29.1.2.

Installed doom-modeline-20231028.1505 and now it's working just fine.
Thanks.
