### ISSUE TITLE
display number of goals in Coq mode

### ISSUE THREAD

**Issue by vzaliva** [seagle0128/doom-modeline#679]
When editing Coq files (.v) using Proof general mode: https://github.com/ProofGeneral/PG, it shows the number of active goals in the mode line. With doom-modeline, this information is suppressed.

The number of active goals is an important piece of information which should be shown to the user.

**Comment by vzaliva** [comment]
I dug a little further and the relevant information is shown in `proof-active-buffer-fake-minor-mode` in modelling. How can I make it displayed by default?

**Comment by seagle0128** [comment]
According to the snippet below, the info is added to minor mode. So just enbale `proof-active-buffer-fake-minor-mode` and  `(setq doom-modeline-minor-modes t)`.


https://github.com/ProofGeneral/PG/blob/0dd686ec46790e918896670b559b11d38a4bb115/generic/proof-shell.el#L191)/ProofGeneral/PG/blob/0dd686ec46790e918896670b559b11d38a4bb115/generic/proof-shell.el#L191

**Comment by vzaliva** [comment]
Yes, `(setq doom-modeline-minor-modes t)` does the trick, but my modeline becomes super cluttered with 9(!) other minor modes shown and does not fit the frame. Is it possible to show just `proof-active-buffer-fake-minor-mode` in my modelling, not others?

**Comment by seagle0128** [comment]
If you don't like the default behavior, you can display it in `global-mode-string` following by the FAQ 5.

e.g. 

```elisp
(add-to-list 'global-mode-string proof-active-buffer-fake-minor-mode)
```

PS: I didn't test it. It might be need some tweaks.

**Comment by vzaliva** [comment]
Thanks. I tried a similar approach, which kind of worked:

`(add-to-list 'global-mode-string
             `(" " ,(assoc 'proof-active-buffer-fake-minor-mode minor-mode-alist)) " ")`

It shows me the number of goals in the mode line, but it is not updated when the number of goals changes.

**Comment by seagle0128** [comment]
```elisp
(add-to-list 'global-mode-string  `(" " ,(assoc 'proof-active-buffer-fake-minor-mode minor-mode-alist)) " ")
```

This doesn't work while the number changes, since it won't be evaluated. You should use function or eval to force to update.

**Comment by vzaliva** [comment]
I don't know how to do that. This is a static list. How can I add a function which evaluates later into it?

I want to point out that the Proof General code forces updates of `proof-active-buffer-fake-minor-mode` string when the number of goals changes. It just did not get propagated to doom-modeline.

**Comment by seagle0128** [comment]
Try this

```elisp
(add-to-list 'global-mode-string '(" " (:eval (coq-build-subgoals-string nbgoals nbunfocused))) " ")
`````

**Comment by vzaliva** [comment]
There are no `nbgoals` and `nbunfocused` variables. They are local variables in `coq-update-minor-mode-alist` function, not exposed outside.

**Comment by seagle0128** [comment]
```elisp
(add-to-list 'global-mode-string '(" " (:eval (assq 'proof-active-buffer-fake-minor-mode minor-mode-alist))) " ")
````

**Comment by seagle0128** [comment]
```elisp
(add-to-list 'global-mode-string '(" " (:eval (assq 'proof-active-buffer-fake-minor-mode minor-mode-alist))) " ")
````

**Comment by vzaliva** [comment]
It worked! Thanks! In case someone else will be looking for the solution: I've added it to the hook for coq-mode in proof general use-package definition:

```
(use-package proof-general
  :ensure t
  :after doom-modeline
  :mode ("\\.v\\'" . coq-mode)
  :custom
  (coq-smie-user-tokens '(("≈" . "=") ("≡" . "=")))
  (proof-splash-enable nil)
  (coq-prog-name "coqtop")
  (coq-compile-before-require nil)
  :hook
  (coq-mode . (lambda ()
                (ws-butler-mode)
                (helm-mode)
                (add-to-list 'global-mode-string '(" " (:eval (assq 'proof-active-buffer-fake-minor-mode minor-mode-alist))) " ")
                )))
```
