### ISSUE TITLE
[Bug] need update for latest jsonrpc accessor change: `jsonrpc--request-continuations`

### ISSUE THREAD

**Issue by garyo** [seagle0128/doom-modeline#687]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

In emacs commit [dceffddbfe7](https://github.com/emacs-mirror/emacs/commit/dceffddbfe), `jsonrpc--request-continuations` is replaced with `jsonrpc--continuations` in `lisp/jsonrpc.el`. As of doom-modeline a312ea8, `doom-modeline-segments.el` uses the old accessor function. 

This trivial patch fixes it for me:
```patch
diff --git a/doom-modeline-segments.el b/doom-modeline-segments.el
index 1182d58..ad93827 100644
--- a/doom-modeline-segments.el
+++ b/doom-modeline-segments.el
@@ -193,7 +193,7 @@
 (declare-function iedit-find-current-occurrence-overlay "ext:iedit-lib")
 (declare-function iedit-prev-occurrence "ext:iedit-lib")
 (declare-function image-get-display-property "image-mode")
-(declare-function jsonrpc--request-continuations "ext:jsonrpc" t t)
+(declare-function jsonrpc--continuations "ext:jsonrpc" t t)
 (declare-function jsonrpc-last-error "ext:jsonrpc" t t)
 (declare-function lsp--workspace-print "ext:lsp-mode")
 (declare-function lsp-describe-session "ext:lsp-mode")
@@ -2073,7 +2073,7 @@ mouse-1: Reload to start server")
   "Get count of pending eglot requests to SERVER."
   (if (fboundp 'jsonrpc-continuation-count)
       (jsonrpc-continuation-count server)
-    (hash-table-count (jsonrpc--request-continuations server))))
+    (hash-table-count (jsonrpc--continuations server))))

 (defvar-local doom-modeline--eglot nil)
 (defun doom-modeline-update-eglot ()
```
but I expect the actual fix will need to cover both cases for compatibility.

### Steps to reproduce

Try to use eglot with doom-modeline, using latest master emacs.

### Expected behavior

Should work without error.

### OS

Windows

### Emacs Version

30

**Comment by seagle0128** [comment]
Thank you for the kind reminder!

**Comment by uqix** [comment]
This fix results in error on Emacs 29.1:

> error in process filter: doom-modeline--eglot-pending-count: Symbol’s function definition is void: jsonrpc--continuations
> error in process filter: Symbol’s function definition is void: jsonrpc--continuations

**Comment by seagle0128** [comment]
@uqix I reverted 9773ef7. Sorry for the incovenience!

**Comment by pcompassion** [comment]
Hi, should I unpin the package to use the fixed version?

**Comment by seagle0128** [comment]
@pcompassion pls use the latest version.

**Comment by pcompassion** [comment]
@seagle0128 thanks for the response, but i tried doing

(unpin! doom-modeline) in my packages.el
and even changing the 

(unless (modulep! +light)
  (package! doom-modeline :pin "93f240f7a0bf35511cfc0a8dd75786744b4bcf77"))
to

(unless (modulep! +light)
  (package! doom-modeline)) 
  
 and doing doom-sync, doens't give me the latest version..

**Comment by seagle0128** [comment]
@pcompassion I think you should file an issue for doom emacs.

**Comment by cole-jacobs** [comment]
@pcompassion maybe you need `doom sync -u` [1]? 

[1] https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#the-bindoom-utility
> You’ll need doom sync -u if you override the recipe of package installed by another module.

**Comment by pcompassion** [comment]
@seagle0128 @pcompassion thanks for the responses, i'll handle it
