### ISSUE TITLE
[Feature Request] Support for Flycheck-status-emoji

### ISSUE THREAD

**Issue by chookity-pokk** [seagle0128/doom-modeline#688]
**Is your feature request related to a problem? Please describe.**
There is a package called [flycheck-status-emoji](https://github.com/liblit/flycheck-status-emoji) that unfortunately can't be used with Doom modeline. When trying to use it the flycheck icon doesn't change but is visible when turning off doom modeline.

**Describe the solution you'd like**
The ability to either have some compatibility with flycheck status emoji. Maybe the option to choose between the built in flycheck and that one.

**Describe alternatives you've considered**
I tried looking into checking the flycheck icon but that doesn't really have the same ability as the described package.

**Comment by seagle0128** [comment]
Enable `doom-modeline-minor-modes` or `(add-to-list 'global-mode-string flycheck-mode-line)`.

**Comment by chookity-pokk** [comment]
> `(add-to-list 'global-mode-string flycheck-mode-line)`

This seems to work on the dashboard but once entering a python file it gets rid of that as well as my perspective. My global mode string is 

```
((:eval
  (flycheck-status-emoji-mode-line-text))
 ""
 (:eval
  (persp-mode-line)))
```

It seems like even if I remove the flycheck stuff from there I miss my perspective anyway which I don't think has usually been the case?

<img width="501" alt="image" src="https://github.com/seagle0128/doom-modeline/assets/24358100/c3c53556-ab41-44e7-8fa4-97c01a448089">


<img width="665" alt="image" src="https://github.com/seagle0128/doom-modeline/assets/24358100/dac84490-fc87-4b0c-981e-ecfdf83a1c0c">

**Comment by chookity-pokk** [comment]
Okay, so I didn't change anything but it works now. I restarted Emacs several times and it didn't work any of those times but this time it seems to have worked. I am going to try and reproduce this and I'll update the issue with what worked and then I'll close it. Thank you for the help!


![image](https://github.com/seagle0128/doom-modeline/assets/24358100/ae6ebfca-e895-4247-86b8-f211602c180a)

**Comment by chookity-pokk** [comment]
Yep, I can't reproduce it not working anymore. It wasn't working, I restarting Emacs probably 10+ times, still didn't work. I tried setting my own modeline value to make sure that was working, it did. I then enabled doom modeline again and it started working. Just a day in the life.
