### ISSUE TITLE
Error using with latest eglot / jsonrpc packages

### ISSUE THREAD

**Issue by bradhowes** [seagle0128/doom-modeline#689]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I upgraded my packages and this brought down `eglot` v1.16 (built-in is 1.12.29). This installed an updated `jsonrpc` package v1.0.23. When starting a mode that uses `eglot` there now appears the following error:

```
Error running timer: (void-function jsonrpc--request-continuations)
```

This is due to the fact that that function no longer exists in the `jsonrpc` package.

I removed the `eglot` upgrade for now until `doom-modeline` is updated.

### Steps to reproduce

* Upgrade `eglot` to v1.16
* Restart Emacs
* Edit source file that uses `eglot` or start it manually with `M-x eglot`

### Expected behavior

No error.

### OS

MacOS

### Emacs Version

29

### Emacs Configurations

Custom

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (void-function jsonrpc--request-continuations)
  jsonrpc--request-continuations(#<eglot-lsp-server eglot-lsp-server-52c05d10>)
  doom-modeline-update-eglot()
  run-hooks(eglot-managed-mode-hook)
  eglot--maybe-activate-editing-mode()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(python-mode-hook)
  python-mode()
```
```


### Anything else

Fix for now is to remove the `eglot` and `jsonrpc` upgrades for now until `doom-modeline` is updated.

**Comment by bradhowes** [comment]
Appears that `jsonrpc-continuation-count` would be the likely candidate to use instead. It works for me but the number that it shows make no sense -- string of repeated '100'...

**Comment by seagle0128** [comment]
Please make sure you are using the latest version of `doom-modeline`.


https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L2072-L2076

**Comment by bradhowes** [comment]
Thanks for the response. I do not see anything more than 4.0.1 and that is what I've been using.

**Comment by seagle0128** [comment]
Are you using the melpa-stable version? I've pushed a new tag: v4.1.0.
