### ISSUE TITLE
Ligature characters instead of some icons (fira code conflict with material icons)

### ISSUE THREAD

**Issue by wedens** [seagle0128/doom-modeline#69]
I've started observing some weird character in a modeline near a buffer name in the active window (where "unsaved" icon is supposed to be):
![image](https://user-images.githubusercontent.com/697162/50051713-befcf500-0149-11e9-8428-4cb7af5bc38a.png)

This character looks like a Fira Code Symbol ligature for ` <~~` that I have configured in `prettify-symbols-mode` (I have almost the same configuration for ligatures as doom-emacs https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/pretty-code/%2Bfira.el).

I tried to reproduce the problem with some older doom-modeline versions and I can't reproduce it in c969900. So, 1d66c50 introduced the problem by changing to material icons. And doing `(insert (doom-modeline-icon-material "save"))` or just `(insert (all-the-icons-material "save"))` indeed results in this ligature character.

Looks like Fira Code Symbol font has overlapping codepoints with material icons font.

I'm not sure there is anything doom-modeline can do about it, other than mention this incompatibility in readme.

doom-modeline ee2aa11
emacs 27.0.50
OS: GNU/Linux

**Comment by seagle0128** [comment]
Can you try this snippet? Maybe you need to change the charset. I am not using `Fira Code` while using `Source Code Pro`.

```elisp
(dolist (charset '(kana han cjk-misc bopomofo gb18030))
  (set-fontset-font "fontset-default" charset "Material Icons" nil 'append))
```

**Comment by wedens** [comment]
It seems to work (correct modeline icons) in some buffers (and it works with ligatures if I enable `prettify-symbols-mode`!),  but in some major mode (e.g. `emacs-lisp-mode`) it crashes emacs with segfault (even with disabled  `prettify-symbols-mode`). :(

**Comment by seagle0128** [comment]
Try to change the charsets. Not all are necessary in my example above.

**Comment by wedens** [comment]
It crashes as soon as I add `gb18030` or `unicode`.  I'm not sure what other charsets I can try, but without any of those two, icons are not displayed properly.

**Comment by wedens** [comment]
As a workaround,  can I locally redefine `doom-modeline-icon-material` so that it uses e.g. Font Awesome icons via some substitution table (mapping from material to font awesome icon)?

**Comment by seagle0128** [comment]
That should be good for you!
