### ISSUE TITLE
[Bug] buffer-position formatting won't respect flags in format specifier for column

### ISSUE THREAD

**Issue by psionic-k** [seagle0128/doom-modeline#691]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Setting `doom-modeline-position-column-line-format` to `("%l:%-3c")` for example, adding flags to the column format specifier, doesn't get respected.  Very specifically, "%5c" will work bu t"%-3c" will not.

I think this is unrelated, but I noticed the string replacements here are assuming the specifiers have no flags:
https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L1674-L1680C76

### Steps to reproduce

````elisp
(setopt doom-modeline-position-column-line-format '("%l:%-3c"))
```
Possibly some more to enable the column display.

### Expected behavior

Right-padding added to the column number

### OS

Linux

### Emacs Version

29

### Emacs Configurations

Custom

### Error callstack

_No response_

### Anything else

I worked around the issue using left padding for now to stabilize the width at low column numbers.

**Comment by seagle0128** [comment]
Not sure if you need this

```elisp
(setopt doom-modeline-position-column-line-format '("%l:%3c"))
```

And make sure `column-number-mode` and `doom-modeline-column-zero-based` are non-nil.

**Comment by psionic-k** [comment]
That's basically my "workaround" before resorting to advice.  I'm rendering commands right after that figure and really need it to be a bit more stable.

**Comment by seagle0128** [comment]
Did you check the behavior of `emacs -Q`  and `(setq mode-line-position-column-line-format '(" (%l,%-3c)"))`?

**Comment by psionic-k** [comment]
That was helpful.  `mode-line-position-column-format` to `(" C%-3c")`

My only other complaint is that it's difficult to insert arbitrary items into the modeline, but I won't open an issue for that.  I'm sure you're aware of the tradeoffs.
