### ISSUE TITLE
[Bug] Lightbulb symbol 01F4A1 not displaying in mode line 

### ISSUE THREAD

**Issue by lestergill** [seagle0128/doom-modeline#692]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Emacs version:
```
(emacs-version)
"GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
 of 2022-01-24, modified by Debian"
```

I am using Monofur Nerd Font Mono:
```
(describe-variable 'nerd-icons-font-family)
#("nerd-icons-font-family is a variable defined in ‘nerd-icons.el’.
Its value is \"Monofur Nerd Font Mono\"
```
Here it is in my ~/.fonts dir:
```
~ $ cd .fonts/
~/.fonts $ ls
IBMPlexMono-Regular.ttf                  MonofurNerdFontMono-Italic.ttf
IBMPlexMono-Regular.ttf:Zone.Identifier  MonofurNerdFontMono-Regular.ttf
IosevkaSS08-Regular.ttc                  MonofurNerdFontPropo-Bold.ttf
IosevkaSS08-Regular.ttc:Zone.Identifier  MonofurNerdFontPropo-Italic.ttf
MonofurNerdFont-Bold.ttf                 MonofurNerdFontPropo-Regular.ttf
MonofurNerdFont-Italic.ttf               ProggyClean.ttf
MonofurNerdFont-Regular.ttf              ProggyClean.ttf:Zone.Identifier
MonofurNerdFontMono-Bold.ttf
```
I am running Emacs in WSL2 as a GUI app on a Windows 10 desktop machine, the WSL2 is using Ubuntu 22.04.2 LTS and kernel 5.15.133.1-microsoft-standard-WSL2

![Screenshot 2024-01-23 130659](https://github.com/seagle0128/doom-modeline/assets/86599603/502b45b4-2f63-44c3-9909-af8ac98ffd28)

You can see it in the taskbar above. Please let me know if you need anything else or if I have made a mistake.

### Steps to reproduce

Install the font in ~/.fonts and refresh the cache. Set the nerd font family variable. Run nerd-icons-install-fonts. Open a Java file, with lsp-mode and lsp-java language server. The lightbulb symbol, that should appear when the language server notices an error or warning, is replaced with a hex symbol as in the image.

### Expected behavior

Lightbulb symbol to be displayed in mode line.

### OS

Linux

### Emacs Version

27

### Emacs Configurations

Vanilla emacs with Doom modeline and Doom theme

**Comment by seagle0128** [comment]
You should install correct fonts via `M-x nerd-icons-install-fonts`. The default font name is "Symbols Nerd Font Mono". Please check `nerd-icons-font-family`. Below is screenshot  in my env (WSL2 + Arch + Emacs 29.1 pgtk)

![image](https://github.com/seagle0128/doom-modeline/assets/140797/335c264e-176a-48bf-a9b0-22c80173c1f8)

**Comment by lestergill** [comment]
I have already done M-x nerd-icons-install-fonts. 

I already posted the output of nerd-icons-font-family. But, I will change it again, to the default. 

```
(describe-variable 'nerd-icons-font-family)
#("nerd-icons-font-family is a variable defined in ‘nerd-icons.el’.
Its value is \"Symbols Nerd Font Mono\"
```

I have the same issue.

![Screenshot 2024-01-24 111749](https://github.com/seagle0128/doom-modeline/assets/86599603/83c1ed99-3f52-43a9-b2e1-d068934de046)

**Comment by seagle0128** [comment]
I guess some fonts are conflicted with `NFM.ttf``, and override some icons.
