### ISSUE TITLE
[Feature Request] display-all-git-branches

### ISSUE THREAD

**Issue by mlarcane** [seagle0128/doom-modeline#693]
Hi,

Thanks for this awesome package. I was wondering, if it would be possible implement something like "display-all-git-branches" where the current git branch is maybe highlighted slightly different. I usually have a couple of branches, and sometimes I actually tend to forget this. Hence, some unwanted commits end up on the wrong branch.

/Mads

**Comment by mlarcane** [comment]
Just discovered `magit-insert-local-branches` which show all branches in the magit menu. So it might not be that relevant; I'm leaving it for now, if anyone should be interested anyway. Feel free to close it.

**Comment by seagle0128** [comment]
I don't think it's a good idea to display all branches on mode-line. I suggest to use other tools to display, e.g. `magit`.
