### ISSUE TITLE
[Bug] Icons on modeline lack sufficient padding

### ISSUE THREAD

**Issue by judemille** [seagle0128/doom-modeline#694]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I am using doom-emacs, with Fira Code, 12pt.
The major mode and checker icons do not have any padding to the right of them, which looks very bad.

### Steps to reproduce

Install doom-emacs, enable icons in modeline

### Expected behavior

Major mode and checker icons have spacing to the right of them.

### OS

Linux

### Emacs Version

29 (gccemacs)

### Emacs Configurations

Doom Emacs

### Anything else

The issue can be seen here:
![image](https://github.com/seagle0128/doom-modeline/assets/8127111/b398f579-a98a-4414-b867-4c1f2c0da8d8)

This issue goes away if uses of `doom-modeline-vspc` in `doom-modeline-segments.el` are replaced with `doom-modeline-spc`.

It is unclear to me why the `vspc` is used anyway -- from all of my experience, the nerd-icons need a full-width space to gain sufficient padding.

**Comment by seagle0128** [comment]
I think it's related to Fira Code font, which is narrower than other nerd fonts. I am using "Cascadia Code", "SF Mono" and "Hack", the screenshot is below

![image](https://github.com/seagle0128/doom-modeline/assets/140797/94104be9-dba5-4613-b387-1b408458456e)

**Comment by judemille** [comment]
I'm using `Fira Code`. I have `:ui unicode` enabled in Doom, and `Symbols Nerd Font` installed and enabled.

**Comment by judemille** [comment]
Here is the appearance with `emacs -Q`:
![image](https://github.com/seagle0128/doom-modeline/assets/8127111/d4de4fc4-1f2f-4a9b-aaef-4d63a76b4f17)

I added MELPA, installed `doom-modeline`, set the font to `FiraCode Nerd Font`, and enabled `doom-modeline-mode`. The gaps between the icons and the text are still uncomfortably small.

**Comment by seagle0128** [comment]
I tested on macOS, Windows and Ubuntu, and no issues were observed. I think it may be related to your WM?

**Comment by judemille** [comment]
I'm running Arch Linux rolling, with KDE 5.27.10.

**Comment by seagle0128** [comment]
Well, I didn't test with KDE. I'm sure there is no issue with GTK, according to my tests.

**Comment by judemille** [comment]
On my laptop, I'm using the `emacs-wayland` package, which has PGTK enabled. I don't think this is toolkit-specific.

Out of curiosity, how does it look for you if you change all `vspc` occurrences to just `spc`?

**Comment by seagle0128** [comment]
No idea why vspc is so narrow in your env. Did you customize the `variable-pitch` face?

![image](https://github.com/seagle0128/doom-modeline/assets/140797/934eec06-a8df-4c79-9783-f5a89a91f791)

**Comment by judemille** [comment]
Changing that did nothing. Replacing all occurrences of `doom-modeline-vspc` with `doom-modeline-spc` does this:
![image](https://github.com/seagle0128/doom-modeline/assets/8127111/288a4aad-77e8-48e0-86f8-ac5429018597)

**Comment by seagle0128** [comment]
Re-evaluate `doom-modeline-segment.el` or compile `doom-modeline-core.el` and restart Emacs after changing.

**Comment by judemille** [comment]
Both are spc, yes. This is known behavior of nerd-icons -- if you put a space after an icon, it will become wider into that space, but still leaving a slight space.

**Comment by seagle0128** [comment]
> Both are spc, yes. This is known behavior of nerd-icons -- if you put a space after an icon, it will become wider into that space, but still leaving a slight space.

Obviously it's different behavior in my env. 

vspc=spc
![image](https://github.com/seagle0128/doom-modeline/assets/140797/fef99315-b2e9-4bc2-9cf2-6e5e6c289dce)

vspc=1/2 spc
![image](https://github.com/seagle0128/doom-modeline/assets/140797/52821c02-99cb-4e64-88ec-e158770b461e)

**Comment by judemille** [comment]
That's fascinating. The only possibly explanation I can come up with is that something about the fontconfig on Arch is different from your Ubuntu install.

**Comment by judemille** [comment]
I've just realized what's going on. It's `Symbols Nerd Font` vs `Symbols Nerd Font Mono`.

I didn't have the mono variant installed. Going to install it and see the behavior.
