### ISSUE TITLE
[Bug] modeline fragments do not get updated correctly when a command that changes the current-buffer is running

### ISSUE THREAD

**Issue by molok** [seagle0128/doom-modeline#695]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When a command that changes the current-buffer is running, the modeline does not get updated.

### Steps to reproduce

eval `((with-current-buffer (sit-for 10))` and immediately remove the focus from the emacs window, the modeline doesn't change to the inactive color.

### Expected behavior

I expect the modeline to be updated when a buffer is being displayed

### OS

Linux

### Emacs Version

29

### Emacs Configurations

Doom Emacs

### Anything else

I encountered this bug because I have several scripts running using invoking emacsclient, I noticed that sometimes the modeline stopped updating for few seconds.

**Comment by seagle0128** [comment]
I couldn't reproduce on my env. Can you please retry with `emac s -Q`?

**Comment by molok** [comment]
I can't reproduce it with `  emacs -Q`, I'll try to figure out what the issue is.

**Comment by seagle0128** [comment]
Can you please provide a recording?
