### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by DoubleAgentDave** [seagle0128/doom-modeline#697]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I have absolutely no idea how to address this. I've updated emacs recently (emacs snapshot latest version as of feb-2024), and the only problem I've got is that doom-modeline doesn't seem to start.

### Steps to reproduce

I have this in my init.el:
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))

and the initial hook is in this line:

(custom-set-variables
 '(package-selected-packages
   '( ................... nerd-icons-ibuffer nerd-icons-dired
			   nerd-icons-completion nerd-icons 
			   doom-modeline doom-themes ...........................))
 '(tool-bar-mode nil))

where the dots indicate a bunch of other packages, which all seem fine.

### Expected behavior

Doom-modeline should run

### OS

Linux

### Emacs Version

30

### Emacs Configurations

emacs-snapshot

### Error callstack

```emacs-lisp
Error (use-package): doom-modeline/:init: Eager macro-expansion failure: (error "Shortdoc f function ‘f-glob’: bad keyword ‘:noeval*’")
⛔ Error (use-package): doom-modeline/:catch: Eager macro-expansion failure: (error "Shortdoc f function ‘f-glob’: bad keyword ‘:noeval*’")
```

**Comment by dr-scsi** [comment]
This is a stab in the dark, but it sounds like your byte-compile packages don't match your Emacs no more.  You can try to:

- Start Emacs with `emacs -Q`
- Do `M-x package-initialize RET`
- Do `M-x package-recompile-all RET`
- Exit Emacs and start a new session

Maybe this helps.

**Comment by seagle0128** [comment]
I haven't tried the latest Emacs recently, and no idea so far. I suggest to use `doom-modeline` with 29.2 currently, and switch the 30.x when it's almost stable.

**Comment by DoubleAgentDave** [comment]
I could do all that, but just deleting the 'elpa' direcory inside .emacs.d has the same effect, i.e. redownloading all the packages and recompiling. Thanks everyone!
