### ISSUE TITLE
Fix the few faces that don't inherit from doom-modeline

### ISSUE THREAD

**Issue by benleis1** [seagle0128/doom-modeline#704]
**Is your feature request related to a problem? Please describe.**
A few of the faces are still inheriting from modeline-face rather than doom-modeline. For instance the Percentage progress.

**Describe the solution you'd like**
Would it make sense for those to inherit from doom-modeline as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by seagle0128** [comment]
Closed by e09b8e9.
