### ISSUE TITLE
the active mode-line length not correct

### ISSUE THREAD

**Issue by stardiviner** [seagle0128/doom-modeline#71]
Here is the screenshot:

![image](https://user-images.githubusercontent.com/378699/50324811-11f4f480-051c-11e9-8ba8-5825613a2c90.png)

The inactive mode-line is correct, but the active mode-line is not correct.

**Comment by seagle0128** [comment]
What's your exact mean? The length looks correct. Many items on the active mode-line, and should drag the window wider. Maybe you need `golden-ratio`?

**Comment by stardiviner** [comment]
I mean, in the middle, obviously has space still, but the active mode-line's right side, the major mode name is partially shown.

**Comment by seagle0128** [comment]
Okay. Some spaces will be reserved there. What's minor mode for `[python 3.7]` in the screenshot?

**Comment by stardiviner** [comment]
It's `pyenv-mode`.

**Comment by seagle0128** [comment]
A couple of questions:

- How about disable `pyenv-mode`?
- What's Emacs version?
- What's the OS? and version? Which WM/DE?

**Comment by seagle0128** [comment]
Any update?

**Comment by stardiviner** [comment]
I've tested, it's because of `doom-modeline--github-notifications-number`. When the icon shown, the mode-line length is not correctly. I think it's because of the icon size issue.
My Emacs version:  `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05`
OS: `Arch Linux`, `Linux dark 4.19.9-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 14 00:58:26 UTC 2018 x86_64 GNU/Linux`
DE: `KDE/Plasma`

**Comment by seagle0128** [comment]
So have nothing to do. Set `doom-modeline-github` to nil to disable it if you don't like it.

**Comment by seagle0128** [comment]
Yep. I was trying to optimize icons. But seems melpa stopped building the package. You can try the latest codes.
