### ISSUE TITLE
[Bug] Error during redisplay

### ISSUE THREAD

**Issue by dchrzanowski** [seagle0128/doom-modeline#714]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The message buffer gets spammed with:

```
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (args-out-of-range 0 0)
Unable to load color "nil"
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (args-out-of-range 0 0) [2 times]
Unable to load color "nil" [2 times]
Error during redisplay: (eval (doom-modeline-segment--vcs)) signaled (args-out-of-range 0 0) [2 times]
Unable to load color "nil"
```

Please not that I am not using any face modifications for doom-modeline. 

### Steps to reproduce

Just move around any buffer that is under a version control.

### Expected behavior

No error spam.

### OS

Linux

### Emacs Version

29

### Emacs Configurations

my own @ https://github.com/dchrzanowski/.emacs.d

**Comment by benthamite** [comment]
(also experiencing this)
