### ISSUE TITLE
[Bug] Reference to free variable `keel-menu-map' after 1d0942d

### ISSUE THREAD

**Issue by dr-scsi** [seagle0128/doom-modeline#716]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The commit 1d0942d now produces:

```
In doom-modeline-segment--k8s:
doom-modeline-segments.el:3191:73: Warning: reference to free variable ‘kele-menu-map’
```

### Steps to reproduce

(byte|native)-compile the file `doom-modeline-segments.el`.

### Expected behavior

No compiler warnings by `defvar`'ing the variable.

### OS

MacOS

### Emacs Version

30 (gccemacs)

### Error callstack

```emacs-lisp
N/A
```

### Anything else

N/A

**Comment by seagle0128** [comment]
cc @jinnovation

**Comment by jinnovation** [comment]
Oops, thank you @seagle0128
