### ISSUE TITLE
The `buffer-info` segment is different for active and inactive modeline

### ISSUE THREAD

**Issue by edkolev** [seagle0128/doom-modeline#72]
The issue is reproduced like so:
- have ~/.emacs.d under git version control
- split a frame in two windows, open `~/.emacd.d/init.el` in both windows
- the active and inactive `buffer-info` segments are different (a screenshot is attached below) - the active is `~/.emacs.d/init.el`, the inactive is `init.el`
- I expect both to be the same

<img width="1435" alt="screenshot 2018-12-21 at 9 22 03" src="https://user-images.githubusercontent.com/1532071/50330289-545e0780-0503-11e9-9a11-15b21a76cf51.png">

This issue appeared recently, maybe it was introduced by #47 

I personally find doom-modeline as a huge improvement over uniquify, a complete replacement. That's just me though.

Maybe a configuration option could be introduced, something which will determine wheter doom-modeline should manage both active and inactive `buffer-info`s or it doom-modeline should leave inactive `buffer-info`s to be managed by uniquify `%b`.

BTW I'm open to submitting a PR, after we decide on the approach.

**Comment by seagle0128** [comment]
This is by designed for the performance and space issue. Do you have any proposal to improve with the same performance?

**Comment by seagle0128** [comment]
I found a simple way to keep the same buffer info in the inactive window. Will commit soon

**Comment by edkolev** [comment]
Great, thanks for the quick reaction time!
