### ISSUE TITLE
help-echo text not showing when in lsp-mode[Bug] 

### ISSUE THREAD

**Issue by benleis1** [seagle0128/doom-modeline#720]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I've noticed none of the help-echo text appears when the mouse hovers on a segment when in lsp-mode. Everything works normally in other modes.

### Steps to reproduce

open a buffer in lsp-mode - I'm using lsp-java and hover over a segment.   I've dumped the modeline and all the help-echo text is really there its just not activating like normal

### Expected behavior

hover over a segment and the help message appears in the echo area 

### OS

MacOS

### Emacs Version

29 (gccemacs)

### Emacs Configurations

vanilla

**Comment by seagle0128** [comment]
I believe `lsp-mode` suppresses `tooltip`. Try disabling/enabling `tooltip-mode` and check the results. I think it's an issue of `lsp-mode` (or `lsp-ui`).

**Comment by benleis1** [comment]
I think you're right. I verified more after this day with doom mode line off and the behavior was the same.

**Comment by seagle0128** [comment]
Then please file an issue in `lsp-mode`. Thanks!

**Comment by benleis1** [comment]
Will do
