### ISSUE TITLE
[Bug] Space inconsistency between `buffer-position` and `selection-info`

### ISSUE THREAD

**Issue by schickele** [seagle0128/doom-modeline#721]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

There is a small visual inconsistency between the `buffer-position` and the `selection-info` segments. When `buffer-position` displays a percent position, both segments are separated by **two spaces**. If the buffer position is instead equal to `Top`, `Bot` or `All`, they are separated by **one space**. Here is a small demonstration:

![bilder_joined_a](https://github.com/seagle0128/doom-modeline/assets/36489836/d5df2538-91de-4711-b6c6-97f773120264)

This is especially noticeable if you highlight the `selection-info` segment like I like to do:

![bilder_joined_b](https://github.com/seagle0128/doom-modeline/assets/36489836/e26b9713-9208-4e6c-8b94-d77b211dfff6)

### Steps to reproduce

Visit a file and select a region.

### Expected behavior

Two separation spaces in every case would be a visually more pleasing solution IMHO. I'm a elisp beginner and I'm not able to draft a pull request myself.

### OS

Linux

### Emacs Version

29

### Emacs Configurations

Vanilla Emacs or Doom Emacs

**Comment by seagle0128** [comment]
The default format is `xxx:xxx  xx%`, as the screenshot below. Did you check your own configurations, or test with `emacs -Q`?

![image](https://github.com/seagle0128/doom-modeline/assets/140797/405aa544-dca0-45da-9ce7-d8089463d6f2)

**Comment by schickele** [comment]
Hello,

Thanks for your feedback. If I'm not not mistaken, we are not talking about
the say thing. The small issue I've reported concerns the inconsistent
simple/double space between the buffer position and the selection-info
segment in the modeline. The selection-info displays how many characters
and lines are selected and isn't visible on your screenshot.

Greetings from Europe

Paul

Am Fr., 26. Apr. 2024 um 05:43 Uhr schrieb Vincent Zhang <
***@***.***>:

**Comment by seagle0128** [comment]
@schickele I realized and rolled back my comment. You happen to see it :cry:

It's related to `doom-modeline-percent-position`.

**Comment by schickele** [comment]
Thanks a lot! It's perfect now:

![bilder_joined](https://github.com/seagle0128/doom-modeline/assets/36489836/009a2571-36e9-499c-bc4a-1e520415f7c6)

**Comment by seagle0128** [comment]
@sebastiaanspeck Are you using the latest version? I cannot reproduce this issue.

**Comment by seagle0128** [comment]
@sebastiaanspeck Gotcha. Already fixed.
