### ISSUE TITLE
[Feature Request] Allow setting the modeline as the headerline

### ISSUE THREAD

**Issue by sa-gam-github-bitrise** [seagle0128/doom-modeline#726]

**Comment by seagle0128** [comment]
Actually `doom-modeline` is designed for mode-line only. It needs many modifications to fully support header-line.

**Comment by jmjones5** [comment]
Is there any plans to make it work on the headerline?

**Comment by seagle0128** [comment]
Not yet. That needs huge changes, since it's against the original design.
