### ISSUE TITLE
[Bug] New Evil Modes Aren't Being Shown When Doom-Modeline-Icon and Doom-Modeline-Buffer-State-Icon both True.

### ISSUE THREAD

**Issue by IQubic** [seagle0128/doom-modeline#730]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

So, I've added a new Evil State. The issue is that when I enter this new state, the modeline still shows me the ""nf-md-alpha_n_circle" symbol as if I were in still in Normal mode. Note that I currently have the default modeline settings set.

### Steps to reproduce

1. Execute the following code in an ELisp buffer:
```
(evil-define-state test
  "Test state."
  :tag " <T> "
  (message (if (evil-test-state-p)
               "Enabling test state."
             "Disabling test state.")))
 ```
 2. Run `M-x evil-test-state`
 3. Notice that the modeline still shows the N in a circle from Nerdfonts

### Expected behavior

Ideally, what I'd like, is a way to be able to set an icon and a color for each new evil mode that I add.

### OS

Linux

### Emacs Version

29

### Emacs Configurations

Doom Emacs

**Comment by seagle0128** [comment]
It's as designed. `doom-modeline` doesn't support customized evil states, unless you override `doom-modeline--evil`.
