### ISSUE TITLE
[Bug] The new `doom-mode line-vcs-name` breaks my branch name

### ISSUE THREAD

**Issue by sebastiaanspeck** [seagle0128/doom-modeline#732]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

If you have a branch name that uses `-` in between, which is a common case, the part before the first `-` will only be shown, while the old manner did not have this bug and only removed the `vc-backend`-prefix

### Steps to reproduce

Have a Git branch like `feat/vcs-name`, the displayed name will be `feat/vsc`.

### Expected behavior

Having a Git branch like `feat/vcs-name`, the displayed name should be `feat/vsc-name`.

### OS

Windows

### Emacs Version

29

**Comment by seagle0128** [comment]
Cheers!
