### ISSUE TITLE
[Bug] The newest `doom-modeline` stops eglot from being shutdown.

### ISSUE THREAD

**Issue by 50ways2sayhard** [seagle0128/doom-modeline#739]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Emacs throws an error in the process sentinel: `No applicable method: jsonrpc-name, nil` after running `M-x eglot-shutdown` when using the newest `doom-modeline`. When I switch to version `36e32f0`, everything works fine and no error is thrown.

My Emacs version is: GNU Emacs 30.0.90 (build 1, aarch64-apple-darwin23.5.0, NS appkit-2487.60 Version 14.5 (Build 23F79)) of 2024-09-02

### Steps to reproduce

1. M-x doom-modeline-mode
2. open a project
3. M-x eglot 
4. M-x eglot-shutdown

### Expected behavior

Executing eglot-shutdown with no error thrown.

### OS

MacOS

### Emacs Version

30 (gccemacs)

**Comment by Icy-Thought** [comment]
This might be a relevant issue, but when you try to kill an eglot buffer while having doom-modeline installed you wind up with `cl-no-applicable-method: No applicable method: jsonrpc-name, nil`. Disabling the modeline does not resolve the issue, but removing it and restarting Emacs seems to get rid of the issue.

**Comment by Icy-Thought** [comment]
Can confirm that it also resolved the issue for me. Thanks a lot for resolving the issue and sharing the solution with us! :)
