### ISSUE TITLE
[Bug] next-line: End of bufferInvalid face reference: normal Invalid face reference: normal

### ISSUE THREAD

**Issue by LuciusChen** [seagle0128/doom-modeline#740]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

The error below will cause some functionalities of Meow to malfunction and become disordered.

`next-line: End of bufferInvalid face reference: normal Invalid face reference: normal`

### Steps to reproduce

When doom-modeline is enabled and telega is started, pressing down (triggering next-line) in telega's =Saved Message()= causes an error.

`next-line: End of bufferInvalid face reference: normal Invalid face reference: normal`

### Expected behavior

No error

### OS

MacOS

### Emacs Version

31

### Emacs Configurations

https://github.com/LuciusChen/.emacs.d

**Comment by seagle0128** [comment]
Did you reproduce with `emacs -Q`? It would be better if more info is provided, e.g. backtrace, logs, screenshots, etc. So far no any clue can approve it's a bug of `doom-modeline`.

**Comment by LuciusChen** [comment]
<img width="2555" alt="image" src="https://github.com/user-attachments/assets/2d7c7ede-bbc4-498d-894c-c8ea50bca5ca">
reproduce with `emacs -Q`
