### ISSUE TITLE
winnum显示太暗了

### ISSUE THREAD

**Issue by improve100** [seagle0128/doom-modeline#741]
光标非聚焦下
![image](https://github.com/user-attachments/assets/ef961e7d-d1ea-4cb7-9445-3257b2fbaf4b)
这个winnum显示太暗了，有什么办法可以调亮一点吗？
光标聚焦下好很多
![image](https://github.com/user-attachments/assets/83657de1-484d-4cb4-b247-41ef1ab28e2f)

**Comment by improve100** [comment]
有推荐主题吗？

> 换个主题，跟主题face有关。

**Comment by seagle0128** [comment]
试试doom-one, 或者 doom-molokai

**Comment by improve100** [comment]
> 光标非聚焦下 ![image](https://private-user-images.githubusercontent.com/6092914/369270928-ef961e7d-d1ea-4cb7-9445-3257b2fbaf4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4OTY4NjYsIm5iZiI6MTcyNjg5NjU2NiwicGF0aCI6Ii82MDkyOTE0LzM2OTI3MDkyOC1lZjk2MWU3ZC1kMWVhLTRjYjctOTQ0NS0zMjU3YjJmYmFmNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMDUyOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTcxMDdjNGE2ZDRmYjMxYmE2NWI3MDgwNDQ3MmM0MGVmZjlkN2Y0ZjVlNWY5YTQ4ZWIzZGEwMDQ1MTYwNGVlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vYKEw8ji7-co88Zl5or9Xn60olTLmox6LshQ0eX6OE0) 这个winnum显示太暗了，有什么办法可以调亮一点吗？ 光标聚焦下好很多 ![image](https://private-user-images.githubusercontent.com/6092914/369273884-83657de1-484d-4cb4-b247-41ef1ab28e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4OTY4NjYsIm5iZiI6MTcyNjg5NjU2NiwicGF0aCI6Ii82MDkyOTE0LzM2OTI3Mzg4NC04MzY1N2RlMS00ODRkLTRjYjQtYjI0Ny00MWVmMWFiMjhlMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMDUyOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODUxNDRlNTc5NWU5MzljOWVhYmU2YjMzZjM3NWY2NjAxZWE1NDQxMjY2ZmI1MGU2NTU4ODA4ZTQ5MTQyMWM0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AWMPU5hmdMPSuUwJZ-mcsR1cuv96NGgUFI-8M-1VHQo)

这个就是doom-molokai 主题
