### ISSUE TITLE
[Bug] lsp-mode progress status not formatted correctly.

### ISSUE THREAD

**Issue by brownts** [seagle0128/doom-modeline#742]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

It appears the `lsp-mode` progress status is not displayed properly when using `doom-modeline`.  When using `doom-modeline`, there is a missing percent sign and the percentage value and number of processed files are concatenated together instead of being spaced apart.  I've included a snapshot showing the behavior with `doom-modeline` enabled and one with it disabled, to show the difference.  The value "23544/2275 files" should be formatted as "23% 544/2275 files", like is shown when `doom-modeline` is not enabled.

![Screenshot_2024-09-30_23-53-32](https://github.com/user-attachments/assets/762fe63a-3015-4509-b516-9bfec506df0a)

![Screenshot_2024-09-30_23-54-48](https://github.com/user-attachments/assets/a002c95e-05f8-4a01-8c97-51803f116e76)

### Steps to reproduce

Start `lsp-mode` where the language server produces a progress report and noticed the formatting of the report.

### Expected behavior

There should be a percentage sign in the modeline along with proper spacing between the percent value and the file complete/total indication.

### OS

Linux

### Emacs Version

29

### Emacs Configurations

Vanilla

**Comment by seagle0128** [comment]
Can you please check if the snippet below fixed the issue?

```elisp
(doom-modeline-def-segment misc-info
  "Mode line construct for miscellaneous information.
By default, this shows the information specified by `global-mode-string'."
  (when (or doom-modeline-display-misc-in-all-mode-lines
            (doom-modeline--segment-visible 'misc-info))
    (doom-modeline-display-text mode-line-misc-info)))
```

**Comment by brownts** [comment]
I checked with the latest commit and this is now working as expected.  Thanks!
