### ISSUE TITLE
[Bug] S-down doesn't select region on emacs-30 when doom-modeline is enabled

### ISSUE THREAD

**Issue by mattiasdrp** [seagle0128/doom-modeline#743]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Hi and thanks for this beautiful package.

My issue is the following one: `S-<down>` doesn't create a region but only with emacs-30. If I compile emacs-29.4 for example, the issue disappears.

### Steps to reproduce

Create an init file with this content:

```
(defvar elpaca-installer-version 0.7)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca elpaca-use-package
        ;; Enable :ensure use-package keyword.
        (elpaca-use-package-mode)
        ;; Assume :ensure t unless otherwise specified.
        (setq elpaca-use-package-by-default t))
(elpaca-wait)

(setq byte-compile-warnings '(cl-functions))

(use-package doom-modeline
  :ensure t
  :config
  (doom-modeline-mode)
  (message "`doom-modeline' loaded"))

;;;; Footer

;; End:
(provide 'init)

;;; init.el ends here

```

Start emacs 30 with this init-file and open it
Try hitting `S-<down>`, no region is selected
Disable `doom-modeline-mode`, you can now select a region with `S-<down>`

### Expected behavior

`S-<down>` should always select a region

### OS

Linux

### Emacs Version

30 (gccemacs)

### Emacs Configurations

https://github.com/mattiasdrp/pokemacs

### Anything else

Normal behaviour:
[emacs-29.webm](https://github.com/user-attachments/assets/3c321ab0-bb0b-42b5-a765-78c2f36b4d0e)

Buggy behaviour:
[emacs-30.webm](https://github.com/user-attachments/assets/c05c2290-b2ff-458d-9754-d8ca0d2aae46)

**Comment by marcelocanales** [comment]
I am experiencing the same issue on Emacs 30 and 31, while everything works correctly on Emacs 29. I've tried several tests and noticed that after editing the buffer (like jumping a line or typing a character), the selection starts working again. However, when switching buffers, the problem reappears until another action like editing is performed in the active buffer. This behavior suggests an inconsistency in how the selection mode is being triggered. I have tested this on macOS and Arch Linux using a minimal configuration for doom-modeline to keep the tests clean.

**Comment by seagle0128** [comment]
I tried Emacs 31 on Windows, but failed to reproduce. Everything works well.

**Comment by mattiasdrp** [comment]
Wow, that's actually funny, the bug was fixed on emacs' side 20 hours ago so you didn't observe it:

https://github.com/emacs-mirror/emacs/commit/57fe24961fd1df04c9df1ba790932d6545f729e8

If you checkout to a previous commit (like 1bf1753d79eaf8c972885f4f0a105ed42344362f, just tested and the bug appears when checking out this commit), you will have the bug ;-)

Anyway, no need to keep this issue open now that Eli fixed it

**Comment by seagle0128** [comment]
Interesting... Thanks for letting me know it!
