### ISSUE TITLE
Feature requests: helm support

### ISSUE THREAD

**Issue by nasyxx** [seagle0128/doom-modeline#75]
Hi, by now helm buffers seems to use the default modeline format by doom-modeline.  If it is possible to use doom-modeline to show helm buffers?

**Comment by seagle0128** [comment]
Sorry! I think I don't understand what you exactly mean. Can you please describe the details?
Since I am not using `helm` while `ivy`, the PRs are welcome.

**Comment by nasyxx** [comment]
When using helm, its modeline is like below, not any form of doom-modeline. When I used spaceline before, it used [this](https://github.com/TheBB/spaceline/blob/ae45a819ea7ae52febb4d7d82170af44dff10f19/spaceline-segments.el#L240-L310) to define the performance of modeline in the helm.

<img width="874" alt="screen shot 2018-12-26 at 3 41 44 pm" src="https://user-images.githubusercontent.com/5007613/50437464-ca5bd780-0924-11e9-8c64-5ffc91b88893.png">
<img width="910" alt="screen shot 2018-12-26 at 3 41 52 pm" src="https://user-images.githubusercontent.com/5007613/50437466-cd56c800-0924-11e9-9211-5379e50ebd73.png">

I guess it is easy to define the helm segments, however, so sorry, I can't figure out what to do if I want to join helm in doom-modeline.

**Comment by seagle0128** [comment]
A workaround is below if you don't mind to lose some features.

```elisp
(advice-add #'helm-display-mode-line :override #'ignore)
```

**Comment by seagle0128** [comment]
Close by 586086889e3c9acb212c517f6b1cab35115a713a.

**Comment by nasyxx** [comment]
Thanks！
