### ISSUE TITLE
[Feature Request] Include 'visual-replace' counts in 'match' segment

### ISSUE THREAD

**Issue by woolsweater** [seagle0128/doom-modeline#755]
**Is your feature request related to a problem? Please describe.**

The Doom `match` segment helpfully displays the number of matches and the current match when using `anzu-query-replace`. But using the new package [visual-replace](https://github.com/szermatt/visual-replace), which uses the same built-in mechanism as `query-replace`, no information is shown.

**Describe the solution you'd like**

Would it be possible for this segment to display current and total information for `visual-replace`?

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by woolsweater** [comment]
Amazing, thank you!

**Comment by woolsweater** [comment]
Hmm, unfortunately the counts don't seem to be showing up. With `emacs -q`, only loading anzu, visual-replace, and doom-modeline:

``` emacs-lisp
(require 'anzu)
(require 'visual-replace)
;; Default to query mode in `visual-replace'
(add-hook 'visual-replace-minibuffer-mode-hook #'visual-replace-toggle-query)
(require 'doom-modeline)
(doom-modeline-mode)
```
![doom-modeline-replace-matches](https://github.com/user-attachments/assets/9c95bfac-3b93-44ee-8a6e-4696d3c454f8)

**Comment by seagle0128** [comment]
> How to display match counts in `visual-replace`?

   It respects `visual-replace-display-total`, so you should use `(setq visual-replace-display-total t)` to display.

**Comment by woolsweater** [comment]
Oof, my mistake. 🤦 Thank you!
