### ISSUE TITLE
[Bug] Wrong buffer file name when it contains a percentage symbol "%"

### ISSUE THREAD

**Issue by abougouffa** [seagle0128/doom-modeline#756]
### Thank you for the bug report

- [X] I am using the latest version of `doom-modeline` related packages.
- [X] I checked [FAQ](https://github.com/seagle0128/doom-modeline#faq).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When a file name contains a percentage symbol, it isn't displayed in the modeline.

See the attached screenshot:

![Screenshot at 2024-12-23 16-57-42](https://github.com/user-attachments/assets/3a32d300-493c-4027-9caa-238f2f70f7f1)

### Steps to reproduce

1. Create a file with % in its name, for example `gcc_%.bbappend`)
2. Open the file in Emacs, the mode line will show `gcc_bbappend` instead of `gcc_%.bbappend`

### Expected behavior

The mode line should will show `gcc_%.bbappend`

### OS

Linux

### Emacs Version

30 (gccemacs)

**Comment by seagle0128** [comment]
I tested with Emacs 30.0.93 on macOS, and the result is below. It seems working well.

<img width="561" alt="image" src="https://github.com/user-attachments/assets/6317a047-c4a6-4cfc-89b8-3091a52112f9" />

**Comment by abougouffa** [comment]
Hi @seagle0128 

Thank you for the quick response.

As it seems from your example, you are using:

```elisp
(setq doom-modeline-buffer-file-name-style 'buffer-name)
```

I confirm it works Ok when the variable is set to `buffer-name`, however, in my case, I'm setting it to `auto`, which causes the `%.` to not be displayed.

Using the `truncate-*` options also cause the same issue.

**Comment by seagle0128** [comment]
Thanks for your thread. I've fixed it. Please update and test.

**Comment by pjhuxford** [comment]
After this change any magit buffers I open are now just titled "%b".

**Comment by seagle0128** [comment]
@pjhuxford Already fixed. Thanks!

**Comment by abougouffa** [comment]
I confirm! The issue is fixed now! Thank you for your responsiveness @seagle0128 !
