### ISSUE TITLE
[Feature Request] Integration with nov.el

### ISSUE THREAD

**Issue by arthsmn** [seagle0128/doom-modeline#759]
**Is your feature request related to a problem? Please describe.**
As doom-modeline already integrates with pdf-tools to show the page number, I would like it to do it for nov.el too.

**Describe the solution you'd like**
When opening an epub file, doom-modeline would show me the page I'm in.

**Describe alternatives you've considered**
None.

**Additional context**
N/A.

**Comment by seagle0128** [comment]
`nov` doesn't support pages itself. Please let know if you happen to know how to display the epub pages.

**Comment by arthsmn** [comment]
> `nov` doesn't support pages itself. Please let know if you happen to know how to display the epub pages.

Sorry, I meant chapters.

**Comment by seagle0128** [comment]
I went through the codes, and it seems no API to get the chapter. We have to parse xml data to display which means it will slow down the mode-line. I won't to support this feature unless someone find out a good solution and submit the PR.

**Comment by arthsmn** [comment]
> I went through the codes, and it seems no API to get the chapter. We have to parse xml data to display which means it will slow down the mode-line. I won't to support this feature unless someone find out a good solution and submit the PR.

Thanks for taking the time to consider this feature!
