### ISSUE TITLE
duplicated versions displayed when using doom

### ISSUE THREAD

**Issue by seanfarley** [seagle0128/doom-modeline#77]
<img width="402" alt="screen shot 2018-12-27 at 8 12 38 pm" src="https://user-images.githubusercontent.com/20887/50500259-c0fe6800-0a15-11e9-898f-66cc10b19c9b.png">

It seems that `mode-name` in doom is `("" +python--version)` which duplicates the work done in the hooks you set. Is this desired?

**Comment by seagle0128** [comment]
If you are using `doom-emacs` and `doom-modeline`,  `("" +python--version)` is not necessary. The version is built in `doom-modeline`.

**Comment by seanfarley** [comment]
Ok, sure, but should I disable or override something? `("" +python--version)` is set by doom so I don't know if I should override it or something else. If the hooks in your package were functions (instead of lambdas) I could remove them in a cofig option. Anyway, I don't know what the preferred behavior should be in this situation here.

**Comment by seanfarley** [comment]
Hmmm, that seems to also get rid of the "Python" part of the majo mode in modeline

**Comment by seanfarley** [comment]
Ah, ok, fixed by `(setq +python-mode-line-indicator (list "Python"))`. Maybe @hlissner has a better idea on how to better integrate this package?

**Comment by seagle0128** [comment]
Great! doom update the mode-line in python mode. I think the solution should work well for you.
