### ISSUE TITLE
[Question] Don't show local Ruby version in major mode.

### ISSUE THREAD

**Issue by gmichokostas** [seagle0128/doom-modeline#78]
Is there any way to not display the Ruby/Python.. version in major mode?

<img width="130" alt="screenshot 2018-12-31 at 14 48 19" src="https://user-images.githubusercontent.com/7119729/50561477-6dd52f80-0d0b-11e9-9db9-f7c601655727.png">

**Comment by seagle0128** [comment]
Not yet. Since someones requested it, I decided to add a toggle for it. Will drop soon.

**Comment by seagle0128** [comment]
Update to the latest version and 
```elisp
(setq doom-modeline-version nil)
```

**Comment by gmichokostas** [comment]
Thank you very much! 🙏
That was really fast!
