### ISSUE TITLE
weired hydra doom-modline interaction

### ISSUE THREAD

**Issue by ssnnoo** [seagle0128/doom-modeline#79]
With doom-modline, the hydra below stops working correctly -> it is not possible anymore to scroll to the beginning of the buffer with ("c" scroll-down-command) ; movement stops once the next "scroll-down-command" would reach the beginning of the file. Manually invoking scroll-down-command ("M-x" scroll-down-command) from the same cursor position works (same for M-v).

(use-package hydra
  :ensure t
  :config
  (defhydra hydra-move ()
    ;; (:body-pre (next-line))
    "move"
    ("n" next-line)
    ("p" previous-line)
    ("f" forward-char)
    ("b" backward-char)
    ("a" beginning-of-line)
    ("e" move-end-of-line)
    ("v" scroll-up-command)
    ("c" scroll-down-command)
 :bind
  ("C-c n" . hydra-move/body))

doom-modline is loaded as follows:

(use-package doom-modeline
  :ensure t
  :defer t
  :hook (after-init . doom-modeline-init)
  :config
  (setq doom-modeline-python-executable "ipython")
  (setq doom-modeline-minor-modes t)
  (setq doom-modeline-github t)
  )

**Comment by seagle0128** [comment]
It doesn't make any sense. `doom-modeline` doesn't impact any input in the buffer.
As the expected, I was unable to reproduce the issue in my env, with or without `doom-modeline`, with or without `-Q`, in 25 or 26.

I believe it's invalid, and please check your configurations. Thanks!
