### ISSUE TITLE
Feature request:  evil-state indicator

### ISSUE THREAD

**Issue by Dickby** [seagle0128/doom-modeline#8]
Since doom-modeline already supports some evil features, how about an evil-state indicator?

**Comment by seagle0128** [comment]
Thanks for the suggestion!
Actually I am not using `evil` frequently. And I think the indicator of `evil-state` in the mode-line is much valuable, since there is the indicate in the minibuffer like `vim`.

![image](https://user-images.githubusercontent.com/140797/42527705-f863ebb6-84ab-11e8-8ced-53e3b1bd0186.png)

Well, I created the segment anyway. Please check if it's what you want.

```elisp
;;
;; evil-state
;;

(doom-modeline-def-segment evil-state
  "The current evil state.  Requires `evil-mode' to be enabled."
  (when (bound-and-true-p evil-local-mode)
    (s-trim-right (evil-state-property evil-state :tag t))))


;;
;; Mode lines
;;

(doom-modeline-def-modeline main
                            (workspace-number window-number bar matches " " buffer-info buffer-position  " " selection-info)
                            (buffer-encoding major-mode vcs flycheck global))

(doom-modeline-def-modeline special
                            (window-number bar evil-state matches " " buffer-info-simple buffer-position " " selection-info)
                            (buffer-encoding major-mode flycheck global))
```

**Comment by Dickby** [comment]
I somehow can't get this working.
There is the variable `evil-mode-line-tag`  that is a ready evil-state-tag with string and colors.
Maybe that should be used?

**Comment by seagle0128** [comment]
It's working for me, with GNU Emacs 26.1. What's the error?

**Comment by Dickby** [comment]
I don't know what i did wrong. Now it's working for me too.
Thanks for the work, maybe consider to make it an opttional feature.

**Comment by Dickby** [comment]
Feel free to close this issue

**Comment by seagle0128** [comment]
Glad to hear that it's working! If you have the better ideas, I may turn back to this feature again.

**Comment by gregf** [comment]
I get the following error trying to implement the above code into my config.

```
Symbol's function definition is void: doom-modeline-def-segment
```
