### ISSUE TITLE
Error during redisplay: (eval (doom-modeline-segment--matches)) signaled (void-function symbol-overlay-assoc)

### ISSUE THREAD

**Issue by vmsp** [seagle0128/doom-modeline#80]
I think the error's because I don't use `symbol-overlay` and the function that calls it is not guarded for this case. Maybe adding a `(when (bound-and-true-p symbol-overlay) ...)` [here](https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline.el#L1207) would solve it?

Btw, great job on the modeline. Happy new year.

**Comment by seagle0128** [comment]
Happy new year!

Sorry for issue. It's introduced in 9feaa79 by mistake. Will fix soon.
