### ISSUE TITLE
Feature request: flymake's indicators

### ISSUE THREAD

**Issue by nsemrau** [seagle0128/doom-modeline#81]
Emacs 26.1 comes with a substantially rewritten and improved `flymake-mode`.

Sadly, flymake's error/warning indicators are not shown by default if `flymake-mode` and doom-modeline are active. The error/warning numbers are appended to flymake's minor mode indicator in vanilla mode-line. You have to `(setq doom-modeline-minor-modes t)`, but that just injects the vanilla list of minor-modes into doom-modeline, whose other minor-mode indicators you then have to laboriously suppress with a package like "diminish" to just see flymake's status.

Here are pictures of the default doom-modeline with flymake on but invisible and the latter picture with  `(setq doom-modeline-minor-modes t)`, so flymake is indeed visible, but only through the list of minor-modes:

![default](https://user-images.githubusercontent.com/4363876/50570090-c6441580-0d7b-11e9-8305-cc9b577a7e93.png)

![minor](https://user-images.githubusercontent.com/4363876/50570094-d22fd780-0d7b-11e9-8583-eed71dd7dce3.png)

I thought not supporting flymake by default was a concious choice, since doom-modeline is about a clutter-free look. It has now come to my attention that the indicators of the third-party package flycheck are supported dy default.

Please support flymake's indicators by default as well. If its internal code has changed too much between the rewritten version in 26.1 and versions in older Emacsen, I think it would be okay to only support >= 26.1 and leave out possibly neccessary machinery for supporting older versions of flymake.

**Comment by seagle0128** [comment]
I was trying to implement it since `lsp` has already used `flymake` by default. My idea is to make the same interface of `flycheck` and `flymake`. Will commit soon.

**Comment by seagle0128** [comment]
New checker indicator for `flymake` and `flycheck` is ready.  `flymake` is the default; enable `flychecker` if `flymake` is disabled. Generally the segment of `flymake` is a little bit slower.

Please try the new release. Thanks.

**Comment by nsemrau** [comment]
Works great, thank you for the quick implementation.

One further suggestion: vanilla flymake shows a number for errors of the level "note", too, but in doom-modeline those are only shown in the tooltip. It would be great if doom-modeline could please show the "note" level as well.

![screenshot from 2019-01-02 18-48-35](https://user-images.githubusercontent.com/4363876/50604890-c13cae80-0ec0-11e9-86a5-abd36abe01ac.png)

![screenshot from 2019-01-02 18-51-59](https://user-images.githubusercontent.com/4363876/50604650-e977dd80-0ebf-11e9-9810-2dcc5a787720.png)

**Comment by seagle0128** [comment]
Done. Available for both `flycheck` and `flymake`.

**Comment by nsemrau** [comment]
Great, the whole feature works as I had it in mind. Thank you again. 🥇

**Comment by seagle0128** [comment]
Add a new customization: `doom-modeline-checker-simple-format`.
