### ISSUE TITLE
Error running timer ‘doom-modeline--github-fetch-notifications’: (void-function async-inject-variables)

### ISSUE THREAD

**Issue by Jackson-soft** [seagle0128/doom-modeline#82]

**Comment by seagle0128** [comment]
Can you provide the information below?

- Operation Version
- Emacs version
- package version
- async version
- `C-h f async-start` and `C-h f async-inject-variables`

**Comment by Jackson-soft** [comment]
Mac OS 14
Emacs 26.1
doom-modeline 20190101.1052
async 20181224.454

**Comment by seagle0128** [comment]
> C-h f async-start and C-h f async-inject-variables

Would you please eval on your env?

**Comment by Jackson-soft** [comment]
<img width="820" alt="default" src="https://user-images.githubusercontent.com/3928114/50587491-27253800-0eb9-11e9-80ba-389017300f5a.png">

**Comment by Jackson-soft** [comment]
<img width="733" alt="default" src="https://user-images.githubusercontent.com/3928114/50587557-5471e600-0eb9-11e9-84a4-a50e5954244b.png">

**Comment by seagle0128** [comment]
Thank you for the information. Please check the new version.
