### ISSUE TITLE
Feature request: More compatibility with regular Emacs modes

### ISSUE THREAD

**Issue by weirdNox** [seagle0128/doom-modeline#9]
Hey there! 
First of all, I wanted to thank you for extracting this modeline from DOOM and maintaining it, it's great :)

I wanted to make a suggestion, if you don't mind diverging from DOOM: I know this modeline is supposed to be minimalistic, so it selects only the information it needs to keep it nice and tidy. 

The problem is that some base modes like `display-time-mode` completely disappear. After investigating, this mode uses `global-mode-string`, which in my case is empty except for the time. So, including it in your modeline wouldn't make a difference for the people that don't want time, but would make it possible to have it.

Another example is the page number in `pdf-view`, which uses `mode-line-position`. Maybe these should be treated in separate issues, I don't know. In the package, instead of using `mode-line-position`, you use `"  %l:%c %p  "`. 

My two suggestions together could look more or less like this:
```elisp
;; For the time string and whatever uses global-mode-string
(doom-modeline-def-segment global
  (when global-mode-string '(" " global-mode-string)))

;; For the position
(setq-default mode-line-position
              '((line-number-mode
                 (column-number-mode
                  (column-number-indicator-zero-based " %l:%c" " %l:%C")
                  " %l")
                 (column-number-mode (column-number-indicator-zero-based " :%c" " :%C")))
                (mode-line-percent-position (" " mode-line-percent-position))
                (:eval (when (or line-number-mode mode-line-percent-position column-number-mode) " "))))

(doom-modeline-def-segment buffer-position
  '(" " mode-line-position))

;; Update the setups accordingly
(doom-modeline-def-modeline main
                            (workspace-number window-number bar matches " " buffer-info buffer-position " " selection-info)
                            (buffer-encoding major-mode vcs flycheck global))

(doom-modeline-def-modeline special
                            (window-number bar matches " " buffer-info-simple buffer-position " " selection-info)
                            (buffer-encoding major-mode flycheck global))

(doom-modeline-def-modeline project
                            (window-number bar buffer-default-directory)
                            (major-mode global))

(doom-modeline-def-modeline media
                            (window-number bar " %b  ")
                            (media-info major-mode global))
```

This makes it automatically compatible with modes like `pdf-view`, and also makes it possible to turn column-line-mode off, for example. Will also display the time, when enabled.

![image](https://user-images.githubusercontent.com/3155049/42481955-e825751e-83dc-11e8-8c43-d5be685baafa.png)

**Comment by seagle0128** [comment]
Appreciate it for your great suggestion!
It's true the goal is keeping minimalistic, but I'm also open to accept PRs which are simple, nice and useful.

The `global` and `buffer-position` are nice to add to the mode-line. I will merge soon. Please test then.
Thanks a lot, again!

**Comment by weirdNox** [comment]
Ah, btw, in case you are wondering about the spaces in buffer-position, I tried to keep the original padding of 2 spaces like `"__%l:%c %p__"` in any combination of `line-number-mode` and `column-number-mode` and the percentage. 

When the `mode-line-position` is empty, it will keep only two spaces `"__"`, the one in `buffer-position` and the one in the main modeline spec.

I chose to do it like this, because if some mode completely replaces `mode-line-position`, they may choose to not pad it, but will at the very least have 1 space of padding (like `pdf-view-mode`, which only pads the string to the left).

**Comment by seagle0128** [comment]
Thanks for the explanations, @weirdNox! I will think about it.

I've added `global-mode-string` in 4d4ec2e8560d168ae0d570c23a6eec29e04d7038.
Regarding `buffer-position`, I have concerns about `mode-line-percent-position` and `column-number-indicator-zero-based` which are introduced in 26. Need more considerations for 25...

**Comment by weirdNox** [comment]
Ohh, I had no idea, I just went to see the default value in my Emacs, which is v26, and adapted from it!

Maybe you could add a check outside with boundp, and if not defined, you could create them with a defvar. 

Or instead of using them directly, using something like 
```elisp
(defvar doom-modeline-percent (or (bound-and-true-p mode-line-percent-position) '(-3 "%p"))
  "...")
(defvar doom-modeline-column-zero-based (or (bound-and-true-p column-number-indicator-zero-based) t)
  "...")
```
(...if the macro `bound-and-true-p` is defined in 25 ahah)

I don't know, your call :)

**Comment by weirdNox** [comment]
Thanks! :D
