### ISSUE TITLE
Feature Request: Make programming environment version parsing asynchronous

### ISSUE THREAD

**Issue by justinbarclay** [seagle0128/doom-modeline#90]
**Is your feature request related to a problem? Please describe.**
When I focus into a buffer that doom-modeline can run `doom-modeline-env-command`, Emacs is blocked for a second or two. Looking into this, I think it's because the version parsing system relies on `shell-command-to-string`.

**Describe the solution you'd like**
If doom-modeline would switch to using `start-process` over `shell-command-to-string`, to execute shell commands I think this would fix the  Emacs when parsing the programming. 

**Describe alternatives you've considered**
None

**Additional context**
These issues are happening on MacOS Mojave and Emacs 27.0. If this is a feature you would like, I've implemented it on a fork and would be happy to work with you to merge it back into doom-modeline.

**Comment by seagle0128** [comment]
Yes, it may be the bottleneck although I didn't encounter it in my env. 
PRs are always welcome!

**Comment by justinbarclay** [comment]
Awesome, just as some documentation of what I am experiencing, I tried to make a gif of it,
https://imgur.com/a/lZaMTuA

Using doom-modeline from `master`, I switch into a Ruby buffer and press M-x and you can see it takes a second or two to respond. Then I switch to my fork, `async-env-parser`, and it responds instantly for me.

**Comment by seagle0128** [comment]
I refactor and optimize this feature today. Please help to review and test. The most improvement is "Not create process buffer while creating the sub-process." Thus make the thing simple and clear IMO.

**Comment by justinbarclay** [comment]
Oh awesome, that's a great catch!
I just tested all the currently supported languages on my Mac and it works wonderfully. :)
