### ISSUE TITLE
doom-modeline-icon is nil by default when runnings emacs as a daemon

### ISSUE THREAD

**Issue by willbush** [seagle0128/doom-modeline#93]
**Describe**

I noticed that `doom-modeline-icon` defaults to `nil` when I run emacs as a daemon on Linux and Windows. Otherwise, it's default value seems to be `t`. Explicitly setting it to true works fine when run emacs as a daemon. Just thought I would point this out since I'm not sure if it's intended or not.

**Steps and Expected**

Run [emacs as a daemon](https://www.emacswiki.org/emacs/EmacsAsDaemon) and
observe that `doom-modeline-icon` is set to `nil`.

**Environment:**

 - OS: NixOS 19.03 and Windows 10
 - Package version: 20190111.1751
 - GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.1) of 2018-12-25

**Comment by seagle0128** [comment]
That's by design. Set it to `non-nil` to enable it forcely.

```elisp
(defvar doom-modeline-icon (display-graphic-p)
  "Whether show `all-the-icons' or not.

Non-nil to show the icons in mode-line.
The icons may not be showed correctly in terminal and on Windows.")
```

**Comment by willbush** [comment]
Ah I see, that makes sense.
