### ISSUE TITLE
doom-modeline starts buffers in background

### ISSUE THREAD

**Issue by bradprob** [seagle0128/doom-modeline#97]
Hi,
sinds a couple of days I am using doom-modeline and from that time my emacs starts buffers in background. The name of these buffers is *emacs<x>* and their content:
`Lisp expression: Git variable 'github.user' is unset.  Set to: `
When I disable the doom-modeline the buffers are not created anymore and emacs works as I expect.
Can you explain what is happening?
Regards

**Comment by seagle0128** [comment]
I think you don't set git env correctly. Try `(setq doom-modeline-github nil)`.

**Comment by bradprob** [comment]
Thanks for your answer! `(setq doom-modeline-github nil)` solves the issue!

**Comment by seagle0128** [comment]
I've set `doom-modeline-github` to nil by default. Close this issue.
