### ISSUE TITLE
nyan-cat and python version bug

### ISSUE THREAD

**Issue by iromise** [seagle0128/doom-modeline#98]
**Describe**
1. show the nyan-cat in tree-macs
2. when set python interpreter in init.el(spacemacs), when Reload it with SPC-e-d-R, the python version in the modeline still show the old version.

**Environment:**
 - OS: MacOS
 - Version 14
 - Package version latest

**Comment by seagle0128** [comment]
> 1. show the nyan-cat in tree-macs
> 1. when set python interpreter in init.el(spacemacs), when Reload it with SPC-e-d-R, the python version in the modeline still show the old version.

1. It's by design. Please disable `nyan-mode` in treemacs yourself.
1. Please set `doom-modeline-python-executable`.

**Comment by iromise** [comment]
sorry, I use spacemacs with doom-line. I will try what you said.

**Comment by iromise** [comment]
for the first, i cannot replay it sorry.
for the second, when i set what you said, the modeline really show what i set, but it won't change `python-shell-interpreter`, so some config won't work, e.g. lsp.

**Comment by seagle0128** [comment]
You should set your env correctly, including `python-shell-interpreter`. It's not an issue of `doom-modeline`. Sorry!

**Comment by iromise** [comment]
yes, I have set. I mean when i set `python-shell-interpreter`, the doom-modeline should also show what I have set?

**Comment by iromise** [comment]
ok, thanks.
